/* ==== p72e_hl_plancastle.js ==== */
/* HOGWARTS — the castle raised from the blueprint (p71z). Every '#' of the plan is a wall, every gap a doorway,
   every room, corridor, court and lawn sits where the plan puts it, at one metre to the cell. Above the ground
   storey the ranges rise as upper floors with windows, battlements and towers; the tall halls keep their height. */
(function () {
  const GK = HL.GK; HL.PL = { X0: 157, Z0: 256, H1: 6.4 };
  /* ------------------------------------------------------------------ reading the plan */
  /* the halls that rise through the floors above: the Great Hall, and the Entrance Hall wherever the first-floor plan shows open air or stairs */
  HL.tallAt = (i, j) => { for (const t of HL.TALLR) if (i >= t[0] && i <= t[2] && j >= t[1] && j <= t[3]) return t[4]; return 0; };
  /* The plans draw most doors shut (a line across the gap), so many rooms have no way in. Starting from where the stairs arrive,
     walk the rooms through the doorways that exist; wherever a room cannot be reached, open a doorway through the thinnest wall it
     shares with a room that can. Returns the wall cells to clear. */
  HL._carve = {}; HL._carveDone = {};
  HL.carves = function (P) { const NX = P.NX, NZ = P.NZ, S = HL.SHAFT, ind2 = (c) => c.kind === 'room' || c.kind === 'corr', ok = P.k === 0 ? ((c) => !!c && (ind2(c) || c.kind === 'court' || c.edge || c.n > 300)) : ((c) => !!c && ind2(c)), seeds = P.k === 0 ? [[236, 145]] : [[166, 160], [106, 83]];
    const c0s = []; for (const seed of seeds) { let c0 = null; for (let r = 0; r < 8 && !c0; r++) for (let dj = -r; dj <= r && !c0; dj++) for (let di = -r; di <= r; di++) { const c = P.compAt(seed[0] + di, seed[1] + dj); if (ok(c)) { c0 = c; break; } } if (c0) c0s.push(c0); } if (!c0s.length) return [];
    const adj = new Map(), link = (a, b) => { if (a === b) return; if (!adj.has(a)) adj.set(a, new Set()); if (!adj.has(b)) adj.set(b, new Set()); adj.get(a).add(b); adj.get(b).add(a); };
    for (const d of P.doors) { if (!d.inn) continue; const ids = new Set(); for (let j = d.j0 - 1; j <= d.j1; j++) for (let i = d.i0 - 1; i <= d.i1; i++) { if (i < 0 || j < 0 || i >= NX || j >= NZ) continue; const c = P.comp[j * NX + i]; if (c >= 0 && ok(P.comps[c])) ids.add(c); } const a = [...ids]; for (let x = 0; x < a.length; x++) for (let y = x + 1; y < a.length; y++) link(a[x], a[y]); }
    // candidate doorways through walls: [compA, compB, cells]
    const cand = new Map(), cid = (i, j) => (i < 0 || j < 0 || i >= NX || j >= NZ || P.door[j * NX + i]) ? -1 : P.comp[j * NX + i], put = (a, b, cells, t) => { if (!ind2(P.comps[a]) && !ind2(P.comps[b])) return; const key = a < b ? a + '_' + b : b + '_' + a, o = cand.get(key); if (!o || t < o.t) cand.set(key, { a, b, cells, t }); };
    for (let j = 1; j < NZ - 2; j++) for (let i = 1; i < NX - 7; i++) { const a = cid(i, j); if (a < 0 || !ok(P.comps[a]) || cid(i, j + 1) !== a) continue; for (let t = 1; t <= 3; t++) { let w = true; for (let q = 1; q <= t; q++) if (!P.isW(i + q, j) || !P.isW(i + q, j + 1)) { w = false; break; } if (!w) break; const b = cid(i + t + 1, j); if (b >= 0 && b !== a && ok(P.comps[b]) && cid(i + t + 1, j + 1) === b && P.isW(i + 1, j - 1) && P.isW(i + 1, j + 2)) { const cells = []; for (let q = 1; q <= t; q++) cells.push([i + q, j], [i + q, j + 1]); put(a, b, cells, t); } } }
    for (let j = 1; j < NZ - 7; j++) for (let i = 1; i < NX - 2; i++) { const a = cid(i, j); if (a < 0 || !ok(P.comps[a]) || cid(i + 1, j) !== a) continue; for (let t = 1; t <= 3; t++) { let w = true; for (let q = 1; q <= t; q++) if (!P.isW(i, j + q) || !P.isW(i + 1, j + q)) { w = false; break; } if (!w) break; const b = cid(i, j + t + 1); if (b >= 0 && b !== a && ok(P.comps[b]) && cid(i + 1, j + t + 1) === b && P.isW(i - 1, j + 1) && P.isW(i + 2, j + 1)) { const cells = []; for (let q = 1; q <= t; q++) cells.push([i, j + q], [i + 1, j + q]); put(a, b, cells, t); } } }
    const wadj = new Map(); for (const o of cand.values()) { for (const [x, y] of [[o.a, o.b], [o.b, o.a]]) { if (!wadj.has(x)) wadj.set(x, []); wadj.get(x).push([y, o]); } }
    const seen = new Set(c0s.map((c) => c.id)), out = []; let frontier = c0s.map((c) => c.id);
    while (frontier.length) { // first everything reachable by existing doors, then one new doorway at a time
      const st = frontier.slice(); frontier = []; while (st.length) { const a = st.pop(); for (const b of (adj.get(a) || [])) if (!seen.has(b)) { seen.add(b); st.push(b); } }
      for (const a of [...seen]) for (const [b, o] of (wadj.get(a) || [])) if (!seen.has(b) && P.comps[b].n >= 6) { seen.add(b); frontier.push(b); for (const c of o.cells) out.push(c); }
    }
    P.seen = seen; // rooms still cut off (across a court, or behind a wall too thick to open): grouped, for the secret passages
    { const un = P.comps.filter((c) => ind2(c) && !seen.has(c.id) && c.n >= 12), done = new Set(); P.islands = []; for (const c of un) { if (done.has(c.id)) continue; const grp = [], st = [c.id]; done.add(c.id); while (st.length) { const a = st.pop(); grp.push(P.comps[a]); for (const b of (adj.get(a) || [])) if (!done.has(b) && !seen.has(b)) { done.add(b); st.push(b); } for (const [b] of (wadj.get(a) || [])) if (!done.has(b) && !seen.has(b)) { done.add(b); st.push(b); } } const rooms = grp.filter((q) => q.kind === 'room').sort((a, b) => b.n - a.n); if (rooms.length && rooms[0].n >= 24) P.islands.push(rooms[0]); } }
    return out; };
  HL.NFLOOR = 3; HL._plans = []; HL.UP = [0, 1, 2, 3, 4]; HL.ALLK = [0, 1, 2, 3, 4]; HL.TOPK = 4; HL.sOf = (k) => k; HL.kOfS = (s2) => clamp(s2, 0, 4);
  HL.kAt = (y) => clamp(Math.floor((y - HL.Y0 + 0.6) / HL.PL.H1), 0, 4);
  /* the stair wells: tall rooms with a gallery ring on every storey and two flights between each: [name, ring width] */
  HL.WELLN = { 'THE GRAND STAIRCASE': 3, 'THE CENTRAL HALL': 3 };
  /* the tall halls with a gallery round them at first-floor level (no stair of their own): [name → gallery width] */
  HL.GALN = { 'DEFENCE AGAINST THE DARK ARTS': 3, 'THE TRANSFIGURATION CLASSROOM': 3, 'THE CHARMS CLASSROOM': 3, 'HISTORY OF MAGIC': 3, 'THE SOUTH HALL': 3, 'THE TROPHY HALL': 3 };
  /* the Astronomy Tower's stair: a square shaft, ten metres a side, straight up through the masonry over the classroom at the tower's foot */
  HL.TSH = { i0: 67, i1: 76, j0: 181, j1: 190 }; HL.inTowerShaft = (i, j) => i >= HL.TSH.i0 && i <= HL.TSH.i1 && j >= HL.TSH.j0 && j <= HL.TSH.j1;
  HL.SHAFT = { i0: -99, i1: -90, j0: -99, j1: -90 }; HL.inShaft = (i, j) => i > HL.SHAFT.i0 && i < HL.SHAFT.i1 && j > HL.SHAFT.j0 && j < HL.SHAFT.j1;
  HL.plan = function (k) { k = k || 0; if (HL._plans[k]) return HL._plans[k]; const g = HL.planGrid(), NX = g.NX, NZ = g.NZ;
    let C = g.rows.map((r) => r.split('')); { if (k > 0) { const P0 = HL.plan(0), H1 = HL.PL.H1; // an upper storey: the same walls, wherever its mass stands this high; tall halls are voids, stair wells keep a gallery ring
        for (let j = 0; j < NZ; j++) for (let i = 0; i < NX; i++) { const ch = C[j][i], z = HL.zoneOf(i, j); if (!z || k > z[5] || ch === 'g' || ch === 'w' || ch === 'P' || !P0.rf(i, j)) C[j][i] = 'g'; }
        for (const c of P0.comps) { if (!c.tallH || c.tallH <= k * H1 + 0.5) continue; const rw = HL.WELLN[c.name] || HL.GALN[c.name] || 0; for (let j = c.j0; j <= c.j1; j++) for (let i = c.i0; i <= c.i1; i++) { if (P0.comp[j * NX + i] !== c.id || C[j][i] === 'g') continue; C[j][i] = rw && (i < c.R.i0 + rw || i > c.R.i1 - rw || j < c.R.j0 + rw || j > c.R.j1 - rw) ? 'F' : 'P'; } } }
      for (const [ci, cj] of (HL._carve[k] || [])) C[cj][ci] = 'F';   // doorways opened so that every room can be walked to (see HL.carves)
      C = C.map((r) => r.join('')); }
    const at = (i, j) => (!(i >= 0) || !(j >= 0) || i >= NX || j >= NZ) ? 'g' : C[j][i], isW = (i, j) => at(i, j) === '#';
    const door = new Uint8Array(NX * NZ), doors = [];
    const scan = (horiz) => { const A = horiz ? NZ : NX, B = horiz ? NX : NZ, w = (a, b) => horiz ? isW(b, a) : isW(a, b); let prev = new Map();
      for (let a = 0; a <= A; a++) { const cur = new Map(); if (a < A) { let b = 0; while (b < B) { if (w(a, b)) { b++; continue; } let e = b; while (e < B && !w(a, e)) e++; if (b > 0 && e < B && e - b <= 4) { const k2 = b * 1000 + e; cur.set(k2, (prev.get(k2) || 0) + 1); } b = e; } }
        for (const [k2, n] of prev) if (!cur.has(k2) && n <= 3) { const b0 = Math.floor(k2 / 1000), e0 = k2 % 1000; for (let q = a - n; q < a; q++) for (let b2 = b0; b2 < e0; b2++) door[horiz ? q * NX + b2 : b2 * NX + q] = horiz ? 1 : 2; doors.push(horiz ? { i0: b0, i1: e0, j0: a - n, j1: a, dir: 1 } : { i0: a - n, i1: a, j0: b0, j1: e0, dir: 2 }); }
        prev = cur; } };
    scan(true); scan(false);
    const comp = new Int32Array(NX * NZ).fill(-1), comps = [];
    for (let j = 0; j < NZ; j++) for (let i = 0; i < NX; i++) { const s = j * NX + i; if (comp[s] >= 0 || isW(i, j) || door[s]) continue; const id = comps.length, c = { id, k, n: 0, cnt: {}, i0: i, i1: i, j0: j, j1: j, h: HL.PL.H1, edge: 0 }, st = [s]; comp[s] = id;
        while (st.length) { const q = st.pop(), qi = q % NX, qj = (q / NX) | 0, ch = C[qj][qi]; c.n++; c.cnt[ch] = (c.cnt[ch] || 0) + 1; if (qi === 0 || qj === 0 || qi === NX - 1 || qj === NZ - 1) c.edge = 1; if (qi < c.i0) c.i0 = qi; if (qi > c.i1) c.i1 = qi; if (qj < c.j0) c.j0 = qj; if (qj > c.j1) c.j1 = qj;
          for (const [di, dj] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) { const ni = qi + di, nj = qj + dj; if (ni < 0 || nj < 0 || ni >= NX || nj >= NZ) continue; const t = nj * NX + ni; if (comp[t] >= 0 || isW(ni, nj) || door[t]) continue; if (k > 0 && (C[nj][ni] === 'P') !== (ch === 'P')) continue; comp[t] = id; st.push(t); } }
        const q = c.cnt, grass = (q.g || 0) + (q.w || 0), ee = k > 0 && grass < c.n * 0.1 ? (q.e || 0) : 0, corr = (q.c || 0) + ee, inn = (q.F || 0) + corr + (q.s || 0), out = (q.P || 0) + grass, gr = q.h || 0; c.kind = gr > inn && gr > out ? 'green' : inn > out ? (corr > inn * 0.5 ? 'corr' : 'room') : ((q.P || 0) > grass ? 'court' : 'out'); if (k > 0) { const all = c.n; c.kind = grass > all * 0.5 ? 'out' : (q.P || 0) > all * 0.5 ? 'court' : (q.c || 0) > all * 0.5 ? 'corr' : 'room'; } if (c.kind === 'room' && c.n < 5) c.kind = 'corr'; comps.push(c); }
    const indoor = new Uint8Array(NX * NZ); for (let s = 0; s < NX * NZ; s++) if (comp[s] >= 0 && (comps[comp[s]].kind === 'room' || comps[comp[s]].kind === 'corr')) indoor[s] = 1;
    for (const d of doors) { let inn = 0; for (let j = d.j0; j < d.j1; j++) for (let i = d.i0; i < d.i1; i++) for (const [di, dj] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) { const ni = i + di, nj = j + dj; if (ni >= 0 && nj >= 0 && ni < NX && nj < NZ && indoor[nj * NX + ni] && !door[nj * NX + ni]) inn = 1; } if (k > 0 && C[d.j0][d.i0] === 'P') inn = 0; d.inn = inn; if (inn) for (let j = d.j0; j < d.j1; j++) for (let i = d.i0; i < d.i1; i++) indoor[j * NX + i] = 1; }
    const roofed = new Uint8Array(NX * NZ); for (let j = 0; j < NZ; j++) for (let i = 0; i < NX; i++) { const s = j * NX + i; if (indoor[s]) { roofed[s] = 1; continue; } if (!isW(i, j)) continue; for (let dj = -1; dj <= 1 && !roofed[s]; dj++) for (let di = -1; di <= 1; di++) { const ni = i + di, nj = j + dj; if (ni >= 0 && nj >= 0 && ni < NX && nj < NZ && indoor[nj * NX + ni]) { roofed[s] = 1; break; } } }
    const P = HL._plans[k] = { k, s: HL.sOf(k), under: false, y: HL.Y0 + HL.sOf(k) * HL.PL.H1, NX, NZ, C, at, isW, door, doors, comp, comps, indoor, roofed, X: (i) => HL.PL.X0 - i, Z: (j) => HL.PL.Z0 - j, cellAt: (x, z) => [Math.floor(HL.PL.X0 - x), Math.floor(HL.PL.Z0 - z)],
      compAt: (i, j) => comp[j * NX + i] >= 0 ? comps[comp[j * NX + i]] : null, rf: (i, j) => i >= 0 && j >= 0 && i < NX && j < NZ && roofed[j * NX + i] === 1, ind: (i, j) => i >= 0 && j >= 0 && i < NX && j < NZ && indoor[j * NX + i] === 1 };
    for (const c of comps) { if (c.kind !== 'room') continue; const W = c.i1 - c.i0 + 1, hgt = new Int32Array(W + 1); let best = 0, R4 = null;
      for (let j = c.j0; j <= c.j1; j++) { for (let q = 0; q < W; q++) hgt[q] = (comp[j * NX + c.i0 + q] === c.id && !door[j * NX + c.i0 + q]) ? hgt[q] + 1 : 0; const st = [];
        for (let q = 0; q <= W; q++) { const h = q < W ? hgt[q] : 0; let start = q; while (st.length && st[st.length - 1][1] >= h) { const [s2, h2] = st.pop(), area = h2 * (q - s2); if (area > best && Math.min(h2, q - s2) >= 2) { best = area; R4 = { i0: c.i0 + s2, i1: c.i0 + q - 1, j0: j - h2 + 1, j1: j }; } start = s2; } st.push([start, h]); } }
      c.R = R4 || { i0: c.i0, i1: c.i1, j0: c.j0, j1: c.j1 }; }
    // named rooms: [plan col, row, name, kind]
    P.ROOMS = k === 0 ? HL.PLACES.map((r) => r.slice()) : [];
    for (const r of P.ROOMS) { let c = P.compAt(r[0], r[1]); if (!(c && c.kind === 'room' && !c.name)) { c = null; let bd = 1e9; for (const q of comps) { if (q.kind !== 'room' || q.name || q.n < 16) continue; const d = Math.hypot((q.i0 + q.i1) / 2 - r[0], (q.j0 + q.j1) / 2 - r[1]); if (d < bd && d < 22) { bd = d; c = q; } } } if (c) { c.name = r[2]; c.type = r[3]; r.c = c; } }
    if (k === 0) { HL.TALLR.length = 2; HL.TALLR[1][4] = 12.8; for (const c of comps) { const hh = { 'THE GRAND STAIRCASE': 32, 'THE CENTRAL HALL': 25.6, 'THE LIBRARY': 12.8, 'THE CLOCK TOWER': 19.2, 'THE LONG GALLERY': 12.8, 'THE VIADUCT ENTRANCE': 12.8, 'DEFENCE AGAINST THE DARK ARTS': 12.8, 'THE TRANSFIGURATION CLASSROOM': 12.8, 'THE CHARMS CLASSROOM': 12.8, 'HISTORY OF MAGIC': 12.8, 'THE SOUTH HALL': 12.8, 'THE TROPHY HALL': 12.8 }[c.name]; if (hh) { HL.TALLR.push([c.R.i0, c.R.j0, c.R.i1, c.R.j1, hh]); c.tallH = hh; } } }
    const pre = ['', 'FIRST-FLOOR ', 'SECOND-FLOOR ', 'THIRD-FLOOR ', 'FOURTH-FLOOR '][k];
    if (k > 0) { const P0 = HL.plan(0); for (const c of comps) { if (c.kind !== 'room') continue; const g0 = P0.compAt((c.R.i0 + c.R.i1) >> 1, (c.R.j0 + c.R.j1) >> 1), gn = g0 && g0.name; if (gn && HL.WELLN[gn]) { c.name = gn; c.type = 'ring'; continue; } if (gn && HL.GALN[gn] && g0.tallH > k * HL.PL.H1 + 0.5) { c.name = ({ 'DEFENCE AGAINST THE DARK ARTS': 'THE DEFENCE GALLERY', 'HISTORY OF MAGIC': 'THE HISTORY GALLERY' })[gn] || gn.replace(/ CLASSROOM$/, '') + ' GALLERY'; c.type = 'ring'; continue; } const ab = gn && HL.ABOVE[gn] && HL.ABOVE[gn][k]; if (ab) { c.name = ab[0]; c.type = ab[1]; } } }
    let nc = 0, no = 0; for (const c of comps) { if (c.kind !== 'room' || c.name) continue; if (c.n >= 150) { nc++; c.name = pre + 'CLASSROOM ' + (nc < 10 ? '0' : '') + nc; c.type = (nc + k) % 4 === 0 ? 'library' : (nc + k) % 4 === 2 ? 'trophy' : 'class'; } else if (c.n >= 60) { no++; c.name = ['A STUDY', 'A TUTOR’S ROOM', 'A READING ROOM', 'AN OFFICE', 'A MUSIC ROOM', 'A STORE OF CURIOSITIES'][(no + k) % 6]; c.type = ['study', 'tutor', 'library', 'study', 'music', 'trophy'][(no + k) % 6]; } else c.type = c.n >= 20 ? 'store' : 'closet'; }
    P.ZN = HL.ZN;
    P.T = (i, j) => { for (const z of P.ZN) if (i >= z[0] && i < z[2] && j >= z[1] && j < z[3]) return z[4]; return 23; };
    // ceiling of a cell on its own floor; the tall halls only on the ground floor
    if (!HL._carveDone[k]) { HL._carveDone[k] = 1; const cv = HL.carves(P); if (cv.length) { HL._carve[k] = cv; HL._plans[k] = null; return HL.plan(k); } } else HL.carves(P);
    P.ceil = (i, j) => { if (k > 0) return HL.PL.H1; const s = j * NX + i; if (indoor[s]) return HL.tallAt(i, j) || HL.PL.H1; let h = HL.PL.H1; for (let dj = -1; dj <= 1; dj++) for (let di = -1; di <= 1; di++) { const ni = i + di, nj = j + dj; if (ni < 0 || nj < 0 || ni >= NX || nj >= NZ) continue; if (indoor[nj * NX + ni]) h = Math.max(h, HL.tallAt(ni, nj) || 0); } return h; };
    return P; };
  /* the water of the game's map is a gorge in the crag, down to the loch: depth by distance from its banks */
  HL.gorge = function (x, z) { if (!HL._gd) { const g = HL.planGrid(), NX = g.NX, NZ = g.NZ, D = new Float32Array(NX * NZ); for (let j = 0; j < NZ; j++) for (let i = 0; i < NX; i++) D[j * NX + i] = g.rows[j][i] === 'w' ? Math.min(i, j, NX - 1 - i, NZ - 1 - j, 60) + 1 : 0;
      for (let j = 0; j < NZ; j++) for (let i = 0; i < NX; i++) { const s = j * NX + i; if (!D[s]) continue; let d = D[s]; if (i > 0) d = Math.min(d, D[s - 1] + 1); if (j > 0) d = Math.min(d, D[s - NX] + 1); D[s] = d; }
      for (let j = NZ - 1; j >= 0; j--) for (let i = NX - 1; i >= 0; i--) { const s = j * NX + i; if (!D[s]) continue; let d = D[s]; if (i < NX - 1) d = Math.min(d, D[s + 1] + 1); if (j < NZ - 1) d = Math.min(d, D[s + NX] + 1); D[s] = d; } HL._gd = { D, NX, NZ }; }
    const G = HL._gd, fi = HL.PL.X0 - x - 0.5, fj = HL.PL.Z0 - z - 0.5, i = Math.floor(fi), j = Math.floor(fj); if (i < 0 || j < 0 || i >= G.NX - 1 || j >= G.NZ - 1) return 0; const u = fi - i, v = fj - j, s = j * G.NX + i;
    return (G.D[s] * (1 - u) + G.D[s + 1] * u) * (1 - v) + (G.D[s + G.NX] * (1 - u) + G.D[s + G.NX + 1] * u) * v; };
  { const h0 = HL.h; HL.h = function (x, z) { const y = h0(x, z), d = HL.gorge(x, z); return d > 1.2 ? Math.min(y, HL.Y0 - 0.3 - Math.min(68, (d - 1.2) * 5.5)) : y; }; }
  /* the crag is hollow under the Great Hall and the Reception Hall: the dungeons */
  { const h1 = HL.h; HL.h = function (x, z) { const y = h1(x, z); return (x > -94 && x < -65 && z > 18.5 && z <= 82) || (x > -102 && x < -60 && z > 81 && z < 93.5) || (x > -9.6 && x < 7.6 && z > 97.6 && z < 118.6) ? Math.min(y, HL.Y0 - 9.5) : y; }; }
  HL.dropY = function (x, z, up) { const inC = HL.inFoot(x, z, 0), top = inC ? HL.Y0 + 2.5 : HL.gy(x, z) + (up || 30), f = PHY.floorBelow(x, z, top); return f ? f.y : (inC ? HL.Y0 : HL.gy(x, z)); };
  HL.inFoot = function (x, z, pad) { const P = HL.plan(), i = Math.floor(HL.PL.X0 - x), j = Math.floor(HL.PL.Z0 - z); if (i < -2 || j < -2 || i >= P.NX + 2 || j >= P.NZ + 2) return Math.abs(x) < 6 + pad && z < -58 && z > -300; const p = Math.ceil(pad || 0);
    for (let dj = -p; dj <= p; dj++) for (let di = -p; di <= p; di++) { const ch = P.at(i + di, j + dj); if (ch !== 'g' && ch !== 'w') return true; if (P.rf(i + di, j + dj)) return true; } return false; };
  /* greedy rectangles over cells sharing a key (key(i,j) → string or null) */
  const greedy = (P, key, fn) => { const NX = P.NX, NZ = P.NZ, done = new Uint8Array(NX * NZ);
    for (let j = 0; j < NZ; j++) for (let i = 0; i < NX; i++) { if (done[j * NX + i]) continue; const k = key(i, j); if (k === null) continue; let i1 = i; while (i1 + 1 < NX && !done[j * NX + i1 + 1] && key(i1 + 1, j) === k) i1++; let j1 = j, ok = true; while (ok && j1 + 1 < NZ) { for (let q = i; q <= i1; q++) if (done[(j1 + 1) * NX + q] || key(q, j1 + 1) !== k) { ok = false; break; } if (ok) j1++; }
        for (let b = j; b <= j1; b++) for (let a = i; a <= i1; a++) done[b * NX + a] = 1; fn(i, j, i1, j1, k); } };
  HL.greedy = greedy;
  for (const n of ['castle', 'interiors', 'rooms', 'rooms2', 'people2']) HL.BUILD = HL.BUILD.filter((f) => f.name !== n);
  HL.curtain = function (hex) { HL._curt = HL._curt || {}; if (!HL._curt[hex]) { const m = new THREE.MeshStandardMaterial({ color: hex, roughness: 0.95, envMapIntensity: 0.15 }); m.userData.tscale = 1; HL._curt[hex] = m; } return HL._curt[hex]; };
  HL.BUILD.unshift(async function plancastle(L) {
    for (const h of HL.DUN.holes) HL.occ.mark(0, (h[0] + h[2]) / 2, (h[1] + h[3]) / 2, (h[2] - h[0]) / 2 + 0.7, (h[3] - h[1]) / 2 + 0.7, 0, 6);
    const NF = HL.ALLK.length, PS = HL.ALLK.map((k) => HL.plan(k)); HL.zones.length = 0; HL.WELL = null; const P0 = PS[0], M = HL.M(), G = GK.M(), I = HL.IM(), Y = HL.Y0, H1 = HL.PL.H1, X = P0.X, Z = P0.Z, NX = P0.NX, NZ = P0.NZ;
    const bx = (i0, j0, i1, j1, y0, y1, mat, o) => KIT.box(X(i1 + 1), y0, Z(j1 + 1), X(i0), y1, Z(j0), mat, o), rs = mulberry(71);
    const turf = new THREE.MeshStandardMaterial({ color: 0x4a3a26, roughness: 1 }); turf.userData.tscale = 1;
    // how high the built storeys stand over each cell (0 = nothing built), and whether the top storey carries on up
    const baseTop = new Float32Array(NX * NZ), goesUp = new Uint8Array(NX * NZ);
    for (let j = 0; j < NZ; j++) for (let i = 0; i < NX; i++) { const s = j * NX + i; let b = 0; if (P0.roofed[s]) b = P0.ceil(i, j); for (const k of HL.UP) if (k > 0 && PS[k].roofed[s]) b = Math.max(b, (PS[k].s + 1) * H1); baseTop[s] = b; goesUp[s] = b ? 1 : 0; }
    /* toward evening the castle is lit from within: a good third of its windows burn, as many again glow dimly */ const rsG = mulberry(4711), GLZ = () => HL.pickGlass(rsG, 0.3);
    const GHt = HL.TALLR[0], inGH = (i, j) => i >= GHt[0] - 2 && j >= GHt[1] - 2 && i <= GHt[2] + 2 && j <= GHt[3] + 2, topOf = (i, j) => { const b = baseTop[j * NX + i]; return b ? Math.max(P0.T(i, j), b + 0.4) : 0; };
    const built = (i, j) => i >= 0 && j >= 0 && i < NX && j < NZ && baseTop[j * NX + i] > 0;
    for (const k of HL.ALLK) { const P = PS[k], yk = P.y, sk = P.s, UG = false, HC = H1, inside = (i, j) => P.rf(i, j) || (k > 0 && !UG && P0.ind(i, j) && HL.tallAt(i, j) > sk * H1 + 0.5), well = (i, j) => { const x = HL.PL.X0 - i - 0.5, z = HL.PL.Z0 - j - 0.5; for (const h of HL.DUN.holes) if (x > h[0] && x < h[2] && z > h[1] && z < h[3]) return true; return false; };
      // ---- floors
      greedy(P, (i, j) => { const ch = P.at(i, j); if (k === 0 && well(i, j)) return null; if (P.ind(i, j)) { if (ch === 'c' || ch === 'e') return 'c'; if (ch === 's') return 's'; const cc = P.compAt(i, j), t = cc && cc.kind === 'room' ? cc.type : ''; return /^(class|tutor|study|office|staff|lounge|dorm|library|music|head|art|chess|mirror|owl|duel|requirement|hospital)$/.test(t) ? 'W' : /^(lobby|gallery|trophy|chamber|clock|ring|entrance)$/.test(t) && k === 0 ? 'M' : 'F'; } if (k > 0) return P.rf(i, j) ? 'F' : null; if (P.rf(i, j)) return 'F'; if (ch === 'P' || ch === 's' || ch === 'F') return 'P'; if (ch === '#') return 'P'; return null; },
        (i0, j0, i1, j1, q) => bx(i0, j0, i1, j1, k ? yk - 0.3 : yk - 1.4, yk, M.stone, { faces: 'YyxXzZ', mats: { y: G.web, Y: UG ? I.flagD : q === 'c' ? I.flagD : q === 's' || q === 'M' ? I.marble : q === 'W' ? I.oak : q === 'F' ? (k ? I.oak : I.flag) : q === 'h' ? turf : M.pave } }));
      if (UG) greedy(P, (i, j) => P.rf(i, j) && !P0.rf(i, j) && !'PsF#h'.includes(P0.at(i, j)) ? 'c' : null, (i0, j0, i1, j1) => bx(i0, j0, i1, j1, Y - 1.4, Y - 0.45, G.dark, { faces: 'yxXzZ' }));
      // ---- parapets where paving (bridges, terraces) runs beside the gorge
      for (let j = 1; j < NZ - 1; j++) for (let i = 1; i < NX - 1; i++) { if (P.at(i, j) !== 'P') continue; if (P.at(i, j - 1) === 'w') KIT.box(X(i + 1), yk, Z(j) - 0.3, X(i), yk + 1.1, Z(j), M.stone, {}); if (P.at(i, j + 1) === 'w') KIT.box(X(i + 1), yk, Z(j + 1), X(i), yk + 1.1, Z(j + 1) + 0.3, M.stone, {}); if (P.at(i - 1, j) === 'w') KIT.box(X(i) - 0.3, yk, Z(j + 1), X(i), yk + 1.1, Z(j), M.stone, {}); if (P.at(i + 1, j) === 'w') KIT.box(X(i + 1), yk, Z(j + 1), X(i + 1) + 0.3, yk + 1.1, Z(j), M.stone, {}); }
      // ---- where the windows will be: those wall cells are built as a sill and a lintel, so the sun really comes in
      const WC = new Map(); (HL.WIN = HL.WIN || {})[k] = WC; const tallW = (i, j) => k === 0 && HL.tallAt(i, j) > H1 + 1, outW = (i, j) => !P.rf(i, j) && !HL.inShaft(i, j) && !(k > 0 && P0.ind(i, j) && HL.tallAt(i, j) > sk * H1 + 0.5);
      if (!UG) { for (let j = 0; j < NZ; j++) for (const dirN of [true, false]) { let i = 0; while (i < NX) { const ex = (q) => P.rf(q, j) && outW(q, j + (dirN ? -1 : 1)); if (!ex(i)) { i++; continue; } let e = i; while (e + 1 < NX && ex(e + 1)) e++; const len = e - i + 1; if (len >= 3) { const n = Math.max(1, Math.round(len / 5.6)); for (let q = 0; q < n; q++) { const ci = Math.round(i + (q + 0.5) * len / n - 0.5); if (!P.isW(ci, j) || P.door[j * NX + ci]) continue; let d = 1; while (d <= 3 && P.isW(ci, j + (dirN ? d : -d))) d++; const inJ = j + (dirN ? d : -d); if (d > 3 || !P.ind(ci, inJ)) continue; const tl = tallW(ci, inJ), o = tl ? [4.2, 4.2 + Math.min(HL.tallAt(ci, inJ) - 5, 15) * 0.8] : [2.2, 5.3]; for (let t = 0; t < d; t++) for (const a of (tl ? [-1, 0, 1] : [0])) if (P.isW(ci + a, j + (dirN ? t : -t))) WC.set((j + (dirN ? t : -t)) * NX + ci + a, o); } } i = e + 1; } }
        for (let i = 0; i < NX; i++) for (const dirE of [true, false]) { let j = 0; while (j < NZ) { const ex = (q) => P.rf(i, q) && outW(i + (dirE ? 1 : -1), q); if (!ex(j)) { j++; continue; } let e = j; while (e + 1 < NZ && ex(e + 1)) e++; const len = e - j + 1; if (len >= 3) { const n = Math.max(1, Math.round(len / 5.6)); for (let q = 0; q < n; q++) { const cj = Math.round(j + (q + 0.5) * len / n - 0.5); if (!P.isW(i, cj) || P.door[cj * NX + i]) continue; let d = 1; while (d <= 3 && P.isW(i + (dirE ? -d : d), cj)) d++; const inI = i + (dirE ? -d : d); if (d > 3 || !P.ind(inI, cj)) continue; const tl = tallW(inI, cj), o = tl ? [4.2, 4.2 + Math.min(HL.tallAt(inI, cj) - 5, 15) * 0.8] : [2.2, 5.3]; for (let t = 0; t < d; t++) for (const a of (tl ? [-1, 0, 1] : [0])) if (P.isW(i + (dirE ? -t : t), cj + a)) WC.set((cj + a) * NX + i + (dirE ? -t : t), o); } } j = e + 1; } } }
      // ---- walls, run by run
      for (let j = 0; j < NZ; j++) { let i = 0; while (i < NX) { if (!P.isW(i, j)) { i++; continue; } const SH = HL.SHAFT, ring = (a, b) => sk >= 2 && a >= SH.i0 && a <= SH.i1 && b >= SH.j0 && b <= SH.j1 && !HL.inShaft(a, b), sig = (q) => { if (!P.rf(q, j) && !ring(q, j)) { if (k > 0) return 'n'; let gh = 0, nb = 0; for (const [di, dj] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) { if (P.at(q + di, j + dj) === 'h') gh = 1; if (P.isW(q + di, j + dj)) nb++; } return gh ? 'g' : nb <= 1 ? 'p' : 'l'; }
            if (k > 0 && !UG && P0.isW(q, j) && P0.rf(q, j) && P0.ceil(q, j) >= (sk + 1) * H1 - 0.1) return 'n'; const wo = WC.get(j * NX + q); let da = ''; if (k === 0 && P.ceil(q, j) > H1 + 1) { for (let kk = 1; kk < PS.length; kk++) if (PS[kk].door[j * NX + q] && P.ceil(q, j) > kk * H1 + 0.5) da += kk; if (da) da = 'D' + da + 'd'; } return 'w' + P.ceil(q, j) + (wo ? 'W' + wo[0] + '_' + wo[1] : '') + da + (inside(q, j - 1) ? 'i' : 'o') + (inside(q, j + 1) ? 'i' : 'o'); };
          const s0 = sig(i); let e = i; while (e + 1 < NX && P.isW(e + 1, j) && sig(e + 1) === s0) e++;
          if (s0 === 'g') bx(i, j, e, j, yk, yk + 3.4, M.green, { mats: { Y: M.lead } }); else if (s0 === 'p') { for (let q = i; q <= e; q++) { const px = X(q) - 0.5, pz = Z(j) - 0.5; GK.pier(px, pz, yk, 4.6, 0.34, { col: false }); PHY.cyl(px, pz, 0.5, yk, yk + 4.6); if ((q + j) % 2 === 0) { KIT.geo(new THREE.SphereGeometry(0.22, 8, 6), KIT.emis(0xffc070, 2.6), new THREE.Matrix4().makeTranslation(px, yk + 4.95, pz)); if ((q + j) % 4 === 0) HL.sl(px, yk + 5.2, pz, 0xffb060, 7, 10); } } } else if (s0 === 'l') bx(i, j, e, j, yk, yk + 1.25, M.stone, { mats: { Y: M.trim } });
          else if (s0 !== 'n') { const h = UG ? HC : P.ceil(i, j), nO = s0[s0.length - 2] === 'o', sO = s0[s0.length - 1] === 'o'; const WM = UG ? G.dark : G.wall, XM = UG ? G.dark : M.stone, mats = { Z: nO ? XM : WM, z: sO ? XM : WM, X: inside(i - 1, j) ? WM : XM, x: inside(e + 1, j) ? WM : XM, Y: G.dress, y: G.dress }, wo = WC.get(j * NX + i), dm = /D(\d+)d/.exec(s0); if (dm) { /* a hall that rises through the storeys above: its wall is left open where one of them has a doorway (that storey builds the arch) */ let ya = 0; for (const kk of dm[1].split('').map(Number)) { if (kk * H1 > ya) bx(i, j, e, j, yk + ya, yk + kk * H1, WM, { faces: 'xXzZY', mats }); ya = (kk + 1) * H1; } if (ya < h) bx(i, j, e, j, yk + ya, yk + h, WM, { faces: 'xXzZy', mats }); } else if (wo && wo[1] < h - 0.3) { bx(i, j, e, j, yk, yk + wo[0], WM, { faces: 'xXzZY', mats }); bx(i, j, e, j, yk + wo[1], yk + h, WM, { faces: 'xXzZy', mats }); PHY.box(X(e + 1), yk + wo[0], Z(j + 1), X(i), yk + wo[1], Z(j)); } else bx(i, j, e, j, yk, yk + h, WM, { faces: 'xXzZ', mats }); }
          i = e + 1; } }
      // ---- doorways
      for (const d of P.doors) { KIT.tag = d.inn ? 'in' + k : ''; const w = d.dir === 1 ? d.i1 - d.i0 : d.j1 - d.j0, t = d.dir === 1 ? d.j1 - d.j0 : d.i1 - d.i0, cx = (X(d.i0) + X(d.i1)) / 2, cz = (Z(d.j0) + Z(d.j1)) / 2, grand = k === 0 && d.dir === 1 && d.j0 === 252 && d.i0 === 156, top = grand ? 6.2 : Math.min(4.6, 2.6 + w * 0.55);
        if (d.inn) { const h = UG ? HC : Math.max(P.ceil(d.i0, d.j0), H1), ext = d.dir === 1 ? (!P.rf(d.i0, d.j0 - 1) || !P.rf(d.i0, d.j1)) : (!P.rf(d.i0 - 1, d.j0) || !P.rf(d.i1, d.j0)); d.ext = ext; if (ext && k > 0 && !UG) { // on the upper floors a gap in an outer wall is a window the plan drew: glaze it
            KIT.tag = ''; bx(d.i0, d.j0, d.i1 - 1, d.j1 - 1, yk, yk + h, M.stone, { faces: 'xXzZ', mats: { Z: G.wall, z: G.wall, X: G.wall, x: G.wall }, col: true }); const ww = Math.min(1.7, w * 0.8);
            if (d.dir === 1) { const outN = !P.rf(d.i0, d.j0 - 1), z = outN ? Z(d.j0) : Z(d.j1), zi = outN ? Z(d.j1) : Z(d.j0), sg = outN ? 1 : -1; HL.win(cx, yk + 2.2, z + sg * 0.02, outN ? 0 : PI, ww, 3.7, GLZ()); KIT.tag = 'in' + k; const W = HL.winGeo(ww, 3.7), m4 = new THREE.Matrix4().makeRotationY(outN ? PI : 0); m4.setPosition(cx, yk + 2.2, zi - sg * 0.03); KIT.geo(W.frame, G.dress, m4, { worldUV: true }); KIT.geo(W.glass, G.day, m4, { uvs: 1 }); }
            else { const outE = !P.rf(d.i1, d.j0), x = outE ? X(d.i1) : X(d.i0), xi = outE ? X(d.i0) : X(d.i1), sg = outE ? -1 : 1; HL.win(x + sg * 0.02, yk + 2.2, cz, outE ? -HALF : HALF, ww, 3.7, GLZ()); KIT.tag = 'in' + k; const W = HL.winGeo(ww, 3.7), m4 = new THREE.Matrix4().makeRotationY(outE ? HALF : -HALF); m4.setPosition(xi - sg * 0.03, yk + 2.2, cz); KIT.geo(W.frame, G.dress, m4, { worldUV: true }); KIT.geo(W.glass, G.day, m4, { uvs: 1 }); }
            continue; }
          if (UG && ext) { bx(d.i0, d.j0, d.i1 - 1, d.j1 - 1, yk, yk + h, G.dark, { faces: 'xXzZ', col: true }); continue; } KIT.tag = ''; bx(d.i0, d.j0, d.i1 - 1, d.j1 - 1, yk + top + 0.2, yk + h, UG ? G.dark : ext ? M.stone : G.wall, { faces: 'xXzZy', col: true }); KIT.tag = ext ? '' : 'in' + k; GK.arch(cx, yk, cz, d.dir === 1 ? 0 : HALF, w, top * 0.6, top, { d: t + 0.24, f: 0.26 }); if (!ext && w >= 2 && w <= 3 && ((d.i0 * 7 + d.j0 * 3 + k) % 5) < 3) HL.doors(cx + (d.dir === 1 ? 0 : (((d.i0 + k) % 2) ? 1 : -1) * (t / 2 + 0.05)), yk, cz + (d.dir === 1 ? (((d.j0 + k) % 2) ? 1 : -1) * (t / 2 + 0.05) : 0), d.dir === 1 ? 'x' : 'z', w, top * 0.6 + 0.2, ((d.i0 + d.j0) % 2) ? 1 : -1);
          if (ext && k > 0 && !UG) { if (d.dir === 1) KIT.box(X(d.i1), yk, cz - 0.15, X(d.i0), yk + 1.1, cz + 0.15, G.dress, {}); else KIT.box(cx - 0.15, yk, Z(d.j1), cx + 0.15, yk + 1.1, Z(d.j0), G.dress, {}); } }
        else if (k === 0 && P.at(d.i0, d.j0) !== 'h') { bx(d.i0, d.j0, d.i1 - 1, d.j1 - 1, yk + 4.7, yk + 5.2, G.dress, { col: false }); GK.arch(cx, yk, cz, d.dir === 1 ? 0 : HALF, w, 2.9, 4.6, { d: t + 0.1, f: 0.2 }); } }
      KIT.tag = '';
      // ---- this storey's windows: a traceried light outside, the same light pouring day into the room
      const tall = (i, j) => k === 0 && HL.tallAt(i, j) > H1 + 1, outA = (i, j) => !P.rf(i, j) && !HL.inShaft(i, j) && !(k > 0 && P0.ind(i, j) && HL.tallAt(i, j) > sk * H1 + 0.5);
      const win = (x, z, th, sg, horiz, ci, cj, d, isTall) => { const hh = isTall ? Math.min(HL.tallAt(ci, cj) - 5, 15) : 3.7, ww = isTall ? 3.2 : 1.7, y0 = isTall ? yk + 4.2 : yk + 2.2; if (!isTall && !UG) { const cc = P.compAt(ci, cj), ty = cc && cc.kind === 'room' ? (cc.type || '') : '', nm2 = (cc && cc.name) || '', cm = HL.curtain(/GRYFFINDOR/.test(nm2) ? 0x7a1420 : /RAVENCLAW/.test(nm2) ? 0x1c3a70 : /SLYTHERIN/.test(nm2) ? 0x1c4a30 : ty === 'hospital' ? 0x9a9484 : ty === 'library' || ty === 'study' ? 0x24402c : ty === 'potions' ? 0x2c2440 : ty === 'lounge' ? 0x5a2a50 : 0x64181e), e = ww / 2 + 0.26, yb = y0 - 0.35, yt = y0 + hh + 0.25, a0 = d - sg * 0.05, a1 = d - sg * 0.2, lo = Math.min(a0, a1), hi = Math.max(a0, a1), ryIn = horiz ? (sg > 0 ? PI : 0) : (sg > 0 ? -HALF : HALF);
          if (HL.hangClaim(horiz ? x : d, horiz ? d : z, ryIn, e * 2 + 0.5, yb, yt + 0.2)) { KIT.tag = 'in' + k; for (const s2 of [-1, 1]) for (let f = 0; f < 3; f++) { const c0 = (horiz ? x : z) + s2 * (e - 0.14 + f * 0.13), wd = 0.075; if (horiz) KIT.box(c0 - wd, yb + f * 0.03, lo - f * 0.012, c0 + wd, yt, hi + f * 0.012, cm, { col: false }); else KIT.box(lo - f * 0.012, yb + f * 0.03, c0 - wd, hi + f * 0.012, yt, c0 + wd, cm, { col: false }); }
            if (horiz) { KIT.box(x - e - 0.42, yt - 0.42, lo - 0.03, x + e + 0.42, yt + 0.04, hi + 0.03, cm, { col: false }); KIT.box(x - e - 0.5, yt + 0.04, lo - 0.02, x + e + 0.5, yt + 0.1, hi + 0.02, M.gold, { col: false }); } else { KIT.box(lo - 0.03, yt - 0.42, z - e - 0.42, hi + 0.03, yt + 0.04, z + e + 0.42, cm, { col: false }); KIT.box(lo - 0.02, yt + 0.04, z - e - 0.5, hi + 0.02, yt + 0.1, z + e + 0.5, M.gold, { col: false }); } KIT.tag = ''; } } if (horiz) HL.win(x, y0, z + sg * 0.02, th, ww, hh, GLZ()); else HL.win(x + sg * 0.02, y0, z, th, ww, hh, GLZ());
        KIT.tag = 'in' + k; const W = HL.winGeo(ww, hh), m4 = new THREE.Matrix4().makeRotationY(th + PI); if (horiz) m4.setPosition(x, y0, d - sg * 0.03); else m4.setPosition(d - sg * 0.03, y0, z); KIT.geo(W.frame, G.dress, m4, { worldUV: true }); KIT.geo(W.glass, G.day, m4, { uvs: 1 }); KIT.geo(W.sill, G.dress, m4, { worldUV: true }); KIT.tag = ''; if (horiz) HL.sl(x, y0 + hh * 0.5, d - sg * 1.6, 0x9cbcff, isTall ? 9 : 5, isTall ? 14 : 8.5); else HL.sl(d - sg * 1.6, y0 + hh * 0.5, z, 0x9cbcff, isTall ? 9 : 5, isTall ? 14 : 8.5); const inRoom = (px, pz) => { const pi = Math.floor(HL.PL.X0 - px), pj = Math.floor(HL.PL.Z0 - pz); return P.comp[pj * NX + pi] === P.comp[cj * NX + ci] && P.comp[pj * NX + pi] >= 0; }, sunny = horiz ? GK.patch(x, y0, d, 0, -sg, ww, hh, yk, inRoom) : GK.patch(d, y0, z, -sg, 0, ww, hh, yk, inRoom); if (sunny || isTall) { if (horiz) GK.shaft(x, y0, d - sg * 0.1, 0, -sg, ww, hh); else GK.shaft(d - sg * 0.1, y0, z, -sg, 0, ww, hh); } };
      if (!UG) for (let j = 0; j < NZ; j++) for (const dirN of [true, false]) { let i = 0; while (i < NX) { const ex = (q) => P.rf(q, j) && outA(q, j + (dirN ? -1 : 1)); if (!ex(i)) { i++; continue; } let e = i; while (e + 1 < NX && ex(e + 1)) e++; const len = e - i + 1; if (len >= 3) { const n = Math.max(1, Math.round(len / 5.6)), z = dirN ? Z(j) : Z(j + 1), sg = dirN ? 1 : -1;
            for (let q = 0; q < n; q++) { const ci = Math.round(i + (q + 0.5) * len / n - 0.5); if (!P.isW(ci, j) || P.door[j * NX + ci]) continue; let d = 1; while (d <= 3 && P.isW(ci, j + (dirN ? d : -d))) d++; const inJ = j + (dirN ? d : -d); if (d > 3 || !P.ind(ci, inJ)) { HL.win(X(ci) - 0.5, yk + 2.2, z + sg * 0.02, dirN ? 0 : PI, 1.7, 3.7, HL.pickGlass(rs, 0.4)); continue; } win(X(ci) - 0.5, z, dirN ? 0 : PI, sg, true, ci, inJ, dirN ? Z(j + d) : Z(j - d + 1), tall(ci, inJ)); } } i = e + 1; } }
      if (!UG) for (let i = 0; i < NX; i++) for (const dirE of [true, false]) { let j = 0; while (j < NZ) { const ex = (q) => P.rf(i, q) && outA(i + (dirE ? 1 : -1), q); if (!ex(j)) { j++; continue; } let e = j; while (e + 1 < NZ && ex(e + 1)) e++; const len = e - j + 1; if (len >= 3) { const n = Math.max(1, Math.round(len / 5.6)), x = dirE ? X(i + 1) : X(i), sg = dirE ? -1 : 1;
            for (let q = 0; q < n; q++) { const cj = Math.round(j + (q + 0.5) * len / n - 0.5); if (!P.isW(i, cj) || P.door[cj * NX + i]) continue; let d = 1; while (d <= 3 && P.isW(i + (dirE ? -d : d), cj)) d++; const inI = i + (dirE ? -d : d); if (d > 3 || !P.ind(inI, cj)) { HL.win(x + sg * 0.02, yk + 2.2, Z(cj) - 0.5, dirE ? -HALF : HALF, 1.7, 3.7, HL.pickGlass(rs, 0.4)); continue; } win(x, Z(cj) - 0.5, dirE ? -HALF : HALF, sg, false, inI, cj, dirE ? X(i - d + 1) : X(i + d), tall(inI, cj)); } } j = e + 1; } }
      KIT.tag = 'in' + k;
      // ---- names, vaults, light: every room and corridor of this storey
      for (const c of P.comps) { if (c.kind !== 'room' && c.kind !== 'corr') continue; const B = c.kind === 'room' ? c.R : c, x0 = X(B.i1 + 1), x1 = X(B.i0), z0 = Z(B.j1 + 1), z1 = Z(B.j0), w = x1 - x0, d = z1 - z0, tl = k === 0 && HL.tallAt((B.i0 + B.i1) >> 1, (B.j0 + B.j1) >> 1);
        if (c.type === 'greathall') HL.zone(c.name, X(c.i1 + 1) - 0.6, Z(c.j1 + 1) - 0.6, X(c.i0) + 0.6, Z(c.j0) + 0.6, yk - 0.6, yk + 40, {}); else if (c.type === 'entrance') HL.zone(c.name, X(c.i1 + 1) - 0.6, Z(c.j1 + 1) - 0.6, X(c.i0) + 0.6, Z(c.j0) + 0.6, yk - 0.6, yk + 15, {}); else if (c.type === 'shaft') { /* the staircase has its own zone */ } else if (c.name) HL.zone(c.name, X(c.i1 + 1) - 0.6, Z(c.j1 + 1) - 0.6, X(c.i0) + 0.6, Z(c.j0) + 0.6, yk - 0.6, yk + HC - 0.4, { hemi: UG ? 0.045 : { potions: 0.04, library: 0.065, hospital: 0.13, dorm: 0.06, lounge: 0.06, armoury: 0.07, store: 0.05 }[c.type] || 0.055 }); else if (c.kind === 'corr' && c.n > 40) HL.zone(['THE CLOISTERS', 'THE FIRST-FLOOR CORRIDORS', 'THE SECOND-FLOOR CORRIDORS', 'THE THIRD-FLOOR CORRIDORS', 'THE FOURTH-FLOOR CORRIDORS'][k], X(c.i1 + 1) - 0.6, Z(c.j1 + 1) - 0.6, X(c.i0) + 0.6, Z(c.j0) + 0.6, yk - 0.6, yk + H1 - 0.4, {});
        const solid = (i, j) => P.isW(i, j) && !P.door[j * NX + i], pan = (axis, cc, side, a0, a1, wallAt, ph) => { let st = null; for (let q = a0; q <= a1 + 1; q++) { const ok = q <= a1 && wallAt(q); if (ok && st === null) st = q; if (!ok && st !== null) { const ua = axis === 'x' ? X(q) : Z(q), ub = axis === 'x' ? X(st) : Z(st); if (ub - ua >= 1.5) HL.wainscot(axis, cc, ua + 0.05, ub - 0.05, yk, ph, side); st = null; } } },
          panAll = (ph) => { const lowW = (i, j) => solid(i, j) && !(WC.has(j * NX + i) && WC.get(j * NX + i)[0] < ph + 0.3); pan('x', z0, 1, B.i0, B.i1, (i) => lowW(i, B.j1 + 1), ph); pan('x', z1, -1, B.i0, B.i1, (i) => lowW(i, B.j0 - 1), ph); pan('z', x0, 1, B.j0, B.j1, (j) => lowW(B.i1 + 1, j), ph); pan('z', x1, -1, B.j0, B.j1, (j) => lowW(B.i0 - 1, j), ph); };
        if (c.kind === 'room' && k === 0 && c.tallH && c.tallH < 14 && !HL.WELLN[c.name] && c.type !== 'clock' && w >= 8 && d >= 8) { // a great room two storeys high: oak to the dado, a string course, a timber roof on arch-braced trusses, great iron crowns of candles
          const IO = HL.IM(), yT = yk + c.tallH - 0.36, yS = yT - 4.6, spanX = w <= d, s0 = spanX ? x0 : z0, s1 = spanX ? x1 : z1, u0 = spanX ? z0 : x0, u1 = spanX ? z1 : x1, hw = (s1 - s0) / 2, P3 = (u, yy, sv) => spanX ? [sv, yy, u] : [u, yy, sv], nT = Math.max(2, Math.round((u1 - u0) / 4.8));
          KIT.box(x0, yT, z0, x1, yT + 0.14, z1, IO.oakD, { col: false, faces: 'y' });
          for (let q = 0; q <= nT; q++) { const u = clamp(u0 + q * (u1 - u0) / nT, u0 + 0.3, u1 - 0.3); KIT.beam(P3(u, yT - 0.3, s0), P3(u, yT - 0.3, s1), 0.5, IO.oak);
            for (const sd of [-1, 1]) { const sw = sd < 0 ? s0 : s1, S = (dd) => sw - sd * dd; KIT.beam(P3(u, yS, S(0.26)), P3(u, yT - 0.3, S(0.26)), 0.4, IO.oak);
              GK.curve((t) => { const a = t * HALF; return P3(u, yS + 0.3 + (yT - 0.9 - yS) * Math.sin(a), S(0.36 + Math.min(hw - 0.5, 5.4) * (1 - Math.cos(a)))); }, 7, 0.32, IO.oak);
              const c0 = P3(u, yS - 0.55, S(0)), c1 = P3(u, yS, S(0.62)); KIT.box(Math.min(c0[0], c1[0]) - (spanX ? 0 : 0.34), c0[1], Math.min(c0[2], c1[2]) - (spanX ? 0.34 : 0), Math.max(c0[0], c1[0]) + (spanX ? 0 : 0.34), c1[1], Math.max(c0[2], c1[2]) + (spanX ? 0.34 : 0), G.dress, { col: false }); }
            const kp = P3(u, yT - 1.3, (s0 + s1) / 2); KIT.beam(kp, P3(u, yT - 0.3, (s0 + s1) / 2), 0.3, IO.oak); KIT.geo(new THREE.SphereGeometry(0.2, 8, 6).scale(1, 1.4, 1), M.gold, new THREE.Matrix4().makeTranslation(kp[0], kp[1] - 0.2, kp[2])); }
          for (const f of [0.25, 0.5, 0.75]) KIT.beam(P3(u0, yT - 0.12, lerp(s0, s1, f)), P3(u1, yT - 0.12, lerp(s0, s1, f)), 0.3, IO.oak);
          panAll(2.6); c.dado = 2.6;
          const nc = Math.max(1, Math.round((u1 - u0) / 9)); for (let q = 0; q < nc; q++) { const cp = P3(u0 + (q + 0.5) * (u1 - u0) / nc, yk + 6.6, (s0 + s1) / 2); HL.chandelier(L, cp[0], cp[1], cp[2], 2.0, 14, yT - 0.4, { i: 24, range: Math.max(hw * 2, 16) }); }
          c.vault = { nx: 1, nz: 1, timber: 1, tall: 1 }; }
        else if (c.kind === 'room' && w >= 4 && d >= 4 && !tl && !c.tallH && /^(lounge|study|dorm|head|staff|tutor|music|office|chamber|chess|art|mirror|owl|class|hospital|duel|requirement|trophy)$/.test(c.type || '')) { // a panelled room: oak wainscot round the walls, a beamed oak ceiling, iron chandeliers
          const yc = yk + H1 - 0.72, IO = HL.IM(), nb = Math.max(1, Math.round(w / 3.2)); KIT.box(x0, yc + 0.3, z0, x1, yc + 0.42, z1, IO.oakD, { col: false, faces: 'y' }); for (let q = 0; q <= nb; q++) { const x = x0 + q * w / nb; KIT.box(x - 0.2, yc - 0.12, z0, x + 0.2, yc + 0.3, z1, IO.oak, { col: false }); } for (const z of [z0 + 0.25, (z0 + z1) / 2, z1 - 0.25]) KIT.box(x0, yc - 0.34, z - 0.22, x1, yc + 0.3, z + 0.22, IO.oak, { col: false });
          panAll(2.5); c.dado = 2.5;
          const nx = Math.max(1, Math.round(w / 8)), nz = Math.max(1, Math.round(d / 8)); for (let a2 = 0; a2 < nx; a2++) for (let b2 = 0; b2 < nz; b2++) HL.chandelier(L, x0 + (a2 + 0.5) * w / nx, yk + H1 - 2.4, z0 + (b2 + 0.5) * d / nz, 1.1, 8, yc, { i: 14, range: Math.max(w / nx, d / nz) * 1.7 }); c.vault = { nx, nz, timber: 1 }; }
        else if (c.kind === 'room' && w >= 4 && d >= 4 && !tl && c.type !== 'entrance' && c.type !== 'greathall' && c.type !== 'shaft' && c.type !== 'ring' && c.type !== 'towerfoot' && !c.tallH) { /* an odd number of bays each way, so that no pier ever stands on the middle line of a room, where the carpet runs and the doors face one another */ const bays = (q) => { if (q <= 12.5) return 1; const r = Math.max(1, Math.round(q / 6.8)); return r % 2 ? r : r + 1; }, nx = bays(w), nz = bays(d), ys = yk + (UG ? 2.5 : 3.4), rise = HC - (ys - yk) - 0.4; GK.vaults(x0, z0, x1, z1, ys, rise, nx, nz, UG ? { rib: 0.2, n: 4, k: 5, web: G.dark, mat: G.dark, boss: false } : { rib: 0.16, n: 4, k: 5 });
          for (let a2 = 0; a2 <= nx; a2++) for (let b2 = 0; b2 <= nz; b2++) { const px = x0 + a2 * w / nx, pz = z0 + b2 * d / nz, ea = a2 === 0 || a2 === nx, eb = b2 === 0 || b2 === nz; if (!ea && !eb) { GK.respond(px, pz, yk, ys - yk, UG ? 0.42 : 0.3, { full: 1, mat: UG ? G.dark : undefined }); HL.occ.mark(k, px, pz, 0.7, 0.7, 0, 6); } else GK.respond(px + (a2 === 0 ? 0.14 : a2 === nx ? -0.14 : 0), pz + (b2 === 0 ? 0.14 : b2 === nz ? -0.14 : 0), yk, ys - yk, 0.17, UG ? { mat: G.dark } : undefined); }
          for (let a2 = 0; a2 < nx; a2++) for (let b2 = 0; b2 < nz; b2++) if (UG ? ((a2 + b2 * 2) % 3 === 0 || nx * nz < 3) : ((a2 + b2) % 2 === 0 || nx * nz < 3)) HL.chandelier(L, x0 + (a2 + 0.5) * w / nx, yk + HC - 2.0, z0 + (b2 + 0.5) * d / nz, Math.min(1.1, w / nx * 0.2), 6, yk + HC - 0.6, { i: UG ? 9 : 13, col: UG ? 0xff9a50 : undefined, range: Math.max(w / nx, d / nz) * 1.9 }); c.vault = { nx, nz }; } }
      // the walls of every furnished room: portraits, a tapestry or two, a sconce — wherever there is masonry to hang them on
      if (!UG) (HL._hang = HL._hang || []).push(() => { KIT.tag = 'in' + k; for (const c of P.comps) { if (c.kind !== 'room' || !c.name || c.type === 'greathall' || c.type === 'entrance' || c.type === 'store' || c.type === 'shaft' || c.type === 'ring' || c.type === 'head' || HL.WELLN[c.name]) continue; const B = c.R, x0 = X(B.i1 + 1), x1 = X(B.i0), z0 = Z(B.j1 + 1), z1 = Z(B.j0); let q = c.id * 3;
        const dd = c.dado || 0, ceilH = (c.tallH && k === 0 ? Math.min(c.tallH, 8) : H1) - 0.9;
        const hang = (px, pz, nx, nz) => { const wi = Math.floor(HL.PL.X0 - (px - nx * 0.5)), wj = Math.floor(HL.PL.Z0 - (pz - nz * 0.5)); if (!P.isW(wi, wj) || P.door[wj * NX + wi]) return; let sill = 99, lint = 0; const wv0 = WC.get(wj * NX + wi); if (wv0) { sill = wv0[0]; lint = wv0[1]; }
          for (const o of [-1, 1]) { const ai = Math.floor(HL.PL.X0 - (px - nx * 0.5 + nz * o)), aj = Math.floor(HL.PL.Z0 - (pz - nz * 0.5 + nx * o)); if (!P.isW(ai, aj) || P.door[aj * NX + ai]) return; const wv = WC.get(aj * NX + ai); if (wv) { sill = Math.min(sill, wv[0]); lint = Math.max(lint, wv[1]); } const fi = Math.floor(HL.PL.X0 - (px + nx * 0.5 + nz * o)), fj = Math.floor(HL.PL.Z0 - (pz + nz * 0.5 + nx * o)); if (P.isW(fi, fj)) return; /* an inside corner within a pace: it would run into the other wall */ }
          for (const o of [-0.8, 0, 0.8]) if (HL.occ.at(k, px + nx * 0.35 + nz * o, pz + nz * 0.35 + nx * o) === 5) return; q++; const ry = Math.atan2(nx, nz), kind = q % 5, free = (lo, hi) => !(sill < hi && lint > lo);
          if (kind < 3) { const w2 = 0.9 + (q % 4) * 0.2, h2 = w2 * 1.25, lo = Math.max(dd + 0.3, 1.75 + (q % 3) * 0.3); if (lo + h2 + 0.26 < ceilH && free(lo - 0.15, lo + h2 + 0.15)) HL.portrait(px + nx * 0.06, yk + lo + h2 / 2, pz + nz * 0.06, ry, w2, q); }
          else if (kind === 3) { const top = Math.min(ceilH, 5.6), hb = Math.min(3.0, top - dd - 0.25); if (hb > 1.2 && free(top - hb, top) && HL.wallOK(px, pz, ry, 1.5, yk + top - hb, yk + top) && HL.hangClaim(px, pz, ry, 1.4, yk + top - hb, yk + top)) HL.banner(px + nx * 0.12, yk + top, pz + nz * 0.12, ry, 1.4, hb, Object.keys(HL.HOUSES)[q % 4]); }
          else if (free(2.2, 3.6) && HL.hangClaim(px, pz, ry, 0.5, yk + Math.max(2.9, dd + 0.45) - 0.4, yk + Math.max(2.9, dd + 0.45) + 0.5)) HL.sconce(L, px, yk + Math.max(2.9, dd + 0.45), pz, nx, nz, { i: 7, range: 8 }); };
        for (let x = x0 + 2.2; x < x1 - 1.5; x += 4.3) { hang(x, z0, 0, 1); hang(x + 1.6, z1, 0, -1); } for (let z = z0 + 2.2; z < z1 - 1.5; z += 4.3) { hang(x0, z, 1, 0); hang(x1, z + 1.6, -1, 0); } } KIT.tag = ''; });
      // corridors (the passages the plan colours): ribs overhead, a runner, sconces, portraits, benches, armour, hangings
      greedy(P, (i, j) => { const ch = P.at(i, j); return P.ind(i, j) && !P.door[j * NX + i] && ch === 'c' ? 'c' : null; }, (i0, j0, i1, j1) => { const x0 = X(i1 + 1), x1 = X(i0), z0 = Z(j1 + 1), z1 = Z(j0), w = x1 - x0, d = z1 - z0, alongX = w >= d, len = alongX ? w : d, wid = alongX ? d : w; if (wid < 2 || len < 3) return;
        const n = Math.max(1, Math.round(len / Math.max(3.2, wid))); if (alongX) GK.vaults(x0, z0, x1, z1, yk + HC - 2.6, 2.2, n, 1, { rib: 0.14, n: 3, k: 4, boss: false, ribs: 'xX', web: UG ? G.dark : undefined, mat: UG ? G.dark : undefined }); else GK.vaults(x0, z0, x1, z1, yk + HC - 2.6, 2.2, 1, n, { rib: 0.14, n: 3, k: 4, boss: false, ribs: 'zZ', web: UG ? G.dark : undefined, mat: UG ? G.dark : undefined });
        if (wid >= 3 && len > 8) { if (alongX) KIT.box(x0 + 0.4, yk + 0.004, (z0 + z1) / 2 - 0.7, x1 - 0.4, yk + 0.016, (z0 + z1) / 2 + 0.7, HL.houseMats().rug, { col: false }); else KIT.box((x0 + x1) / 2 - 0.7, yk + 0.004, z0 + 0.4, (x0 + x1) / 2 + 0.7, yk + 0.016, z1 - 0.4, HL.houseMats().rug, { col: false }); }
        HL.CORR = HL.CORR || []; HL.CORR.push({ k, x0, x1, z0, z1, alongX, len, wid, y: yk });
        // a point on a side wall: u along, sd = which side; returns [x, z, nx, nz] if there is masonry behind it
        const side = (u, sd) => { const px = alongX ? x0 + u : (sd > 0 ? x1 : x0), pz = alongX ? (sd > 0 ? z1 : z0) : z0 + u, nx = alongX ? 0 : -sd, nz = alongX ? -sd : 0, wi = Math.floor(HL.PL.X0 - (px - nx * 0.5)), wj = Math.floor(HL.PL.Z0 - (pz - nz * 0.5)); return P.isW(wi, wj) && !P.door[wj * NX + wi] && !WC.has(wj * NX + wi) ? [px, pz, nx, nz] : null; };
        if (!UG && wid >= 2.5) for (const sd of [-1, 1]) { let ua = -1; for (let u = 0; u <= len + 0.01; u += 1) { const ok = u < len - 0.4 && !!side(u + 0.5, sd); if (ok && ua < 0) ua = u; if (!ok && ua >= 0) { if (u - ua >= 2) { if (alongX) HL.wainscot('x', sd > 0 ? z1 : z0, x0 + ua + 0.04, x0 + Math.min(u, len) - 0.04, yk, 1.45, -sd); else HL.wainscot('z', sd > 0 ? x1 : x0, z0 + ua + 0.04, z0 + Math.min(u, len) - 0.04, yk, 1.45, -sd); } ua = -1; } } }
        let q = 0; for (let u = 1.6; u < len - 1.2; u += 2.6, q++) for (const sd of [-1, 1]) { const s = side(u, sd); if (!s) continue; const kind = Math.abs((q * 7 + (sd > 0 ? 3 : 0) + ((x0 * 3 + z0) | 0)) % 9), ry = Math.atan2(s[2], s[3]);
            if (q % 3 === (sd > 0 ? 0 : 1)) { if (HL.hangClaim(s[0], s[1], ry, 0.5, yk + 2.5, yk + 3.4)) HL.sconce(L, s[0], yk + 2.9, s[1], s[2], s[3], { i: 10, range: 10 }); continue; }
            if (kind < 5) { if (side(u - 0.9, sd) && side(u + 0.9, sd)) { const w2 = 0.8 + (kind % 4) * 0.22, lo = (wid >= 2.5 && !UG ? 1.45 : 0) + 0.3 + (kind % 3) * 0.2; HL.portrait(s[0] + s[2] * 0.06, yk + lo + w2 * 0.625, s[1] + s[3] * 0.06, ry, w2, q + kind + (sd > 0 ? 5 : 0)); } }
            else if (kind === 5 && wid >= 3 && HL.occ.put(k, s[0] + s[2] * 0.4, s[1] + s[3] * 0.4, 0.9, 0.3, ry, 0.1)) { KIT.obox(s[0] + s[2] * 0.4, yk + 0.42, s[1] + s[3] * 0.4, 0.9, yk + 0.5, 0.24, ry, I.oak, { col: false }); for (const e of [-0.75, 0.75]) KIT.obox(s[0] + s[2] * 0.4 + Math.cos(ry) * e, yk, s[1] + s[3] * 0.4 - Math.sin(ry) * e, 0.05, yk + 0.42, 0.2, ry, I.oakD, { col: false }); PHY.obox(s[0] + s[2] * 0.4, s[1] + s[3] * 0.4, 0.9, 0.25, yk, yk + 0.5, ry); }
            else if (kind === 6 && !UG && side(u - 0.8, sd) && side(u + 0.8, sd) && HL.wallOK(s[0], s[1], ry, 1.4, yk + 1.8, yk + 4.6) && HL.hangClaim(s[0], s[1], ry, 1.3, yk + 1.8, yk + 4.6)) HL.banner(s[0] + s[2] * 0.12, yk + 4.6, s[1] + s[3] * 0.12, ry, 1.3, 2.8, Object.keys(HL.HOUSES)[(q + k) % 4]);
            else if (kind === 7 && wid >= 3 && HL.occ.put(k, s[0] + s[2] * 0.5, s[1] + s[3] * 0.5, 0.5, 0.5, 0, 0.1)) { KIT.obox(s[0] + s[2] * 0.5, yk, s[1] + s[3] * 0.5, 0.42, yk + 0.5, 0.42, ry, G.dress, { col: false }); PHY.cyl(s[0] + s[2] * 0.5, s[1] + s[3] * 0.5, 0.45, yk, yk + 2.4); HL.ARMOUR = HL.ARMOUR || []; HL.ARMOUR.push([s[0] + s[2] * 0.5, yk + 0.5, s[1] + s[3] * 0.5, ry]); } } });
      KIT.tag = '';
    }
    // ---- a skin on the upper storeys: wherever an open floor or a hall's void would look straight out of the building, close it with masonry and a window
    for (const k of HL.UP) { if (!k) continue; const P = PS[k], yk = P.y, open = (i, j) => i >= 0 && j >= 0 && i < NX && j < NZ && !P.isW(i, j) && (P.ind(i, j) || (P0.ind(i, j) && HL.tallAt(i, j) > P.s * H1 + 0.5)), out = (i, j) => !built(i, j) || (!P.rf(i, j) && !HL.inShaft(i, j) && !(P0.ind(i, j) && HL.tallAt(i, j) > P.s * H1 + 0.5) && !(i >= 150 && i <= 158 && j >= 89 && j <= 107 && P.s <= 2));
      for (let j = 0; j < NZ; j++) for (const dj of [-1, 1]) { let i = 0; while (i < NX) { if (!(open(i, j) && out(i, j + dj))) { i++; continue; } let e = i; while (e + 1 < NX && open(e + 1, j) && out(e + 1, j + dj)) e++; const z = dj < 0 ? Z(j) : Z(j + 1); KIT.box(X(e + 1), yk, Math.min(z, z - dj * 0.35), X(i), yk + H1, Math.max(z, z - dj * 0.35), M.stone, { mats: dj < 0 ? { z: G.wall } : { Z: G.wall } }); if (e - i >= 2) HL.win((X(e + 1) + X(i)) / 2, yk + 2.2, z + (dj < 0 ? 1 : -1) * -0.02 + (dj < 0 ? 0.37 : -0.37) * 0, dj < 0 ? 0 : PI, 1.7, 3.7, GLZ()); i = e + 1; } }
      for (let i = 0; i < NX; i++) for (const di of [-1, 1]) { let j = 0; while (j < NZ) { if (!(open(i, j) && out(i + di, j))) { j++; continue; } let e = j; while (e + 1 < NZ && open(i, e + 1) && out(i + di, e + 1)) e++; const x = di < 0 ? X(i) : X(i + 1); KIT.box(Math.min(x, x + di * 0.35), yk, Z(e + 1), Math.max(x, x + di * 0.35), yk + H1, Z(j), M.stone, { mats: di < 0 ? { x: G.wall } : { X: G.wall } }); j = e + 1; } } }
    // ---- above the built storeys: the ranges carry on up as solid masonry with windows; lower parts are capped with lead
    greedy(P0, (i, j) => { const b = baseTop[j * NX + i]; if (!b || HL.inShaft(i, j) || HL.inTowerShaft(i, j)) return null; if (inGH(i, j) && HL.tallAt(i, j)) return null; return b + '_' + topOf(i, j); }, (i0, j0, i1, j1, q) => { const [b, t] = q.split('_').map(Number); bx(i0, j0, i1, j1, Y + b, Y + t, M.stone, { mats: { y: G.web, Y: M.lead } }); });
    { const SH = HL.SHAFT, edge = (i, j, di, dj) => built(i, j) && !(i >= SH.i0 - 1 && i <= SH.i1 + 1 && j >= SH.j0 - 1 && j <= SH.j1 + 1) && (!built(i + di, j + dj) || topOf(i + di, j + dj) < topOf(i, j) - 0.5);
      const run = (horiz, a0, a1, c, pos) => { const len = a1 - a0 + 1; if (len < 2) return; const i0 = horiz ? a0 : c, j0 = horiz ? c : a0, T = topOf(i0, j0), b = baseTop[j0 * NX + i0], sg = pos ? 1 : -1;
        if (horiz) { const z = pos ? Z(c) : Z(c + 1); KIT.box(X(a1 + 1), Y + T, z - (pos ? 0.5 : 0), X(a0), Y + T + 1.1, z + (pos ? 0 : 0.5), M.stone, { col: false }); for (let u = X(a1 + 1) + 0.6; u < X(a0) - 0.5; u += 2.4) KIT.box(u, Y + T + 1.1, z - (pos ? 0.5 : 0), u + 1.2, Y + T + 2.0, z + (pos ? 0 : 0.5), M.stone, { col: false });
          for (let yy = Y + b + 0.3; yy < Y + T - 3; yy += 6.6) KIT.box(X(a1 + 1), yy, z - (pos ? 0 : 0.18), X(a0), yy + 0.36, z + (pos ? 0.18 : 0), M.trim, { col: false });
          if (len >= 8 && !built(a0, c + (pos ? -1 : 1))) { const nb = Math.max(1, Math.round(len / 11.2)); for (let q = 0; q <= nb; q++) { const u = X(a0) - q * len / nb; if (HL.plan(0).door[c * NX + Math.min(NX - 1, Math.max(0, Math.floor(HL.PL.X0 - u)))]) continue; KIT.box(u - 0.45, Y - 2, z + sg * 0.0, u + 0.45, Y + T - 2.5, z + sg * 0.75, M.stone, { col: false }); KIT.box(u - 0.55, Y - 2, z, u + 0.55, Y + T * 0.45, z + sg * 1.3, M.stone, { col: false }); HL.pin(u, Y + T - 2.5, z + sg * 0.4, 0.42, 2.4); } }
          if (len >= 3) { const n = Math.max(1, Math.round(len / 5.6)); for (let q = 0; q < n; q++) { const ci = Math.round(a0 + (q + 0.5) * len / n - 0.5); for (let wy = Y + b + 2.2; wy + 4.4 < Y + T - 1.5; wy += 6.6) if (rs() > 0.1) HL.win(X(ci) - 0.5, wy, z + sg * 0.02, pos ? 0 : PI, 1.7, 3.7, HL.pickGlass(rs, 0.4)); } }
          if (len >= 8) { const n = Math.max(1, Math.round(len / 9)); for (let q = 0; q < n; q++) { const ci = Math.round(a0 + (q + 0.5) * len / n), cin = c + (pos ? 3 : -3); if (built(ci, cin) && Math.abs(topOf(ci, cin) - T) < 0.5 && built(ci, c + (pos ? 6 : -6))) HL.dormer(X(ci), Y + T + 1.5, z - sg * 2.1, pos ? 0 : PI, 2.3); } } }
        else { const x = pos ? X(c + 1) : X(c), s2 = pos ? -1 : 1; KIT.box(x - (pos ? 0 : 0.5), Y + T, Z(a1 + 1), x + (pos ? 0.5 : 0), Y + T + 1.1, Z(a0), M.stone, { col: false }); for (let u = Z(a1 + 1) + 0.6; u < Z(a0) - 0.5; u += 2.4) KIT.box(x - (pos ? 0 : 0.5), Y + T + 1.1, u, x + (pos ? 0.5 : 0), Y + T + 2.0, u + 1.2, M.stone, { col: false });
          for (let yy = Y + b + 0.3; yy < Y + T - 3; yy += 6.6) KIT.box(x - (pos ? 0.18 : 0), yy, Z(a1 + 1), x + (pos ? 0 : 0.18), yy + 0.36, Z(a0), M.trim, { col: false });
          if (len >= 8 && !built(c + (pos ? 1 : -1), a0)) { const nb = Math.max(1, Math.round(len / 11.2)); for (let q = 0; q <= nb; q++) { const u = Z(a0) - q * len / nb; if (HL.plan(0).door[Math.min(NZ - 1, Math.max(0, Math.floor(HL.PL.Z0 - u))) * NX + c]) continue; KIT.box(Math.min(x, x + s2 * 0.75), Y - 2, u - 0.45, Math.max(x, x + s2 * 0.75), Y + T - 2.5, u + 0.45, M.stone, { col: false }); KIT.box(Math.min(x, x + s2 * 1.3), Y - 2, u - 0.55, Math.max(x, x + s2 * 1.3), Y + T * 0.45, u + 0.55, M.stone, { col: false }); HL.pin(x + s2 * 0.4, Y + T - 2.5, u, 0.42, 2.4); } }
          if (len >= 3) { const n = Math.max(1, Math.round(len / 5.6)); for (let q = 0; q < n; q++) { const cj = Math.round(a0 + (q + 0.5) * len / n - 0.5); for (let wy = Y + b + 2.2; wy + 4.4 < Y + T - 1.5; wy += 6.6) if (rs() > 0.1) HL.win(x + s2 * 0.02, wy, Z(cj) - 0.5, pos ? -HALF : HALF, 1.7, 3.7, HL.pickGlass(rs, 0.4)); }  }
          if (len >= 8) { const n = Math.max(1, Math.round(len / 9)); for (let q = 0; q < n; q++) { const cj = Math.round(a0 + (q + 0.5) * len / n), cin = c + (pos ? -3 : 3); if (built(cin, cj) && Math.abs(topOf(cin, cj) - T) < 0.5 && built(c + (pos ? -6 : 6), cj)) HL.dormer(x - s2 * 2.1, Y + T + 1.5, Z(cj), pos ? -HALF : HALF, 2.3); } } } };
      for (let j = 0; j < NZ; j++) for (const pos of [true, false]) { let i = 0; while (i < NX) { const ex = (q) => edge(q, j, 0, pos ? -1 : 1) && Math.abs(topOf(q, j) - topOf(i, j)) < 0.1 && baseTop[j * NX + q] === baseTop[j * NX + i]; if (!edge(i, j, 0, pos ? -1 : 1)) { i++; continue; } let e = i; while (e + 1 < NX && ex(e + 1)) e++; run(true, i, e, j, pos); i = e + 1; } }
      for (let i = 0; i < NX; i++) for (const pos of [true, false]) { let j = 0; while (j < NZ) { const ex = (q) => edge(i, q, pos ? 1 : -1, 0) && Math.abs(topOf(i, q) - topOf(i, j)) < 0.1 && baseTop[q * NX + i] === baseTop[j * NX + i]; if (!edge(i, j, pos ? 1 : -1, 0)) { j++; continue; } let e = j; while (e + 1 < NZ && ex(e + 1)) e++; run(false, j, e, i, pos); j = e + 1; } } }
    // ---- roofs
    { const T0 = HL.TALLR[0], x0 = X(T0[2] + 1), x1 = X(T0[0]), z0 = Z(T0[3] + 1), z1 = Z(T0[1]), h = T0[4]; HL.gable(x0, z0, x1, z1, Y + h, 15, 'z', { inside: HL.ceilMat(), t: 2, gable: M.stone }); for (const [tx, tz] of [[x0, z0], [x0, z1], [x1, z0], [x1, z1]]) HL.round(tx, tz, 3.2, Y + h - 6, 22, { base: Y + h - 6, steep: 3.2, col: false }); const fx = (x0 + x1) / 2, fz = (z0 + z1) / 2; KIT.cyl(fx, Y + h + 13, fz, 1.6, 6, M.lead, { seg: 8, col: false }); HL.cone(fx, fz, 2.2, Y + h + 19, 17, { seg: 8 }); }
    { const D = new Float32Array(NX * NZ), inR = (i, j) => built(i, j) && !(inGH(i, j) && HL.tallAt(i, j)), big = 1e3; for (let s = 0; s < NX * NZ; s++) D[s] = inR(s % NX, (s / NX) | 0) ? big : 0;
      const lower = (i, j, t) => !inR(i, j) || topOf(i, j) < t - 0.5; for (let j = 0; j < NZ; j++) for (let i = 0; i < NX; i++) { if (!inR(i, j)) continue; const t = topOf(i, j); if (lower(i - 1, j, t) || lower(i + 1, j, t) || lower(i, j - 1, t) || lower(i, j + 1, t)) D[j * NX + i] = 0.5; }
      for (let pass = 0; pass < 2; pass++) { for (let j = 0; j < NZ; j++) for (let i = 0; i < NX; i++) { const s = j * NX + i; if (!D[s]) continue; let d = D[s]; if (i > 0) d = Math.min(d, D[s - 1] + 1); if (j > 0) d = Math.min(d, D[s - NX] + 1); if (i > 0 && j > 0) d = Math.min(d, D[s - NX - 1] + 1.41); if (i < NX - 1 && j > 0) d = Math.min(d, D[s - NX + 1] + 1.41); D[s] = d; }
        for (let j = NZ - 1; j >= 0; j--) for (let i = NX - 1; i >= 0; i--) { const s = j * NX + i; if (!D[s]) continue; let d = D[s]; if (i < NX - 1) d = Math.min(d, D[s + 1] + 1); if (j < NZ - 1) d = Math.min(d, D[s + NX] + 1); if (i < NX - 1 && j < NZ - 1) d = Math.min(d, D[s + NX + 1] + 1.41); if (i > 0 && j < NZ - 1) d = Math.min(d, D[s + NX - 1] + 1.41); D[s] = d; } }
      const dv = (i, j, t) => { let d = big; for (const [a, b] of [[i, j], [i - 1, j], [i, j - 1], [i - 1, j - 1]]) { if (a < 0 || b < 0 || a >= NX || b >= NZ || !inR(a, b) || topOf(a, b) < t - 0.5) return 0; if (Math.abs(topOf(a, b) - t) < 0.5) d = Math.min(d, D[b * NX + a]); } return d === big ? 0 : d; };
      const pos = []; for (let j = 0; j < NZ; j++) for (let i = 0; i < NX; i++) { if (!inR(i, j) || D[j * NX + i] < 1.4) continue; const t = topOf(i, j), y = (a, b) => Y + t + 0.9 + Math.min(14, Math.max(0, dv(a, b, t) - 1) * 1.45), A = [X(i), y(i, j), Z(j)], B = [X(i + 1), y(i + 1, j), Z(j)], Cc = [X(i + 1), y(i + 1, j + 1), Z(j + 1)], Dd = [X(i), y(i, j + 1), Z(j + 1)];
          if (Math.abs(A[1] - Cc[1]) < Math.abs(B[1] - Dd[1])) pos.push(...A, ...Cc, ...B, ...A, ...Dd, ...Cc); else pos.push(...A, ...Dd, ...B, ...B, ...Dd, ...Cc); }
      const g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); g.computeVertexNormals(); KIT.geo(g, M.roof, null, { worldUV: true }); }
    const tw = (i, j, r, h, o) => { h = Math.round(h * 1.45); let T = 0; const rr = Math.ceil(r) + 2; for (let dj = -rr; dj <= rr; dj++) for (let di = -rr; di <= rr; di++) if (built(i + di, j + dj)) T = Math.max(T, topOf(i + di, j + dj)); T = T || 23; const x = X(i), z = Z(j); if (!built(i, j) && !built(i - 1, j) && !built(i, j - 1) && !built(i + 1, j) && !built(i, j + 1)) { HL.round(x, z, r, Y, T + h, Object.assign({ steep: 2.6 }, o || {})); return; } HL.round(x, z, r, Y + T, h, Object.assign({ base: Y + T, col: false, steep: 2.6 }, o || {}));
      if (o && o.deck) { /* the Astronomy Tower is hollow: a ring of wall below the deck, the wall in pieces at deck level (leaving the doorway), solid above */ const yD = Y + T + h - 9, da = Math.atan2(92.4 - x, 74.1 - z); PHY.ring(x, z, 7.3, r, Y + T - 0.5, yD - 0.4, 28); for (let q = 0; q < 28; q++) { const an = (q + 0.5) / 28 * TAU; if (Math.abs(wrapA(an - da)) < 0.24) continue; PHY.obox(x + Math.sin(an) * (r - 0.6), z + Math.cos(an) * (r - 0.6), TAU * r / 28 / 2 + 0.12, 0.6, yD - 0.4, yD + 4.4, an); } PHY.cyl(x, z, r, yD + 4.2, Y + T + h); HL.ASTRO = { x, z, r, yb: Y + T, yD, top: Y + T + h }; }
      else PHY.cyl(x, z, r, Y + T, Y + T + h);
      if (o && o.deck) { const yD = Y + T + h - 9, R2 = r + 3.4, n = 36, hw = TAU * R2 / n / 2 + 0.06; KIT.ringCyl(x, yD - 3.2, z, r + 0.2, 2.8, M.stone, { seg: 28, r1: R2, rin: 7.3 }); KIT.ringCyl(x, yD - 0.4, z, R2, 0.4, M.trim, { seg: 28, rin: 7.3 }); PHY.ring(x, z, 7.3, R2, yD - 0.4, yD, 28); for (let q = 0; q < n; q++) { const an = q / n * TAU; KIT.obox(x + Math.sin(an) * (R2 - 0.25), yD, z + Math.cos(an) * (R2 - 0.25), hw, yD + (q % 2 ? 0.9 : 1.35), 0.22, an, M.stone, {}); } HL.DECK = [x, yD, z, r, R2]; } };
    // the towers of the game's skyline: [col, row, radius, height above the roofs]
    tw(72, 186, 8.5, 54, { pots: 5, steep: 2.2, open: true, deck: true, hollow: 7.3 }); tw(80, 195, 3.2, 50, { steep: 3.4 });      // Astronomy Tower and its stair turret
    tw(28, 72, 6.5, 30, { pots: 3, steep: 2.6 }); tw(27, 184, 6, 24, { pots: 3 }); tw(110, 182, 7, 34, { pots: 4 });   // Bell Tower, West Tower, Defence Against the Dark Arts tower
    tw(118, 70, 6, 22, { steep: 2.8 }); tw(116, 98, 7, 14, { steep: 2.2 });                               // Divination, the Central Hall lantern
    tw(139, 149, 9, 44, { pots: 5, steep: 2.4 }); tw(132, 217, 9, 40, { pots: 5, steep: 2.4 }); tw(190, 213, 7, 30, { pots: 3 });   // Ravenclaw, Gryffindor, Faculty
    tw(175, 168, 13, 26, { pots: 5, steep: 2.3 }); tw(186, 159, 5, 50, { steep: 3.2 });                   // the Grand Staircase tower, the Headmaster's turret
    // the Clock Tower: a square stage over the hall on the axis of the south bridge, a dial on every face
    { const C = P0.comps.find((c) => c.name === 'THE CLOCK TOWER'); if (C) { const xa = X(C.R.i1 + 1) - 1, xb = X(C.R.i0) + 1, zS = Z(C.R.j1 + 1) - 1, T = topOf(C.R.i0, C.R.j0), hw = (xb - xa) / 2, xc = (xa + xb) / 2, zc = zS + hw, y0 = Y + T, h = 26;
        KIT.box(xc - hw, y0, zc - hw, xc + hw, y0 + h, zc + hw, M.stone, {}); for (const yy of [y0 + 0.2, y0 + 8.4, y0 + h - 1]) KIT.box(xc - hw - 0.2, yy, zc - hw - 0.2, xc + hw + 0.2, yy + 0.5, zc + hw + 0.2, M.trim, { col: false });
        for (const sx of [-1, 1]) for (const sz of [-1, 1]) HL.round(xc + sx * hw, zc + sz * hw, 1.6, y0 - 10, h + 14, { base: y0 - 10, col: false, steep: 3.6, arches: false });
        for (const [nx, nz] of [[0, 1], [0, -1], [1, 0], [-1, 0]]) { for (const o of [-2.4, 0, 2.4]) HL.win(xc + nx * (hw + 0.03) + (nz ? o : 0), y0 + h - 8.2, zc + nz * (hw + 0.03) + (nx ? o : 0), Math.atan2(nx, nz), 1.3, 5.2, M.glassD); HL.clockDial(xc + nx * (hw + 0.12), y0 + 12.6, zc + nz * (hw + 0.12), Math.atan2(nx, nz), 7.2); }
        HL.pyr(xc, zc, hw + 0.5, hw + 0.5, y0 + h, 21, 0); HL.CLOCKX = { xc, zc, hw, zS, y0, h }; } }
    tw(217, 129, 3.4, 16, { steep: 3.4 }); tw(255, 129, 3.4, 16, { steep: 3.4 }); tw(216, 164, 3, 12, { steep: 3 }); tw(256, 164, 3, 12, { steep: 3 });   // Clock Tower, the Entrance Hall's bell towers
    HL.viaduct(L, 0, -296, Z(NZ - 1) + 1, Y, 11);   // (it used to stop forty metres short of the far bank, over a drop: now it lands on the plateau and the Hogsmeade road begins at its end)
  });
  /* The culling audit. From where the player stands, rays level and a little down, all round: the first opaque thing each meets with everything drawn must be the first thing it meets with the culling applied. Returns [rays, rays whose view the culling changed, examples]. */
  HL.auditSight = function (nd) { const a = PLAYER.a, rc = new THREE.Raycaster(), o = new THREE.Vector3(a.x, a.y + 1.6, a.z), d = new THREE.Vector3(), hid = [], ex = []; rc.far = 260; rc.camera = R.camera; let n = 0, bad = 0;
    R.scene.traverse((q) => { const fs = q.userData && q.userData.fs; if (fs && fs.h) { hid.push(q); q.layers.mask = fs.m; } });
    const chain = (q, tagOk) => { for (let p = q; p; p = p.parent) if (!p.visible && !(tagOk && p.userData && p.userData.tag)) return false; return true; }, solid = (h) => h.object.isMesh && !h.object.isSkinnedMesh && h.face && h.object.material && !Array.isArray(h.object.material) && !h.object.material.transparent && h.object.material.blending !== THREE.AdditiveBlending && h.object.material.depthWrite !== false && h.object.frustumCulled !== false;
    for (let i = 0; i < (nd || 16); i++) for (const py of [0, -0.12]) { const an = i / (nd || 16) * TAU + 0.07; d.set(Math.sin(an) * Math.cos(py), Math.sin(py), Math.cos(an) * Math.cos(py)); rc.set(o, d); const hits = rc.intersectObjects(R.scene.children, true).filter(solid), truth = hits.find((h) => chain(h.object, true)), seen = hits.find((h) => chain(h.object, false) && !(h.object.userData.fs && h.object.userData.fs.h)); n++;
        if (truth && (!seen || seen.distance > truth.distance + 0.8)) { bad++; if (ex.length < 4) ex.push((truth.object.userData.tag || 'structure') + ' at ' + truth.distance.toFixed(0) + ' m'); } }
    for (const q of hid) q.layers.mask = 0; return [n, bad, ex]; };
  /* interiors are drawn only from inside the castle, and only the storeys next to the one you stand on */
  HL.START.push(function (L) { let list = null, heavy = null, far = null, doors = null, t = 0; const v = new THREE.Vector3();
    L.updates.push((dt) => { t -= dt; if (t > 0) return; t = 0.2; if (HL.NEAR) { const cp = R.camera.position; for (const o of HL.NEAR) { const n = o.userData.near; o.visible = Math.abs(cp.x - n[0]) < n[3] && Math.abs(cp.z - n[2]) < n[3] && Math.abs(cp.y - n[1]) < n[4]; } }
      if (!list) { list = []; heavy = []; far = []; const boned = (o) => { for (let p = o.parent; p; p = p.parent) if (p.isBone) return true; return false; };
        R.scene.traverse((o) => { if (o.userData && o.userData.tag) { list.push(o); /* where it stands, for the distance cull. An instanced mesh is measured by its instances, not by the one candle at the origin its geometry holds (the Great Hall's floating candles and the flying memos were being culled as if they stood at 0,0,0); things that move about (frustumCulled off) are not measured at all */ if (o.isMesh && o.geometry && o.frustumCulled !== false) { let bs; if (o.isInstancedMesh) { if (o.computeBoundingSphere) o.computeBoundingSphere(); bs = o.boundingSphere; } else { if (!o.geometry.boundingSphere) o.geometry.computeBoundingSphere(); bs = o.geometry.boundingSphere; } if (bs && bs.radius === bs.radius) { o.updateMatrixWorld(); const c2 = bs.center.clone().applyMatrix4(o.matrixWorld); o.userData.bs = [c2.x, c2.z, bs.radius]; } } }
          /* big instanced things out of doors (grass, forest) are not drawn from deep inside — but the hundreds of candles afloat in the Great Hall are instanced too, and they are INSIDE: only what stands outside the castle's footprint counts */
          else if (o.isInstancedMesh && o.count > 300 && !o.userData.near && (() => { if (!o.boundingSphere && o.computeBoundingSphere) o.computeBoundingSphere(); const bs = o.boundingSphere; if (!bs) return true; o.updateMatrixWorld(); const c3 = bs.center.clone().applyMatrix4(o.matrixWorld); return !(HL.inFoot(c3.x, c3.z, 0) && c3.y < HL.Y0 + 45 && bs.radius < 90); })()) heavy.push(o);
          /* everything else that stands still in the world: it is not drawn from deep inside the castle when it is far off behind the walls (300 distant things were being drawn from the Great Hall) */
          else if (o.isSprite && !boned(o)) { o.userData.fs = { c: new THREE.Vector3(), r: 1.5, m: o.layers.mask }; far.push(o); }
          else if (o.isMesh && !o.isSkinnedMesh && !o.userData.near && o.frustumCulled !== false && o.geometry && o.material && o.material.depthTest !== false && !boned(o)) { let bs; if (o.isInstancedMesh) { if (!o.boundingSphere && o.computeBoundingSphere) o.computeBoundingSphere(); bs = o.boundingSphere; } else { if (!o.geometry.boundingSphere) o.geometry.computeBoundingSphere(); bs = o.geometry.boundingSphere; } o.updateMatrixWorld(); const r2 = bs ? bs.radius * o.matrixWorld.getMaxScaleOnAxis() : 1e9; if (bs && r2 < 1500 && r2 === r2) { o.userData.fs = { c: bs.center.clone(), r: r2, m: o.layers.mask }; far.push(o); } } });
        doors = HL.plan(0).doors.filter((d) => d.inn && d.ext).map((d) => [HL.PL.X0 - (d.i0 + d.i1) / 2, HL.PL.Z0 - (d.j0 + d.j1) / 2]); HL.CULL = { tagged: list.length, far: far.length, heavy: heavy.length, hidden: 0 }; }
      const c = R.camera.position, a = PLAYER.a, Y = HL.Y0, inside = c.x > HL.PL.X0 - 280 && c.x < HL.PL.X0 + 4 && c.z > HL.PL.Z0 - 320 && c.z < HL.PL.Z0 + 4 && c.y < Y + 60 && c.y > Y - 12, py = a ? a.y : c.y, fl = (y, e) => HL.kAt(y, e), f = fl(py, 1.2), fc = fl(c.y, 0.9), ai = a ? Math.floor(HL.PL.X0 - a.x) : -1, aj = a ? Math.floor(HL.PL.Z0 - a.z) : -1, hall = a && HL.tallAt(ai, aj) > 0;
      let deep = false; if (inside && a && HL.plan(f).ind(ai, aj) && HL.plan(fc).ind(Math.floor(HL.PL.X0 - c.x), Math.floor(HL.PL.Z0 - c.z))) { deep = true; if (f === 0) for (const d of doors) if (Math.hypot(d[0] - a.x, d[1] - a.z) < 26) { deep = false; break; } }
      /* 'in the dungeons' means under the castle — not merely lower than its floor (the pitch, the lake shore and the forest all lie lower, and were being treated as dungeon: the Quidditch crowd was never drawn) */ let dun = !!a && inside && a.y < Y - 4 && a.y > Y - 12 && HL.inFoot(a.x, a.z, 0); if (dun) for (const h of HL.DUN.holes) if (Math.abs(a.x - (h[0] + h[2]) / 2) < (h[2] - h[0]) / 2 + 7 && Math.abs(a.z - (h[1] + h[3]) / 2) < (h[3] - h[1]) / 2 + 7) dun = false; if (dun) deep = true; R.shEvery = deep ? 6 : inside ? 3 : 2;
      const px = a ? a.x : c.x, pz = a ? a.z : c.z, lim = deep ? 62 : (inside && a && HL.plan(f).ind(ai, aj)) ? 74 : 130, hk = hall ? Math.ceil(HL.tallAt(ai, aj) / HL.PL.H1 - 0.2) - 1 : 0, indoor = inside && a && HL.plan(f).ind(ai, aj); /* the tall hall you stand in, as a rectangle of the world: the storeys above are drawn only where they stand about it */ let hr = null; if (hall) for (const t2 of HL.TALLR) if (ai >= t2[0] && ai <= t2[2] && aj >= t2[1] && aj <= t2[3]) { hr = [HL.PL.X0 - t2[2] - 1, HL.PL.X0 - t2[0], HL.PL.Z0 - t2[3] - 1, HL.PL.Z0 - t2[1]]; break; }
      for (const o of list) { const g = o.userData.tag, k = +g.slice(2), bs = o.userData.bs, off = inside && bs && Math.hypot(bs[0] - px, bs[1] - pz) - bs[2] > lim; if (dun) { o.visible = inside && g === 'in' && !off; continue; } if (g[0] === 'p') { o.visible = inside && (k === f || k === fc) && !off; continue; } /* from the floor of a tall hall the storeys above show too, but only what stands about the hall itself */
        o.visible = inside && !off && (g === 'in' || k === f || k === fc || (hall && k <= hk && (!bs || !hr || (bs[0] > hr[0] - bs[2] - 5 && bs[0] < hr[1] + bs[2] + 5 && bs[1] > hr[2] - bs[2] - 5 && bs[1] < hr[3] + bs[2] + 5)))); }
      for (const o of heavy) o.visible = !deep;
      let nh = 0; for (const o of far) { const fs = o.userData.fs; let hide = false; if (inside) { v.copy(fs.c).applyMatrix4(o.matrixWorld); const d = Math.hypot(v.x - px, v.z - pz) - fs.r; /* NB the castle's own walls, floors and vaults are among these (untagged, in 48 m chunks through every storey): they may only go when they are far beyond any sight line indoors */ hide = deep ? d > (fs.r >= 15 ? 110 : 62) : indoor ? (fs.r < 15 && d > 95) : (fs.r < 15 && d > 130); } if (hide) nh++; if (hide !== !!fs.h) { fs.h = hide; o.layers.mask = hide ? 0 : fs.m; } } if (HL.CULL) { HL.CULL.hidden = nh; HL.CULL.deep = deep; } }); });
})();
