/* ==== p72h_hl_tower.js ==== */
/* THE ASTRONOMY TOWER, climbed. From the Astronomy classroom at the tower's foot (third floor) a square stair winds up
   a ten-metre shaft — thirty-two flights round an open well, a lancet and a sconce on every turn — to a door that opens
   on the observation deck, ninety-seven metres over the castle floor. Built with the classroom (so its floor is kept
   clear), drawn always (it stands above the storeys the castle shows by floor). */
/* a cylinder (or a cone frustum: o.r1 = its top radius) that is a ring: the side, and an annulus top and bottom from o.rin outward. No collider. */
KIT.ringCyl = function (cx, y0, cz, r, h, mat, o) { o = o || {}; const seg = o.seg || 24, r1 = o.r1 !== undefined ? o.r1 : r, ts = mat.userData.tscale || 2, uvs = o.uvs || Math.max(1, Math.round(TAU * r / ts));
  KIT.geo(new THREE.CylinderGeometry(r1, r, h, seg, 1, true), mat, new THREE.Matrix4().makeTranslation(cx, y0 + h / 2, cz), { worldUV: false, uvs, uvs2: h / ts });
  if (r1 > o.rin + 0.02) { const g = new THREE.RingGeometry(o.rin, r1, seg, 1); g.rotateX(-HALF); KIT.geo(g, mat, new THREE.Matrix4().makeTranslation(cx, y0 + h, cz), { worldUV: true }); }
  if (r > o.rin + 0.02) { const g = new THREE.RingGeometry(o.rin, r, seg, 1); g.rotateX(HALF); KIT.geo(g, mat, new THREE.Matrix4().makeTranslation(cx, y0, cz), { worldUV: true }); } return null; };
HL.towerStair = function (L, k, Y3) { const A = HL.ASTRO; if (!A) return null; const G = HL.GK.M(), I = HL.IM(), M = HL.M(), tag0 = KIT.tag; KIT.tag = '';
  const X0 = HL.PL.X0 - HL.TSH.i1 - 1, X1 = HL.PL.X0 - HL.TSH.i0, Z0 = HL.PL.Z0 - HL.TSH.j1 - 1, Z1 = HL.PL.Z0 - HL.TSH.j0, fw = 1.8, yD = A.yD, NF = 32, rise = (yD - Y3) / NF, yc = Y3 + HL.PL.H1, yTop = yD + 4.2, step = G.dress, cx = (X0 + X1) / 2, cz = (Z0 + Z1) / 2;
  const S = HL.TSQ = { X0, X1, Z0, Z1, fw, rise, NF, Y3, yD, foot: [X1 - fw / 2, Z1 - fw / 2], door: [X1 + 1.6, Z1 - fw / 2], way: [] };
  // ---- the flights: north side (east to west), west (north to south), south (west to east), east (south to north) — and round again
  for (let f = 0; f < NF; f++) { const side = f % 4, y0 = Y3 + f * rise, y1 = y0 + rise; let r, rail;
    if (side === 0) { r = KIT.stairs(X1 - fw, Z1 - fw, X0 + fw, Z1, y0, y1, 'x', step, 14); rail = [X0 + fw, Z1 - fw - 0.12, X1 - fw, Z1 - fw]; S.way.push([X1 - fw - 0.4, Z1 - fw / 2, y0], [X0 + fw / 2, Z1 - fw / 2, y1]); }
    else if (side === 1) { r = KIT.stairs(X0, Z1 - fw, X0 + fw, Z0 + fw, y0, y1, 'z', step, 14); rail = [X0 + fw, Z0 + fw, X0 + fw + 0.12, Z1 - fw]; S.way.push([X0 + fw / 2, Z1 - fw - 0.4, y0], [X0 + fw / 2, Z0 + fw / 2, y1]); }
    else if (side === 2) { r = KIT.stairs(X0 + fw, Z0, X1 - fw, Z0 + fw, y0, y1, 'x', step, 14); rail = [X0 + fw, Z0 + fw, X1 - fw, Z0 + fw + 0.12]; S.way.push([X0 + fw + 0.4, Z0 + fw / 2, y0], [X1 - fw / 2, Z0 + fw / 2, y1]); }
    else { r = KIT.stairs(X1 - fw, Z0 + fw, X1, Z1 - fw, y0, y1, 'z', step, 14); rail = [X1 - fw - 0.12, Z0 + fw, X1 - fw, Z1 - fw]; S.way.push([X1 - fw / 2, Z0 + fw + 0.4, y0], [X1 - fw / 2, Z1 - fw / 2, y1]); }
    r.y0 = Math.min(y0, y1) - 0.25;                                                   // (a ramp's collider otherwise reaches a metre and a half below its foot: a wall across the flight beneath)
    /* the rail on the well side: a moulded stone coping on balusters, following the flight */ { const hz = side % 2 === 0, a0 = hz ? rail[0] : rail[1], a1 = hz ? rail[2] : rail[3], up = (side === 0 || side === 1) ? -1 : 1, mid = hz ? (rail[1] + rail[3]) / 2 : (rail[0] + rail[2]) / 2, yA = up > 0 ? y0 : y1, yB = up > 0 ? y1 : y0, P = (t, yy) => hz ? [lerp(a0, a1, t), yy, mid] : [mid, yy, lerp(a0, a1, t)];
      KIT.beam(P(0, yA + 1.05), P(1, yB + 1.05), 0.16, G.dress); for (let q = 0; q <= 6; q++) { const t = q / 6, yy = lerp(yA, yB, t); KIT.beam(P(t, yy - 0.1), P(t, yy + 1.0), 0.09, G.dress); }
      for (let q = 0; q < 4; q++) { const t0 = q / 4, t1 = (q + 1) / 4, ya = Math.min(lerp(yA, yB, t0), lerp(yA, yB, t1)) - 0.3, yb = Math.max(lerp(yA, yB, t0), lerp(yA, yB, t1)) + 1.1; if (hz) PHY.box(lerp(a0, a1, t0), ya, rail[1], lerp(a0, a1, t1), yb, rail[3]); else PHY.box(rail[0], ya, lerp(a0, a1, t0), rail[2], yb, lerp(a0, a1, t1)); } }
    /* the landing in the corner this flight climbs to */ { const lx = side === 0 || side === 1 ? X0 : X1 - fw, lz = side === 0 || side === 3 ? Z1 - fw : Z0; KIT.box(lx, y1 - 0.3, lz, lx + fw, y1, lz + fw, step, { col: true }); /* the newel at its inner corner */ const nx = lx === X0 ? X0 + fw : X1 - fw, nz = lz === Z0 ? Z0 + fw : Z1 - fw; KIT.box(nx - 0.14, y1 - 0.3, nz - 0.14, nx + 0.14, y1 + 1.25, nz + 0.14, G.dress, { col: true }); KIT.geo(new THREE.SphereGeometry(0.17, 8, 6), I.brass, new THREE.Matrix4().makeTranslation(nx, y1 + 1.4, nz)); }
    /* where the stair still stands free in the classroom (below its ceiling) the outer side wants a rail too */ if (Math.min(y0, y1) < yc - 0.5 && side < 3) { const ya = y0 - 0.3, yb = Math.min(y1 + 1.1, yc); if (side === 0) { PHY.box(X0, ya, Z1 - 0.1, X1 - fw, yb, Z1); KIT.beam([X1 - fw, y0 + 1.05, Z1 - 0.06], [X0 + fw, y1 + 1.05, Z1 - 0.06], 0.14, G.dress); KIT.box(X0, y1 - 0.3, Z1 - 0.12, X0 + fw, y1 + 1.1, Z1, G.dress, { col: false }); KIT.box(X0, y1 - 0.3, Z1 - fw, X0 + 0.12, y1 + 1.1, Z1, G.dress, { col: true }); }
      else if (side === 1) { PHY.box(X0, ya, Z0, X0 + 0.1, yb, Z1 - fw); KIT.beam([X0 + 0.06, y0 + 1.05, Z1 - fw], [X0 + 0.06, y1 + 1.05, Z0 + fw], 0.14, G.dress); KIT.box(X0, y1 - 0.3, Z0, X0 + 0.12, Math.min(y1 + 1.1, yc), Z0 + fw, G.dress, { col: true }); KIT.box(X0, y1 - 0.3, Z0, X0 + fw, Math.min(y1 + 1.1, yc), Z0 + 0.12, G.dress, { col: true }); }
      else { PHY.box(X0 + fw, ya, Z0, X1, yb, Z0 + 0.1); KIT.beam([X0 + fw, y0 + 1.05, Z0 + 0.06], [X1 - fw, Math.min(y1 + 1.05, yc), Z0 + 0.06], 0.14, G.dress); } } }
  // ---- the shaft: four walls of the castle's own stone from the classroom ceiling to the roof of the stair (the east one opens at the top), a boarded ceiling
  { const wy0 = yc, dz0 = Z1 - fw + 0.1, dz1 = Z1 - 0.1, face = (x0, z0, x1, z1, y0, y1, f) => { if (y1 - y0 > 0.05) KIT.box(x0, y0, z0, x1, y1, z1, G.wall, { faces: f, col: false }); };
    for (let y = wy0; y < yTop - 0.01; y += 9.6) { const y1 = Math.min(yTop, y + 9.6); face(X0, Z1 - 0.03, X1, Z1 + 0.5, y, y1, 'z'); face(X0, Z0 - 0.5, X1, Z0 + 0.03, y, y1, 'Z'); face(X0 - 0.5, Z0, X0 + 0.03, Z1, y, y1, 'X'); face(X1 - 0.03, Z0, X1 + 0.5, Z1, y, Math.min(y1, yD), 'x'); }
    face(X1 - 0.03, Z0, X1 + 0.5, dz0, yD, yTop, 'x'); face(X1 - 0.03, dz1, X1 + 0.5, Z1, yD, yTop, 'x'); face(X1 - 0.03, dz0, X1 + 0.5, dz1, yD + 2.6, yTop, 'x');
    PHY.box(X0, wy0, Z1, X1, yTop, Z1 + 0.6); PHY.box(X0, wy0, Z0 - 0.6, X1, yTop, Z0); PHY.box(X0 - 0.6, wy0, Z0, X0, yTop, Z1); PHY.box(X1, wy0, Z0, X1 + 0.6, yD, Z1); PHY.box(X1, yD, Z0, X1 + 0.6, yTop, dz0); PHY.box(X1, yD, dz1, X1 + 0.6, yTop, Z1); PHY.box(X1, yD + 2.6, dz0, X1 + 0.6, yTop, dz1);
    KIT.box(X0, yTop, Z0, X1, yTop + 0.3, Z1, I.oak, { col: true }); for (let x = X0 + 1.25; x < X1; x += 2.5) KIT.box(x - 0.14, yTop - 0.32, Z0, x + 0.14, yTop, Z1, I.oakD, { col: false });
    /* a lancet of daylight and a sconce on every turn, turn about on the four walls */
    const W = HL.winGeo(1.1, 3.4); for (let t = 0, y = yc + 2.2; y < yD + 0.5; y += rise * 2, t++) { const s4 = t % 4, m4 = new THREE.Matrix4(); let wx, wz, nx = 0, nz = 0; if (s4 === 0) { wx = cx; wz = Z0 + 0.05; nz = 1; m4.makeRotationY(0); } else if (s4 === 1) { wx = X1 - 0.05; wz = cz - 1.5; nx = -1; m4.makeRotationY(-HALF); } else if (s4 === 2) { wx = cx; wz = Z1 - 0.05; nz = -1; m4.makeRotationY(PI); } else { wx = X0 + 0.05; wz = cz; nx = 1; m4.makeRotationY(HALF); }
      m4.setPosition(wx, y, wz); KIT.geo(W.frame, G.dress, m4, { worldUV: true }); KIT.geo(W.glass, G.day, m4, { uvs: 1 }); KIT.geo(W.sill, G.dress, m4, { worldUV: true });
      const sx = s4 === 0 ? X1 - 0.05 : s4 === 1 ? cx : s4 === 2 ? X0 + 0.05 : cx, sz = s4 === 0 ? cz : s4 === 1 ? Z1 - 0.05 : s4 === 2 ? cz : Z0 + 0.05, snx = s4 === 0 ? -1 : s4 === 2 ? 1 : 0, snz = s4 === 1 ? -1 : s4 === 3 ? 1 : 0; HL.sconce(L, sx, y + 1.2, sz, snx, snz, { i: 7, range: 13 }); HL.sl(cx, y + 3, cz, 0xbfd0ff, 2.2, 14); } }
  // ---- the top: the last landing, the passage through the drum wall, a stone doorcase standing proud of it on the deck
  { const pz0 = Z1 - fw + 0.1, pz1 = Z1 - 0.1, px1 = A.x + Math.sqrt(A.r * A.r - Math.pow(pz0 - A.z, 2)) + 0.22, dark = new THREE.MeshBasicMaterial({ color: 0x0b0906 }); dark.userData.tscale = 1;
    KIT.box(X1, yD - 0.4, pz0, px1, yD, pz1, step, { col: true }); KIT.box(X1, yD, pz0 - 0.32, px1, yD + 2.75, pz0, G.wall, { col: true }); KIT.box(X1, yD, pz1, px1, yD + 2.75, pz1 + 0.32, G.wall, { col: true }); KIT.box(X1, yD + 2.6, pz0 - 0.32, px1 + 0.06, yD + 2.95, pz1 + 0.32, G.dress, { col: true });
    for (const z of [pz0 - 0.16, pz1 + 0.16]) KIT.box(px1 - 0.3, yD, z - 0.2, px1 + 0.08, yD + 2.6, z + 0.2, G.dress, { col: false }); KIT.quad(dark, [px1 + 0.02, yD, pz1], [px1 + 0.02, yD, pz0], [px1 + 0.02, yD + 2.6, pz0], [px1 + 0.02, yD + 2.6, pz1], [1, 0, 0], (p) => [p[2], p[1]]);
    HL.sconce(L, X1 - 0.05, yD + 2.3, Z0 + 2.4, -1, 0, { i: 8, range: 12 }); S.door = [px1 + 1.2, pz0 + (pz1 - pz0) / 2]; S.way.push([X1 + 0.9, Z1 - fw / 2, yD], [px1 + 1.2, Z1 - fw / 2, yD]); }
  HL.zone('THE ASTRONOMY TOWER STAIR', X0, Z0, X1 + 3, Z1, yc + 0.2, yTop, { hemi: 0.2 });
  // ---- what the classroom may not furnish: the strips the first three flights stand on (north, west, south), the well's rim
  for (const [x0, z0, x1, z1] of [[X0, Z1 - fw, X1 - fw, Z1], [X0, Z0, X0 + fw, Z1], [X0, Z0, X1 - fw, Z0 + fw]]) HL.occ.mark(k, (x0 + x1) / 2, (z0 + z1) / 2, (x1 - x0) / 2 + 0.25, (z1 - z0) / 2 + 0.25, 0, 6);
  KIT.tag = tag0; return S; };
