/* ==== p76_hl_quidditch.js ==== */
/* HOGWARTS — Quidditch. The pitch (mown lawn, six golden hoops, a ring of draped towers full of spectators) and the
   match: you fly Chaser for your house — carry, pass and shoot the Quaffle past the Keeper, shoulder it off rivals,
   dodge two Bludgers, and when the Golden Snitch is loosed anyone may chase it down for 150 points and the match. */
HL.Q = { on: false, flyers: [], bl: [], score: [0, 0], t: 0, phase: 'off', ball: null, snitch: null, crowd: null, excite: 0, hoops: [[], []] };
(function () {
  const Q = HL.Q, C = HL.PITCH; Q.C = C; Q.AX = 36; Q.AZ = 96; Q.HZ = 77; Q.Y0 = C.y; Q.CEIL = 78;   // (a bigger pitch, in a stadium: it was 31 by 84 with low benches and towers standing apart)
  Q.ROWS = 12; Q.DEPTH = Q.ROWS * 1.25 + 1.4;
  Q.RIVAL = { gryffindor: 'slytherin', slytherin: 'gryffindor', ravenclaw: 'hufflepuff', hufflepuff: 'ravenclaw' };
  /* ---------------------------------------------------------------- the ground */
  Q.clothTex = function (c1, c2, kind) { const c = document.createElement('canvas'); c.width = c.height = 256; const x = c.getContext('2d'), A = '#' + new THREE.Color(c1).getHexString(), B = '#' + new THREE.Color(c2).getHexString();
    x.fillStyle = A; x.fillRect(0, 0, 256, 256); x.fillStyle = B; if (kind === 0) for (let i = 0; i < 4; i++) for (let j = 0; j < 4; j++) { if ((i + j) % 2) x.fillRect(i * 64, j * 64, 64, 64); } else if (kind === 1) for (let i = 0; i < 4; i++) x.fillRect(i * 64, 0, 32, 256); else { for (let j = 0; j < 4; j++) { x.beginPath(); x.moveTo(0, j * 64); x.lineTo(128, j * 64 + 32); x.lineTo(256, j * 64); x.lineTo(256, j * 64 + 26); x.lineTo(128, j * 64 + 58); x.lineTo(0, j * 64 + 26); x.fill(); } }
    for (let i = 0; i < 2600; i++) { x.fillStyle = `rgba(0,0,0,${Math.random() * 0.07})`; x.fillRect(Math.random() * 256, Math.random() * 256, 2, 6); }
    const t = new THREE.CanvasTexture(c); t.colorSpace = THREE.SRGBColorSpace; t.wrapS = t.wrapT = THREE.RepeatWrapping; t.anisotropy = 4; return t; };
  Q.lawn = function () { const c = document.createElement('canvas'); c.width = 512; c.height = 1024; const x = c.getContext('2d');
    for (let j = 0; j < 16; j++) { x.fillStyle = j % 2 ? '#3c5a26' : '#46662a'; x.fillRect(0, j * 64, 512, 64); }
    for (let i = 0; i < 26000; i++) { const g = 60 + Math.random() * 60; x.fillStyle = `rgba(${g * 0.55 | 0},${g | 0},${g * 0.3 | 0},0.22)`; x.fillRect(Math.random() * 512, Math.random() * 1024, 1.5, 3 + Math.random() * 3); }
    x.strokeStyle = 'rgba(240,240,225,0.85)'; x.lineWidth = 5; x.beginPath(); x.ellipse(256, 512, 236, 494, 0, 0, TAU); x.stroke(); x.beginPath(); x.moveTo(20, 512); x.lineTo(492, 512); x.stroke(); x.beginPath(); x.arc(256, 512, 44, 0, TAU); x.stroke();
    for (const y of [512 - 400, 512 + 400]) { /* the keeper's area: turf worn thin under the hoops and a chalk line round it (a flat sand-coloured disc read as a placeholder) */ const g = x.createRadialGradient(256, y, 8, 256, y, 112); g.addColorStop(0, 'rgba(120,112,66,0.55)'); g.addColorStop(0.6, 'rgba(104,110,58,0.32)'); g.addColorStop(1, 'rgba(90,110,50,0)'); x.save(); x.translate(256, y); x.scale(1, 50 / 110); x.translate(-256, -y); x.fillStyle = g; x.beginPath(); x.arc(256, y, 112, 0, TAU); x.fill(); x.restore(); x.strokeStyle = 'rgba(240,240,225,0.72)'; x.lineWidth = 4; x.beginPath(); x.ellipse(256, y, 104, 46, 0, 0, TAU); x.stroke(); }
    const t = new THREE.CanvasTexture(c); t.colorSpace = THREE.SRGBColorSpace; t.anisotropy = 8; return t; };
  HL.foot(C.x - Q.AX - 36, C.z - Q.AZ - 34, C.x + Q.AX + 36, C.z + Q.AZ + 34);
  HL.BUILD.push(async function pitch(L) {
    const M = HL.M(), Y = Q.Y0, rs = MG.rs('pitch');
    { const g = new THREE.PlaneGeometry((Q.AX + 5) * 2, (Q.AZ + 5) * 2); g.rotateX(-HALF); const me = new THREE.Mesh(g, new THREE.MeshStandardMaterial({ map: Q.lawn(), roughness: 0.95, envMapIntensity: 0.3 })); me.position.set(C.x, Y + 0.06, C.z); me.receiveShadow = true; LEVEL.add(me); }
    // hoops: three at each end
    const gold = new THREE.MeshStandardMaterial({ color: 0xe0b24a, metalness: 1, roughness: 0.28, envMapIntensity: 1.3 }); gold.userData.tscale = 1;
    for (const s of [-1, 1]) [[-8, 10.5], [0, 14], [8, 11.5]].forEach(([dx, h], i) => { const x = C.x + dx, z = C.z + s * Q.HZ; KIT.cyl(x, Y, z, 0.16, h - 1.7, gold, { seg: 10, r1: 0.11 }); KIT.cyl(x, Y, z, 0.45, 0.3, gold, { seg: 12, col: false, r1: 0.2 });
      KIT.geo(new THREE.TorusGeometry(1.72, 0.12, 10, 36), gold, new THREE.Matrix4().makeTranslation(x, Y + h, z)); Q.hoops[s < 0 ? 0 : 1].push({ x, y: Y + h, z, r: 1.6, glow: 0, i }); });
    // the towers: timber frames draped in house cloth, a box of spectators under a peaked canopy, a pennant
    const houses = Object.keys(HL.HOUSES), people = [], N = 16, cl0 = new THREE.MeshStandardMaterial({ map: Q.clothTex(0x1c3a7a, 0xa8763a, 1), roughness: 0.9, side: THREE.DoubleSide }); cl0.userData.tscale = 1;
    for (let k = 0; k < N; k++) { const a = (k + 0.5) / N * TAU, ex = Q.AX + 7.5 + Q.DEPTH + 7.2, ez = Q.AZ + 6.5 + Q.DEPTH + 7.2, x = C.x + Math.sin(a) * ex, z = C.z + Math.cos(a) * ez, H = HL.HOUSES[houses[k % 4]], h = 31 + (k % 3) * 4 + (Math.abs(Math.sin(a)) > 0.8 ? 5 : 0), w = 5.2, yaw = Math.atan2(C.x - x, C.z - z);   /* the towers rise out of the back of the bowl, well above it */
      const gy = HL.h(x, z) - 0.5, cl = new THREE.MeshStandardMaterial({ map: Q.clothTex(H.col, H.col2, k % 3), roughness: 0.9, side: THREE.DoubleSide, envMapIntensity: 0.3 }); cl.userData.tscale = 1; cl.userData.noShadow = false;
      const P = CAS.rot(x, z, yaw);
      for (const [lx, lz] of [[-w, -w], [w, -w], [w, w], [-w, w]]) { const p = P(lx, lz); KIT.beam([p[0], gy, p[1]], [p[0], Y + h + 4.2, p[1]], 0.36, M.woodD); }
      for (let yy = Y + 3; yy < Y + h; yy += 5) for (const [a0, a1] of [[[-w, -w], [w, w]], [[w, -w], [-w, w]]]) { const p0 = P(a0[0], a0[1]), p1 = P(a1[0], a1[1]); KIT.beam([p0[0], yy, p0[1]], [p1[0], yy + 4, p1[1]], 0.16, M.woodD); }
      // draped sides (four hangings), the deck, the parapet, the canopy
      for (const [lx, lz, ry] of [[0, w + 0.05, 0], [0, -w - 0.05, PI], [w + 0.05, 0, HALF], [-w - 0.05, 0, -HALF]]) { const p = P(lx, lz), g = new THREE.PlaneGeometry(w * 2, h - 1, 4, 1); const uv = g.attributes.uv; for (let i = 0; i < uv.count; i++) uv.setXY(i, uv.getX(i) * 2, uv.getY(i) * (h / 5));
        const m4 = new THREE.Matrix4().makeRotationY(yaw + ry); m4.setPosition(p[0], Y + (h - 1) / 2 + 1, p[1]); KIT.geo(g, cl, m4); }
      KIT.obox(x, Y + h, z, w + 0.4, Y + h + 0.3, w + 0.4, yaw, M.wood, { col: true }); PHY.obox(x, z, w, w, gy, Y + h, yaw);
      for (const [lx, lz, hx, hz] of [[0, w + 0.3, w + 0.4, 0.12], [0, -w - 0.3, w + 0.4, 0.12], [w + 0.3, 0, 0.12, w + 0.4], [-w - 0.3, 0, 0.12, w + 0.4]]) { const p = P(lx, lz); KIT.obox(p[0], Y + h + 0.3, p[1], hx, Y + h + 1.3, hz, yaw, M.woodD, { col: false }); }
      { const g = new THREE.ConeGeometry((w + 1.2) * 1.414, 4.6, 4, 1); g.rotateY(PI / 4 + yaw); KIT.geo(g, cl, new THREE.Matrix4().makeTranslation(x, Y + h + 6.5, z), { uvs: 3, uvs2: 1 }); KIT.cyl(x, Y + h + 8.6, z, 0.07, 4, M.woodD, { seg: 6, col: false }); }
      WORLD.banner(L, x, Y + h + 12.4, z, yaw + HALF, 1.6, 3.4, H.col, H.col2);
      for (let r = 0; r < 3; r++) for (let i = 0; i < 7; i++) { const p = P(-w + 0.7 + i * (w * 2 - 1.4) / 6 + rnd(-0.1, 0.1), w - 0.9 - r * 2.6 + (r ? 1.3 : 0)); if (rs() < 0.14) continue; people.push([p[0], Y + h + 0.3 + r * 0.55, p[1], yaw, rs() < 0.75 ? H.col : (rs() < 0.5 ? H.col2 : 0x2a2a30), rs()]); }
    }
    // the bowl: raked timber stands all the way round in two tiers with an aisle between them, bunting along the front rail, a tall back wall hung with house cloth inside and out — a stadium, with the towers rising behind it
    { const NS = 36, ROWS = Q.ROWS, bun = new THREE.MeshStandardMaterial({ map: Q.clothTex(0x8a1818, 0xd8a326, 2), roughness: 0.9, side: THREE.DoubleSide }); bun.userData.tscale = 1; const drape = houses.map((hh, i) => { const m = new THREE.MeshStandardMaterial({ map: Q.clothTex(HL.HOUSES[hh].col, HL.HOUSES[hh].col2, (i + 1) % 3), roughness: 0.9, side: THREE.DoubleSide, envMapIntensity: 0.3 }); m.userData.tscale = 1; return m; });
      const rowD = (r) => r * 1.25 + (r >= 6 ? 1.4 : 0), rowH = (r) => 2.2 + r * 1.0 + (r >= 6 ? 1.3 : 0), topH = rowH(ROWS - 1) + 4.6, backD = rowD(ROWS - 1) + 1.5;
      for (let k = 0; k < NS; k++) { const a = (k + 0.5) / NS * TAU, ex = Q.AX + 7.5, ez = Q.AZ + 6.5, x = C.x + Math.sin(a) * ex, z = C.z + Math.cos(a) * ez, yaw = Math.atan2(C.x - x, C.z - z), P = CAS.rot(x, z, yaw), arc = (d) => (TAU * (ex + ez + d * 2) / 2 / NS) * 0.57, len = arc(0), H = houses[k % 4];
        if (Math.abs(Math.sin(a)) > 0.93 && Math.abs(z - (C.z - 20)) < 10 && x < C.x) continue;                         // the players' gate on the east side
        for (let r = 0; r < ROWS; r++) { const d = rowD(r), h = rowH(r), lr = arc(d), p = P(0, -d); KIT.obox(p[0], Y + h, p[1], lr, Y + h + 0.3, 0.62, yaw, M.wood, { col: false }); KIT.obox(p[0], Y - 0.4, p[1], lr, Y + h, 0.08, yaw, M.woodD, { col: false });
          const np = Math.max(7, Math.round(lr * 2 / 0.95)); for (let i = 0; i < np; i++) { if (rs() < 0.13) continue; const q = P(-lr + 0.4 + i * (lr * 2 - 0.8) / (np - 1) + rnd(-0.08, 0.08), -d + 0.1); people.push([q[0], Y + h + 0.3, q[1], yaw, rs() < 0.7 ? HL.HOUSES[H].col : (rs() < 0.5 ? HL.HOUSES[H].col2 : 0x2a2a30), rs()]); } }
        { const p = P(0, -rowD(6) + 1.0); KIT.obox(p[0], Y + rowH(5) + 0.3, p[1], arc(rowD(6)), Y + rowH(5) + 0.42, 0.75, yaw, M.woodD, { col: false }); }   // the aisle between the tiers
        { const p = P(0, 0.75); KIT.obox(p[0], Y - 0.4, p[1], len, Y + 2.6, 0.1, yaw, M.woodD, { col: true }); const g = new THREE.PlaneGeometry(len * 2, 1.6); const uv = g.attributes.uv; for (let i = 0; i < uv.count; i++) uv.setXY(i, uv.getX(i) * 3, uv.getY(i) * 0.5); const m4 = new THREE.Matrix4().makeRotationY(yaw); const q = P(0, 0.88); m4.setPosition(q[0], Y + 1.6, q[1]); KIT.geo(g, k % 2 ? bun : cl0, m4); }
        { /* the back wall: timber, a band of house cloth above the top row inside, a full drape outside */ const lb = arc(backD) * 1.02, bk = P(0, -backD); KIT.obox(bk[0], Y - 0.6, bk[1], lb, Y + topH, 0.14, yaw, M.woodD, { col: true });
          for (const [dz, y0, y1, ry] of [[0.16, rowH(ROWS - 1) + 1.6, topH - 0.2, 0], [-0.16, 0.4, topH - 0.2, PI]]) { const g = new THREE.PlaneGeometry(lb * 2, y1 - y0); const uv = g.attributes.uv; for (let i = 0; i < uv.count; i++) uv.setXY(i, uv.getX(i) * 3, uv.getY(i) * ((y1 - y0) / 5)); const m4 = new THREE.Matrix4().makeRotationY(yaw + ry), q = P(0, -backD + dz); m4.setPosition(q[0], Y + (y0 + y1) / 2, q[1]); KIT.geo(g, drape[k % 4], m4); }
          for (const e of [-1, 1]) { const q = P(e * lb, -backD); KIT.beam([q[0], Y - 0.6, q[1]], [q[0], Y + topH + 1.2, q[1]], 0.3, M.woodD); } const q2 = P(0, -backD); KIT.obox(q2[0], Y + topH, q2[1], lb, Y + topH + 0.25, 0.3, yaw, M.wood, { col: false }); } } }
    // the crowd: one instanced draw. Each spectator is a small robed figure — robe and pointed hat in their house's colour, a scarf in its second,
    // a face of their own — who sways, and when the match heats up throws both arms in the air and jumps (colours: 1 = robe tint, 2 = scarf tint, else as painted)
    { const parts = [], add = (g, col, part) => parts.push([g, col, part]);
      { const robe = new THREE.CylinderGeometry(0.15, 0.3, 0.92, 7); robe.translate(0, 0.46, 0); add(robe, [1, 1, 1], 1); const sh = new THREE.SphereGeometry(0.2, 7, 5); sh.scale(1.15, 0.55, 0.8); sh.translate(0, 0.9, 0); add(sh, [1, 1, 1], 1);
        const scarf = new THREE.CylinderGeometry(0.115, 0.125, 0.09, 8); scarf.translate(0, 1.0, 0); add(scarf, [1, 1, 1], 2); const tail = new THREE.BoxGeometry(0.07, 0.3, 0.03); tail.translate(0.07, 0.84, 0.13); add(tail, [1, 1, 1], 2);
        const head = new THREE.SphereGeometry(0.135, 8, 6); head.translate(0, 1.16, 0); add(head, [1, 1, 1], 3); const hat = new THREE.ConeGeometry(0.15, 0.4, 7); hat.translate(0, 1.47, 0); add(hat, [0.5, 0.5, 0.5], 1); const brim = new THREE.CylinderGeometry(0.24, 0.24, 0.025, 9); brim.translate(0, 1.275, 0); add(brim, [0.5, 0.5, 0.5], 1);
        for (const sx of [-1, 1]) { const arm = new THREE.CylinderGeometry(0.045, 0.055, 0.52, 5); arm.translate(0, 0.26, 0); arm.rotateZ(-sx * 2.6); arm.translate(sx * 0.2, 0.9, 0.02); add(arm, [0.92, 0.92, 0.92], sx < 0 ? 4 : 5); const hand = new THREE.SphereGeometry(0.05, 5, 4); hand.translate(sx * 0.2 + sx * Math.sin(2.6) * 0.52, 0.9 + Math.cos(2.6) * 0.52, 0.02); add(hand, [1, 1, 1], sx < 0 ? 6 : 7); } }
      const P2 = [], N2 = [], C2 = [], A2 = []; for (const [g0, c, part] of parts) { const g = g0.index ? g0.toNonIndexed() : g0; g.computeVertexNormals(); const p = g.attributes.position, n = g.attributes.normal; for (let i = 0; i < p.count; i++) { P2.push(p.getX(i), p.getY(i), p.getZ(i)); N2.push(n.getX(i), n.getY(i), n.getZ(i)); C2.push(c[0], c[1], c[2]); A2.push(part); } }
      const geo = new THREE.BufferGeometry(); geo.setAttribute('position', new THREE.Float32BufferAttribute(P2, 3)); geo.setAttribute('normal', new THREE.Float32BufferAttribute(N2, 3)); geo.setAttribute('color', new THREE.Float32BufferAttribute(C2, 3)); geo.setAttribute('aPart', new THREE.Float32BufferAttribute(A2, 1));
      const mat = new THREE.MeshLambertMaterial({ vertexColors: true }), U = { uT: { value: 0 }, uX: { value: 0 } }; Q.crowdU = U;
      mat.onBeforeCompile = (sh) => { sh.uniforms.uT = U.uT; sh.uniforms.uX = U.uX;
        sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nuniform float uT, uX; attribute float aPh, aPart; attribute vec3 aTint, aTint2, aSkin;')
          .replace('#include <color_vertex>', '#include <color_vertex>\n{ vec3 tc = aPart < 0.5 ? vec3(1.0) : aPart < 1.5 ? aTint : aPart < 2.5 ? aTint2 : aPart < 3.5 ? aSkin : aPart < 5.5 ? aTint : aSkin; vColor.rgb = color.rgb * tc; }')
          .replace('#include <begin_vertex>', '#include <begin_vertex>\n{ float ph = aPh * 6.283; float keen = 0.35 + 0.65 * fract(aPh * 7.31); float up = clamp(uX * keen * 1.5 - 0.15 + 0.12 * sin(uT * 0.7 + ph), 0.0, 1.0); if (aPart > 3.5) { /* an arm (or its hand): swung up from the shoulder as the excitement rises, and waved */ float sx = (aPart < 4.5 || (aPart > 5.5 && aPart < 6.5)) ? -1.0 : 1.0; vec2 piv = vec2(sx * 0.2, 0.9); float ang = sx * (up * 2.5 + up * 0.35 * sin(uT * 9.0 + ph * 3.0)); float cs = cos(ang), sn = sin(ang); vec2 d = transformed.xy - piv; transformed.xy = piv + vec2(d.x * cs - d.y * sn, d.x * sn + d.y * cs); } transformed.y += (0.03 + 0.3 * uX * keen) * max(0.0, sin(uT * (5.0 + aPh * 3.0) + ph)) * (0.35 + position.y); transformed.x += sin(uT * 1.6 + ph) * 0.045 * position.y; }'); };
      mat.customProgramCacheKey = () => 'hlstands';
      const n = people.length, im = new THREE.InstancedMesh(geo, mat, n), m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), col = new THREE.Color(), ph = new Float32Array(n), t1 = new Float32Array(n * 3), t2 = new Float32Array(n * 3), sk = new Float32Array(n * 3), SK = [[0.86, 0.64, 0.52], [0.78, 0.56, 0.44], [0.56, 0.38, 0.27], [0.36, 0.24, 0.17], [0.82, 0.6, 0.48]], two = {}; for (const k in HL.HOUSES) two[HL.HOUSES[k].col] = HL.HOUSES[k].col2, two[HL.HOUSES[k].col2] = HL.HOUSES[k].col;
      people.forEach((p, i) => { q.setFromAxisAngle(YUP, p[3]); const s = 0.9 + p[5] * 0.25; m4.compose(V3(p[0], p[1], p[2]), q, V3(s, s, s)); im.setMatrixAt(i, m4); ph[i] = p[5]; col.set(p[4]); t1[i * 3] = col.r * 0.95 + 0.02; t1[i * 3 + 1] = col.g * 0.95 + 0.02; t1[i * 3 + 2] = col.b * 0.95 + 0.02; col.set(two[p[4]] !== undefined ? two[p[4]] : 0xd8c8a0); t2[i * 3] = col.r * 1.05 + 0.03; t2[i * 3 + 1] = col.g * 1.05 + 0.03; t2[i * 3 + 2] = col.b * 1.05 + 0.03; const S2 = SK[(i * 7 + 3) % SK.length]; sk[i * 3] = S2[0]; sk[i * 3 + 1] = S2[1]; sk[i * 3 + 2] = S2[2]; });
      geo.setAttribute('aPh', new THREE.InstancedBufferAttribute(ph, 1)); geo.setAttribute('aTint', new THREE.InstancedBufferAttribute(t1, 3)); geo.setAttribute('aTint2', new THREE.InstancedBufferAttribute(t2, 3)); geo.setAttribute('aSkin', new THREE.InstancedBufferAttribute(sk, 3)); im.instanceMatrix.needsUpdate = true; im.computeBoundingSphere(); im.castShadow = false; LEVEL.add(im); Q.crowd = im; Q.people = people;
      L.updates.push((dt, t) => { U.uT.value = t; Q.excite = Math.max(0, Q.excite - dt * 0.35); U.uX.value = damp(U.uX.value, Math.min(1, Q.excite), 4, dt); for (const side of Q.hoops) for (const h of side) h.glow = Math.max(0, h.glow - dt); }); }
    // the players' gate and the referee's spot
    Q.REF = [C.x - Q.AX - 4, Y, C.z - 20];
    for (const s of [-1, 1]) WORLD.brazier(L, C.x - Q.AX - 4, C.z + s * 6 - 20, { y: Y });
  });
  /* ---------------------------------------------------------------- balls */
  Q.mkBall = function (r, col, rough, metal) { const m = new THREE.Mesh(new THREE.IcosahedronGeometry(r, 2), new THREE.MeshStandardMaterial({ color: col, roughness: rough, metalness: metal, envMapIntensity: 1 })); m.castShadow = true; R.scene.add(m); return m; };
  Q.mkSnitch = function () { const g = new THREE.Group(), gold = new THREE.MeshStandardMaterial({ color: 0xffd060, metalness: 1, roughness: 0.2, emissive: 0x6a4a08, emissiveIntensity: 1.2, envMapIntensity: 1.6 });
    g.add(new THREE.Mesh(new THREE.SphereGeometry(0.055, 14, 10), gold)); const wg = new THREE.PlaneGeometry(0.26, 0.07, 3, 1); wg.translate(0.15, 0, 0); const wm = new THREE.MeshStandardMaterial({ color: 0xfff0c0, metalness: 0.8, roughness: 0.3, side: THREE.DoubleSide, emissive: 0x8a6a20, emissiveIntensity: 1 });
    const wl = new THREE.Mesh(wg, wm), wr = new THREE.Mesh(wg, wm); wr.scale.x = -1; g.add(wl, wr); g.userData.w = [wl, wr]; g.add(HL.sprite([1.0, 0.8, 0.3], 3, 0.7)); R.scene.add(g); return g; };
  /* ---------------------------------------------------------------- the match */
  Q.inField = (x, z, m) => { const dx = (x - C.x) / (Q.AX + m), dz = (z - C.z) / (Q.AZ + m); return dx * dx + dz * dz < 1; };
  Q.DIFF = [{ n: 'BEGINNER', keep: -0.2, sp: 0.88, seek: 1.5, tk: 0.5, st: 0.9, ks: 9, rd: 0.2, bl: 0.12, rg: 26, pd: 23, mt: 1.6 }, { n: 'SEASONED', keep: 0, sp: 1, seek: 1, tk: 1, st: 0.6, ks: 13, rd: 0.65, bl: 0.2, rg: 31, pd: 26.5, mt: 0.9 }, { n: 'LEGEND', keep: 0.14, sp: 1.1, seek: 0.72, tk: 1.5, st: 0.42, ks: 15, rd: 0.88, bl: 0.28, rg: 35, pd: 29, mt: 0.55 }];
  Q.start = async function (opt) {
    if (Q.on || Q.loading) return; Q.loading = true; const U = HL.ui; U.fade(1); await new Promise((r) => setTimeout(r, 600));
    const o = Q.opt = Object.assign({ house: HL.house, rival: Q.RIVAL[HL.house], diff: 1, len: 300, role: 'chaser', arcade: false, sn: 30 }, opt || {}); Q.D = Q.DIFF[o.diff];
    const mine = o.house, rival = o.rival; Q.teams = [mine, rival]; Q.stats = { goals: 0, shots: 0, saves: 0, tackles: 0, passes: 0, dodges: 0, hits: 0, top: 0, poss: 0, possT: 0 }; Q.reach = 0; Q.log = [];
    const names = []; for (const [h, n] of [[mine, 5], [rival, 5]]) for (let v = 1; v <= n; v++) names.push(HL.student(h, v % 2 === 0, v, true)); const pn = HL.student(mine, HL.witch, 0, true); names.push(pn);
    await CAST.need(names);
    // the player takes the field in match robes
    CHAR.T.maul = CHAR.T[pn]; const sp = [C.x, Q.Y0 + 0.1, C.z - 14]; PLAYER.spawn(sp[0], sp[1], sp[2], 0); CAM.reset(0);
    Q.flyers = []; const P = PLAYER.a; HL.fly.mount(); P.y = Q.Y0 + 9; Q.me = { a: P, team: 0, role: o.role, isPlayer: true, vel: HL.fly.vel, stunT: 0, noCatch: 0, name: 'You' }; Q.flyers.push(Q.me);
    const mk = (team, role, i, x, y, z) => { const h = Q.teams[team], v = team === 0 ? i + 1 : i + 1, T = CHAR.T[HL.student(h, v % 2 === 0, v, true)], a = new Actor(T, { x, y, z, yaw: team ? PI : 0, hp: 100, team: 'q' + team, moves: MOV.wizard, r: 0.34, h: 1.8 }); a.noTarget = true;
      const f = { a, R: new Rider(a), team, role, vel: new THREE.Vector3(), stunT: 0, noCatch: 0, ph: RNG() * 9, lane: i, name: HL.HOUSES[h].name + ' ' + role }; f.R.yaw = team ? PI : 0; Q.flyers.push(f); return f; };
    const s0 = -1, s1 = 1;
    mk(0, 'chaser', 0, C.x - 10, Q.Y0 + 9, C.z - 18); mk(0, 'chaser', 1, C.x + 10, Q.Y0 + 9, C.z - 18); mk(0, 'keeper', 2, C.x, Q.Y0 + 12, C.z + s0 * (Q.HZ - 5)); if (o.role === 'seeker') mk(0, 'chaser', 3, C.x, Q.Y0 + 10, C.z - 16); else mk(0, 'seeker', 3, C.x - 20, Q.Y0 + 30, C.z - 30);
    mk(1, 'chaser', 0, C.x - 12, Q.Y0 + 9, C.z + 16); mk(1, 'chaser', 1, C.x, Q.Y0 + 10, C.z + 14); mk(1, 'chaser', 2, C.x + 12, Q.Y0 + 9, C.z + 16); mk(1, 'keeper', 3, C.x, Q.Y0 + 12, C.z + s1 * (Q.HZ - 5)); mk(1, 'seeker', 4, C.x + 20, Q.Y0 + 30, C.z + 30);
    Q.ball = { m: Q.mkBall(0.17, 0x8a2a1a, 0.6, 0), p: V3(C.x, Q.Y0 + 12, C.z), v: V3(0, 14, 0), holder: null, lastTeam: -1, shot: null };
    Q.bl = [0, 1].map((i) => ({ m: Q.mkBall(0.2, 0x1c1c20, 0.35, 0.9), p: V3(C.x + (i ? 14 : -14), Q.Y0 + 20, C.z), v: V3(0, 6, i ? 8 : -8), tgt: null, tT: 2 + i * 2, hitT: 0 }));
    Q.snitch = null; Q.score = [0, 0]; Q.t = 0; Q.T = o.len; Q.snT = o.role === 'seeker' ? 6 : o.len * 0.55; Q.SNP = o.role === 'seeker' ? 150 : (o.sn || 30); Q.aiCatch = 0; Q.phase = 'intro'; Q.iT = 0; Q.cT = 3.6; Q.cN = 9; Q.rsT = 0; Q.grabs = 0; Q.reach = 0; Q.on = true; Q.loading = false; Q.outT = 0; Q.excite = 0.6;
    const E = U.el; E.Q.classList.add('on'); E.Qa.textContent = HL.HOUSES[mine].name.toUpperCase(); E.Qb.textContent = HL.HOUSES[rival].name.toUpperCase(); E.Qa.style.color = HL.HOUSES[mine].css; E.Qb.style.color = HL.HOUSES[rival].css;
    E.Bar.style.display = 'none'; E.BarT.style.display = 'none'; E.Quest.style.display = 'none'; U.fade(0);
    U.toast(HL.HOUSES[mine].name.toUpperCase() + '  v  ' + HL.HOUSES[rival].name.toUpperCase(), o.role === 'seeker' ? 'You fly Seeker. Find the Golden Snitch, stay on its tail and close your hand on it.' : 'You fly Chaser. Take the Quaffle through the far hoops — ten points a goal.', 6);
    Q.hintT = 6.2; if (Q.intro) Q.intro();
  };
  Q.end = function (reason) {
    if (!Q.on || Q.phase === 'over') return; Q.phase = 'over'; const U = HL.ui, a = Q.score[0], b = Q.score[1], win = a > b, H = HL.HOUSES[Q.teams[0]];
    MG.slowmo = 0.3; MG.slowmoT = 0; MG.slowmoDur = 1.2; Q.excite = 3;
    U.toast(win ? H.name.toUpperCase() + ' WIN!' : a === b ? 'A DRAW' : HL.HOUSES[Q.teams[1]].name.toUpperCase() + ' WIN', `${a} – ${b}` + (reason ? ' · ' + reason : ''), 7);
    const pts = Math.round(a / 2) + (win ? 50 : 0); if (!Q.opt.arcade) { /* (a match from the Quidditch menu is not the castle's business: it used to post the story's side quest over the results card) */ HL.save.points = (HL.save.points || 0) + pts; HL.save.best.q = Math.max(HL.save.best.q || 0, a); HL.save.qPlayed = 1; if (win) HL.save.qWon = (HL.save.qWon || 0) + 1; HL.store(); }
    Q.result = { a, b, win, draw: a === b, reason, pts, stats: Q.stats, teams: Q.teams.slice(), t: Q.t };
    if (!Q.opt.arcade) MG.after(6.5, () => { U.pop('+' + pts + ' HOUSE POINTS'); }, true);
    for (let i = 0; i < 6; i++) MG.after(0.4 + i * 0.7, () => { if (!Q.on) return; const p = V3(C.x + rnd(-30, 30), Q.Y0 + rnd(30, 55), C.z + rnd(-70, 70)), c = new THREE.Color(HL.HOUSES[Q.teams[win ? 0 : 1]].col); FX.spark(p, null, 60, 13, [2 + c.r * 5, 2 + c.g * 5, 1 + c.b * 5], 1.2); FX.flashLight(p, [1, 0.8, 0.5], 50, 60, 0.4); }, true);
    MG.after(Q.opt.arcade ? 6 : 8.5, () => Q.cleanup(), true);
  };
  Q.cleanup = function () {
    const U = HL.ui; U.fade(1);
    setTimeout(() => { for (const f of Q.flyers) if (!f.isPlayer) { f.R.dispose(); f.a.dispose(); } Q.flyers = []; for (const b of Q.bl) R.scene.remove(b.m); Q.bl = []; if (Q.ball) R.scene.remove(Q.ball.m); Q.ball = null; if (Q.snitch) { R.scene.remove(Q.snitch.m); Q.snitch = null; }
      if (HL.fly.on) HL.fly.dismount(true); const n = HL.student(HL.house, HL.witch, 0); if (CHAR.T[n]) CHAR.T.maul = CHAR.T[n]; PLAYER.spawn(Q.REF[0] + 3, Q.Y0, Q.REF[2], HALF); CAM.reset(HALF); CAM.cine = null;
      Q.on = false; Q.phase = 'off'; const E = U.el; E.Q.classList.remove('on'); E.Bar.style.display = ''; E.BarT.style.display = ''; E.Quest.style.display = ''; U.fade(0);
      const nx = Q.quitNext, tut = Q.tut; Q.quitNext = null; Q.quitting = false; if (Q.tutClear) Q.tutClear();
      if (nx) nx(); else if (tut && Q.tutResults) Q.tutResults(tut.story); else if (Q.opt.arcade && Q.results) Q.results(); else if (HL.onMatchEnd) HL.onMatchEnd(); }, 700);
  };
  Q.pos = (f, o) => (o || new THREE.Vector3()).set(f.a.x, f.a.y + 0.9, f.a.z);
  Q.goalOf = (team) => (team === 0 ? 1 : 0);                              // team 0 attacks the +z hoops
  Q.drop = function (f, v) { const B = Q.ball; if (B.holder !== f) return; B.holder = null; Q.pos(f, B.p); B.v.copy(v || f.vel).multiplyScalar(0.6); B.v.y += 3; f.noCatch = 0.9; B.shot = null; };
  Q.throwBall = function (f, target, speed, shot) { const B = Q.ball; if (B.holder !== f) return; B.holder = null; Q.pos(f, B.p); const d = target.clone().sub(B.p); const L = d.length(); d.multiplyScalar(1 / L); B.p.addScaledVector(d, 0.7); B.v.copy(d).multiplyScalar(speed); B.v.y += 3.5 * L / speed;   /* (lobbed to arrive at what it was thrown at: it used to fall two metres short at thirty) */ f.noCatch = 0.6; B.lastTeam = f.team; B.shot = shot ? { team: f.team, by: f, t: Q.t } : null; B.passTo = shot ? null : B.passTo;
    if (!f.isPlayer && f.a.play) f.a.play('throwQ', { fade: 0.08 }); else if (f.isPlayer) PLAYER.a.play('throwQ', { fade: 0.06 }); };
  Q.goal = function (team, hoop) { const val = Q.ball.shot && Q.ball.shot.power ? 20 : 10; Q.score[team] += val; if (Q.snitch && Q.race && Q.me.role !== 'seeker') Q.race[team] = Math.min(0.97, Q.race[team] + 0.06);   /* (a goal while the Snitch is out spurs that side's Seeker: outscore them and yours gets there first) */ if (team === 0 && Q.ball.shot && Q.ball.shot.by.isPlayer) Q.stats.goals++; Q.say(team === 0 ? HL.HOUSES[Q.teams[0]].name + ' score!' : HL.HOUSES[Q.teams[1]].name + ' put it through the hoop.'); hoop.glow = 1.5; Q.excite = 2.2; const p = V3(hoop.x, hoop.y, hoop.z), H = HL.HOUSES[Q.teams[team]], c = new THREE.Color(H.col); Q.gb = { t: 2.3, team, val };   // (the match HUD puts the goal up in letters you cannot miss)
    FX.ring(p, [c.r * 4 + 1, c.g * 4 + 1, c.b * 4 + 0.6], 7, 0.7); FX.spark(p, null, 50, 12, [3 + c.r * 4, 2.4 + c.g * 4, 1 + c.b * 4], 0.9); FX.flashLight(p, [1, 0.85, 0.5], 60, 30, 0.5); if (team === 0) { MG.slowmo = 0.3; MG.slowmoT = 0; MG.slowmoDur = 0.5; R.kick(0.3); FX.addShake(0.2); }
    /* the stands go up: bursts in the scorers' colours over the towers and along the stands */ { const c2 = new THREE.Color(H.col2), pe = Q.people || []; for (let q = 0; q < 14 && pe.length; q++) { const e = pe[(q * 67 + (Q.score[0] + Q.score[1]) * 13) % pe.length], cc = q % 2 ? c2 : c; MG.after(0.15 + q * 0.09, () => { if (!Q.on) return; const pp = V3(e[0], e[1] + 3 + (q % 3) * 2.5, e[2]); FX.spark(pp, null, 34, 9, [1 + cc.r * 5, 1 + cc.g * 5, 0.6 + cc.b * 5], 1.1); if (q % 4 === 0) FX.flashLight(pp, [1, 0.8, 0.5], 30, 22, 0.3); }); } }
    // the Quaffle goes to the Keeper who was beaten
    const k = Q.flyers.find((f) => f.role === 'keeper' && f.team !== team), B = Q.ball; B.holder = k; B.shot = null; B.v.set(0, 0, 0); k.holdT = 1.2; Q.rsT = 4.5; Q.rsTeam = team; };   /* the restart: for a few seconds the side that scored falls back to its own half (you could sit on their Keeper's first pass and score again, and again) */
  Q.say = function (t) { Q.log.push(t); if (Q.log.length > 30) Q.log.shift(); Q.sayT = 3.2; Q.sayS = t; };
  Q.status = function () { if (Q.me.role === 'seeker') { if (!Q.snitch) return 'Circle high and watch for a glint of gold…'; const n = Math.round(Q.reach * 8); return '<b>THE SNITCH</b> — stay on its tail  ' + '▮'.repeat(n) + '▯'.repeat(8 - n) + '   ' + '◆'.repeat(Q.grabs || 0) + '◇'.repeat(3 - (Q.grabs || 0)); } const B = Q.ball, me = Q.me; if (Q.phase === 'count') return 'Brooms up…'; if (Q.snitch) { if (B && B.holder === me) return '<b>THE SNITCH IS LOOSE</b> · you have the Quaffle — <b>LMB</b> shoot'; if (!B || !B.holder || B.holder.team === 0) return '<b>THE SNITCH IS LOOSE</b> — every goal spurs your Seeker · <b>LMB</b> knocks theirs off it'; }
    if (!B) return ''; if (B.holder === me) return 'You have the Quaffle — <b>LMB</b> shoot (hold to wind up) · <b>E</b> pass'; if (B.holder && B.holder.team === 0) return 'Your Chaser has it — <b>E</b> call for the pass'; if (B.holder) return 'Rivals have it — <b>LMB</b> lunge at the carrier and take it'; return 'Loose Quaffle — fly at it!'; };
  Q.way = function () { if (!Q.on) return null; if (Q.snitch) return [Q.snitch.p.x, Q.snitch.p.y, Q.snitch.p.z]; const B = Q.ball; if (!B || B.holder === Q.me) { const h = Q.hoops[1][1]; return B ? [h.x, h.y, h.z] : null; } return [B.p.x, B.p.y, B.p.z]; };
  /* steering for the computer's flyers */
  Q.steer = function (f, tx, ty, tz, maxSp, dt, acc) { const a = f.a, dx = tx - a.x, dy = ty - (a.y + 0.9), dz = tz - a.z, d = Math.hypot(dx, dy, dz) || 1, sp = Math.min(maxSp, d * 1.6 + 2); _v1.set(dx / d * sp, dy / d * sp, dz / d * sp);
    for (const o of Q.flyers) { if (o === f) continue; const ox = a.x - o.a.x, oy = a.y - o.a.y, oz = a.z - o.a.z, od = Math.hypot(ox, oy, oz); if (od < 2.6 && od > 0.01) _v1.addScaledVector(_v2.set(ox, oy, oz), (2.6 - od) * 3 / od); }
    f.vel.lerp(_v1, 1 - Math.exp(-(acc || 2.2) * dt)); };
  Q.move = function (f, dt) { const a = f.a, Rd = f.R; if (f.stunT > 0) { f.stunT -= dt; f.vel.multiplyScalar(Math.exp(-1.5 * dt)); Rd.roll += dt * 9; } a.x += f.vel.x * dt; a.y += f.vel.y * dt; a.z += f.vel.z * dt;
    a.y = clamp(a.y, Q.Y0 + 1.4, Q.CEIL); const dx = (a.x - C.x) / (Q.AX + 4), dz = (a.z - C.z) / (Q.AZ + 4), e = dx * dx + dz * dz; if (e > 1) { const k = 1 / Math.sqrt(e); a.x = C.x + (a.x - C.x) * k; a.z = C.z + (a.z - C.z) * k; }
    const sp = f.vel.length(); if (sp > 1.5 && f.stunT <= 0) { const yw = Math.atan2(f.vel.x, f.vel.z), dy = wrapA(yw - Rd.yaw); Rd.yaw += dy * Math.min(1, dt * 6); Rd.pitch = damp(Rd.pitch, Math.asin(clamp(f.vel.y / sp, -1, 1)) * 0.8, 5, dt); Rd.roll = damp(Rd.roll, clamp(-dy * 1.6, -0.9, 0.9), 5, dt); } else if (f.stunT <= 0) { Rd.pitch = damp(Rd.pitch, 0, 3, dt); Rd.roll = damp(Rd.roll, 0, 3, dt); if (f.face !== undefined) Rd.yaw = dampA(Rd.yaw, f.face, 4, dt); }
    Rd.speed = sp; Rd.update(dt); };
  /* a computer flyer's tackle on whoever has the Quaffle. On you it is announced: he draws level, winds up (a red mark over him), and only then swings — roll (R) inside that and he misses; if it lands he comes away with the ball. One winds up at a time. */
  Q.tackleAI = function (f, c, dt) { const B = Q.ball, a = f.a, dC = Q.pos(f, _v5).distanceTo(Q.pos(c, _v4)); f.tkCd = Math.max(0, (f.tkCd || 0) - dt);
    if (c.isPlayer) { if (!(f.wind > 0) && dC < 4.2 && f.tkCd <= 0 && c.stunT <= 0 && !Q.flyers.some((o) => o !== f && o.wind > 0)) f.wind = 0.62 / Math.sqrt(Q.D.tk);
      if (f.wind > 0) { f.wind -= dt; if (f.wind <= 0) { f.wind = 0; f.tkCd = 2.6 / Q.D.tk; if (HL.fly.spinT > 0 || Q.t - (Q.rollAt || -9) < 1.0) Q.dodgedTk(f); else if (dC < 3.5) { Q.knock(c, V3(c.a.x - a.x, 0.2, c.a.z - a.z).normalize(), 'TACKLED!'); if (!B.holder) { B.holder = f; B.lastTeam = f.team; B.shot = null; f.holdT = 0; f.noCatch = 0; } } } } }
    else if (dC < 1.7 && RNG() < dt * (f.team === 0 ? Q.D.mt : 1.6) && c.role !== 'keeper') Q.knock(c, V3(c.a.x - a.x, 0.2, c.a.z - a.z).normalize(), 'TACKLED!'); };
  Q.knock = function (f, dir, by) { f.stunT = 1.1; if (Q.ball.holder === f) Q.drop(f, dir.clone().multiplyScalar(8)); if (f.isPlayer) { HL.fly.bump({}); HL.fly.vel.addScaledVector(dir, 9); HL.ui.pop(by || 'BLUDGER!'); HL.ui.hurt(20); } else f.vel.addScaledVector(dir, 10); FX.spark(Q.pos(f), dir, 16, 6, [3, 2.6, 2], 0.4); };
  Q.update = function (dt) {
    if (!Q.on) return; const B = Q.ball, me = Q.me, U = HL.ui, E = U.el; me.a = PLAYER.a;
    if (Q.arena && Q.phase !== 'intro' && Q.phase !== 'over') Q.arena.cam(dt);
    if (PLAYER.state !== 'fly' && Q.phase !== 'over') { if (!HL.fly.on) HL.fly.mount(); }
    for (const f of Q.flyers) { f.noCatch = Math.max(0, f.noCatch - dt); }
    if (me.stunT > 0) me.stunT -= dt;
    if (Q.phase === 'intro') { Q.iT += dt; HL.fly.speed = 0; HL.fly.vel.set(0, 0, 0); B.p.set(C.x, Q.Y0 + 1.2, C.z); B.m.position.copy(B.p); if (Q.iT > 5.2 || (Q.iT > 0.6 && (IN.take('attack') || IN.take('jump') || IN.take('confirm')))) { Q.phase = 'count'; CAM.cine = null; CAM.reset(0); U.el.Toast.classList.remove('on'); U.toastT = 0;   /* (the title card goes with the flyover) */ U.hint(Q.me.role === 'seeker' ? '<kbd>W</kbd> fly &nbsp; <kbd>SHIFT</kbd> boost &nbsp; <kbd>LMB</kbd> lunge &nbsp; <kbd>R</kbd> barrel roll (dodges Bludgers) &nbsp; <kbd>SPACE</kbd>/<kbd>C</kbd> up / down' : '<kbd>W</kbd> fly &nbsp; <kbd>F</kbd> face the play &nbsp; <kbd>LMB</kbd> shoot / lunge &nbsp; <kbd>E</kbd> pass &nbsp; <kbd>R</kbd> roll &nbsp; <kbd>SHIFT</kbd> boost', 9); } }
    if (Q.phase === 'play') { Q.stats.top = Math.max(Q.stats.top, HL.fly.speed); Q.stats.possT += dt; if (B.holder && B.holder.team === 0) Q.stats.poss += dt; }
    if (Q.phase === 'count') { Q.cT -= dt; const n = Math.ceil(Q.cT - 0.6); if (n !== Q.cN) { Q.cN = n; if (n > 0) U.pop(String(n)); else U.pop('PLAY!'); } if (Q.cT <= 0.6 && B.v.y === 14 && !Q.tossed) { Q.tossed = true; } if (Q.cT <= 0) { Q.phase = 'play'; Q.tossed = false; }
      B.p.set(C.x, Q.Y0 + 3 + (3.6 - Q.cT) * 2.4, C.z); B.v.set(0, 9, 0); HL.fly.speed = Math.min(HL.fly.speed, 3); }
    if (Q.phase === 'play') { Q.t += dt; Q.rsT = Math.max(0, (Q.rsT || 0) - dt); if (Q.arcade) Q.arcade(dt);
      // ---- the Quaffle
      if (B.holder) { const f = B.holder; Q.pos(f, B.p); const R0 = f.isPlayer ? HL.fly.R : f.R; if (R0) { B.p.addScaledVector(_v1.set(-Math.cos(R0.yaw), 0, Math.sin(R0.yaw)), 0.34).addScaledVector(R0.fw, 0.25); B.p.y -= 0.2; } }
      else { B.v.y -= 7 * dt; B.v.multiplyScalar(Math.exp(-0.18 * dt));
        /* a dropped Quaffle does not lie on the grass: it is charmed to sink slowly and hang a broom's height up, where a Chaser can scoop it (it used to come to rest on the ground under everyone's reach — the match stood still for good, two Chasers hovering over it) */
        { const hov = Q.Y0 + 3.4; if (B.p.y < hov + 2.5 && !B.shot) { const k = clamp((hov + 2.5 - B.p.y) / 2.5, 0, 1); B.v.y += (7 * k + (hov - B.p.y) * 5 * k) * dt; B.v.y *= Math.exp(-2.2 * k * dt); const dr = Math.exp(-1.4 * k * dt); B.v.x *= dr; B.v.z *= dr; } }
        const np = _v3.copy(B.p).addScaledVector(B.v, dt);
        // through a hoop?
        for (let side = 0; side < 2; side++) for (const h of Q.hoops[side]) { if ((B.p.z - h.z) * (np.z - h.z) < 0) { const t = (h.z - B.p.z) / (np.z - B.p.z), x = B.p.x + (np.x - B.p.x) * t, y = B.p.y + (np.y - B.p.y) * t, d = Math.hypot(x - h.x, y - h.y);
              if (d < h.r) { const team = side === 1 ? 0 : 1, dirOK = side === 1 ? B.v.z > 0 : B.v.z < 0; if (dirOK && B.lastTeam === team) { Q.goal(team, h); break; } } else if (d < h.r + 0.34) { B.v.z *= -0.5; B.v.x += (x - h.x) * 3; np.copy(B.p); FX.spark(V3(x, y, h.z), null, 10, 4, [3, 2.4, 1], 0.3); U.pop('OFF THE RIM'); } } }
        if (!B.holder) { B.p.copy(np); if (B.p.y < Q.Y0 + 0.25) { B.p.y = Q.Y0 + 0.25; B.v.y = Math.abs(B.v.y) * 0.5; B.v.x *= 0.7; B.v.z *= 0.7; }
          const dx = (B.p.x - C.x) / (Q.AX + 7), dz = (B.p.z - C.z) / (Q.AZ + 7); if (dx * dx + dz * dz > 1) { B.v.x = (C.x - B.p.x) * 0.5; B.v.z = (C.z - B.p.z) * 0.5; B.v.y = 5; }
          // caught by whoever reaches it (a Keeper's reach is long; a shot can be saved)
          let best = null, bd = 1e9; for (const f of Q.flyers) { if (f.noCatch > 0 || f.stunT > 0 || f.role === 'seeker') continue; /* a shot is not plucked out of the thrower's hand by the rival beside him, and a Roaring Shot is nobody's to catch */ if (B.shot && f.team !== B.shot.team && (B.shot.power || (f.role !== 'keeper' && Q.t - (B.shot.t || 0) < 0.3))) continue; const d = Q.pos(f, _v4).distanceTo(B.p), reach = f.role === 'keeper' ? 2.3 : f.isPlayer ? 3.1 : 1.8; if (d < reach && d < bd) { bd = d; best = f; } }
          if (best) { if (B.shot && best.role === 'keeper' && best.team !== B.shot.team) { /* one dive a shot (he used to get a fresh chance every frame the ball was within his reach — six of them — and saved nearly everything) */ const sp = B.v.length(); if (B.shot.beat) best = null; else if (RNG() < (B.shot.power ? 0 : B.shot.by.isPlayer ? clamp(0.9 - 0.4 * (B.shot.pw || 0.3) + Q.D.keep, 0.08, 0.92) : (best.team === 0 ? clamp(0.35 - Q.D.keep * 0.7, 0.15, 0.6) : 0.45))) { U.pop('SAVED!'); Q.excite = 1.2; if (best.team === 0) Q.stats.saves++; Q.say('Saved by the Keeper!'); } else { B.shot.beat = true; best = null; } }
            if (best) { B.holder = best; B.shot = null; B.lastTeam = best.team; best.holdT = 0; if (best.role === 'keeper') { /* a Keeper with the ball in his hands restarts play: the other side falls back (you could hover by him and pick off every throw-out) */ Q.rsT = 4; Q.rsTeam = 1 - best.team; best.holdT = 0.9; } if (best.isPlayer) { PLAYER.a.play('catchQ', { fade: 0.06 }); R.kick(0.12); } else if (best.team === 0 && B.passTo === best) { /* pass completed */ } } } } }
      B.m.position.copy(B.p); B.m.rotation.x += dt * 5;
      // ---- the player's hands
      if (me.role === 'seeker') { if (IN.take('attack')) { HL.fly.speed = Math.min(54, HL.fly.speed + 10); R.kick(0.2); } }
      else if (me.stunT <= 0) Q.hands(dt);   // (p77c: shots wound up and aimed at the hoop you look at, lunges that steal, passes)
      delete IN.buf.attack; delete IN.buf.push; delete IN.buf.block;
      // ---- the computer's flyers
      for (const f of Q.flyers) { if (f.isPlayer) continue; const a = f.a, att = f.team === 0 ? 1 : -1, gz = C.z + att * Q.HZ, own = C.z - att * Q.HZ, dk = f.team === 1 ? Q.D.sp : 1; let sp = 21;
        if (f.wind > 0 && !(B.holder && B.holder.isPlayer)) f.wind = 0; f.burst = Math.max(0, (f.burst || 0) - dt); f.burstCd = Math.max(0, (f.burstCd || 0) - dt);
        if (f.stunT > 0) { Q.move(f, dt); continue; }
        if (f.script) { f.script(f, dt); Q.move(f, dt); continue; }   // (the flying lesson directs its own cast)
        if (f.role === 'keeper') { const ahead = own + att * 5; let tx = C.x, ty = Q.Y0 + 12; if (!B.holder || B.holder.team !== f.team) { const k = clamp(1 - Math.abs(B.p.z - own) / 70, 0, 1); tx = C.x + clamp(B.p.x - C.x, -8, 8) * (0.5 + 0.5 * k); ty = clamp(lerp(Q.Y0 + 12, B.p.y, k), Q.Y0 + 9, Q.Y0 + 15); }
          /* their Keeper watches where you are looking: the hoop you aim at is the one he drifts to cover — look at one, then turn and shoot at another */ if (f.team === 1 && B.holder === me && Q.aimHoop && Math.abs(me.a.z - own) < 55) { tx = lerp(tx, Q.aimHoop.x, Q.D.rd); ty = lerp(ty, clamp(Q.aimHoop.y, Q.Y0 + 9, Q.Y0 + 15), Q.D.rd); }
          f.face = att > 0 ? 0 : PI; Q.steer(f, tx, ty, ahead, f.team === 1 ? Q.D.ks : 10.5, dt, 3);
          if (B.holder === f) { f.holdT = (f.holdT || 0) - dt; if (f.holdT <= 0) { const mates = Q.flyers.filter((o) => o.team === f.team && o.role === 'chaser'); const m = mates[(RNG() * mates.length) | 0]; B.passTo = m; Q.throwBall(f, Q.pos(m).addScaledVector(m.vel || HL.fly.vel, 0.4), 28, false); } } }
        else if (f.role === 'seeker') { if (Q.snitch) { const s = Q.snitch.p; Q.steer(f, s.x + Math.sin(Q.t * 1.3 + f.ph) * 7, s.y + 2, s.z + Math.cos(Q.t * 1.1 + f.ph) * 7, 22, dt, 1.4); } else { const t = Q.t * 0.16 + f.ph; Q.steer(f, C.x + Math.sin(t) * 24, Q.Y0 + 34 + Math.sin(t * 1.7) * 6, C.z + Math.cos(t * 0.8) * 60, 15, dt, 1.2); } }
        else { // Chasers
          if (Q.rsT > 0 && f.team === Q.rsTeam && B.holder !== f) Q.steer(f, C.x + (f.lane - 1) * 13, Q.Y0 + 11, C.z - att * (12 + f.lane * 6), 21, dt, 2.2);
          else if (B.holder === f) { f.holdT = (f.holdT || 0) + dt; const dG = Math.abs(gz - a.z), hp = Q.hoops[f.team === 0 ? 1 : 0][(f.lane + ((Q.t / 3) | 0)) % 3];
            let threat = null; for (const o of Q.flyers) if (o.team !== f.team && o.role === 'chaser' && Q.pos(o, _v4).distanceTo(Q.pos(f, _v5)) < 7) threat = o;
            if (dG < (f.team === 1 ? Q.D.rg : 30) + f.lane * 4 && f.holdT > 0.5) { Q.throwBall(f, V3(hp.x + rnd(-1.1, 1.1), hp.y + rnd(-0.9, 0.9), hp.z), f.team === 1 ? 29 + Q.D.sp * 3 : 31, true); }
            else if (threat && f.holdT > 0.8 && RNG() < dt * 1.6 * (f.team === 1 ? Q.D.tk : 1)) { const mates = Q.flyers.filter((o) => o.team === f.team && o.role === 'chaser' && o !== f); let m = mates[(RNG() * mates.length) | 0]; if (f.team === 0 && (me.a.z - a.z) * att > -6 && RNG() < 0.6) m = me; if (m) { B.passTo = m; Q.throwBall(f, Q.pos(m).addScaledVector(m.isPlayer ? HL.fly.vel : m.vel, 0.4), 28, false); } }
            else Q.steer(f, hp.x + Math.sin(Q.t * 0.9 + f.ph) * 6, hp.y + Math.sin(Q.t * 1.3 + f.ph) * 2.5 - 1, gz - att * 14, (f.team === 1 ? 21.5 : 21) * dk, dt, 2.2); }
          else if (!B.holder) { const mine = Q.flyers.filter((o) => o.team === f.team && o.role === 'chaser' && !o.isPlayer).sort((p, q) => Q.pos(p, _v4).distanceTo(B.p) - Q.pos(q, _v5).distanceTo(B.p)); if (mine[0] === f || (B.passTo === f)) Q.steer(f, B.p.x + B.v.x * 0.3, B.p.y + B.v.y * 0.3, B.p.z + B.v.z * 0.3, 24, dt, 3.2); else Q.steer(f, C.x + (f.lane - 1) * 12, Q.Y0 + 11, B.p.z - att * 12, 18, dt, 2); }
          else if (B.holder.team === f.team) { const c = B.holder.a; Q.steer(f, C.x + (f.lane - 1) * 15 + Math.sin(Q.t + f.ph) * 4, Q.Y0 + 10 + f.lane * 2, c.z + att * (10 + f.lane * 5), 21, dt, 2); }
          else { const c = B.holder, cs = Q.flyers.filter((o) => o.team === f.team && o.role === 'chaser' && !o.isPlayer).sort((p, q) => Q.pos(p, _v4).distanceTo(B.p) - Q.pos(q, _v5).distanceTo(B.p));
            if (cs[0] === f) { const cp = Q.pos(c, _v4), lead = c.isPlayer ? HL.fly.vel : c.vel; /* the rival nearest you closes fast, and on the higher difficulties throws in a burst of his own over the last few yards: carrying the Quaffle you need your boost, a pass or a roll */ if (c.isPlayer && Q.D.tk >= 1) { const dP = cp.distanceTo(Q.pos(f, _v5)); if (dP < 11 && dP > 4.5 && f.burstCd <= 0) { f.burst = 0.5; f.burstCd = 3.6 / Q.D.tk; } }
              Q.steer(f, cp.x + lead.x * 0.35, cp.y + lead.y * 0.35, cp.z + lead.z * 0.35, f.burst > 0 ? 36 : f.team === 1 ? Q.D.pd : 25, dt, f.burst > 0 ? 5 : 2.6);
              Q.tackleAI(f, c, dt); }
            else if (cs[1] === f && c.isPlayer) { /* the second defender gets goal-side of you, and tackles too if you fly into him */ Q.steer(f, lerp(c.a.x, C.x, 0.3), c.a.y + 0.9, c.a.z + Math.sign(own - c.a.z) * 9, Q.D.pd - 1.5, dt, 2.4); Q.tackleAI(f, c, dt); }
            else Q.steer(f, C.x + (f.lane - 1) * 11, Q.Y0 + 11, own + att * (16 + f.lane * 7), 19, dt, 2); } }
        Q.move(f, dt); }
      // ---- Bludgers
      for (const b of Q.bl) { if (b.park) { b.p.set(C.x, Q.Y0 - 40, C.z); b.m.position.copy(b.p); b.m.visible = false; b.tgt = null; continue; } b.tT -= dt; b.hitT = Math.max(0, b.hitT - dt); if (b.tT <= 0 || !b.tgt) { b.tT = rnd(5.5, 9); const pool = Q.flyers.filter((f) => f.role !== 'keeper'); b.tgt = RNG() < Q.D.bl && !Q.bl.some((o) => o !== b && o.tgt === me) ? me : (B.holder && RNG() < 0.5 ? B.holder : pool[(RNG() * pool.length) | 0]); if (b.tgt === me) { U.pop('BLUDGER INCOMING'); } }
        const tp = Q.pos(b.tgt, _v1), to = _v2.copy(tp).sub(b.p), d = to.length(); to.multiplyScalar(1 / (d || 1)); b.v.lerp(to.multiplyScalar((b.tgt === me ? 25 : 22) * (b.slow || 1)), 1 - Math.exp(-1.25 * dt)); b.p.addScaledVector(b.v, dt); b.p.y = clamp(b.p.y, Q.Y0 + 1, Q.CEIL + 6); b.m.position.copy(b.p); b.m.rotation.x += dt * 9; b.m.rotation.y += dt * 5;
        if (RNG() < dt * 30) FX.puff(b.p, 1, { size: 0.16, grow: 2, col: [0.1, 0.1, 0.12], a: 0.35, life: 0.5, spread: 0.1 });
        if (b.hitT <= 0) for (const f of Q.flyers) { if (f.stunT > 0) continue; const bd = Q.pos(f, _v3).distanceTo(b.p); if (f.isPlayer && HL.fly.spinT > 0) { if (bd < 3 && !b.dodged) { b.dodged = true; Q.stats.dodges++; U.pop('DODGED!'); MG.slowmo = 0.35; MG.slowmoT = 0; MG.slowmoDur = 0.3; b.tT = 0.2; } continue; } if (bd < 1.15) { if (f.isPlayer) Q.stats.hits++; b.dodged = false; Q.knock(f, _v4.copy(b.v).normalize().clone()); b.hitT = 1.5; b.v.multiplyScalar(-0.5); b.v.y += 6; b.tT = Math.min(b.tT, 1.5); b.tgt = null; break; } } }
      // ---- the Snitch
      const o2 = Q.opt; if (!Q.snitch && Q.t > Q.snT) { Q.snitch = { m: Q.mkSnitch(), p: V3(C.x, Q.Y0 + 26, C.z), v: V3(10, 2, 8), nT: 0, tgt: V3() }; Q.aiCatch = rnd(55, 95) * Q.D.seek * (o2.role === 'seeker' ? 1.5 : 1); U.toast('THE GOLDEN SNITCH', o2.role === 'seeker' ? 'It is loose over the pitch. 150 points — and the match — to whoever catches it.' : 'The Seekers are after it: ' + Q.SNP + ' points and the final whistle to the side that catches it. Every goal spurs your Seeker on — and a lunge knocks theirs off it.', 6.5); Q.excite = 1.5; }
      if (Q.snitch) { const S = Q.snitch, skr0 = me.role === 'seeker'; S.nT -= dt; const dm = Q.pos(me, _v1).distanceTo(S.p);
        if (S.nT <= 0 || dm < 9) { if (S.nT <= 0 || RNG() < dt * 5) { S.nT = rnd(0.5, 1.5); const away = _v2.copy(S.p).sub(Q.pos(me, _v1)).normalize(); S.tgt.set(C.x + rnd(-24, 24), Q.Y0 + rnd(5, 40), C.z + rnd(-66, 66)); if (dm < 16) S.tgt.addScaledVector(away, 16); S.tgt.x = clamp(S.tgt.x, C.x - 26, C.x + 26); S.tgt.z = clamp(S.tgt.z, C.z - 70, C.z + 70); S.tgt.y = clamp(S.tgt.y, Q.Y0 + 3, Q.Y0 + 42); } }
        S.bolt = Math.max(0, (S.bolt || 0) - dt); const to = _v2.copy(S.tgt).sub(S.p), d = to.length() || 1, sp = S.bolt > 0 ? 36 : dm < 12 ? (skr0 ? 21.5 : 23) : 15; S.v.lerp(to.multiplyScalar(sp / d), 1 - Math.exp(-3.2 * dt)); S.p.addScaledVector(S.v, dt); S.p.y += Math.sin(Q.t * 9) * dt * 2;
        S.m.position.copy(S.p); S.m.lookAt(_v3.copy(S.p).add(S.v)); const fl = Math.sin(Q.t * 70) * 0.9; S.m.userData.w[0].rotation.z = fl; S.m.userData.w[1].rotation.z = -fl;
        if (RNG() < dt * 40) FX.puff(S.p, 1, { add: true, size: 0.05, grow: 0.3, col: [3.2, 2.4, 0.6], a: 0.9, life: 0.7, spread: 0.08, rise: 0.01 });
        const skr = me.role === 'seeker'; if (skr) { Q.reach = clamp(Q.reach + (dm < 3.4 ? dt * 0.9 : dm < 6 ? dt * 0.25 : -dt * 0.5), 0, 1); }
        if (skr && Q.reach >= 1 && (Q.grabs || 0) < 2 && me.stunT <= 0) { /* twice it slips your fingers and bolts; the third time your hand closes (a Seeker's match used to be over in twenty seconds) */ Q.grabs = (Q.grabs || 0) + 1; Q.reach = 0; S.nT = 0; S.bolt = 1.7; U.pop(Q.grabs === 1 ? 'IT SLIPS YOUR FINGERS!' : 'SO CLOSE — ONCE MORE!'); R.kick(0.3); Q.excite = Math.max(Q.excite, 1.4); FX.spark(S.p, null, 24, 7, [4, 3, 1], 0.5); }
        else if (skr && Q.reach >= 1 && me.stunT <= 0) { /* (only a Seeker's hand closes on it: flying Chaser you used to end the match by blundering through it) */ Q.score[0] += Q.SNP; Q.stats.snitch = 1; FX.spark(S.p, null, 60, 9, [4, 3, 1], 1); FX.flashLight(S.p, [1, 0.8, 0.3], 60, 30, 0.6); R.kick(0.5); PLAYER.a.play('catchQ', { fade: 0.05 }); Q.end('you caught the Snitch!'); }
        else if (skr) { const rs = Q.flyers.find((f) => f.team === 1 && f.role === 'seeker'), near = rs && Q.pos(rs, _v4).distanceTo(S.p) < 16; Q.aiCatch -= dt * (near ? 1 : 0.25); if (Q.aiCatch <= 0) { Q.score[1] += Q.SNP; Q.end(HL.HOUSES[Q.teams[1]].name + '’s Seeker caught the Snitch'); } }
        else { /* as a Chaser the Snitch is a race you can see and tip: two Seekers closing on it (the bars under the score). Theirs is the quicker unless you knock him off it; it used to be a hidden timer that ended the match for the rivals six times in ten */
          const rs = Q.flyers.find((f) => f.team === 1 && f.role === 'seeker'), rc = Q.race || (Q.race = [0, 0]); rc[0] = Math.min(1, rc[0] + dt / (Q.T * 0.37) * (1 + 0.6 * Math.sin(Q.t * 0.37 + 1.3))); if (!(rs && rs.stunT > 0)) rc[1] = Math.min(1, rc[1] + dt / (Q.T * 0.37 * Math.pow(Q.D.seek, 0.8)) * (1 + 0.6 * Math.sin(Q.t * 0.29 + 4.1)));
          const w = rc[1] >= 1 ? 1 : rc[0] >= 1 ? 0 : -1; if (w >= 0) { Q.score[w] += Q.SNP; Q.end(HL.HOUSES[Q.teams[w]].name + '’s Seeker caught the Snitch'); } } }
      if (Q.t > Q.T && Q.phase === 'play') Q.end('full time');
      // ---- stay over the pitch
      const pa = PLAYER.a; if (!Q.inField(pa.x, pa.z, 16) || pa.y > Q.CEIL + 12) { Q.outT += dt; if (Q.outT > 0.5) U.setText('qs', E.Qs, 'Return to the pitch!'); HL.fly.vel.x += (C.x - pa.x) * dt * 0.8; HL.fly.vel.z += (C.z - pa.z) * dt * 0.8; if (!Q.inField(pa.x, pa.z, 40)) { pa.x = lerp(pa.x, C.x, dt * 2); pa.z = lerp(pa.z, C.z, dt * 2); } } else Q.outT = 0;
    }
    if (Q.phase === 'over') { for (const f of Q.flyers) if (!f.isPlayer) { Q.steer(f, f.a.x, Q.Y0 + 14, f.a.z, 5, dt, 1); Q.move(f, dt); } }
    else if (Q.phase === 'count' || Q.phase === 'intro') for (const f of Q.flyers) if (!f.isPlayer) { f.face = f.team ? PI : 0; Q.steer(f, f.a.x, f.a.y + 0.9, f.a.z, 2, dt, 2); Q.move(f, dt); }
    // scoreboard
    const tl = Math.max(0, Q.T - Q.t); U.setText('qa', E.Qsa, Q.score[0]); U.setText('qb', E.Qsb, Q.score[1]); U.setText('qt', E.Qt, Math.floor(tl / 60) + ':' + String(Math.floor(tl % 60)).padStart(2, '0'));
    if (Q.outT <= 0.5) { const s = Q.status(); if (U.last.qs !== s) { U.last.qs = s; E.Qs.innerHTML = s; } }
  };
})();
