/* ==== p78b_hl_lands.js ==== */
/* HOGWARTS — the lands about the castle: Hogsmeade (a crooked high street of stone-and-timber shops under steep slate
   roofs, smoking chimneys, lamps, the Three Broomsticks), the gamekeeper's hut and its pumpkin patch, the boathouse on
   the Black Lake, the Owlery on its rock, a forest of dark firs — and Floo flames to travel between them. */
HL.VIL = { x: -335, z: -450, y: 60 };
HL.foot(HL.VIL.x - 75, HL.VIL.z - 6.9, HL.VIL.x + 75, HL.VIL.z + 6.9);                         // the high street, house front to house front
HL.foot(HL.VIL.x - 13, HL.VIL.z - 28, HL.VIL.x + 13, HL.VIL.z - 6);                              // the square
HL.HDRECT = { x0: HL.VIL.x - 6.5, x1: HL.VIL.x + 4.5, z0: HL.VIL.z - 37.4, z1: HL.VIL.z - 28.4 }; HL.foot(HL.HDRECT.x0 - 0.5, HL.HDRECT.z0 - 0.5, HL.HDRECT.x1 + 0.5, HL.HDRECT.z1 + 1.6);   // Honeydukes' plot, at the back of the square
HL.TBRECT = { x0: HL.VIL.x - 12.5, x1: HL.VIL.x + 3, z0: HL.VIL.z + 6.6, z1: HL.VIL.z + 17.4 }; HL.foot(HL.TBRECT.x0 - 0.5, HL.TBRECT.z0 - 1, HL.TBRECT.x1 + 0.5, HL.TBRECT.z1 + 0.5);   // the Three Broomsticks' plot
HL.signTex = function (text, bg, fg) { const c = document.createElement('canvas'); c.width = 256; c.height = 96; const x = c.getContext('2d'); x.fillStyle = bg; x.fillRect(0, 0, 256, 96); x.strokeStyle = fg; x.lineWidth = 5; x.strokeRect(6, 6, 244, 84);
  x.fillStyle = fg; x.textAlign = 'center'; x.textBaseline = 'middle'; let fs = 40; x.font = `${fs}px HLA, Georgia, serif`; while (x.measureText(text).width > 220 && fs > 14) { fs -= 2; x.font = `${fs}px HLA, Georgia, serif`; } x.fillText(text, 128, 50);
  const t = new THREE.CanvasTexture(c); t.colorSpace = THREE.SRGBColorSpace; t.anisotropy = 4; return t; };
/* a village house: a rubble ground floor, a jettied timber-framed storey or two, a steep roof, a chimney */
HL.cottage = function (L, x, z, th, w, d, o) {
  o = o || {}; const M = HL.M(), rs = mulberry((x * 31 + z * 17) | 0), y = HL.gy(x, z), P = CAS.rot(x, z, th), h1 = o.h1 || 3.1, st = o.storeys || 1, h2 = 2.7 * st, jt = 0.34, top = y + h1 + h2, c = Math.cos(th), s = Math.sin(th);
  KIT.obox(x, y - 2, z, w / 2, y + h1, d / 2, th, M.village, { col: true });
  KIT.obox(x, y + h1, z, w / 2 + jt, top, d / 2 + jt, th, o.stone ? M.village : M.plaster, { col: false }); KIT.obox(x, y + h1 - 0.16, z, w / 2 + jt + 0.06, y + h1 + 0.12, d / 2 + jt + 0.06, th, M.woodD, { col: false });
  if (!o.stone) { const post = (lx, lz, hx, hz, y0, y1) => { const p = P(lx, lz); KIT.obox(p[0], y0, p[1], hx, y1, hz, th, M.woodD, { col: false }); };
    for (const sd of [-1, 1]) { const n = Math.max(2, Math.round(w / 1.5)); for (let i = 0; i <= n; i++) post(-w / 2 - jt + i * (w + jt * 2) / n, sd * (d / 2 + jt + 0.03), 0.09, 0.04, y + h1, top); for (let k = 1; k <= st; k++) post(0, sd * (d / 2 + jt + 0.03), w / 2 + jt, 0.04, y + h1 + 2.7 * k - 0.2, y + h1 + 2.7 * k);
      const m = Math.max(2, Math.round(d / 1.6)); for (let i = 0; i <= m; i++) post(sd * (w / 2 + jt + 0.03), -d / 2 - jt + i * (d + jt * 2) / m, 0.04, 0.09, y + h1, top);
      for (let i = 0; i < n; i += 2) { const a = P(-w / 2 - jt + i * (w + jt * 2) / n, sd * (d / 2 + jt + 0.05)), b = P(-w / 2 - jt + (i + 1) * (w + jt * 2) / n, sd * (d / 2 + jt + 0.05)); KIT.beam([a[0], y + h1 + 0.1, a[1]], [b[0], y + h1 + 2.5, b[1]], 0.13, M.woodD); } } }
  // roof: a steep prism, its ridge along the street, sagging a little with age
  { const rise = (o.rise || 0.95) * d * 0.62, g = new THREE.CylinderGeometry(1, 1, 1, 3, 1); g.rotateZ(HALF); g.rotateX(-HALF); g.scale(w + jt * 2 + 0.9, rise / 1.5, (d + jt * 2 + 1.0) / 1.732); g.rotateZ((rs() - 0.5) * 0.05); g.rotateY(th); KIT.geo(g, o.roofMat || M.roofV, new THREE.Matrix4().makeTranslation(x, top + rise / 3 - 0.08, z), { uvs: Math.max(2, w / 2.4), uvs2: 2 });
    const cp = P(w * 0.28 * (rs() < 0.5 ? 1 : -1), -d * 0.12); KIT.obox(cp[0], top - 0.5, cp[1], 0.42, top + rise + 0.9, 0.42, th, M.village, { col: false }); for (const q of [-0.18, 0.18]) KIT.cyl(cp[0] + c * q, top + rise + 0.9, cp[1] - s * q, 0.13, 0.42, M.roofV, { seg: 8, col: false });
    if (REALM.smoke && rs() < 0.75) REALM.smoke(L, cp[0], top + rise + 1.4, cp[1], {});
    PHY.obox(x, z, w / 2 + jt, d / 2 + jt, top, top + rise * 0.6, th, { noFloor: true }); }
  // door, shop window, upper lights
  const fz = d / 2, lit = (k) => (rs() < (k || 0.7) ? M.glass : rs() < 0.5 ? M.glassDim : M.glassD);
  { const p = P(o.door !== undefined ? o.door : -w * 0.22, fz + 0.03); KIT.obox(p[0], y, p[1], 0.55, y + 2.1, 0.06, th, M.woodD, { col: false }); KIT.obox(p[0], y + 2.1, p[1], 0.68, y + 2.3, 0.1, th, M.trim, { col: false }); const st2 = P(o.door !== undefined ? o.door : -w * 0.22, fz + 0.5); KIT.obox(st2[0], y - 0.3, st2[1], 0.8, y + 0.12, 0.45, th, M.village, { col: false }); HL.lastDoor = [p[0] + s * 1.2, y, p[1] + c * 1.2]; }
  if (o.shop) { /* a lit shop window throws its light across the street */ { const lp = P(w * 0.16, fz + 1.5); HL.sl(lp[0], y + 1.7, lp[1], 0xffb060, 7.5, 10); }
    const p = P(w * 0.16, fz + 0.04); KIT.obox(p[0], y + 0.8, p[1], w * 0.26, y + 2.3, 0.05, th, M.glass, { col: false }); for (let i = -1; i <= 1; i++) { const q = P(w * 0.16 + i * w * 0.17, fz + 0.09); KIT.obox(q[0], y + 0.8, q[1], 0.04, y + 2.3, 0.03, th, M.woodD, { col: false }); } const q = P(w * 0.16, fz + 0.09); KIT.obox(q[0], y + 1.5, q[1], w * 0.26, y + 1.57, 0.03, th, M.woodD, { col: false }); KIT.obox(q[0], y + 0.62, q[1], w * 0.28, y + 0.8, 0.12, th, M.woodD, { col: false }); }
  else { const p = P(w * 0.2, fz + 0.03); HL.win(p[0], y + 1.0, p[1], th, 0.9, 1.4, lit(0.6), { mat: M.woodD }); }
  for (let k = 0; k < st; k++) { const n = Math.max(2, Math.round(w / 2.6)); for (let i = 0; i < n; i++) { const lx = -w / 2 + (i + 0.5) * w / n; for (const sd of [1, -1]) { if (sd < 0 && rs() < 0.4) continue; const p = P(lx, sd * (fz + jt + 0.05)); KIT.obox(p[0], y + h1 + 0.9 + k * 2.7, p[1], 0.42, y + h1 + 2.0 + k * 2.7, 0.04, th, lit(0.65), { col: false }); const q = P(lx, sd * (fz + jt + 0.1)); KIT.obox(q[0], y + h1 + 0.9 + k * 2.7, q[1], 0.03, y + h1 + 2.0 + k * 2.7, 0.03, th, M.woodD, { col: false }); KIT.obox(q[0], y + h1 + 1.42 + k * 2.7, q[1], 0.42, y + h1 + 1.48 + k * 2.7, 0.03, th, M.woodD, { col: false }); } } }
  if (o.name) { const p = P(-w * 0.22 + 1.3, fz + jt + 0.9), q = P(-w * 0.22 + 1.3, fz + jt), t = HL.signTex(o.name, o.bg || '#2a1c12', o.fg || '#e8c878'), sm = new THREE.MeshStandardMaterial({ map: t, roughness: 0.8, side: THREE.DoubleSide }); sm.userData.tscale = 1;
    KIT.beam([q[0], y + h1 + 1.2, q[1]], [p[0] + s * 0.5, y + h1 + 1.2, p[1] + c * 0.5], 0.08, M.iron); const m4 = new THREE.Matrix4().makeRotationY(th + HALF); m4.setPosition(p[0], y + h1 + 0.62, p[1]); KIT.geo(new THREE.PlaneGeometry(1.5, 0.56), sm, m4); KIT.geo(new THREE.BoxGeometry(1.56, 0.62, 0.05), M.woodD, m4, { worldUV: true }); }
  return { y, top };
};
/* firs: one merged, vertex-painted tree per kind, instanced by cell */
HL.firGeo = function (seed, lo) { const rs = mulberry(seed), list = [], tiers = lo ? 4 : 9 + (seed % 3); list.push([new THREE.CylinderGeometry(0.01, 0.034, 1, 6).translate(0, 0.5, 0), [0.075, 0.052, 0.036]]);
  /* each whorl of branches is a skirt with a star-shaped hem: every other point of its rim is drawn in and lifted, the tips droop; whorls overlap and turn against one another */
  for (let i = 0; i < tiers; i++) { const f = i / (tiers - 1), y0 = 0.15 + f * 0.72, r = lerp(0.215, 0.03, Math.pow(f, 0.85)) * (0.85 + rs() * 0.3), h = lerp(0.26, 0.14, f), seg = lo ? 6 : 12, g = new THREE.ConeGeometry(r, h, seg, lo ? 1 : 2, true), p = g.attributes.position;
    for (let k = 0; k < p.count; k++) { const x = p.getX(k), yy = p.getY(k), z = p.getZ(k), rad = Math.hypot(x, z); if (rad < 1e-5) continue; const ai = Math.round(Math.atan2(z, x) / TAU * seg + seg) % seg, e = yy < -h * 0.2 ? 1 : yy < h * 0.2 ? 0.5 : 0, inn = (ai % 2) ? 1 : (lo ? 0.9 : 0.5), j = inn * (1 + (rs() - 0.5) * 0.3 * e); p.setXYZ(k, x * lerp(1, j, e), yy - e * (lo ? 0.12 : (ai % 2 ? 0.34 + rs() * 0.2 : -0.1)) * h, z * lerp(1, j, e)); }
    g.translate(0, y0 + h / 2, 0); g.rotateY(rs() * 3 + i * 0.9); g.computeVertexNormals(); const sh = 0.42 + 0.58 * f, bl = 0.8 + rs() * 0.4; list.push([g, [0.016 * sh * bl, (0.046 * sh + rs() * 0.01) * bl, 0.03 * sh * bl]]); }
  return HL.mergeCol(list); };
/* foliage close to the lens dithers away (the third-person eye inside a canopy saw black back-faces filling the frame) */
HL.NEARFADE = '#include <clipping_planes_fragment>\n{ float cdN = length(vViewPosition), faN = smoothstep(1.3, 3.4, cdN); if (faN < 0.999 && faN < fract(52.9829189 * fract(dot(gl_FragCoord.xy, vec2(0.06711056, 0.00583715))))) discard; }';
HL.conifers = function (L, list) {
  if (!list.length) return; const U = { uT: { value: 0 } }, mat = new THREE.MeshLambertMaterial({ vertexColors: true, side: THREE.DoubleSide });
  mat.onBeforeCompile = (sh) => { sh.uniforms.uT = U.uT; sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nuniform float uT; varying vec3 vFo;').replace('#include <begin_vertex>', '#include <begin_vertex>\n{ vFo = position; vec4 ip = instanceMatrix * vec4(position, 1.0); transformed.x += sin(uT * 1.1 + ip.x * 0.2 + ip.z * 0.13) * 0.012 * position.y; }');
    /* needles: the flat faces are broken into streaks running out along the branch, darker toward the trunk and under each whorl, a paler tip */
    sh.fragmentShader = sh.fragmentShader.replace('#include <clipping_planes_fragment>', HL.NEARFADE).replace('#include <common>', '#include <common>\nvarying vec3 vFo; float fH(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }').replace('#include <color_fragment>', '#include <color_fragment>\n{ float rad = length(vFo.xz), an = atan(vFo.z, vFo.x); float st = fH(vec2(floor(an * 38.0), floor(vFo.y * 26.0))); float tip = smoothstep(0.02, 0.16, rad); diffuseColor.rgb *= (0.62 + 0.62 * st) * mix(0.55, 1.12, tip) * (gl_FrontFacing ? 1.0 : 0.72); }'); }; mat.customProgramCacheKey = () => 'hlfir2';
  const geos = [HL.firGeo(11), HL.firGeo(23), HL.firGeo(37)], lows = [HL.firGeo(11, 1), HL.firGeo(23, 1), HL.firGeo(37, 1)], ims = [], cell = {}, m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), col = new THREE.Color();
  list.forEach((t, i) => { const k = (i % 3) + '|' + Math.floor(t[0] / 220) + '|' + Math.floor(t[1] / 220); (cell[k] = cell[k] || []).push(t); });
  for (const k in cell) { const arr = cell[k], im = new THREE.InstancedMesh(geos[+k[0]], mat, arr.length); arr.forEach((t, i) => { const y = HL.gy(t[0], t[1]) - 0.4; q.setFromAxisAngle(YUP, t[3] || 0); m4.compose(V3(t[0], y, t[1]), q, V3(t[2], t[2], t[2])); im.setMatrixAt(i, m4); im.setColorAt(i, col.setRGB(0.8 + (i % 5) * 0.09, 0.85 + (i % 7) * 0.05, 0.8 + (i % 3) * 0.1)); if (Math.hypot(t[0] - 8, t[1] - 14) < 520) PHY.cyl(t[0], t[1], 0.02 * t[2], y - 1, y + t[2] * 0.4); });
    im.instanceMatrix.needsUpdate = true; im.instanceColor.needsUpdate = true; im.computeBoundingSphere(); im.castShadow = false; im.receiveShadow = false; LEVEL.add(im); ims.push([im, +k[0]]); }
  L.updates.push((dt, t) => { U.uT.value = t; if ((MG.frame & 15) === 0) { const c = R.camera.position; for (const [im, k] of ims) { const b = im.boundingSphere, far = Math.hypot(c.x - b.center.x, c.z - b.center.z) - b.radius > 240, g = far ? lows[k] : geos[k]; if (im.geometry !== g) im.geometry = g; } } });
};
HL.FLOO = [];
HL.floo = function (L, name, x, z, yaw, yy) { const M = HL.M(), y = yy !== undefined ? yy : HL.dropY(x, z, 30); KIT.cyl(x, y, z, 0.7, 0.5, M.trim, { seg: 10 }); KIT.cyl(x, y + 0.5, z, 0.5, 0.25, M.iron, { seg: 10, col: false, r1: 0.62 }); WORLD.fire(L, x, y + 0.7, z, 0.9, { col: 0x40ff80, range: 9, i: 2.4 });
  const me = HL.sprite([0.25, 1.0, 0.45], 2.2, 2.4); me.position.set(x, y + 1.4, z); LEVEL.add(me); const f = { name, p: [x + Math.sin(yaw || 0) * 2.2, y, z + Math.cos(yaw || 0) * 2.2, (yaw || 0) + PI] }; HL.FLOO.push(f);
  HL.interact([x, y + 1, z], 3.2, 'Travel by Floo flame', () => HL.flooMenu(f)); return f; };
HL.flooMenu = function (from) { const U = HL.ui; MG.state = 'house'; if (document.exitPointerLock) document.exitPointerLock(); const close = () => { U.screen(''); MG.state = 'play'; MG.onKey = null; IN.buf = {}; HL.noPauseT = MG.rt + 0.25; };
  const S = U.screen(`<div class="hlPause"><h3>FLOO FLAMES</h3><p style="font-style:italic;color:#cfc6b0;margin:-8px 0 14px">Speak clearly.</p>${HL.FLOO.map((f, i) => f === from ? '' : `<div class="hlBtn" data-i="${i}">${f.name.toUpperCase()}</div>`).join('')}<div class="hlBtn" data-i="-1" style="margin-top:14px">STAY</div></div>`);
  S.querySelectorAll('.hlBtn').forEach((b) => b.onclick = () => { const i = +b.dataset.i; if (i < 0) return close(); const f = HL.FLOO[i]; U.fade(1); close(); setTimeout(() => { const a = PLAYER.a; a.x = f.p[0]; a.y = f.p[1] + 0.1; a.z = f.p[2]; a.vx = a.vy = a.vz = 0; a.yaw = f.p[3]; CAM.yaw = f.p[3]; CAM.snap = true; if (a.inst.cloth && a.inst.cloth.reset) a.inst.cloth.reset(); FX.puff(V3(a.x, a.y + 1, a.z), 16, { add: true, size: 0.4, grow: 2, col: [0.4, 2.2, 0.8], a: 0.7, life: 0.8, spread: 2 }); U.fade(0); U.spellName(f.name); }, 500); });
  MG.onKey = (c) => { if (c === 'Escape') close(); }; };
HL.BUILD.push(async function lands(L, G) {
  const M = HL.M(), V = HL.VIL, rs = MG.rs('hogsmeade'), Y = HL.Y0;
  // ============================================================ HOGSMEADE
  { const y0 = V.y;
    const shops = [['ZONKO’S', 8, 8, 2, { bg: '#6a3a10', shop: true }], ['OLLIVANDERS', 7, 8, 2, { bg: '#1c1c22', shop: true }], ['SCRIVENSHAFT’S', 8, 7, 1, { bg: '#1c2c3a', shop: true }], ['GLADRAGS', 9, 8, 1, { bg: '#2c3a1c', shop: true }], ['THE HOG’S HEAD', 11, 9, 1, { bg: '#22201c', fg: '#c8c0b0', stone: true }], ['DERVISH & BANGES', 8, 8, 2, { bg: '#3a1c1c', shop: true }], ['SPINTWITCHES', 8, 7, 1, { bg: '#1c3a3a', shop: true }], ['TOMES & SCROLLS', 8, 8, 2, { bg: '#2a1c3a', shop: true }], ['POST OFFICE', 9, 8, 1, { bg: '#3a3012', shop: true }], ['MADAM PUDDIFOOT’S', 8, 7, 1, { bg: '#6a2c4a', fg: '#ffe0ee', shop: true }]];
    let xn = V.x - 66, xs = V.x - 62, k = 0; HL.VILDOORS = {};
    HL.TBLOT = null; while (xn < V.x + 64 || xs < V.x + 64) { /* the Three Broomsticks keeps the best plot in the village: the north side, facing the square (it is built in p78n — a pub you can walk into) */ if (xn <= xs && !HL.TBLOT && xn >= HL.TBRECT.x0 - 9) { HL.TBLOT = HL.TBRECT; xn = HL.TBRECT.x1 + 1.6; continue; }
      const north = xn <= xs, sp = shops[k % shops.length], w = sp[1] * (0.9 + rs() * 0.2), d = sp[2], named = k < shops.length; const cx = (north ? xn : xs) + w / 2, off = 6.4 + d / 2 + rs() * 1.2, z = V.z + (north ? off : -off), th = (north ? PI : 0) + (rs() - 0.5) * 0.16;
      if (Math.abs(cx - V.x) < 9 && !north) { xs += 16; continue; }                                         // the little square opens on the south side
      HL.cottage(L, cx, z, th, w, d, Object.assign({ storeys: sp[3], name: named ? sp[0] : null, rise: 0.85 + rs() * 0.45, roofMat: rs() < 0.5 ? M.roofV : M.roof }, named ? sp[4] : { shop: rs() < 0.4 })); if (named) HL.VILDOORS[sp[0]] = HL.lastDoor.slice();
      HL.foot(cx - w / 2 - 1, z - d / 2 - 1, cx + w / 2 + 1, z + d / 2 + 1); if (north) xn += w + 1.2 + rs() * 2.4; else xs += w + 1.2 + rs() * 2.4; k++; }
    // a second, straggling row behind, and cottages up the lane
    for (let i = 0; i < 9; i++) { const x = V.x - 60 + i * 14 + rs() * 5, z = V.z + (i % 2 ? 30 : -31) + rs() * 6; if (x > HL.HDRECT.x0 - 8 && x < HL.HDRECT.x1 + 8 && z < V.z - 20) continue;   // (Honeydukes stands here)
      HL.cottage(L, x, z, (i % 2 ? PI : 0) + (rs() - 0.5) * 0.5, 7 + rs() * 3, 6.5 + rs() * 2, { storeys: 1, rise: 0.9 + rs() * 0.4, shop: false }); HL.foot(x - 6, z - 5, x + 6, z + 5); }
    // the square: a well, a market cross, stalls, lamps down the street
    KIT.cyl(V.x, HL.h(V.x, V.z - 14) - 0.6, V.z - 14, 1.5, 1.5, M.village, { seg: 12 }); for (const s of [-1, 1]) KIT.box(V.x + s * 1.3 - 0.1, HL.h(V.x, V.z - 14), V.z - 14.1, V.x + s * 1.3 + 0.1, HL.h(V.x, V.z - 14) + 3, V.z - 13.9, M.woodD, { col: false }); HL.cone(V.x, V.z - 14, 2.1, HL.h(V.x, V.z - 14) + 3, 1.8, { seg: 8, mat: M.roofV });
    for (let x = V.x - 60; x <= V.x + 62; x += 20) for (const s of [-1, 1]) { const lx = x + (s > 0 ? 6 : 0), lz = V.z + s * 4.6, gy = HL.h(lx, lz); KIT.cyl(lx, gy - 0.3, lz, 0.1, 3.5, M.iron, { seg: 6 }); KIT.box(lx - 0.5, gy + 3.1, lz - 0.04, lx + 0.04, gy + 3.18, lz + 0.04, M.iron, { col: false }); HL.lantern(L, lx - 0.4, gy + 2.8, lz, { i: 34, range: 18, glow: 6 }); }
    for (const [dx, dz, c1] of [[-8, -17, 0x7a2018], [8, -18, 0x1c4a6a], [3, -24, 0x6a5a18]]) { const x = V.x + dx, z = V.z + dz, gy = HL.h(x, z), cm = new THREE.MeshStandardMaterial({ color: c1, roughness: 0.9, side: THREE.DoubleSide }); cm.userData.tscale = 1; KIT.box(x - 1.4, gy + 0.8, z - 0.7, x + 1.4, gy + 0.9, z + 0.7, M.wood, { col: false }); PHY.box(x - 1.4, gy, z - 0.7, x + 1.4, gy + 0.9, z + 0.7); for (const [a, b] of [[-1.3, -0.6], [1.3, -0.6], [1.3, 0.6], [-1.3, 0.6]]) KIT.box(x + a - 0.05, gy - 0.3, z + b - 0.05, x + a + 0.05, gy + 2.2, z + b + 0.05, M.woodD, { col: false });
      HL.quad(cm, [x - 1.6, gy + 2.0, z - 0.9], [x + 1.6, gy + 2.0, z - 0.9], [x + 1.6, gy + 2.5, z + 0.9], [x - 1.6, gy + 2.5, z + 0.9], [0, 1, 0]); for (let i = 0; i < 5; i++) KIT.geo(new THREE.SphereGeometry(0.13, 8, 6), i % 2 ? M.gold : cm, new THREE.Matrix4().makeTranslation(x - 1 + i * 0.5, gy + 1.02, z + (i % 2) * 0.3 - 0.15)); }
    for (const [dx, dz, kd] of [[-12, 5.4, 'barrel1'], [-11, 5.8, 'barrel2'], [22, -5.6, 'crate'], [40, 5.6, 'barrel1'], [-36, -5.4, 'crate'], [-37, -5.9, 'barrel2']]) { const me = AST.mesh(kd); me.position.set(V.x + dx, HL.h(V.x + dx, V.z + dz), V.z + dz); me.rotation.y = dx; LEVEL.add(me); }
    HL.floo(L, 'Hogsmeade', V.x + 4, V.z - 21, 0);
    /* (the Butterbeer is ordered at the bar inside the Three Broomsticks: p78n) */
  }
  // ============================================================ THE GAMEKEEPER'S HUT
  { const H = HL.HUT, y = HL.h(H.x, H.z); HL.foot(H.x - 7, H.z - 7, H.x + 7, H.z + 7);
    KIT.cyl(H.x, y - 1.5, H.z, 4.8, 5.2, M.village, { seg: 16, uvs: 10 }); PHY.cyl(H.x, H.z, 4.8, y - 1, y + 8); HL.cone(H.x, H.z, 6.3, y + 3.7, 5.6, { seg: 16, mat: M.roofV });
    KIT.cyl(H.x + 5.6, y - 1.5, H.z + 1.6, 2.7, 4.3, M.village, { seg: 12, uvs: 6 }); PHY.cyl(H.x + 5.6, H.z + 1.6, 2.7, y - 1, y + 6); HL.cone(H.x + 5.6, H.z + 1.6, 3.6, y + 2.8, 3.8, { seg: 12, mat: M.roofV });
    KIT.box(H.x - 2.2, y, H.z - 3.4, H.x - 1.2, y + 8.4, H.z - 2.4, M.village, { col: false }); if (REALM.smoke) REALM.smoke(L, H.x - 1.7, y + 8.8, H.z - 2.9, {});
    KIT.obox(H.x, y, H.z - 4.82, 0.7, y + 2.3, 0.08, 0, M.woodD, { col: false }); HL.win(H.x + 2.6, y + 1.0, H.z - 4.05, PI - 0.56, 0.9, 1.3, M.glass, { mat: M.woodD }); HL.win(H.x - 2.6, y + 1.0, H.z - 4.05, PI + 0.56, 0.9, 1.3, M.glass, { mat: M.woodD }); HL.lantern(L, H.x + 1.3, y + 2.4, H.z - 5.1, { i: 12, range: 11 });
    const pm = new THREE.MeshStandardMaterial({ color: 0xd8701a, roughness: 0.6 }), sm = new THREE.MeshStandardMaterial({ color: 0x3a5a1c, roughness: 0.9 }); pm.userData.tscale = sm.userData.tscale = 1; const r2 = MG.rs('pumpkins');
    for (let i = 0; i < 18; i++) { const px = H.x - 13 + r2() * 9, pz = H.z - 9 + r2() * 12, s = 0.3 + r2() * r2() * 0.9, g = new THREE.SphereGeometry(s, 12, 8); g.scale(1, 0.72, 1); const p = g.attributes.position; for (let q = 0; q < p.count; q++) { const a = Math.atan2(p.getZ(q), p.getX(q)), k2 = 1 - 0.07 * Math.abs(Math.sin(a * 5)); p.setX(q, p.getX(q) * k2); p.setZ(q, p.getZ(q) * k2); } g.computeVertexNormals();
      const gy = HL.h(px, pz); KIT.geo(g, pm, new THREE.Matrix4().makeTranslation(px, gy + s * 0.6, pz)); KIT.cyl(px, gy + s * 1.25, pz, 0.03, s * 0.3, sm, { seg: 5, col: false }); if (s > 0.7) PHY.cyl(px, pz, s * 0.8, gy, gy + s); }
    for (let i = 0; i < 14; i++) { const a0 = 1.9 + i * 0.2, a1 = a0 + 0.2, r = 15, p0 = [H.x + Math.cos(a0) * r, H.z + Math.sin(a0) * r], p1 = [H.x + Math.cos(a1) * r, H.z + Math.sin(a1) * r]; const g0 = HL.h(p0[0], p0[1]), g1 = HL.h(p1[0], p1[1]); KIT.box(p0[0] - 0.07, g0 - 0.3, p0[1] - 0.07, p0[0] + 0.07, g0 + 1.1, p0[1] + 0.07, M.woodD, { col: false }); KIT.beam([p0[0], g0 + 0.9, p0[1]], [p1[0], g1 + 0.9, p1[1]], 0.07, M.woodD); KIT.beam([p0[0], g0 + 0.5, p0[1]], [p1[0], g1 + 0.5, p1[1]], 0.07, M.woodD); }
    for (let i = 0; i < 9; i++) KIT.rbox(H.x + 8.6 + (i % 3) * 0.34, y + 0.16 + Math.floor(i / 3) * 0.3, H.z - 2.4, 0.15, 0.15, 0.6, 0, 0.1 * i, 0, M.woodD, 0.03);
    HL.interact([H.x, y + 1, H.z - 5.6], 3, 'Knock on the gamekeeper’s door', () => { (HL.ui.say || HL.ui.toast)('The Gamekeeper', 'Yeh’ll want ter stay out o’ the forest, mind. Poachers about — an’ worse. Mind the pumpkins.', 6); HL.quest.flags.hut = 1; });
    HL.floo(L, 'The gamekeeper’s hut', H.x + 10, H.z - 8, -1); }
  // ============================================================ THE BOATHOUSE on the lake, the Owlery on its rock
  { let bx = 130; const bz = 46; while (bx < 260 && HL.h(bx, bz) > 0.6) bx += 2; const y = 0.9; HL.BOAT = [bx - 6, bz];
    for (const [dx, dz] of [[-5, -5], [5, -5], [5, 5], [-5, 5], [9, -5], [9, 5]]) KIT.cyl(bx + dx, -12, bz + dz, 0.3, 13.6, M.woodD, { seg: 8, col: false });
    KIT.box(bx - 14, y, bz - 6, bx + 16, y + 0.3, bz + 6, M.wood, { col: true }); KIT.box(bx + 16, y, bz - 1.4, bx + 34, y + 0.25, bz + 1.4, M.wood, { col: true }); for (let x = bx + 18; x < bx + 34; x += 4) for (const s of [-1, 1]) KIT.cyl(x, -10, bz + s * 1.3, 0.16, 11.6, M.woodD, { seg: 6, col: false });
    HL.shell(bx - 8, bz - 5.4, bx + 8, bz + 5.4, y + 0.3, 5.2, { t: 0.7, roof: 'x', rise: 4.4, floor: M.wood, plinth: false, mat: M.village, inside: M.wood, ops: { X: [{ p: bz, w: 5, s: 0, hd: 4 }], x: [{ p: bz, w: 2, s: 0, hd: 3 }], z: [{ p: bx - 3, w: 1.6, s: 1.2, hd: 3.4, bars: 1 }, { p: bx + 3, w: 1.6, s: 1.2, hd: 3.4, bars: 1 }], Z: [{ p: bx - 3, w: 1.6, s: 1.2, hd: 3.4, bars: 1 }, { p: bx + 3, w: 1.6, s: 1.2, hd: 3.4, bars: 1 }] } });
    HL.lantern(L, bx + 9, y + 3.6, bz, { i: 16, range: 14 }); HL.lantern(L, bx + 33, y + 2.3, bz, { i: 12, range: 12 }); KIT.cyl(bx + 33, y, bz + 0.5, 0.08, 2, M.iron, { seg: 6, col: false });
    HL.boats = []; const hull = new THREE.SphereGeometry(1, 14, 8, 0, TAU, HALF, HALF); hull.scale(0.75, 0.55, 2.2); const bm = new THREE.MeshStandardMaterial({ color: 0x4a3222, roughness: 0.7, side: THREE.DoubleSide });
    for (let i = 0; i < 7; i++) { const g = new THREE.Group(), me = new THREE.Mesh(hull, bm); me.castShadow = true; g.add(me); for (const z of [-0.8, 0.5]) { const s = new THREE.Mesh(new THREE.BoxGeometry(1.2, 0.05, 0.3), bm); s.position.set(0, -0.12, z); g.add(s); } const lp = HL.sprite([1.0, 0.7, 0.3], 2.4, 0.9); lp.position.set(0, 0.7, 2.0); g.add(lp); const pole = new THREE.Mesh(new THREE.CylinderGeometry(0.02, 0.02, 0.9, 5), bm); pole.position.set(0, 0.3, 2.0); g.add(pole);
      g.position.set(bx + 20 + (i % 4) * 4.4 + (i > 3 ? 14 : 0), 0.32, bz + (i % 2 ? 3.6 : -3.6) + (i > 3 ? (i - 5) * 9 : 0)); g.rotation.y = HALF + (i > 3 ? i : 0.2 * i); LEVEL.add(g); HL.boats.push(g); }
    L.updates.push((dt, t) => { HL.boats.forEach((g, i) => { g.position.y = 0.3 + Math.sin(t * 1.1 + i * 1.7) * 0.06; g.rotation.z = Math.sin(t * 0.9 + i) * 0.04; }); });
    HL.floo(L, 'The boathouse', bx - 11, bz, HALF);
    const ox = 204, oz = 176, oy = HL.h(ox, oz); for (let i = 0; i < 9; i++) { const a = i / 9 * TAU; if (WORLD.boulder) WORLD.boulder(ox + Math.cos(a) * 9, oz + Math.sin(a) * 9, 3 + (i % 3) * 1.6, 500 + i * 13, TERRAIN.cliffMat(0xa8a8a4), { detail: 3, col: false }); }
    HL.round(ox, oz, 6.5, oy + 4, 44, { steep: 2.6, open: true, lit: 0.15, base: oy - 4 }); HL.round(ox + 7, oz + 3, 2.6, oy + 4, 30, { steep: 3, base: oy - 3 }); HL.foot(ox - 9, oz - 9, ox + 11, oz + 9); HL.OWLERY = [ox, oy, oz]; }
  // Floo flames at the castle and the pitch
  HL.floo(L, 'Hogwarts — the Viaduct Courtyard', -98, 132, 0.8); HL.floo(L, 'The Quidditch pitch', HL.Q.REF[0] - 3, HL.Q.REF[2] + 12, HALF);
  if (REALM.smokeBuild) REALM.smokeBuild(L);
});
/* quests: two errands that take you out of the castle */
(function () { const i = HL.QUESTS.findIndex((q) => q.id === 'rings');
  HL.QUESTS.splice(i + 1, 0, { id: 'hut', t: 'THE GROUNDS', n: 'The gamekeeper’s hut', o: 'Fly down to the hut at the forest’s edge and knock', way: () => [HL.HUT.x, HL.h(HL.HUT.x, HL.HUT.z) + 2, HL.HUT.z - 6], done: () => HL.quest.flags.hut, pts: 10 },
    { id: 'village', t: 'A HOGSMEADE WEEKEND', n: 'Visit Hogsmeade', o: 'Take the long bridge south and follow the road to the village (or fly, or use a Floo flame); go into the Three Broomsticks on the square and order a Butterbeer at the bar', way: () => { const d = HL.VILDOORS && HL.VILDOORS['THE THREE BROOMSTICKS']; return d ? [d[0], d[1] + 2, d[2]] : [HL.VIL.x, HL.VIL.y + 3, HL.VIL.z]; }, done: () => HL.quest.flags.beer, pts: 15 }); })();
