/* ==== p78d_hl_quests2.js ==== */
/* HOGWARTS — the opening errands, walked through the castle as Hogwarts Legacy lays it out: up the south bridge to the
   Clock Tower Courtyard, through the South Wing and the Grand Staircase to the Reception Hall and the Great Hall, out
   to the Viaduct Courtyard, over the Viaduct Bridge to the Library Annex. */
(function () {
  const Q = HL.QUESTS, at = (id) => Q.findIndex((q) => q.id === id), Y = () => HL.Y0, room = (re) => { for (const k of HL.ALLK) { const P = HL.plan(k), c = P.comps.find((q) => q.name && q.type !== 'ring' && re.test(q.name)); if (c) return [P.X((c.R.i0 + c.R.i1 + 1) / 2), P.y + 2, P.Z((c.R.j0 + c.R.j1 + 1) / 2)]; } return null; }, inZone = (a, re) => { const Z = HL.zoneAt(a.x, a.y + 1, a.z); return !!(Z && re.test(Z.name)); };
  Object.assign(Q[at('arrive')], { n: 'The Clock Tower Courtyard', o: 'Walk up the bridge to the Clock Tower: its great doors are the way into the castle  (<kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd>, hold <kbd>SHIFT</kbd> to run)', way: () => [-8, Y() + 1.5, -20], done: (a) => a.z > -40 && Math.abs(a.x) < 40 });
  Q.splice(at('arrive'), 0, { id: 'lock', t: 'A CHARMED LOCK', n: 'The chest on the bridge', o: 'Press <kbd>E</kbd> at the chest beside you, then cast the spells it shows, in order, on <kbd>1</kbd>–<kbd>8</kbd>', way: () => { const c = (HL.LOOT.chests || []).find((q) => q.id === 'first'); return c ? [c.x, c.y + 1.2, c.z] : null; }, done: () => { const c = (HL.LOOT.chests || []).find((q) => q.id === 'first'); return !c || c.open; }, pts: 5 });
  Object.assign(Q[at('hall')], { o: 'Go in by the Clock Tower\u2019s great doors and through the South Hall to the Faculty Tower; from there the Long Gallery runs north to the Reception Hall, and the Great Hall opens off it  (<kbd>M</kbd> unfolds the map)', way: () => room(/GREAT HALL/), done: (a) => inZone(a, /GREAT HALL/) });
  Q.splice(at('duel'), 1); Q.splice(at('hall') + 1, 0,
    { id: 'kitchens', t: 'THE DUNGEONS', n: 'Below the Great Hall', o: 'Take the stair down from the Reception Hall (beside the Great Hall doors), follow the passage south and find the kitchens  (<kbd>M</kbd>, then <kbd>0</kbd>, shows the dungeons)', way: () => [-79.5, Y() - HL.DUN.d + 2, 30], done: (a) => inZone(a, /KITCHENS/), pts: 15 },
    { id: 'duel', t: 'DEFENCE AGAINST THE DARK ARTS', n: 'Wand practice', o: () => `Strike the practice dummies in the Viaduct Courtyard  (<kbd>LMB</kbd> basic cast, <kbd>1</kbd>–<kbd>8</kbd> spells)  ${Math.min(8, HL.quest.n)} / 8`, way: () => HL.dummies && HL.dummies[1] ? [HL.dummies[1].x, Y() + 2, HL.dummies[1].z] : null, done: () => HL.quest.n >= 8, pts: 10 },
    { id: 'bout', t: 'CROSSED WANDS', n: 'Step into the ring', o: 'Speak with Lucan Brattleby under the pendulum in the Clock Tower hall and win a round of Crossed Wands  (<kbd>RMB</kbd> holds Protego; a block made at the last moment answers with Stupefy)', way: () => HL.duel && HL.duel.lucan ? [HL.duel.lucan.x, Y() + 1.6, HL.duel.lucan.z] : null, done: () => (HL.save.duel || 0) >= 1, pts: 15 },
    { id: 'class', t: 'THE LIBRARY ANNEX', n: 'Over the Viaduct Bridge', o: 'Cross the Viaduct Bridge from the courtyard and find the Library', way: () => room(/^THE LIBRARY/), done: (a) => inZone(a, /^THE LIBRARY/), pts: 10 },
    { id: 'ward', t: 'THE GRAND STAIRCASE', n: 'The Hospital Wing', o: 'Climb the Grand Staircase to the second floor and find the Hospital Wing, high over the South Hall', way: () => room(/HOSPITAL WING/), done: (a) => inZone(a, /HOSPITAL WING/), pts: 10 },
    { id: 'climb', t: 'YOUR HOUSE', n: 'Your common room', o: () => ({ gryffindor: 'Climb the Grand Staircase to the fourth floor and find the Gryffindor common room', ravenclaw: 'Find Ravenclaw Tower (ground floor, beside the Grand Staircase court) \u2014 your house\u2019s rooms rise above it', slytherin: 'Find the Slytherin entrance, the hall north of the Grand Staircase, and take its stair down to your common room under the lake', hufflepuff: 'Go down to the dungeons (the stair in the Reception Hall) and find the Hufflepuff common room' })[HL.save.house || HL.house] || 'Find your common room',
      way: () => { const h = HL.save.house || HL.house, D = HL.DUN; return h === 'slytherin' && D.sly ? [D.sly.cx, Y() - D.d + 2, D.sly.cz] : h === 'hufflepuff' && D.huf ? [D.huf.cx, Y() - D.d + 2, D.huf.cz] : h === 'ravenclaw' ? room(/RAVENCLAW TOWER/) : room(/GRYFFINDOR COMMON/); }, done: (a) => inZone(a, ({ slytherin: /SLYTHERIN COMMON/, hufflepuff: /HUFFLEPUFF COMMON/, ravenclaw: /RAVENCLAW/ })[HL.save.house || HL.house] || /GRYFFINDOR COMMON/), pts: 20 },
    { id: 'head', t: 'THE FACULTY TOWER', n: 'The Headmaster\u2019s Office', o: 'On the fourth floor, find the Headmaster\u2019s Office at the top of the Faculty Tower', way: () => room(/HEADMASTER\u2019S OFFICE/), done: (a) => inZone(a, /HEADMASTER\u2019S OFFICE/), pts: 30 },
    { id: 'tour', t: 'THE CASTLE', n: 'Find your way about', o: () => `Discover places in the castle  ${Math.min(20, Object.keys(HL.save.seen || {}).length)} / 20`, way: () => null, done: () => Object.keys(HL.save.seen || {}).length >= 20, pts: 20 });
  const s0 = HL.quest.start; HL.quest.start = function (cont) { if (HL.save.qv !== 15) { HL.save.qv = 15; HL.save.quest = 0; HL.save.seen = {}; HL.store(); } const r = s0.call(this, cont), i = HL.quest.i, f = HL.quest.flags; delete f.camp; delete f.mage; delete f.troll; if (i > at('camp')) f.camp = 4; if (i > at('mage')) f.mage = 1; if (i > at('troll')) f.troll = 1; return r; };
  /* people and pages in the castle; mirror passages to the parts no doorway reaches */
  HL.BUILD.push(async function castlelife(L) { const N = HL.STUDENTS || [], rs = mulberry(4242), P = HL.plan(0); let n = 0;
    const put = (x, y, z, yaw, base) => { const t = N[n++ % Math.max(1, N.length)]; if (t && CHAR.T[t]) HL.npc(t, x, z, yaw, { y, base, far: 38 }); };
    for (const c of HL.CORR || []) { if (c.len < 12 || c.wid < 3 || rs() > 0.4 || n > 40) continue; const u = 3 + rs() * (c.len - 6), v = c.wid / 2 + (rs() - 0.5) * (c.wid - 2), x = c.alongX ? c.x0 + u : c.x0 + v, z = c.alongX ? c.z0 + v : c.z0 + u, yaw = rs() * 6.28; put(x, c.y, z, yaw, 'talk'); put(x + Math.sin(yaw) * 1.3, c.y, z + Math.cos(yaw) * 1.3, yaw + Math.PI, rs() < 0.5 ? 'idle' : 'calm'); }
    if (HL.EHR) { const E = HL.EHR, xc = (E.x0 + E.x1) / 2; for (const [dx, dz, yaw, b] of [[-3, 6, 0.6, 'talk'], [-1.6, 7, -2.4, 'idle'], [8, 12, -1.2, 'calm'], [-9, 20, 1.2, 'talk'], [-7.6, 20.8, -1.9, 'calm']]) put(xc + dx, HL.Y0, E.z0 + dz, yaw, b); }
    if (HL.COURT) { const C = HL.COURT; for (const [fx, fz, yaw, b] of [[0.3, 0.3, 1, 'talk'], [0.34, 0.32, -2, 'idle'], [0.7, 0.6, 2.2, 'calm'], [0.2, 0.75, 0.4, 'idle']]) put(lerp(C.x0, C.x1, fx), HL.Y0, lerp(C.z0, C.z1, fz), yaw, b); }
    let pg = 0; for (const k of HL.ALLK) for (const c of HL.plan(k).comps) { const P = HL.plan(k); if (c.kind !== 'room' || !c.name || c.type === 'ring' || /CLASSROOM \d|A STUDY|TUTOR|AN OFFICE|READING ROOM|A MUSIC|STORE OF/.test(c.name) || (k > 0 && (c.id + k) % 3) || pg > 44) continue; const x = P.X((c.R.i0 + c.R.i1 + 1) / 2) + 1.2, z = P.Z((c.R.j0 + c.R.j1 + 1) / 2) + 1.2; HL.page('room' + k + '_' + c.id, x, P.y + 2.4, z, c.name.replace(/^THE /, 'The ').replace(/\B[A-Z]/g, (m) => m.toLowerCase())); pg++; }
    { const I = HL.IM(), M = HL.M(), glass = KIT.emis(0x9fd8ff, 1.3), isl = P.islands || [];
      const mirror = (x, y, z) => { KIT.tag = 'in0'; KIT.box(x - 0.7, y, z - 0.12, x + 0.7, y + 2.6, z + 0.12, M.gold, { col: false }); KIT.box(x - 0.56, y + 0.16, z - 0.14, x + 0.56, y + 2.44, z + 0.14, glass, { col: false }); KIT.box(x - 0.9, y, z - 0.3, x + 0.9, y + 0.14, z + 0.3, I.oakD, { col: false }); PHY.cyl(x, z, 0.5, y, y + 2.6); HL.sl(x, y + 1.6, z + 0.8, 0x9fd8ff, 5, 6); KIT.tag = ''; };
      const go = (x, y, z, label) => { const a = PLAYER.a; HL.ui.fade(1); setTimeout(() => { a.x = x; a.y = y + 0.1; a.z = z; a.vx = a.vy = a.vz = 0; CAM.snap = true; if (a.inst.cloth && a.inst.cloth.reset) a.inst.cloth.reset(); HL.ui.fade(0); HL.ui.spellName(label); }, 350); };
      const free = (c) => { const R4 = c.R, cx = (R4.i0 + R4.i1) >> 1, cj = (R4.j0 + R4.j1) >> 1; for (let r = 0; r < 6; r++) for (let dj = -r; dj <= r; dj++) for (let di = -r; di <= r; di++) { const i = cx + di, j = cj + dj; if (P.comp[j * P.NX + i] === c.id && !P.isW(i, j) && !P.isW(i + 1, j) && !P.isW(i - 1, j) && !P.isW(i, j + 1) && !P.isW(i, j - 1)) return [P.X(i) - 0.5, P.Z(j) - 0.5]; } return [P.X(cx) - 0.5, P.Z(cj) - 0.5]; };
      HL.PASSAGES = 0; if (isl.length && HL.EHR) { const E = HL.EHR, hub = [E.x1 - 3, E.z0 + 3]; isl.sort((a, b) => (b.name ? 1 : 0) - (a.name ? 1 : 0) || b.n - a.n); const T = isl.slice(0, 40).map((c) => { const p0 = free(c), p = HL.occ.spot(0, p0[0], p0[1], 1.0, 6, 3) || p0; return { x: p[0], z: p[1], name: c.name || 'A HIDDEN ROOM' }; }); HL.occ.mark(0, hub[0], hub[1], 1, 1, 0, 3); mirror(hub[0], P.y, hub[1]); let k = 0;
        HL.interact([hub[0], P.y + 1.2, hub[1] - 0.6], 2.2, 'Step through the mirror (a secret passage, ' + T.length + ' in the castle)', () => { const t = T[k++ % T.length]; go(t.x, P.y, t.z - 1.3, 'A SECRET PASSAGE · ' + t.name); });
        for (const t of T) { mirror(t.x, P.y, t.z); HL.interact([t.x, P.y + 1.2, t.z - 0.6], 2.2, 'Step back through the mirror', () => go(hub[0], P.y, hub[1] - 1.4, 'THE ENTRANCE HALL')); HL.PASSAGES++; } } }
    // Floo flames through the castle (the map's fast travel): by the door of each great room
    { const spots = [[0, /^THE LIBRARY$/, 'The Library'], [0, /CENTRAL HALL/, 'The Central Hall'], [0, /RECEPTION HALL/, 'The Reception Hall'], [0, /CLOCK TOWER/, 'The Clock Tower'], [0, /POTIONS CLASSROOM/, 'The Potions Classroom'], [0, /ASTRONOMY TOWER/, 'The Astronomy Tower'], [4, /GRYFFINDOR COMMON/, 'The Gryffindor Common Room'], [4, /RAVENCLAW COMMON/, 'The Ravenclaw Common Room'], [4, /HEADMASTER\u2019S OFFICE/, 'The Headmaster\u2019s Office'], [2, /HOSPITAL WING/, 'The Hospital Wing'], [2, /ASTRONOMY CLASSROOM/, 'The Astronomy Classroom'], [3, /ROOM OF REQUIREMENT/, 'The Room of Requirement'], [0, /SOUTH HALL/, 'The South Hall']];
      for (const [k, re, nm] of spots) { const P2 = HL.plan(k), c = P2.comps.find((q) => q.name && q.type !== 'ring' && re.test(q.name)); if (!c) continue; const sp = HL.occ.spot(k, P2.X(c.R.i0) - 1.5, P2.Z(c.R.j1 + 1) + 1.5, 0.9, 8, 3) || [P2.X(c.R.i0) - 1.3, P2.Z(c.R.j1 + 1) + 1.3]; KIT.tag = 'in' + k; HL.floo(L, nm, sp[0], sp[1], 0.8, P2.y); KIT.tag = ''; } }
    if (HL.GHR) HL.page('dais', (HL.GHR.x0 + HL.GHR.x1) / 2, HL.Y0 + 3.2, HL.GHR.z0 + 9, 'The High Table'); });
})();
