/* ==== p78g_hl_ghosts.js ==== */
/* HOGWARTS — the castle ghosts: pearl-white, translucent, drifting a hand above the floor along their haunts
   (through walls and tables, as they do). Each has a word for you. */
HL.START.push(function (L) { const N = HL.STUDENTS || [], Y = HL.Y0, yd = Y - (HL.DUN ? HL.DUN.d : 7); if (!N.length) return; HL.ghosts = [];
  const mat = new THREE.MeshBasicMaterial({ color: new THREE.Color(0.62, 0.78, 1.0), transparent: true, opacity: 0.34, depthWrite: false, blending: THREE.AdditiveBlending, toneMapped: false });
  const tp = (i) => (CHAR.T.prof_a && i % 2 === 0) ? 'prof_a' : (CHAR.T.prof_b && i % 2) ? 'prof_b' : N[i % N.length];
  [['Peeves', [-37, Y + 0.9, 63], [-37, Y + 0.9, 93], ['Speak with Peeves', 'Ickle firsties, lost in the castle! Shall Peeves show you the way? It’s THAT way. Or is it?', 'Peeves knows where all four common rooms are, and Peeves isn’t telling. Lions on the fourth floor, eagles too, snakes under the lake, badgers by the kitchens. Oops.', 'Nobody has ever stood in all four in one term. Nobody! Wheeee!']],
   ['Nearly Headless Nick', [-79.5, Y, 24], [-79.5, Y, 76], ['Speak with Sir Nicholas', 'Welcome back to Hogwarts. Mind the trick stair in the Grand Staircase, and do try the kitchens, below the Great Hall.', 'Nearly headless? I prefer “Sir Nicholas de Mimsy-Porpington”.']],
   ['The Grey Lady', [-96, Y, 88], [-58, Y, 88], ['Speak with the Grey Lady', 'The dungeons lie under these flagstones. The stair is just there, by the Great Hall doors.', 'Ravenclaw Tower is across the gorge, beyond the Grand Staircase.']],
   ['The Fat Friar', [-79.5, yd, 44], [-79.5, yd, 79], ['Speak with the Fat Friar', 'Hufflepuff common room on this side, the cellars over there, and the kitchens at the end. Bless you!', 'Have you found every chest down here? There are five.']],
   ['The Bloody Baron', [-26, Y, 80], [-11, Y, 95], ['Speak with the Bloody Baron', '…', 'Slytherin lies below the hall to the north of this stair. Mind the steps.', 'The staircase climbs five storeys. The Headmaster keeps the top.']],
   ['Professor Binns', [116, Y, 118], [133, Y, 118], ['Speak with Professor Binns', 'In 1289 the International Warlock Convention met… do sit down.', 'I have taught History of Magic for a very long time. I did not notice dying.']]
  ].forEach((g, i) => { const t = tp(i); if (!CHAR.T[t]) return; const a = HL.npc(t, g[1][0], g[1][2], 0, { y: g[1][1] + 0.3, name: g[0], far: 70, base: 'idle' }); a.turn = false; let said = 0; const u = HL.interact([g[1][0], g[1][1] + 1.2, g[1][2]], 3, g[3][0], () => { (HL.save.met = HL.save.met || {})[g[0]] = 1; HL.store(); (HL.ui.say || HL.ui.toast)(g[0], g[3][1 + (said++ % (g[3].length - 1))], 6, a, g[3].length > 2 ? 'E — GO ON' : ''); });
    a.root.traverse((o) => { if (o.isMesh) { o.material = mat; o.castShadow = false; o.receiveShadow = false; o.renderOrder = 5; } }); if (a.inst && a.inst.cloth && a.inst.cloth.group) a.inst.cloth.group.traverse((o) => { if (o.isMesh) { o.material = mat; o.castShadow = false; o.renderOrder = 5; } });
    a.sitY = g[1][1] + 0.3; a.ghost = true; HL.ghosts.push({ a, u, p: g[1], q: g[2], t: i * 3.7, L: Math.hypot(g[2][0] - g[1][0], g[2][2] - g[1][2]) }); });
  L.updates.push((dt, tt) => { for (const g of HL.ghosts) { g.t += dt; const per = g.L / 1.1, ph = (g.t % (per * 2)) / per, f = ph < 1 ? ph : 2 - ph, s = f * f * (3 - 2 * f), a = g.a; a.x = lerp(g.p[0], g.q[0], s); a.z = lerp(g.p[2], g.q[2], s); a.sitY = g.p[1] + 0.32 + Math.sin(tt * 1.3 + g.L) * 0.12; a.y = a.sitY; const want = Math.atan2(g.q[0] - g.p[0], g.q[2] - g.p[2]) + (ph < 1 ? 0 : PI); a.yaw += wrapA(want - a.yaw) * Math.min(1, dt * 2.5); g.u.p.set(a.x, a.y + 1.2, a.z); } });
});
/* enchanted books drifting about the Library, re-shelving themselves */
HL.START.push(function (L) { const P = HL.plan(0), c = P.comps.find((q) => q.name === 'THE LIBRARY'); if (!c) return; const x0 = P.X(c.R.i1 + 1), x1 = P.X(c.R.i0), z0 = P.Z(c.R.j1 + 1), z1 = P.Z(c.R.j0), Y = HL.Y0, N = 46, rs = mulberry(88);
  const g = new THREE.BoxGeometry(0.44, 0.09, 0.58), im = new THREE.InstancedMesh(g, new THREE.MeshStandardMaterial({ roughness: 0.7 }), N), col = new THREE.Color(), B = []; im.userData.tag = 'in0'; im.frustumCulled = false; im.castShadow = false;
  for (let i = 0; i < N; i++) { col.setHSL([0.02, 0.6, 0.33, 0.1, 0.75][i % 5] + rs() * 0.04, 0.6, 0.34 + rs() * 0.16); im.setColorAt(i, col); B.push({ cx: lerp(x0 + 4, x1 - 4, rs()), cz: lerp(z0 + 4, z1 - 4, rs()), y: Y + 2.5 + rs() * 4.2, r: 2 + rs() * 5, w: (0.12 + rs() * 0.22) * (rs() < 0.5 ? -1 : 1), ph: rs() * 6.28, fl: 3 + rs() * 4 }); }
  LEVEL.add(im); const m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), e = new THREE.Euler(), p = new THREE.Vector3(), s = new THREE.Vector3(1, 1, 1); for (let i = 0; i < N; i++) im.setMatrixAt(i, new THREE.Matrix4().makeTranslation(B[i].cx, B[i].y, B[i].cz)); im.instanceMatrix.needsUpdate = true;
  L.updates.push((dt, t) => { if (!im.visible) return; for (let i = 0; i < N; i++) { const b = B[i], a = b.ph + t * b.w; p.set(clamp(b.cx + Math.cos(a) * b.r, x0 + 1, x1 - 1), b.y + Math.sin(t * 0.7 + b.ph) * 0.5, clamp(b.cz + Math.sin(a * 1.3) * b.r, z0 + 1, z1 - 1)); e.set(Math.sin(t * b.fl + b.ph) * 0.35, -a + (b.w > 0 ? 0 : PI), Math.sin(t * 0.9 + b.ph) * 0.3); q.setFromEuler(e); m4.compose(p, q, s); im.setMatrixAt(i, m4); } im.instanceMatrix.needsUpdate = true; }); });

/* the Clock Tower: the pendulum swings, the wheels turn, every dial in the castle keeps the real time */
HL.START.push(function (L) { let tk = 0; L.updates.push((dt, t) => { const C = HL.CLOCK; if (C && C.pend && C.pend.visible) { C.pend.rotation.z = Math.sin(t * 1.35) * 0.3; for (const g of C.cogs) g.rotation.z += dt * g.userData.sp; }
    tk -= dt; if (tk > 0 || !HL.DIALS) return; tk = 1; const d = new Date(), mi = d.getMinutes() + d.getSeconds() / 60, hr = (d.getHours() % 12) + mi / 60; for (const q of HL.DIALS) { q.m.rotation.z = -mi / 60 * TAU; q.h.rotation.z = -hr / 12 * TAU; } }); });
