/* ==== p78h_hl_greenhouses.js ==== */
/* HOGWARTS — the greenhouses north of the Bell Tower Courtyard: iron and glass over the low walls the plan draws, a gabled
   glass roof, planting benches down both sides and a bed of larger things down the middle. Also the names of the open-air
   places (courts, bridges, greenhouses) for the map. */
HL.OUTDOOR = [];
HL.BUILD.push(async function greenhouses(L) {
  const M = HL.M(), G = HL.GK.M(), I = HL.IM(), Y = HL.Y0, rs = mulberry(5150), X = (i) => HL.PL.X0 - i, Z = (j) => HL.PL.Z0 - j;
  const glass = new THREE.MeshPhysicalMaterial({ color: 0xcfeadf, roughness: 0.04, metalness: 0, transparent: true, opacity: 0.2, envMapIntensity: 2.2, depthWrite: false, side: THREE.DoubleSide }); glass.userData.tscale = 1;
  const hm = (c, r) => { const m = new THREE.MeshStandardMaterial({ color: c, roughness: r === undefined ? 0.9 : r }); m.userData.tscale = 1; return m; }, soil = hm(0x2a1c12), terra = hm(0x9a5030), leaf = [hm(0x2f6a2a), hm(0x4a8a34), hm(0x1f5030), hm(0x6a9a3a)], bloom = [KIT.emis(0xff6090, 0.7), KIT.emis(0xffc040, 0.7), KIT.emis(0x9a70ff, 0.8), KIT.emis(0xff7030, 0.7), hm(0xf0f0e8)];
  KIT.tag = '';
  const plant = (x, y, z, s) => { const t = (rs() * 6) | 0, lf = leaf[(rs() * 4) | 0];
    if (t === 0) { for (let q = 0; q < 3; q++) KIT.geo(new THREE.SphereGeometry(0.2 + rs() * 0.16, 7, 5), lf, new THREE.Matrix4().makeScale(s, s * (0.8 + rs() * 0.5), s).setPosition(x + (rs() - 0.5) * 0.3 * s, y + (0.18 + q * 0.14) * s, z + (rs() - 0.5) * 0.3 * s)); }
    else if (t === 1) { for (let q = 0; q < 5; q++) { const a = q / 5 * TAU + rs(), g = new THREE.ConeGeometry(0.07 * s, (0.7 + rs() * 0.5) * s, 4); g.translate(0, 0.35 * s, 0); g.rotateZ(0.5); g.rotateY(a); KIT.geo(g, lf, new THREE.Matrix4().makeTranslation(x, y, z)); } }
    else if (t === 2) { KIT.cyl(x, y, z, 0.02 * s, 0.55 * s, lf, { seg: 5, col: false }); KIT.geo(new THREE.SphereGeometry(0.12 * s, 7, 5), bloom[(rs() * 5) | 0], new THREE.Matrix4().makeTranslation(x, y + 0.6 * s, z)); for (let q = 0; q < 2; q++) KIT.geo(new THREE.SphereGeometry(0.13 * s, 6, 4), lf, new THREE.Matrix4().makeScale(1.6, 0.35, 1).setPosition(x + (q ? 0.14 : -0.14) * s, y + 0.2 * s, z)); }
    else if (t === 3) { KIT.cyl(x, y, z, 0.16 * s, 0.26 * s, terra, { seg: 8, col: false, r1: 0.2 * s }); KIT.geo(new THREE.SphereGeometry(0.15 * s, 7, 5), hm(0xb89a70), new THREE.Matrix4().makeScale(1, 0.7, 1).setPosition(x, y + 0.3 * s, z)); for (let q = 0; q < 4; q++) { const g = new THREE.ConeGeometry(0.05 * s, 0.4 * s, 4); g.translate(0, 0.2 * s, 0); g.rotateZ(0.6); g.rotateY(q * 1.6); KIT.geo(g, lf, new THREE.Matrix4().makeTranslation(x, y + 0.36 * s, z)); } }   // a mandrake in its pot
    else if (t === 4) { KIT.cyl(x, y, z, 0.035 * s, 1.1 * s, hm(0x4a3a22), { seg: 5, col: false }); for (let q = 0; q < 4; q++) KIT.geo(new THREE.SphereGeometry((0.26 - q * 0.04) * s, 7, 5), lf, new THREE.Matrix4().makeTranslation(x + (rs() - 0.5) * 0.3 * s, y + (0.8 + q * 0.22) * s, z + (rs() - 0.5) * 0.3 * s)); }
    else { for (let q = 0; q < 4; q++) { const a = rs() * TAU; KIT.beam([x, y, z], [x + Math.cos(a) * 0.4 * s, y + (0.5 + rs() * 0.5) * s, z + Math.sin(a) * 0.4 * s], 0.035 * s, lf); KIT.geo(new THREE.SphereGeometry(0.08 * s, 6, 4), bloom[(rs() * 5) | 0], new THREE.Matrix4().makeTranslation(x + Math.cos(a) * 0.42 * s, y + 0.9 * s, z + Math.sin(a) * 0.42 * s)); } } };
  const bench = (xa, za, xb, zb, h, big) => { KIT.box(xa, Y, za, xb, Y + h, zb, I.oakD, { mats: { Y: soil } }); KIT.box(xa - 0.05, Y + h - 0.12, za - 0.05, xb + 0.05, Y + h + 0.04, zb + 0.05, I.oak, { col: false, faces: 'xXzZ' }); HL.occ.mark(0, (xa + xb) / 2, (za + zb) / 2, (xb - xa) / 2, (zb - za) / 2, 0, 3);
    for (let z = za + 0.4; z < zb - 0.2; z += big ? 1.3 : 0.62) for (let x = xa + 0.3; x < xb - 0.15; x += big ? 0.9 : 0.5) plant(x + (rs() - 0.5) * 0.12, Y + h, z + (rs() - 0.5) * 0.14, big ? 1.5 + rs() * 0.9 : 0.75 + rs() * 0.5); };
  const house = (i0, i1, name, last, n) => { const x0 = X(i1), x1 = X(i0 + 1), z0 = Z(40), z1 = Z(19), xc = (x0 + x1) / 2, zc = (z0 + z1) / 2, yb = Y + 1.25, ye = Y + 4.6, yr = Y + 8.4, xa = x0 - 0.5, xb = x1 + 0.5, za = z0 - 0.5, zb = z1 + 0.5, hw = (xb - xa) / 2, sl = Math.hypot(hw, yr - ye), an = Math.atan2(yr - ye, hw);
    HL.OUTDOOR.push({ name, x0, x1, z0, z1, kind: 'green' }); HL.zone(name, x0, z0, x1, z1, Y - 1, Y + 9, { hemi: 0.75 });
    const wall = (ax, az, bx2, bz, y0, y1) => { KIT.box(Math.min(ax, bx2) - 0.05, y0, Math.min(az, bz) - 0.05, Math.max(ax, bx2) + 0.05, y1, Math.max(az, bz) + 0.05, glass, { col: false }); PHY.box(Math.min(ax, bx2) - 0.1, y0, Math.min(az, bz) - 0.1, Math.max(ax, bx2) + 0.1, y1, Math.max(az, bz) + 0.1); };
    wall(xa, za, xa, zb, yb, ye); if (last) wall(xb, za, xb, zb, yb, ye); wall(xa, zb, xb, zb, yb, ye); wall(xa, za, xc - 1.5, za, yb, ye); wall(xc + 1.5, za, xb, za, yb, ye); wall(xc - 1.5, za, xc + 1.5, za, Y + 3.3, ye);
    for (const sd of [-1, 1]) KIT.rbox(xc + sd * hw / 2, (ye + yr) / 2, zc, sl / 2, 0.03, (zb - za) / 2, 0, 0, -sd * an, glass, 0);
    for (const z of [za, zb]) { const sh = new THREE.Shape(); sh.moveTo(-hw, 0); sh.lineTo(hw, 0); sh.lineTo(0, yr - ye); sh.closePath(); KIT.geo(new THREE.ShapeGeometry(sh), glass, new THREE.Matrix4().makeTranslation(xc, ye, z)); KIT.beam([xa, ye, z], [xb, ye, z], 0.1, M.iron); KIT.beam([xc, ye, z], [xc, yr, z], 0.07, M.iron); }
    for (let z = za; z <= zb + 0.01; z += (zb - za) / 10) { KIT.beam([xa, ye, z], [xc, yr, z], 0.08, M.iron); KIT.beam([xb, ye, z], [xc, yr, z], 0.08, M.iron); KIT.beam([xa, yb, z], [xa, ye, z], 0.07, M.iron); if (last) KIT.beam([xb, yb, z], [xb, ye, z], 0.07, M.iron); }
    for (let x = xa; x <= xb + 0.01; x += (xb - xa) / 6) { KIT.beam([x, yb, zb], [x, ye, zb], 0.07, M.iron); if (Math.abs(x - xc) > 1.4) KIT.beam([x, yb, za], [x, ye, za], 0.07, M.iron); }
    KIT.beam([xa, ye, za], [xa, ye, zb], 0.1, M.iron); if (last) KIT.beam([xb, ye, za], [xb, ye, zb], 0.1, M.iron); KIT.beam([xc, yr, za], [xc, yr, zb], 0.12, M.iron); for (const f of [0.5]) for (const sd of [-1, 1]) KIT.beam([xc + sd * hw * f, lerp(yr, ye, f), za], [xc + sd * hw * f, lerp(yr, ye, f), zb], 0.06, M.iron);
    for (const sx of [-1.5, 1.5]) KIT.beam([xc + sx, Y, za], [xc + sx, Y + 3.3, za], 0.12, M.iron); KIT.beam([xc - 1.5, Y + 3.3, za], [xc + 1.5, Y + 3.3, za], 0.12, M.iron);
    // the beds: a planting bench down each side, larger things down the middle, vines up the ribs, lamps
    bench(x0 + 0.5, z0 + 1.6, x0 + 1.6, z1 - 1.2, 0.85, false); bench(x1 - 1.6, z0 + 1.6, x1 - 0.5, z1 - 1.2, 0.85, false); bench(xc - 1.1, z0 + 5.4, xc + 1.1, z1 - 2.6, 0.55, true);
    for (let q = 0; q < 5; q++) { const z = lerp(za, zb, (q + 0.5) / 5), sd = q % 2 ? 1 : -1; KIT.beam([xc + sd * hw, yb, z + 0.2], [xc + sd * hw * 0.3, lerp(yr, ye, 0.3), z + 0.2], 0.05, leaf[q % 4]); for (let t = 0.15; t < 1; t += 0.14) KIT.geo(new THREE.SphereGeometry(0.16 + rs() * 0.12, 6, 4), leaf[(q + 1) % 4], new THREE.Matrix4().makeTranslation(lerp(xc + sd * hw, xc + sd * hw * 0.3, t) - sd * 0.1, lerp(yb, lerp(yr, ye, 0.3), t) - 0.14, z + 0.2 + (rs() - 0.5) * 0.3)); }
    for (const f of [0.25, 0.75]) { const z = lerp(z0, z1, f); for (const sx of [-3.2, 3.2]) HL.lantern(L, xc + sx, Y + 4.2, z, { i: 9, range: 9 }); } HL.sl(xc, Y + 3, zc, 0xc8ffd0, 5, 12);
    if (HL.page) HL.page('green' + n, xc + 3.2, Y + 1.8, z1 - 3, name.charAt(0) + name.slice(1).toLowerCase()); return { x0, x1, z0, z1, xc, zc }; };
  const hs = [house(109, 123, 'GREENHOUSE THREE', false, 3), house(93, 107, 'GREENHOUSE TWO', false, 2), house(77, 91, 'GREENHOUSE ONE', true, 1)]; HL.GREEN = hs;
  // the open courts and bridges of the plan, for the map
  HL.OUTDOOR.push({ name: 'THE BELL TOWER COURTYARD', x0: X(74), x1: X(17), z0: Z(62), z1: Z(41), kind: 'court' }, { name: 'THE GREENHOUSE COURT', x0: X(128), x1: X(75), z0: Z(62), z1: Z(41), kind: 'court' }, { name: 'THE SUSPENSION BRIDGE', x0: 33, x1: 42, z0: 81, z1: 84, kind: 'bridge' }, { name: 'THE TRANSFIGURATION COURTYARD', x0: 65, x1: 112, z0: 106, z1: 151, kind: 'court' }, { name: 'THE QUAD COURTYARD', x0: -2, x1: 24, z0: 58, z1: 87, kind: 'court' },
    { name: 'THE CLOCK TOWER COURTYARD', x0: -19, x1: 18, z0: -40, z1: 3, kind: 'court' }, { name: 'THE VIADUCT COURTYARD', x0: -105, x1: -53, z0: 129, z1: 182, kind: 'court' }, { name: 'THE VIADUCT', x0: -52, x1: 7, z0: 151, z1: 158, kind: 'bridge' }, { name: 'THE SOUTH BRIDGE', x0: -6, x1: 5, z0: -60, z1: -41, kind: 'bridge' });
});
HL.START.push(function (L) { const N = HL.STUDENTS || [], Gh = HL.GREEN; if (!Gh || !N.length) return; const Y = HL.Y0;
  const t = CHAR.T.prof_b ? 'prof_b' : N[0]; if (CHAR.T[t]) HL.npc(t, Gh[2].xc + 2.6, Gh[2].z0 + 4, 2.4, { y: Y, name: 'The Professor of Herbology', far: 50, base: 'calm', talk: ['Speak with the Professor of Herbology', 'Earmuffs on before you lift a Mandrake, please. Greenhouse Three is for the seventh-years: mind the Tentacula.', 'The passage between Arithmancy and Divination is the quickest way back: it comes out in the Central Hall.'] });
  [[Gh[1].xc - 2.8, Gh[1].zc + 2, 1.2, 'idle'], [Gh[1].xc + 2.9, Gh[1].zc - 3, -1.8, 'calm'], [Gh[0].xc + 2.8, Gh[0].zc, -1.4, 'idle'], [Gh[2].xc - 2.8, Gh[2].zc + 5, 1.6, 'talk']].forEach((s, i) => { const st = N[(i * 5 + 2) % N.length]; if (CHAR.T[st]) HL.npc(st, s[0], s[1], s[2], { y: Y, base: s[3], far: 45 }); }); });
