/* ==== p78i_hl_life.js ==== */
/* HOGWARTS — the life of the castle. People walk its passages, halls, courts and the bridge (and stop for you); a professor
   stands before every class; knots of students talk in the halls and common rooms; paper memos fly the corridors.
   Every walker keeps to a lane that was checked against the occupancy grid, so nobody walks through a table. */
HL.START.push(function (L) { const N = HL.STUDENTS || []; if (!N.length || !HL.occ) return; const rs = mulberry(9090), Y = HL.Y0, H1 = HL.PL.H1; let ni = 0;
  const stu = () => { for (let q = 0; q < N.length; q++) { const t = N[(ni++) % N.length]; if (CHAR.T[t]) return t; } return null; };
  const freeAt = (k, x, z) => { const v = HL.occ.at(k, x, z); return v === 0 || v === 2 || v === 4; }, lanes = [];
  /* a lane a → b on storey k: cut down to its longest clear stretch (a body's width either side) */
  const lane = (k, y, ax, az, bx, bz, o) => { const L2 = Math.hypot(bx - ax, bz - az), n = Math.max(1, Math.floor(L2 / 0.5)), px = -(bz - az) / L2, pz = (bx - ax) / L2; let best = [0, -1], s0 = -1;
    for (let i = 0; i <= n; i++) { const t = i / n, x = lerp(ax, bx, t), z = lerp(az, bz, t), ok = k < 0 || (freeAt(k, x, z) && freeAt(k, x + px * 0.45, z + pz * 0.45) && freeAt(k, x - px * 0.45, z - pz * 0.45)); if (ok && s0 < 0) s0 = i; if ((!ok || i === n) && s0 >= 0) { const e = ok ? i : i - 1; if (e - s0 > best[1] - best[0]) best = [s0, e]; s0 = -1; } }
    const len = (best[1] - best[0]) * L2 / n; if (len < 7) return null; const la = { k, y, a: [lerp(ax, bx, best[0] / n), lerp(az, bz, best[0] / n)], b: [lerp(ax, bx, best[1] / n), lerp(az, bz, best[1] / n)], len, px, pz, yaw: Math.atan2(bx - ax, bz - az), out: !!(o && o.out), off: 0.55 }; lanes.push(la); return la; };
  // ---- the passages of every storey
  for (const c of HL.CORR || []) { if (c.len < 9 || c.wid < 2) continue; const off = c.wid >= 3 ? 0.55 : 0, m = 1.4; const la = c.alongX ? lane(c.k, c.y, c.x0 + m, (c.z0 + c.z1) / 2, c.x1 - m, (c.z0 + c.z1) / 2) : lane(c.k, c.y, (c.x0 + c.x1) / 2, c.z0 + m, (c.x0 + c.x1) / 2, c.z1 - m); if (la) la.off = off; }
  // ---- the halls you pass through: down the carpet, and down either side of it
  for (const k of HL.ALLK) { const P = HL.plan(k); for (const c of P.comps) { if (c.kind !== 'room' || !/^(lobby|gallery|entrance|clock)$/.test(c.type || '') || HL.WELLN[c.name]) continue; const x0 = P.X(c.R.i1 + 1), x1 = P.X(c.R.i0), z0 = P.Z(c.R.j1 + 1), z1 = P.Z(c.R.j0), w = x1 - x0, d = z1 - z0, lx = w >= d;
      for (const f of (Math.min(w, d) >= 16 ? [0.5, 0.2] : [0.5])) { const la = lx ? lane(k, P.y, x0 + 1.6, lerp(z0, z1, f), x1 - 1.6, lerp(z0, z1, f)) : lane(k, P.y, lerp(x0, x1, f), z0 + 1.6, lerp(x0, x1, f), z1 - 1.6); if (la) { la.off = 0.6; la.hall = 1; } } } }
  { const G2 = HL.GHR; if (G2) for (const dx of [-8.3, 0, 8.3]) { const la = lane(0, Y, (G2.x0 + G2.x1) / 2 + dx, G2.z0 + 15, (G2.x0 + G2.x1) / 2 + dx, G2.z1 - 2); if (la) { la.off = 0.5; la.hall = 1; } } }
  // ---- the courts (their crossing paths) and the bridge
  for (const o of HL.OUTDOOR || []) { if (o.kind !== 'court') continue; const cx = (o.x0 + o.x1) / 2, cz = (o.z0 + o.z1) / 2; for (const [ax, az, bx, bz] of [[cx, o.z0 + 1.6, cx, cz - 6.2], [cx, cz + 6.2, cx, o.z1 - 1.6], [o.x0 + 1.6, cz, cx - 6.2, cz], [cx + 6.2, cz, o.x1 - 1.6, cz]]) { if (Math.hypot(bx - ax, bz - az) < 7) continue; const la = lane(-1, Y, ax, az, bx, bz, { out: 1 }); if (la) la.off = 0.5; } }
  { const la = lane(-1, Y, 0, -236, 0, -64, { out: 1 }); if (la) { la.off = 1.4; la.bridge = 1; } const lb = lane(-1, Y, -0.5, -38, -0.5, -26, { out: 1 }); }
  /* Hogsmeade's high street, both sides of the crown of the road, and a turn round the square */
  if (HL.VIL) { const V = HL.VIL; for (const dz of [-2.6, 2.4]) { const la = lane(-1, V.y, V.x - 66, V.z + dz, V.x + 64, V.z + dz, { out: 1 }); if (la) { la.off = 0.7; la.vil = 1; } } const lb = lane(-1, V.y, V.x - 6, V.z - 24, V.x - 6, V.z - 8, { out: 1 }); if (lb) { lb.off = 0.6; lb.vil = 1; } }
  // ---- walkers
  HL.walkers = []; const cap = { 0: 44, 1: 9, 2: 9, 3: 7, 4: 5, '-1': 26, v: 16 }, used = {};
  lanes.sort((a, b) => (b.hall || 0) - (a.hall || 0) || b.len - a.len);
  for (const la of lanes) { const n = la.bridge ? 7 : la.vil ? Math.round(la.len / 19) : clamp(Math.round(la.len / (la.hall ? 12 : 14)), 1, 3), ck = la.vil ? 'v' : la.k; for (let q = 0; q < n; q++) { if ((used[ck] || 0) >= cap[ck]) break; const t = stu(); if (!t) break; const w = { la, t: (q + 0.2 + rs() * 0.6) / n, dir: q % 2 ? 1 : -1, v: 1.05 + rs() * 0.5, pause: rs() * 2 };
        const x = lerp(la.a[0], la.b[0], w.t), z = lerp(la.a[1], la.b[1], w.t), a = HL.npc(rs() < 0.07 && CHAR.T.prof_b ? 'prof_b' : t, x, z, la.yaw, { y: la.y, base: 'idle', far: la.out ? 62 : 40 }); a.x = x; a.z = z; if (la.out) a.dyMax = 40; w.a = a; HL.walkers.push(w); used[ck] = (used[ck] || 0) + 1; } }
  /* walking: each keeps to its side of the lane; when you are near, it gives you room (steps wide of you if the floor there is free), and stops rather than walk into you */
  L.updates.push((dt) => { const P2 = PLAYER.a; for (const w of HL.walkers) { const a = w.a, la = w.la; if (w.pause > 0) { w.pause -= dt; a.speed = 0; continue; }
      const bx = lerp(la.a[0], la.b[0], w.t), bz = lerp(la.a[1], la.b[1], w.t), sd0 = w.dir * la.off; let want = sd0;
      if (P2 && !a.hiddenN && Math.abs(P2.y - a.y) < 2) { const dx = P2.x - a.x, dz = P2.z - a.z, dd = Math.hypot(dx, dz); if (dd < 5.5) { const lat = (P2.x - bx) * la.px + (P2.z - bz) * la.pz, away = sd0 + (sd0 - lat >= 0 ? 1.15 : -1.15); if (la.k < 0 || freeAt(la.k, bx + la.px * away, bz + la.pz * away)) want = away; if (dd < 1.1 && (dx * Math.sin(a.yaw) + dz * Math.cos(a.yaw)) > 0) { a.speed = 0; w.pause = 0.4; continue; } } }
      w.lat = damp(w.lat === undefined ? sd0 : w.lat, want, 3, dt);
      w.t += w.dir * w.v * dt / la.len; if (w.t >= 1) { w.t = 1; w.dir = -1; w.pause = 0.8 + rs() * 3; } else if (w.t <= 0) { w.t = 0; w.dir = 1; w.pause = 0.8 + rs() * 3; }
      a.x = lerp(la.a[0], la.b[0], w.t) + la.px * w.lat; a.z = lerp(la.a[1], la.b[1], w.t) + la.pz * w.lat; a.y = la.vil ? HL.gy(a.x, a.z) + 0.07 : la.y; a.grounded = true; a.speed = w.v; a.mvx = 0; a.mvz = 1; const ty = la.yaw + (w.dir > 0 ? 0 : PI); a.yaw += wrapA(ty - a.yaw) * Math.min(1, dt * 6); } });
  // ---- a professor before every class
  const PN = [[/TRANSFIGURATION CLASSROOM/, 'Professor Weasley', 'Wands away until I say. Today: beetles into buttons.', 'You will find the Hospital Wing two floors above the South Hall, should a spell go astray.'], [/CHARMS CLASSROOM/, 'Professor Ronen', 'Swish and flick! No, no, swish, then flick.', 'A charm well cast is half a duel won.'], [/FIG/, 'Professor Fig', 'Ancient magic leaves traces, if you know how to look.', 'Mind the Restricted Section. Or do not, and tell me what you find.'], [/BEASTS/, 'Professor Howin', 'Approach a beast as you would be approached: slowly.', 'The paddock is out beyond the Bell Tower Courtyard.'], [/ASTRONOMY/, 'Professor Shah', 'The deck at the top of this tower has the clearest sky in Scotland.', 'Bring your telescope at midnight.'], [/DIVINATION/, 'Professor Onai', 'Look into the crystal. What looks back?', 'The leaves never lie; they merely mumble.'], [/POTIONS|ALCHEMY|ANTIDOTES/, 'Professor Sharp', 'A potion is patience in a bottle. Stir clockwise.', 'Touch nothing on my shelves.'], [/DEFENCE/, 'The Defence Master', 'Protego first. Always Protego first.', 'The practice dummies are in the Viaduct Courtyard.'], [/ARITHMANCY|NUMEROLOGY/, 'The Arithmancy Mistress', 'Seven is the most powerfully magical number. Show your working.', 'Numbers do not flatter.'], [/MUGGLE/, 'The Muggle Studies Master', 'A telephone, class, is not a kind of wand.', 'They manage remarkably well without magic.'], [/RUNES|ANCIENT STUDIES/, 'The Runes Mistress', 'Ehwaz means partnership. Eihwaz means defence. Do not confuse them again.', 'Translate lines four to nine.']];
  let np = 0; for (const p of HL.PROFS || []) { if (np > 22 || /HISTORY/.test(p[4])) continue; const m = PN.find((q) => q[0].test(p[4])) || [0, 'A Professor', 'Sit down, please; we have a great deal to cover.', 'Essays on my desk by Friday.'], t = np % 2 ? 'prof_a' : 'prof_b'; if (!CHAR.T[t]) continue; HL.npc(t, p[0], p[1], p[2], { y: p[3], name: m[1], base: 'calm', far: 44, talk: ['Speak with ' + m[1], m[2], m[3]] }); np++; }
  // ---- knots of students at talk in the halls and the common rooms
  /* every hall on the ground floor has its knots of talk (the bigger the hall, the more), every common room too, and a couple on each landing above; the library reads rather than talks, so it gets few */
  let ng = 0; { const jobs = []; for (const k of HL.ALLK) { const P = HL.plan(k); for (const c of P.comps) { if (c.kind !== 'room') continue; const hallish = /^(lobby|gallery|entrance|trophy|library)$/.test(c.type || '') && !HL.WELLN[c.name], comm = c.type === 'lounge' && /COMMON|LOUNGE|CLUB/.test(c.name || ''); if (!hallish && !comm) continue; const x0 = P.X(c.R.i1 + 1), x1 = P.X(c.R.i0), z0 = P.Z(c.R.j1 + 1), z1 = P.Z(c.R.j0), ar = (x1 - x0) * (z1 - z0);
        jobs.push({ k, P, x0, x1, z0, z1, gn: comm ? 3 : c.type === 'library' ? 2 : k === 0 ? clamp(Math.round(ar / 110), 2, c.type === 'entrance' ? 7 : 5) : clamp(Math.round(ar / 220), 1, 2), pri: (k === 0 ? 0 : 10) + (comm ? 5 : 0) }); } } jobs.sort((a, b) => a.pri - b.pri);
    for (const J of jobs) { if (ng > 230) break; const { k, P, x0, x1, z0, z1 } = J; for (let g = 0; g < J.gn; g++) { const gx = lerp(x0 + 2.5, x1 - 2.5, rs()), gz = lerp(z0 + 2.5, z1 - 2.5, rs()), sp = HL.occ.spot(k, gx, gz, 1.0, 5, 4); if (!sp) continue; const n = 2 + ((rs() * 2) | 0); for (let q = 0; q < n; q++) { const an = q / n * TAU + g, t = stu(); if (!t) break; const a = HL.npc(t, sp[0] + Math.sin(an) * 0.62, sp[1] + Math.cos(an) * 0.62, an + PI, { y: P.y, base: ['talk', 'idle', 'calm'][q % 3], far: 38 }); a.x = sp[0] + Math.sin(an) * 0.62; a.z = sp[1] + Math.cos(an) * 0.62; a.yaw = an + PI; ng++; } } } }
  // ---- those standing at their work: at a cauldron in Potions, and the like
  for (const q of HL.STANDS || []) { const t = stu(); if (!t) break; const a = HL.npc(t, q[0], q[1], q[2], { y: q[3], base: ['calm', 'idle'][ng % 2], far: 30 }); a.x = q[0]; a.z = q[1]; a.yaw = q[2]; ng++; }
  // ---- memos: folded paper on the wing along the passages
  { const g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute([0, 0, 0.22, 0.13, 0.02, -0.12, 0, 0.05, -0.1, 0, 0, 0.22, 0, 0.05, -0.1, -0.13, 0.02, -0.12, 0, 0, 0.22, 0, -0.06, -0.1, 0, 0.05, -0.1], 3)); g.computeVertexNormals(); const mat = new THREE.MeshLambertMaterial({ color: 0xe8dfc4, side: THREE.DoubleSide, emissive: 0x3a3424 });
    for (const k of HL.ALLK) { const ls = lanes.filter((la) => la.k === k && !la.out && la.len > 12); if (!ls.length) continue; const n = Math.min(26, ls.length * 2), im = new THREE.InstancedMesh(g, mat, n), M2 = []; im.userData.tag = 'in' + k; im.frustumCulled = false; im.castShadow = false; for (let i = 0; i < n; i++) M2.push({ la: ls[i % ls.length], t: rs(), dir: i % 2 ? 1 : -1, v: 2.6 + rs() * 2, h: 2.3 + rs() * 1.2, ph: rs() * 6, off: (rs() - 0.5) * 1.2 }); LEVEL.add(im);
      const m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), e = new THREE.Euler(), p = new THREE.Vector3(), s = new THREE.Vector3(1, 1, 1); L.updates.push((dt, t) => { if (!im.visible) return; for (let i = 0; i < n; i++) { const m = M2[i], la = m.la; m.t += m.dir * m.v * dt / la.len; if (m.t > 1) { m.t = 1; m.dir = -1; } else if (m.t < 0) { m.t = 0; m.dir = 1; } p.set(lerp(la.a[0], la.b[0], m.t) + la.px * (m.off + Math.sin(t * 1.7 + m.ph) * 0.3), la.y + m.h + Math.sin(t * 2.3 + m.ph) * 0.25, lerp(la.a[1], la.b[1], m.t) + la.pz * (m.off + Math.sin(t * 1.7 + m.ph) * 0.3)); e.set(Math.sin(t * 2.3 + m.ph) * 0.2, la.yaw + (m.dir > 0 ? 0 : PI), Math.sin(t * 3.1 + m.ph) * 0.35); q.setFromEuler(e); m4.compose(p, q, s); im.setMatrixAt(i, m4); } im.instanceMatrix.needsUpdate = true; }); } }
  // ---- the staff at the High Table
  { const names = ['Professor Garlick', 'Professor Hecat', 'Professor Kogawa', 'Madam Scribner', 'Nurse Blainey', 'Mr Moon', 'Professor Binns’s empty chair']; (HL.STAFFSEATS || []).forEach((q, i) => { const t = i % 2 ? 'prof_a' : 'prof_b'; if (i < 6 && CHAR.T[t]) HL.npc(t, q[0], q[2], q[3], { sit: true, y: q[1], far: 70, name: names[i] }); }); }
  // ---- what people are saying as you pass: a line over the head of someone near you, now and then
  { const lines = { any: ['Have you done the Potions essay? Two rolls of parchment!', 'I heard there’s a troll in the hills past the Forest.', 'Meet me in the Library after Charms.', 'The staircase moved while I was ON it.', 'Peeves put ink in the Trophy Room cups again.', 'Is it true the kitchens are under the Great Hall?', 'I’m going to try out for Quidditch this year.', 'Don’t be late for Transfiguration; she turns latecomers’ desks into pigs.', 'Someone said there’s a Room that only appears when you need it.', 'Ten points from Slytherin. Ten! For breathing!', 'My owl hasn’t come back from Hogsmeade yet.', 'The Fat Friar told me where the Hufflepuff barrels are. I’m not telling.', 'Did you see the dragon bones in Defence? They’re real.', 'I got lost on the third floor for an hour.', 'There’s treacle tart tonight.', 'Wingardium Levi-O-sa. Not Levio-SA.', 'I swear that portrait was watching me.', 'Careful, the Bloody Baron is in a mood.', 'Honeydukes on Saturday?', 'The view from the Astronomy Tower is worth the stairs.'],
      prof: ['No running in the corridors.', 'Wands away between lessons, please.', 'I expect that essay on my desk by Friday.', 'Mind the suits of armour; they bruise easily.', 'Five points for holding the door.'] };
    const el = document.createElement('div'); el.className = 'hlBark'; el.style.cssText = 'position:absolute;left:0;top:0;transform:translate(-50%,-100%);max-width:300px;padding:6px 12px 7px;font:italic 15px/1.25 "Apple Chancery",Luminari,Georgia,serif;color:#2c1a0a;background:rgba(240,226,188,0.93);border:1px solid rgba(58,36,18,0.8);border-radius:3px 12px 3px 12px;box-shadow:0 4px 16px rgba(0,0,0,0.5);pointer-events:none;opacity:0;transition:opacity .35s;z-index:6;text-align:center'; (HL.ui.el && HL.ui.el.Hud ? HL.ui.el.Hud : document.body).appendChild(el);
    let who = null, tLeft = 0, wait = 3, nLine = 0; const v = new THREE.Vector3(); HL.SAY = { el, n: 0, who: null }; HL.LINES = lines;
    L.updates.push((dt) => { const P2 = PLAYER.a; if (!P2 || MG.state !== 'play' || HL.Q.on || (HL.SAYBOX && HL.SAYBOX.on)) { el.style.opacity = 0; who = null; wait = Math.max(wait, 3); return; }
      if (who) { tLeft -= dt; const d = Math.hypot(who.x - P2.x, who.z - P2.z); if (tLeft <= 0 || d > 13 || who.hiddenN) { who = null; HL.SAY.who = null; el.style.opacity = 0; wait = 2.5 + rs() * 4; return; } v.set(who.x, who.y + (who.sitY !== undefined ? 1.55 : 2.05), who.z).project(R.camera); if (v.z > 1 || Math.abs(v.x) > 1.05 || Math.abs(v.y) > 1.05 || (PLAYER.state === 'fly' && innerHeight < 620)) { el.style.opacity = 0; return; } let bx = (v.x * 0.5 + 0.5) * innerWidth, by = Math.min((-v.y * 0.5 + 0.5) * innerHeight, innerHeight * 0.55); if (document.body.classList.contains('touch')) { bx = Math.max(150, Math.min(bx, innerWidth - 400)); by = Math.max(by, 128); }   /* (on a phone it never lies over the spell buttons, the stick or the quest) */
        el.style.left = bx.toFixed(0) + 'px'; el.style.top = by.toFixed(0) + 'px'; el.style.opacity = 1; return; }   /* (kept above the hint lane; none in flight on a phone) */
      wait -= dt; if (wait > 0) return; wait = 0.6; let best = null, bd = 9.5; const fx = Math.sin(CAM.yaw), fz = Math.cos(CAM.yaw); for (const a of HL.npcs) { if (a.hiddenN || a.label === 'x' || (HL.ghosts || []).some((g) => g.a === a)) continue; const dx = a.x - P2.x, dz = a.z - P2.z, d = Math.hypot(dx, dz); if (d < bd && d > 1.2 && Math.abs(a.y - P2.y) < 2.5 && (dx * fx + dz * fz) / d > 0.35) { bd = d; best = a; } }
      if (!best) return; who = best; tLeft = 4.2; const isP = /Professor|Master|Mistress|Madam|Nurse|Mr /.test(best.label || ''), pool = isP ? lines.prof : lines.any; const li = Math.abs(nLine++ * 7 + Math.round(best.x)) % pool.length; el.textContent = (best.label ? best.label + ': ' : '') + '“' + pool[li] + '”'; HL.SAY.n++; HL.SAY.who = best; HL.SAY.i = li; /* …and it is spoken (p83) */ if (HL.AU && HL.AU.say) HL.AU.say(best, li, isP); }); }
  HL.LIFE = { lanes: lanes.length, walkers: HL.walkers.length, profs: np, groups: ng };
});
/* the air indoors: dust in the light, drifting. A cloud of motes that stays about the camera wherever it goes inside the castle. */
HL.START.push(function (L) { const N = 420, B = 18, pos = new Float32Array(N * 3), ph = new Float32Array(N), rs = mulberry(1212); for (let i = 0; i < N; i++) { pos[i * 3] = rs() * B; pos[i * 3 + 1] = rs() * 7; pos[i * 3 + 2] = rs() * B; ph[i] = rs() * 6.28; }
  const g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.BufferAttribute(pos, 3)); g.setAttribute('aPh', new THREE.BufferAttribute(ph, 1));
  const U = { uT: { value: 0 }, uC: { value: new THREE.Vector3() }, uK: { value: 0 }, uS: { value: 1 } };
  const m = new THREE.ShaderMaterial({ uniforms: U, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending,
    vertexShader: 'uniform float uT; uniform vec3 uC; uniform float uS; attribute float aPh; varying float vA; void main() { vec3 p = position + vec3(sin(uT * 0.11 + aPh) * 0.9, uT * 0.035 + sin(uT * 0.2 + aPh * 2.0) * 0.3, cos(uT * 0.09 + aPh * 1.3) * 0.9); vec3 c = vec3(uC.x, floor(uC.y / 7.0) * 7.0, uC.z); p.xz = mod(p.xz - c.xz + 9.0, 18.0) - 9.0 + c.xz; p.y = mod(p.y - uC.y + 3.5, 7.0) - 3.5 + uC.y; vec4 mv = modelViewMatrix * vec4(p, 1.0); float d = -mv.z; vA = smoothstep(0.6, 2.5, d) * (1.0 - smoothstep(6.0, 9.0, d)) * (0.55 + 0.45 * sin(uT * 1.7 + aPh * 5.0)); gl_PointSize = clamp(60.0 / d, 1.5, 9.0) * uS; gl_Position = projectionMatrix * mv; }',
    fragmentShader: 'uniform float uK; varying float vA; void main() { vec2 q = gl_PointCoord - 0.5; float a = (1.0 - smoothstep(0.0, 0.5, length(q))) * vA * uK; gl_FragColor = vec4(vec3(1.0, 0.86, 0.6) * a * 0.9, a); }' });
  const pts = new THREE.Points(g, m); pts.frustumCulled = false; pts.renderOrder = 4; LEVEL.add(pts); HL.MOTES = pts;
  L.updates.push((dt, t) => { const a = PLAYER.a, c = R.camera.position; U.uT.value = t; U.uC.value.copy(c); U.uS.value = Math.min(1.3, (R.h || 720) / 720);   /* (in the frame's own pixels: at a phone's lower render scale the motes read as snow) */ const inside = !!a && a.y > HL.Y0 - 9 && HL.inFoot(c.x, c.z, 0) && !!HL.zoneAt(a.x, a.y + 1, a.z); U.uK.value = damp(U.uK.value, inside ? 1 : 0, 2.5, dt); pts.visible = U.uK.value > 0.01; }); });
