/* ==== p78k_hl_duel.js ==== */
/* HOGWARTS — Crossed Wands. The duelling club meets under the pendulum in the Clock Tower hall, the first room you walk
   into: a ring inlaid in the floor, the club gathered along the walls, Lucan Brattleby keeping the ladder. Three rounds
   against other students — one, then two, then two and the reigning champion behind a ward — fought with everything
   the player's wand can do. Nobody dies of it: the loser is Stupefied and carried off. */
HL.duel = { on: false, round: 0, foes: [], arena: null, t: 0, phase: '',
  ROUNDS: [
    { n: 'The First Round', who: [['hufflepuff', 0, 'Arthur Plummly', 190, 'duelHex']], pts: 10, line: 'One on one. Bow, then wands up — and do try not to break a window.' },
    { n: 'The Second Round', who: [['ravenclaw', 1, 'Constance Dagworth', 170, 'duelHex'], ['slytherin', 0, 'Hector Fawley', 180, 'duelHex']], pts: 20, line: 'Two at once. Keep moving, and put up Protego (right mouse) when you see a wand glow.' },
    { n: 'The Final', who: [['gryffindor', 1, 'Nerida Roberts', 190, 'duelHex'], ['ravenclaw', 0, 'Lawrence Crickett', 190, 'duelFire'], ['slytherin', 1, 'Imelda Reyes-Burke, the champion', 340, 'duelFire', 'force']], pts: 50, line: 'The champion fights behind a violet ward. A force spell breaks it: Accio (2) or Depulso (3).' } ] };
Object.assign(HL.SPELLS, { duelHex: { name: 'Stupefy', col: [1.0, 0.2, 0.12], dmg: 9, speed: 24, size: 0.2 }, duelFire: { name: 'Incendio', col: [1.0, 0.45, 0.08], dmg: 13, speed: 22, size: 0.3, kind: 'fire' } });
HL.START.push(function (L) { const D = HL.duel, P = HL.plan(0), c = P.comps.find((q) => q.name === 'THE CLOCK TOWER'); if (!c || !HL.STUDENTS) return; const Y = P.y;
  const x0 = P.X(c.R.i1 + 1), x1 = P.X(c.R.i0), z0 = P.Z(c.R.j1 + 1), z1 = P.Z(c.R.j0), cx = (x0 + x1) / 2, cz = (z0 + z1) / 2, A = D.arena = { x0: x0 + 1.9, x1: x1 - 1.9, z0: z0 + 2.2, z1: z1 - 2.2, y: Y, cx, cz };
  // ---- the ring in the floor: two gilt circles, the points of the compass, crossed wands at the centre (drawn; laid a hair over the flags and the carpet)
  { const N = 1024, cv = document.createElement('canvas'); cv.width = cv.height = N; const q = cv.getContext('2d'), h = N / 2; q.clearRect(0, 0, N, N); q.translate(h, h);
    const ring = (r, w, col) => { q.strokeStyle = col; q.lineWidth = w; q.beginPath(); q.arc(0, 0, r, 0, TAU); q.stroke(); };
    q.fillStyle = 'rgba(24,16,10,0.34)'; q.beginPath(); q.arc(0, 0, h * 0.97, 0, TAU); q.fill(); q.strokeStyle = 'rgba(30,20,12,0.92)'; q.lineWidth = h * 0.085; q.beginPath(); q.arc(0, 0, h * 0.925, 0, TAU); q.stroke(); q.strokeStyle = 'rgba(30,20,12,0.8)'; q.lineWidth = h * 0.07; q.beginPath(); q.arc(0, 0, h * 0.655, 0, TAU); q.stroke();
    ring(h * 0.96, 10, 'rgba(214,170,74,0.95)'); ring(h * 0.90, 3, 'rgba(214,170,74,0.8)'); ring(h * 0.60, 3, 'rgba(214,170,74,0.6)'); ring(h * 0.22, 6, 'rgba(214,170,74,0.9)');
    for (let i = 0; i < 24; i++) { q.save(); q.rotate(i / 24 * TAU); q.fillStyle = 'rgba(214,170,74,' + (i % 6 === 0 ? 0.95 : 0.6) + ')'; q.beginPath(); q.moveTo(0, -h * 0.90); q.lineTo(i % 6 === 0 ? 14 : 6, -h * (i % 6 === 0 ? 0.74 : 0.82)); q.lineTo(i % 6 === 0 ? -14 : -6, -h * (i % 6 === 0 ? 0.74 : 0.82)); q.closePath(); q.fill(); q.restore(); }
    q.font = 'bold 34px Georgia'; q.textAlign = 'center'; q.fillStyle = 'rgba(236,196,96,0.98)'; const txt = 'CROSSED  WANDS  ·  HOGWARTS  DUELLING  CLUB  ·  '; for (let i = 0; i < txt.length; i++) { q.save(); q.rotate(i / txt.length * TAU); q.fillText(txt[i], 0, -h * 0.655); q.restore(); }
    for (const s of [-1, 1]) { q.save(); q.rotate(s * 0.62); q.fillStyle = 'rgba(232,196,110,0.95)'; q.fillRect(-5, -h * 0.19, 10, h * 0.38); q.fillStyle = 'rgba(120,70,30,0.95)'; q.fillRect(-7, h * 0.07, 14, h * 0.12); q.restore(); }
    const tx = new THREE.CanvasTexture(cv); tx.colorSpace = THREE.SRGBColorSpace; tx.anisotropy = 8; const R0 = Math.min(A.x1 - A.x0, A.z1 - A.z0) / 2 + 0.6, g = new THREE.CircleGeometry(R0, 64); g.rotateX(-HALF);
    const m = new THREE.Mesh(g, new THREE.MeshStandardMaterial({ map: tx, transparent: true, roughness: 0.5, metalness: 0.6, polygonOffset: true, polygonOffsetFactor: -3, polygonOffsetUnits: -3, depthWrite: false })); m.position.set(cx, Y + 0.03, cz); m.renderOrder = 2; m.receiveShadow = true; m.userData.tag = 'in0'; LEVEL.add(m); D.ring = m; D.R0 = R0; }
  // ---- the club along the walls, and Lucan by the north door with the ladder board
  const N = HL.STUDENTS, spots = []; for (const sx of [-1, 1]) for (let t = 0.14; t < 0.9; t += 0.19) spots.push([sx < 0 ? x0 + 1.0 : x1 - 1.0, lerp(z0 + 2, z1 - 2, t), sx < 0 ? HALF : -HALF]);
  D.crowd = []; spots.forEach((s, i) => { const sp = HL.occ.spot(0, s[0], s[1], 0.35, 2.5, 4); if (!sp || !CHAR.T[N[i % N.length]]) return; for (let q = 0; q < (i % 3 === 0 ? 1 : 2); q++) { const px = sp[0] + (q ? 0.0 : 0), pz = sp[1] + q * 0.75, a = HL.npc(N[(i * 3 + q * 5) % N.length], px, pz, s[2] + (q ? -0.25 : 0.2), { y: Y, base: ['idle', 'talk', 'calm'][(i + q) % 3], far: 40 }); a.x = px; a.z = pz; a.turn = false; a.clubFar = 6.5; D.crowd.push(a); } });
  const lu = HL.occ.spot(0, x0 + 2.6, z1 - 2.4, 0.4, 3, 4) || [x0 + 2.6, z1 - 2.4], lt = CHAR.T.wiz_gryffindor_m2 ? 'wiz_gryffindor_m2' : N[1]; D.lucan = HL.npc(lt, lu[0], lu[1], PI * 0.85, { y: Y, name: 'Lucan Brattleby', base: 'talk', far: 60 }); D.lucan.x = lu[0]; D.lucan.z = lu[1];
  D.use = HL.interact([lu[0], Y + 1.2, lu[1]], 3.2, 'Speak with Lucan Brattleby  (Crossed Wands)', () => D.ask());
  /* a gold mark turns over his head while he has a bout to offer */ { const mk = HL.sprite([1.9, 1.35, 0.3], 1.2, 0.42); mk.position.set(lu[0], Y + 2.45, lu[1]); mk.userData.tag = 'in0'; LEVEL.add(mk); L.updates.push((dt, t) => { mk.position.y = Y + 2.45 + Math.sin(t * 2.4) * 0.07; mk.material.opacity = D.on ? 0 : 0.75 + 0.25 * Math.sin(t * 3.1); }); }
  // ---- two of the club at practice across the ring whenever nobody is fighting for the ladder: a spell, a shield or a stagger, and the other's turn
  { const mk = (tpl, x, z, yaw) => { const a = HL.npc(tpl, x, z, yaw, { y: Y, base: 'aim', far: 60 }); a.x = x; a.z = z; a.yaw = yaw; a.noProxy = true; const i = HL.npcs.indexOf(a); if (i >= 0) HL.npcs.splice(i, 1); a.wand = HL.wand(0x2a1c12); R.scene.add(a.wand); HL.occ.mark(0, x, z, 0.35, 0.35, 0, 4); return a; };
    const pair = D.spar = [mk(N[2 % N.length], cx - 3.7, cz + 0.4, HALF), mk(N[7 % N.length], cx + 3.7, cz + 0.4, -HALF)], spr = HL.sprite([1, 0.3, 0.2], 2.2, 0.55); spr.visible = false; R.scene.add(spr); let st = 2, turn = 0, bolt = null;
    L.updates.push((dt) => { const Pp = PLAYER.a, on = !D.on && !!Pp && Math.hypot(Pp.x - cx, Pp.z - cz) < 44 && Math.abs(Pp.y - Y) < 7;
      for (const s2 of pair) if (s2.root.visible !== on) { s2.root.visible = on; s2.wand.visible = on; if (s2.inst.cloth) s2.inst.cloth.setVisible(on); } if (!on) { spr.visible = false; bolt = null; return; }
      for (const s2 of pair) { s2.y = Y; s2.grounded = true; s2.speed = 0; s2.animate(dt); s2.pose3D(dt); HL.placeWand(s2, dt); }
      st -= dt; if (st <= 0 && !bolt) { const A2 = pair[turn], B2 = pair[1 - turn], col = [[1.0, 0.25, 0.15], [0.4, 0.7, 1.0], [1.0, 0.8, 0.2]][(RNG() * 3) | 0]; A2.play('cast1', { fade: 0.06 }); st = 1.5 + RNG() * 1.7; turn = 1 - turn;
        MG.after(0.14, () => { if (D.on || !A2.root.visible) return; const p0 = HL.wandTip(A2, new THREE.Vector3()), p1 = B2.chest(new THREE.Vector3()); bolt = { p0, p1, t: 0, B: B2, col, block: RNG() < 0.5 }; spr.material.color.setRGB(col[0] * 2.4, col[1] * 2.4, col[2] * 2.4); spr.position.copy(p0); spr.visible = true; FX.flashLight(p0, col, 4, 5, 0.12); }); }
      if (bolt) { bolt.t += dt / 0.28; if (bolt.t >= 1) { spr.visible = false; FX.spark(bolt.p1, null, bolt.block ? 22 : 12, bolt.block ? 6 : 4, bolt.block ? [1.5, 2.5, 5] : [bolt.col[0] * 3, bolt.col[1] * 3, bolt.col[2] * 3], 0.3); if (bolt.block) FX.flashLight(bolt.p1, [0.5, 0.9, 1.8], 5, 5, 0.15); else bolt.B.play('hit', { fade: 0.06 }); bolt = null; } else spr.position.lerpVectors(bolt.p0, bolt.p1, bolt.t); } }); }
  // ---- the ladder: who you fight next, kept on the HUD while a bout is on
  const el = document.createElement('div'); el.id = 'hlDuel'; el.style.cssText = 'position:absolute;left:50%;top:22px;transform:translateX(-50%);min-width:340px;padding:8px 18px 10px;text-align:center;color:#f0e2c0;font-family:HLA,Georgia,serif;text-shadow:0 1px 4px #000;background:linear-gradient(rgba(20,14,8,0.72),rgba(20,14,8,0.5));border:1px solid rgba(214,170,74,0.55);border-radius:3px;display:none;pointer-events:none;z-index:5'; (HL.ui.el.Hud || document.body).appendChild(el); D.el = el;
  const p0 = PLAYER.die; PLAYER.die = function () { if (D.on) return D.lose(); return p0.apply(this, arguments); };
  const f0 = HL.onFoeDown; HL.onFoeDown = function (f) { if (f.duel) { HL.store(); return; } return f0(f); };
  D.next = () => Math.min(D.ROUNDS.length, HL.save.duel || 0);   // rounds won so far = the index of the next
  D.ask = function () { if (D.on) return; const n = D.next(), R2 = D.ROUNDS[Math.min(n, D.ROUNDS.length - 1)]; (HL.save.met = HL.save.met || {})['Lucan Brattleby'] = 1; if (MG.rt < (D.armT || 0)) { D.armT = 0; return D.start(Math.min(n, D.ROUNDS.length - 1)); }
    D.armT = MG.rt + 9; (HL.ui.say || HL.ui.toast)('Lucan Brattleby', n >= D.ROUNDS.length ? 'Our champion! The ring is always open to you — press E again and I will find you three who fancy their chances.' : (n === 0 ? 'Welcome to Crossed Wands — duelling, strictly unofficial. ' : 'Back for more? ') + R2.n + ': ' + R2.line + '  Press E again to step into the ring.', 9, D.lucan, 'E — STEP INTO THE RING'); };
  D.start = function (r) { const R2 = D.ROUNDS[r], a = PLAYER.a; if (!a || D.on) return; D.on = true; D.round = r; D.phase = 'bow'; D.t = 0; D.foes = []; HL.ui.fade(1);
    D.held = (HL.walkers || []).filter((w) => w.a.x > x0 - 1 && w.a.x < x1 + 1 && w.a.z > z0 - 1 && w.a.z < z1 + 1 && Math.abs(w.a.y - Y) < 2); for (const w of D.held) { w._fd = w.a.farD; w.a.farD = 0; w._pz = w.pause; w.pause = 1e9; }
    MG.after(0.45, () => { a.x = cx; a.z = A.z0 + 1.2; a.y = Y + 0.05; a.vx = a.vy = a.vz = 0; a.yaw = 0; a.hp = a.hpMax; CAM.yaw = 0; CAM.pitch = 0.12; CAM.snap = true; if (PLAYER.state === 'fly' && HL.fly && HL.fly.dismount) HL.fly.dismount(true); if (a.inst.cloth && a.inst.cloth.reset) a.inst.cloth.reset();
      R2.who.forEach((w, i) => { const key = 'duel_' + r + '_' + i, tpl = HL.student(w[0], !!w[1], 1 + ((i + r) % 3)), use = CHAR.T[tpl] ? tpl : N[(i * 5 + r) % N.length]; HL.FOE[key] = { tpl: use, name: w[2], hp: w[3], cd: [1.3, 2.3], spell: w[4], ward: w[5], pts: 0, want: 7.5, gap: 0.85, poise: true };
        const fx = cx + (i - (R2.who.length - 1) / 2) * 3.2, fz = A.z1 - 1.4, f = new HLFoe(key, fx, fz, { y: Y + 0.05, yaw: PI, base: 'fold' }); f.duel = true; f.alertT = -2.6; f.home = [cx, cz]; f.mark = HL.sprite([1.7, 0.22, 0.12], 1.3, 0.3); f.mark.position.set(fx, Y + 2.3, fz); R.scene.add(f.mark); D.foes.push(f); });
      HL.ui.fade(0); HL.ui.toast('CROSSED WANDS — ' + R2.n.toUpperCase(), R2.line, 5); D.show(); }, true); };
  D.show = function () { const R2 = D.ROUNDS[D.round]; el.style.display = D.on ? 'block' : 'none'; if (!D.on) return; el.innerHTML = '<div style="font-size:12px;letter-spacing:.3em;color:#d6aa4a">CROSSED WANDS · ' + R2.n.toUpperCase() + '</div>' + D.foes.map((f) => '<div style="margin-top:6px;font-size:15px;letter-spacing:.04em;opacity:' + (f.alive ? 1 : 0.45) + '">' + f.label + '<div style="height:6px;margin-top:3px;background:rgba(0,0,0,0.55);border:1px solid rgba(214,170,74,0.5)"><div style="height:100%;width:' + Math.max(0, Math.round(f.hp / f.hpMax * 100)) + '%;background:linear-gradient(#e0523a,#8e1c1c)"></div></div></div>').join(''); };
  D.finish = function () { D.on = false; D.phase = ''; el.style.display = 'none'; for (const f of D.foes) if (f.mark) { if (f.mark.parent) f.mark.parent.remove(f.mark); f.mark = null; } for (const w of D.held || []) { w.a.farD = w._fd; w.pause = 0; } D.held = []; };
  D.win = function () { const r = D.round, R2 = D.ROUNDS[r], first = (HL.save.duel || 0) <= r; if (first) { HL.save.duel = r + 1; HL.save.points = (HL.save.points || 0) + R2.pts; } HL.store(); D.finish();
    HL.ui.pop(first ? '+' + R2.pts + ' HOUSE POINTS' : 'WELL FOUGHT'); if (first && r === D.ROUNDS.length - 1 && HL.LOOT && HL.LOOT.make) { try { HL.LOOT.give(HL.LOOT.make({ slot: 'wand', r: 3, il: 12 }), true); MG.after(6.2, () => HL.ui.toast('THE CHAMPION’S PRIZE', 'Lucan presses a wand handle into your palm — look in your pack (I).', 6), true); } catch (e) { /* no loot table: the title is prize enough */ } } HL.ui.toast(r === D.ROUNDS.length - 1 ? 'CROSSED WANDS CHAMPION' : R2.n.toUpperCase() + ' — WON', r === D.ROUNDS.length - 1 ? 'The club is on its feet. Lucan chalks your name at the top of the ladder.' : 'Lucan: “Neatly done. ' + D.ROUNDS[r + 1].n + ' is yours whenever you like.”', 6); FX.spark(V3(cx, Y + 2.2, cz), null, 60, 9, [3, 2.2, 0.6], 1.0); };
  D.lose = function () { const a = PLAYER.a; D.phase = 'lost'; HL.ui.fade(1); D.finish(); for (const f of D.foes) if (!f.gone) f.remove(); D.foes = []; MG.after(0.6, () => { a.alive = true; a.hp = a.hpMax; a.vx = a.vy = a.vz = 0; a.x = lu[0] + 1.4; a.z = lu[1] - 1.2; a.y = Y + 0.05; a.stop && a.stop(0.01); PLAYER.state = 'move'; HL.P.pending = null; CAM.snap = true; HL.ui.fade(0); (HL.ui.say || HL.ui.toast)('Lucan Brattleby', 'Ennervate! … There you are. Bested, but nobody wins their first. The ring is here when you want it.', 6, D.lucan); }, true); };
  L.updates.push((dt) => { if (!D.on) return; const a = PLAYER.a; D.t += dt; /* whisked away mid-bout (the Floo, a fall): the bout is off */ if (a && D.phase !== 'bow' && (Math.hypot(a.x - cx, a.z - cz) > 40 || Math.abs(a.y - Y) > 6)) { D.finish(); for (const f of D.foes) if (!f.gone) f.remove(); D.foes = []; return; } const cl = (o) => { if (o.x < A.x0) { o.x = A.x0; o.vx = Math.max(0, o.vx); } else if (o.x > A.x1) { o.x = A.x1; o.vx = Math.min(0, o.vx); } if (o.z < A.z0) { o.z = A.z0; o.vz = Math.max(0, o.vz); } else if (o.z > A.z1) { o.z = A.z1; o.vz = Math.min(0, o.vz); } };
    /* a duellist answers a battering with Protego: a blue-white shield nothing gets through, held for a breath, then down again */
    if (D.phase === 'fight') for (const f of D.foes) { if (!f.alive || f.gone) continue; if (f._hp0 === undefined) { f._hp0 = f.hp; f.gT = 2 + RNG() * 2; } f.gT -= dt;
      if (f.ward === 'guard') { f.gOn -= dt; if (f.gOn <= 0) { f.ward = null; f._hp0 = f.hp; f.gT = 2.6 + RNG() * 2.2; } }
      else if (!f.ward && f.gT <= 0 && f._hp0 - f.hp > 22 && !(HL.st(f).freeze > 0) && !(HL.st(f).lift > 0)) { if (!f.wardMesh) f.setWard('guard'); f.ward = 'guard'; f.gOn = 1.25; f.wardMesh.material.uniforms.uCol.value.setRGB(0.5, 0.95, 1.9); f.wardMesh.material.uniforms.uHit.value = 1; f.play && f.play('cast1', { fade: 0.08 }); } }
    if (a && a.alive) cl(a); for (const f of D.foes) { if (f.alive && !f.gone) cl(f); if (f.mark) { f.mark.visible = f.alive && !f.gone; f.mark.position.set(f.x, f.y + 2.28 + Math.sin(MG.t * 3 + f.x) * 0.05, f.z); } } if (!(MG.frame % 6)) D.show();
    if (D.phase === 'bow' && D.foes.length && D.t > 3) D.phase = 'fight';
    if (D.phase === 'fight' && D.foes.length && D.foes.every((f) => !f.alive)) { D.phase = 'won'; D.t = 0; } if (D.phase === 'won' && D.t > 1.6) D.win(); });
});
