/* ==== p78l_hl_journal.js ==== */
/* HOGWARTS — the quest journal (J). The story is the line of errands the castle walks you through; beside it run the
   side quests, each taken up from someone in the castle or stumbled into, each with its own steps. The journal is an
   open book: quests down the left-hand page, the chosen one written out on the right — who asked, what for, what is
   done and what is left, what it earns. A side quest can be followed (its step takes the place of the story's on
   the HUD, and its marker on the compass). */
HL.STORY = {
  lock: ['PROLOGUE', 'Professor Fig', 'A chest sits by the parapet where the carriages set you down, its lock charmed shut. “First lesson,” says Professor Fig. “A lock like this wants the right spells in the right order. Watch the runes; answer them.”'],
  arrive: ['PROLOGUE', 'Professor Fig', 'The long bridge runs north to the Clock Tower, and under the clock its great doors stand open. Every first-year remembers this walk. So will you.'],
  hall: ['CHAPTER I · THE SORTING FEAST', 'The Deputy Headmistress', 'The feast has begun without you. Through the Clock Tower and the South Hall, up the Long Gallery — follow the noise of four hundred people at supper — to the Great Hall, where the candles hang in the air and the ceiling is the sky.'],
  kitchens: ['CHAPTER I · THE SORTING FEAST', 'The Fat Friar', '“All that food comes from somewhere, you know.” Below the Great Hall, down the stair from the Reception Hall, the kitchens fill a vault as large as the hall above them. The house-elves like visitors who are polite.'],
  bout: ['CHAPTER II · A PROPER EDUCATION', 'Lucan Brattleby', 'Straw men do not hit back. Under the pendulum in the Clock Tower a fifth-year called Lucan Brattleby runs a duelling club the professors pretend not to know about. “Crossed Wands. One round. If you can stand at the end of it, you are in.”'],
  duel: ['CHAPTER II · A PROPER EDUCATION', 'Professor Hecat', 'Defence Against the Dark Arts begins in the Viaduct Courtyard with a row of straw men. “I do not care how you were taught before. Hit it. Again. Now with something that is not the basic cast.”'],
  'class': ['CHAPTER II · A PROPER EDUCATION', 'Madam Scribner', 'Across the Viaduct Bridge the Library climbs four storeys in shelves. Somewhere beyond its reading tables a rope hangs across a doorway: the Restricted Section. Madam Scribner is watching you look at it.'],
  ward: ['CHAPTER II · A PROPER EDUCATION', 'Nurse Blainey', 'The Grand Staircase turns as it pleases and lets you off where it likes. The Hospital Wing is high over the South Hall; learn the way now, while you can still walk it.'],
  climb: ['CHAPTER III · YOUR HOUSE', 'Your prefect', 'Every house keeps its door a secret from the other three. Yours has been told to expect you. Find your common room — the fire will be lit.'],
  head: ['CHAPTER III · YOUR HOUSE', 'Professor Weasley', 'The Headmaster’s Office sits at the very top of the Faculty Tower, behind a griffin that pretends not to see students. You have been sent for. Nobody will say why.'],
  tour: ['CHAPTER III · YOUR HOUSE', 'The castle', 'Hogwarts has a hundred and forty-two staircases and more rooms than anyone has counted. Learn it: the wings, the towers, the courts. The map (M) inks in each place as you find it.'],
  rings: ['CHAPTER IV · THE HOUSE CUP', 'Madam Kogawa', 'Flying class. A course of rings hangs over the lake and the lawns. “Through every one, in order. I will be timing you, and I will be honest about it.”'],
  hut: ['CHAPTER IV · THE HOUSE CUP', 'The gamekeeper', 'Down past the lawns, where the Forbidden Forest begins, there is a round stone hut with a light in its window. Knock. Something has been troubling the forest and its keeper wants a word.'],
  match: ['CHAPTER IV · THE HOUSE CUP', 'Madam Kogawa', 'Quidditch. Seven a side, four balls, three hoops, one Snitch. Your house needs a win and the pitch gate is open.'],
  camp: ['CHAPTER V · TROUBLE IN THE FOREST', 'The gamekeeper', 'Poachers have pitched a camp among the old trees — snares, cages, a fire that should not be there. Four of them. They will not leave because they are asked.'],
  mage: ['CHAPTER V · TROUBLE IN THE FOREST', 'The gamekeeper', 'The poachers answered to someone. He waits at the standing stones behind a ward the colour of a bruise; ordinary spells slide off it. Force breaks force.'],
  troll: ['CHAPTER V · TROUBLE IN THE FOREST', 'The gamekeeper', 'What the Dark Wizard was baiting is awake now, and it is very large. Keep moving. Use everything.'],
  free: ['EPILOGUE', '', 'The term goes on. The castle is yours to roam: pages to find, chests to open, a ladder to climb at Crossed Wands, a pitch that is always open.'] };
HL.SIDE = [
  { id: 'crossed', t: 'Crossed Wands', giver: 'Lucan Brattleby', where: 'the Clock Tower', pts: 25, desc: 'Under the pendulum in the Clock Tower the duelling club meets, strictly unofficially. Lucan Brattleby keeps the ladder. Three rounds stand between you and the top of it — and the champion fights behind a ward.',
    open: () => !!(HL.save.met && HL.save.met['Lucan Brattleby']) || (HL.save.duel || 0) > 0, hint: 'They say a duelling club meets in the Clock Tower hall. Ask for Lucan Brattleby.',
    steps: [['Win the first round (one opponent)', () => (HL.save.duel || 0) >= 1], ['Win the second round (two at once)', () => (HL.save.duel || 0) >= 2], ['Win the final and take the champion’s place', () => (HL.save.duel || 0) >= 3]], way: () => HL.duel && HL.duel.lucan ? [HL.duel.lucan.x, HL.Y0 + 1.6, HL.duel.lucan.z] : null },
  { id: 'pages', t: 'The Field Guide', giver: 'Madam Scribner', where: 'the Library', pts: 30, desc: 'Leaves of the Wizard’s Field Guide have worked loose and drifted all over the castle and its grounds, each one turning in the air where it came to rest. The librarian would like them back before somebody reads them.',
    open: () => HL.SECRETS.some((s) => s.got), hint: 'Glowing pages turn in the air here and there about the castle. Walk through one.',
    steps: [[() => 'Gather five pages  ' + Math.min(5, HL.SECRETS.filter((s) => s.got).length) + ' / 5', () => HL.SECRETS.filter((s) => s.got).length >= 5], [() => 'Gather twelve pages  ' + Math.min(12, HL.SECRETS.filter((s) => s.got).length) + ' / 12', () => HL.SECRETS.filter((s) => s.got).length >= Math.min(12, HL.SECRETS.length)]] },
  { id: 'locks', t: 'Charmed Locks', giver: 'Professor Ronen', where: 'the Charms Classroom', pts: 30, desc: '“A charmed lock is a conversation,” says Professor Ronen. “It tells you what it wants. You answer, in order, and it opens.” There are locked chests in every wing of the castle and several beneath it.',
    open: () => (HL.LOOT.chests || []).filter((c) => c.open).length >= 2, hint: 'Locked chests stand about the castle. Open a couple and someone will take an interest.',
    steps: [[() => 'Open four chests  ' + Math.min(4, (HL.LOOT.chests || []).filter((c) => c.open).length) + ' / 4', () => (HL.LOOT.chests || []).filter((c) => c.open).length >= 4], [() => 'Open nine chests  ' + Math.min(9, (HL.LOOT.chests || []).filter((c) => c.open).length) + ' / 9', () => (HL.LOOT.chests || []).filter((c) => c.open).length >= Math.min(9, (HL.LOOT.chests || []).length)]] },
  { id: 'ghosts', t: 'A Word with the Dead', giver: 'Nearly Headless Nick', where: 'the castle', pts: 20, desc: 'Each house has its ghost, and each ghost has been here longer than the paintings. They know where everything is. They will tell you, at length.',
    open: () => HL.jMet(/Nick|Friar|Baron|Grey Lady/) >= 1, hint: 'The house ghosts drift about the castle. Speak with one.',
    steps: [[() => 'Speak with the four house ghosts  ' + HL.jMet(/Nick|Friar|Baron|Grey Lady/) + ' / 4', () => HL.jMet(/Nick|Friar|Baron|Grey Lady/) >= 4]] },
  { id: 'faculty', t: 'Meet the Faculty', giver: 'Professor Weasley', where: 'the classrooms', pts: 25, desc: 'A professor stands before every class in the castle. The Deputy Headmistress expects you to have introduced yourself to all of them by the end of the week, and she will know if you have not.',
    open: () => HL.jMet(/Professor/) >= 1, hint: 'Speak with a professor in any classroom.',
    steps: [[() => 'Speak with three professors  ' + Math.min(3, HL.jMet(/Professor/)) + ' / 3', () => HL.jMet(/Professor/) >= 3], [() => 'Speak with eight professors  ' + Math.min(8, HL.jMet(/Professor/)) + ' / 8', () => HL.jMet(/Professor/) >= 8]] },
  { id: 'depths', t: 'From Cellar to Rafters', giver: 'The Bloody Baron', where: 'every floor', pts: 30, desc: '“The staircase climbs five storeys, and the castle goes down as far again,” says the Baron. See all of it: the dungeons under the Great Hall, and every floor above the ground.',
    open: () => Object.keys(HL.save.floors || {}).length >= 2, hint: 'Climb the Grand Staircase, or take the stair down from the Reception Hall.',
    steps: [[() => 'Set foot in the dungeons and on all five floors  ' + Object.keys(HL.save.floors || {}).length + ' / 6', () => Object.keys(HL.save.floors || {}).length >= 6]] },
  { id: 'houses', t: 'The Four Common Rooms', giver: 'Peeves', where: 'towers and dungeons', pts: 40, desc: 'Peeves says nobody has ever stood in all four common rooms in one term, and that anybody who tried would be caught. Gryffindor and Ravenclaw are high in their towers; Slytherin is under the lake; Hufflepuff is by the kitchens.',
    open: () => HL.jSeen(/COMMON ROOM/) >= 1, hint: 'Find any house’s common room.',
    steps: [[() => 'Stand in all four common rooms  ' + HL.jSeen(/COMMON ROOM/) + ' / 4', () => HL.jSeen(/COMMON ROOM/) >= 4]] },
  { id: 'weekend', t: 'A Hogsmeade Weekend', giver: 'Sirona Ryan', where: 'Hogsmeade', pts: 30, desc: 'Third-years and above may visit the village, and everybody does. The Three Broomsticks on the square for a Butterbeer; Honeydukes behind it for everything your teeth should not have; a high street of shopkeepers who have been waiting all term for someone to talk to; and down in the cutting behind the sweet shop, the scarlet engine that brought everyone here, still in steam.',
    open: () => HL.jMet(/Sirona|Flume|Zonko|Ollivander|Spintwitch|Gladrag|Tome|Banges|barman/) >= 1 || !!(HL.save.seen && Object.keys(HL.save.seen).some((k) => /BROOMSTICKS|HONEYDUKES/.test(k))), hint: 'South over the long bridge and along the road: Hogsmeade. There is a pub on the square. (The Floo flames will take you, too.)',
    steps: [['Order a Butterbeer from Sirona at the bar of the Three Broomsticks', () => !!(HL.save.met && HL.save.met['Sirona Ryan'])], ['Speak with Mr Flume in Honeydukes, at the back of the square', () => !!(HL.save.met && HL.save.met['Mr Flume'])], [() => 'Pass the time of day with three more shopkeepers along the high street  ' + Math.min(3, HL.jMet(/Zonko|Ollivander|Spintwitch|Gladrag|Tome|Banges|barman/)) + ' / 3', () => HL.jMet(/Zonko|Ollivander|Spintwitch|Gladrag|Tome|Banges|barman/) >= 3], ['Walk down to the station behind Honeydukes and look over the Hogwarts Express (speak to the Guard at the first carriage)', () => !!(HL.save.met && HL.save.met['The Guard'])]], way: () => HL.TB ? [HL.TB.door[0], HL.TB.y + 2, HL.TB.door[2]] : null },
  { id: 'quidditch', t: 'For the House', giver: 'Madam Kogawa', where: 'the Quidditch pitch', pts: 40, desc: 'Seven a side, four balls, three hoops and a stadium that has not been quiet since 1163. Madam Kogawa keeps the gate. Your house keeps score.',
    open: () => !!HL.save.qPlayed || (HL.save.qWon || 0) > 0 || !!(HL.save.best && HL.save.best.q), hint: 'Quidditch is played on the pitch east of the castle — or straight from the title screen.',
    steps: [['Play a match of Quidditch to the final whistle', () => !!HL.save.qPlayed || (HL.save.qWon || 0) > 0 || !!(HL.save.best && HL.save.best.q)], ['Win a match for your house', () => (HL.save.qWon || 0) >= 1], [() => 'Win three  ' + Math.min(3, HL.save.qWon || 0) + ' / 3', () => (HL.save.qWon || 0) >= 3]], way: () => HL.Q && HL.Q.REF ? [HL.Q.REF[0], HL.Q.Y0 + 2, HL.Q.REF[2]] : null },
  { id: 'sky', t: 'The Top of the World', giver: 'Professor Shah', where: 'the Astronomy Tower', pts: 20, desc: 'The Astronomy Tower is the highest point of the castle, and round its head runs an observation deck of telescopes and brass. Professor Shah holds that nobody understands Hogwarts until they have looked down on it. Thirty-two flights, or a broom.',
    open: () => !!HL.save.flown, hint: 'Take to the air (B) outdoors.',
    steps: [['Stand among the telescopes on the observation deck at the head of the Astronomy Tower — climb the stair that goes up out of the Astronomy classroom (third floor, north-west), or fly', () => !!HL.save.deck]], way: () => HL.DECK ? [HL.DECK[0], HL.DECK[1] + 2, HL.DECK[2]] : null } ];
HL.jMet = (re) => Object.keys(HL.save.met || {}).filter((k) => re.test(k)).length;
HL.jSeen = (re) => Object.keys(HL.save.seen || {}).filter((k) => re.test(k)).length;
HL.J = { sel: null, track: null,
  st: (q) => { const S = HL.save.sq = HL.save.sq || {}; return S[q.id] || (S[q.id] = { s: 0, i: 0 }); },   // s: 0 not yet taken up, 1 under way, 2 done
  main: () => HL.QUESTS.map((q, i) => ({ q, i, state: i < HL.quest.i ? 2 : i === HL.quest.i ? 1 : 0 })),
  stepText: (s) => typeof s[0] === 'function' ? s[0]() : s[0] };
Object.assign(IN.ACT, { journal: { k: ['KeyJ'], p: 88 } });
HL.START.push(function (L) { const J = HL.J; let t = 0;
  /* side quests are taken up when their door is found, step on when a step is met, and pay when the last is */
  L.updates.push((dt) => { const a = PLAYER.a; if (HL.Q.on || HL.Q.loading) { IN.take('journal'); return; } if (IN.take('journal')) J.open(); if (!a) return; t -= dt; if (t > 0) return; t = 0.5;
    /* the story's first arrival: walking into the Sorting Feast gets a moment of its own */
    { const cur = HL.quest.cur().id; if (J._last === 'hall' && cur !== 'hall' && !MG.flags.test) { const hs = Object.keys(HL.HOUSES), hi = Math.max(0, hs.indexOf(HL.save.house || HL.house)), H2 = HL.HOUSES[hs[hi]], G2 = HL.GHR; MG.after(5.5, () => HL.ui.toast('THE SORTING FEAST', 'Four hundred faces turn. Somewhere down the hall a fork is dropped.', 4.5), true);
        MG.after(10.5, () => HL.ui.toast('The Headmaster', '“Late. But here. Sit with ' + H2.name + ' — and let us have no more interruptions before the pudding.”', 6.5), true);
        MG.after(17.5, () => { HL.ui.toast(H2.name.toUpperCase(), 'Your table makes room for you. The candles overhead burn a little brighter.', 5.5); if (G2) for (let q = 0; q < 5; q++) FX.spark(V3((G2.x0 + G2.x1) / 2 + [-12.4, -4.3, 4.3, 12.4][hi], HL.Y0 + 3.2, lerp(G2.z0 + 18, G2.z1 - 6, q / 4)), null, 26, 5, [new THREE.Color(H2.col).r * 4 + 0.6, new THREE.Color(H2.col).g * 4 + 0.5, new THREE.Color(H2.col).b * 4 + 0.3], 0.9); }, true); } J._last = cur; }
    if (!HL.save.letter && !MG.flags.test && !MG.flags.play && MG.state === 'play' && PLAYER.state !== 'cine' && !CAM.cine && HL.quest.i <= 1 && a.alive) { J.letT = (J.letT || 0) + 1; if (J.letT > 3) { J.letter(); return; } }
    { const fl = HL.save.floors = HL.save.floors || {}, k = a.y < HL.Y0 - 4 ? 'd' : (HL.inFoot && HL.inFoot(a.x, a.z, 0) && a.y < HL.Y0 + 33 && HL.plan(HL.kAt(a.y + 0.5)).ind(Math.floor(HL.PL.X0 - a.x), Math.floor(HL.PL.Z0 - a.z)) ? 'k' + HL.kAt(a.y + 0.5) : null); if (k && !fl[k] && (k !== 'd' || HL.zoneAt(a.x, a.y + 1, a.z))) { fl[k] = 1; HL.store(); } if (PLAYER.state === 'fly' && !HL.save.flown) { HL.save.flown = 1; HL.store(); } if (!HL.save.deck && HL.DECK && Math.hypot(a.x - HL.DECK[0], a.z - HL.DECK[2]) < HL.DECK[4] + 1.5 && Math.abs(a.y - HL.DECK[1]) < 2.5 && PLAYER.state !== 'fly') { HL.save.deck = 1; HL.store(); } }
    for (const q of HL.SIDE) { const s = J.st(q); if (s.s === 0 && q.open()) { s.s = 1; HL.store(); HL.ui.toast('NEW SIDE QUEST', q.t + (TOUCH.on ? ' — tap the journal to read it' : ' — press J to open your journal'), 5); } if (s.s !== 1) continue;
      while (s.i < q.steps.length && q.steps[s.i][1]()) { s.i++; if (s.i < q.steps.length) HL.ui.pop(q.t.toUpperCase() + ' — STEP DONE'); }
      if (s.i >= q.steps.length) { s.s = 2; HL.save.points = (HL.save.points || 0) + q.pts; HL.store(); HL.ui.toast(q.t.toUpperCase() + ' — COMPLETE', 'Side quest finished · +' + q.pts + ' house points', 6); if (J.track === q.id) J.track = null; HL.quest._o = null; } } });
  /* a followed side quest takes the story's place on the HUD and the compass */
  const show0 = HL.quest.show, way0 = HL.quest.way;
  HL.quest.show = function () { const q = J.track && HL.SIDE.find((x) => x.id === J.track), s = q && J.st(q); if (!q || s.s !== 1) return show0.call(this); const o = J.stepText(q.steps[Math.min(s.i, q.steps.length - 1)]); if (HL.quest._o !== o + q.id) { HL.quest._o = o + q.id; HL.ui.setQuest('SIDE QUEST', q.t, o); } };
  HL.quest.way = function () { const q = J.track && HL.SIDE.find((x) => x.id === J.track); if (q && J.st(q).s === 1 && !HL.Q.on) return q.way ? q.way() : null; return way0.call(this); };
  // ---- the book
  const css = document.createElement('style'); css.textContent = `
.hlJ{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:radial-gradient(ellipse at center,rgba(10,7,4,.55),rgba(4,3,2,.9));font-family:HLB,Georgia,serif;color:#2c1a0a}
.hlJ .book{position:relative;width:min(1180px,94vw);height:min(720px,88vh);display:flex;border-radius:6px 10px 10px 6px;box-shadow:0 30px 80px rgba(0,0,0,.8),0 0 0 10px #3a2414,0 0 0 12px #6b4a24,0 0 0 14px #2a1a0c;background:#e9d9ae}
.hlJ .pg{flex:1;position:relative;padding:34px 40px 30px;overflow:hidden;background:radial-gradient(ellipse at 30% 20%,#f3e6c0,#e6d3a2 60%,#d2b97f);}
.hlJ .pg.l{border-right:1px solid rgba(90,60,25,.35);box-shadow:inset -34px 0 40px -28px rgba(70,44,16,.55)}
.hlJ .pg.r{box-shadow:inset 34px 0 40px -28px rgba(70,44,16,.55)}
.hlJ .pg:after{content:'';position:absolute;inset:0;pointer-events:none;background:repeating-linear-gradient(0deg,rgba(120,84,40,.035) 0 2px,transparent 2px 5px),radial-gradient(circle at 80% 90%,rgba(110,70,24,.22),transparent 40%),radial-gradient(circle at 8% 6%,rgba(110,70,24,.18),transparent 30%)}
.hlJ h1{font-family:HLA,Georgia,serif;font-size:30px;letter-spacing:.16em;margin:0 0 2px;text-align:center;color:#4a2a10}
.hlJ .rule{height:10px;margin:6px 30px 12px;background:linear-gradient(90deg,transparent,#7a5326 20%,#7a5326 80%,transparent);-webkit-mask:linear-gradient(#000 0 0) center/100% 1px no-repeat;mask:linear-gradient(#000 0 0) center/100% 1px no-repeat}
.hlJ .sec{font-family:HLA,Georgia,serif;font-size:13px;letter-spacing:.32em;color:#8a5a1c;margin:14px 0 6px}
.hlJ .list{height:calc(100% - 96px);overflow-y:auto;padding-right:8px;position:relative;z-index:1}
.hlJ .list::-webkit-scrollbar{width:6px}.hlJ .list::-webkit-scrollbar-thumb{background:rgba(90,60,25,.4);border-radius:3px}
.hlJ .it{display:flex;align-items:baseline;gap:10px;padding:5px 8px 5px 6px;cursor:pointer;border-radius:3px;font-size:18px;line-height:1.2}
.hlJ .it:hover{background:rgba(120,80,30,.14)}.hlJ .it.on{background:rgba(120,80,30,.24);box-shadow:inset 3px 0 0 #8e1c1c}
.hlJ .it .mk{width:16px;flex:none;text-align:center;font-size:14px;color:#8e1c1c}.hlJ .it.done{color:rgba(60,36,14,.55)}.hlJ .it.done .nm{text-decoration:line-through;text-decoration-color:rgba(60,36,14,.5)}
.hlJ .it.lock{color:rgba(60,36,14,.45);font-style:italic}.hlJ .it .tr{margin-left:auto;font-family:HLA,Georgia,serif;font-size:10px;letter-spacing:.2em;color:#8e1c1c}
.hlJ .ch{font-family:HLA,Georgia,serif;font-size:12px;letter-spacing:.3em;color:#8a5a1c;text-align:center}
.hlJ h2{font-family:HLA,Georgia,serif;font-size:27px;letter-spacing:.08em;text-align:center;margin:4px 0 2px;color:#3a2010}
.hlJ .by{text-align:center;font-style:italic;font-size:16px;color:#6a4a26}
.hlJ .desc{font-size:18.5px;line-height:1.42;margin:12px 4px 10px;text-align:justify;position:relative;z-index:1}.hlJ .desc:first-letter{font-family:HLA,Georgia,serif;font-size:44px;float:left;line-height:.9;padding:4px 6px 0 0;color:#8e1c1c}
.hlJ .ob{font-size:17.5px;line-height:1.3;padding:4px 0 4px 28px;position:relative;z-index:1}.hlJ .ob:before{content:'◇';position:absolute;left:4px;top:3px;color:#8a5a1c}
.hlJ .ob.d{color:rgba(60,36,14,.55)}.hlJ .ob.d:before{content:'✦';color:#5a7a2a}.hlJ .ob.c{font-weight:bold}.hlJ .ob.c:before{content:'◆';color:#8e1c1c}
.hlJ .ob kbd{font-family:HLA,Georgia,serif;font-size:12px;color:#2c1a0a;text-shadow:none;border:1px solid #6b4a24;border-radius:3px;padding:0 5px;margin:0 2px;background:rgba(255,250,235,.5);box-shadow:none}
.hlJ .rw{margin-top:12px;text-align:center;font-size:16px;color:#6a4a26;position:relative;z-index:1}.hlJ .rw b{color:#8e1c1c}
.hlJ .btn{display:block;margin:14px auto 0;padding:7px 22px;font-family:HLA,Georgia,serif;font-size:13px;letter-spacing:.24em;color:#f3e6c0;background:linear-gradient(#8e1c1c,#5e1010);border:1px solid #3a0a0a;border-radius:3px;cursor:pointer;position:relative;z-index:1;box-shadow:0 2px 6px rgba(0,0,0,.35)}.hlJ .btn:hover{background:linear-gradient(#a82424,#701414)}
.hlJ .foot{position:absolute;left:0;right:0;bottom:10px;text-align:center;font-family:HLA,Georgia,serif;font-size:11px;letter-spacing:.26em;color:rgba(74,42,16,.7);z-index:1}
.hlJ .letter{position:relative;width:min(640px,92vw);max-height:92vh;overflow:hidden;padding:44px 56px 64px;background:radial-gradient(ellipse at 30% 20%,#f5e9c6,#e8d6a6 60%,#d0b67c);box-shadow:0 30px 80px rgba(0,0,0,.8);border-radius:2px;transform:rotate(-0.6deg);font-size:19px;line-height:1.45;cursor:pointer}
.hlJ .letter:after{content:'';position:absolute;inset:0;pointer-events:none;background:repeating-linear-gradient(0deg,rgba(120,84,40,.035) 0 2px,transparent 2px 5px),radial-gradient(circle at 85% 92%,rgba(110,70,24,.25),transparent 40%),radial-gradient(circle at 6% 5%,rgba(110,70,24,.2),transparent 30%)}
.hlJ .letter .crest{font-family:HLA,Georgia,serif;font-size:25px;letter-spacing:.14em;text-align:center;color:#4a2a10;line-height:1.25}.hlJ .letter .crest span{font-size:15px;letter-spacing:.2em;font-style:italic}
.hlJ .letter p{margin:0 0 12px;text-align:justify;position:relative;z-index:1}.hlJ .letter p.sig{text-align:left;margin-top:20px}.hlJ .letter p.sig i{font-size:28px;font-family:'Snell Roundhand','Apple Chancery',cursive}.hlJ .letter small{font-size:14px;letter-spacing:.12em}
.hlJ .letter kbd{font-family:HLA,Georgia,serif;font-size:13px;color:#2c1a0a;text-shadow:none;border:1px solid #6b4a24;border-radius:3px;padding:0 6px;background:rgba(255,250,235,.5);box-shadow:none}
.hlJ .letter .seal{right:54px;top:auto;bottom:66px;width:74px;height:74px;font-size:30px}
.hlJ .seal{position:absolute;right:26px;top:22px;width:58px;height:58px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#c23a2a,#7a1616 70%);box-shadow:0 2px 6px rgba(0,0,0,.4),inset 0 0 0 3px rgba(0,0,0,.15);color:#f0d9a8;font-family:HLA,Georgia,serif;font-size:10px;letter-spacing:.1em;display:flex;align-items:center;justify-content:center;text-align:center;transform:rotate(-14deg);z-index:1}`; document.head.appendChild(css);
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;');
  J.render = function () { const mains = J.main(), cur = mains.find((m) => m.state === 1) || mains[mains.length - 1]; if (!J.sel) J.sel = 'm:' + cur.q.id;
    let left = '<div class="sec">THE STORY</div>'; for (const m of mains) { if (m.state === 0 && m.i > HL.quest.i + 1) continue; const id = 'm:' + m.q.id; left += `<div class="it ${m.state === 2 ? 'done' : m.state === 0 ? 'lock' : ''} ${J.sel === id ? 'on' : ''}" data-id="${id}"><span class="mk">${m.state === 2 ? '✦' : m.state === 1 ? '◆' : '·'}</span><span class="nm">${esc(m.state === 0 ? 'What comes next…' : m.q.n)}</span>${m.state === 1 && !J.track ? '<span class="tr">FOLLOWING</span>' : ''}</div>`; }
    left += '<div class="sec">SIDE QUESTS</div>'; for (const q of HL.SIDE) { const s = J.st(q), id = 's:' + q.id; left += `<div class="it ${s.s === 2 ? 'done' : s.s === 0 ? 'lock' : ''} ${J.sel === id ? 'on' : ''}" data-id="${id}"><span class="mk">${s.s === 2 ? '✦' : s.s === 1 ? '◆' : '?'}</span><span class="nm">${esc(s.s === 0 ? 'A rumour: ' + q.where : q.t)}</span>${J.track === q.id ? '<span class="tr">FOLLOWING</span>' : ''}</div>`; }
    left += `<div class="sec">THE CASTLE</div><div class="it ${J.sel === 'c:all' ? 'on' : ''}" data-id="c:all"><span class="mk">❦</span><span class="nm">What you have found</span></div>`;
    let right = ''; const [kind, sid] = J.sel.split(':');
    if (kind === 'm') { const m = mains.find((x) => x.q.id === sid) || cur, S = HL.STORY[m.q.id] || ['', '', ''], o = typeof m.q.o === 'function' ? m.q.o() : m.q.o;
      right = m.state === 0 ? `<div class="ch">THE STORY</div><h2>What comes next…</h2><div class="desc">The page is blank, but for a faint line of ink that has not decided what to say. Finish what is in front of you and it will make up its mind.</div>` :
        `<div class="ch">${esc(S[0] || m.q.t)}</div><h2>${esc(m.q.n)}</h2>${S[1] ? `<div class="by">from ${esc(S[1])}</div>` : ''}<div class="rule"></div><div class="desc">${esc(S[2])}</div><div class="sec">${m.state === 2 ? 'DONE' : 'TO DO'}</div><div class="ob ${m.state === 2 ? 'd' : 'c'}">${o}</div>${m.q.pts ? `<div class="rw">Reward: <b>${m.q.pts} house points</b></div>` : ''}${m.state === 2 ? '<div class="seal">DONE</div>' : ''}${m.state === 1 && J.track ? '<div class="btn" data-track="">FOLLOW THE STORY</div>' : ''}`; }
    else if (kind === 'c') { const ch = HL.LOOT.chests || [], pg = HL.SECRETS, row = (k, v) => `<div class="ob d" style="color:#2c1a0a"><b>${v}</b> &nbsp;${k}</div>`, rank = ['not yet on the ladder', 'won the first round', 'won the second round', 'Champion of Crossed Wands'][Math.min(3, HL.save.duel || 0)];
      right = `<div class="ch">THE CASTLE</div><h2>What you have found</h2><div class="rule"></div><div class="desc">A castle of this size keeps its own accounts. These are yours, so far.</div>` + row('places in the castle and its grounds discovered', Object.keys(HL.save.seen || {}).length) + row('of ' + pg.length + ' Field Guide pages gathered', pg.filter((q) => q.got).length) + row('of ' + ch.length + ' charmed chests opened', ch.filter((q) => q.open).length) + row('of 6 levels of the castle walked (dungeons to fourth floor)', Object.keys(HL.save.floors || {}).length) + row('ghosts spoken with', HL.jMet(/Nick|Friar|Baron|Grey Lady|Binns|Peeves/)) + row('professors spoken with', HL.jMet(/Professor|Madam|Nurse/)) + row('— Crossed Wands', rank) + `<div class="rw"><b>${HL.save.points || 0}</b> house points for ${(HL.HOUSES[HL.save.house || HL.house] || { name: 'your house' }).name}</div>`; }
    else { const q = HL.SIDE.find((x) => x.id === sid), s = J.st(q);
      right = s.s === 0 ? `<div class="ch">A RUMOUR</div><h2>${esc(q.where.replace(/^the /, 'The '))}</h2><div class="rule"></div><div class="desc">${esc(q.hint)}</div>` :
        `<div class="ch">SIDE QUEST</div><h2>${esc(q.t)}</h2><div class="by">from ${esc(q.giver)}, ${esc(q.where)}</div><div class="rule"></div><div class="desc">${esc(q.desc)}</div><div class="sec">${s.s === 2 ? 'DONE' : 'TO DO'}</div>` + q.steps.map((st, i) => `<div class="ob ${i < s.i ? 'd' : i === s.i ? 'c' : ''}">${esc(J.stepText(st))}</div>`).join('') + `<div class="rw">Reward: <b>${q.pts} house points</b></div>${s.s === 2 ? '<div class="seal">DONE</div>' : `<div class="btn" data-track="${J.track === q.id ? '' : q.id}">${J.track === q.id ? 'STOP FOLLOWING' : 'FOLLOW THIS QUEST'}</div>`}`; }
    const done = mains.filter((m) => m.state === 2).length + HL.SIDE.filter((q) => J.st(q).s === 2).length, all = mains.length - 1 + HL.SIDE.length;
    const S2 = HL.ui.screen(`<div class="hlJ"><div class="book"><div class="pg l"><h1>Quest Journal</h1><div class="rule"></div><div class="list">${left}</div><div class="foot">${done} OF ${all} DONE · ${HL.save.points || 0} HOUSE POINTS</div></div><div class="pg r">${right}<div class="foot">J OR ESC TO CLOSE</div></div></div></div>`);
    S2.querySelectorAll('.it').forEach((e) => e.onclick = () => { J.sel = e.dataset.id; const sc = S2.querySelector('.list').scrollTop; J.render(); HL.ui.el.Screen.querySelector('.list').scrollTop = sc; }); const b = S2.querySelector('.btn'); if (b) b.onclick = () => { J.track = b.dataset.track || null; HL.quest._o = null; J.render(); }; };
  /* the letter: read once, when a new term begins — who is writing, what is expected of you, which keys keep your errands */
  J.letter = function () { if (MG.state !== 'play') return; MG.state = 'journal'; if (document.exitPointerLock) document.exitPointerLock(); if (HL.SAY && HL.SAY.el) HL.SAY.el.style.opacity = 0; const H2 = HL.HOUSES[HL.save.house || HL.house] || { name: 'your' };
    const S2 = HL.ui.screen(`<div class="hlJ"><div class="letter"><div class="crest">HOGWARTS SCHOOL<br><span>of</span> WITCHCRAFT <span>and</span> WIZARDRY</div><div class="rule"></div>
      <p>Dear ${HL.save.witch ? 'Miss' : 'Sir'},</p><p>We are pleased to confirm that a place has been kept for you in <b>${esc(H2.name)}</b> House. Term began without you, as terms do; the Sorting Feast is laid in the Great Hall and you are expected at it.</p>
      <p>You will cross the long bridge to the Clock Tower, whose doors are the way in. Present yourself at the feast, learn the castle — it is larger than it looks and it does not keep still — and attend your classes. Professor Hecat will want to see what your wand arm is worth. So, I am told, will a certain club that meets under the pendulum and which I have not heard of.</p>
      <p>Your <b>journal</b> (<kbd>J</kbd>) will keep your errands in order. Your <b>map</b> (<kbd>M</kbd>) inks itself in as you walk. Do try not to be late.</p>
      <p class="sig">Yours sincerely,<br><i>M. Weasley</i><br><small>Deputy Headmistress</small></p><div class="seal">H</div><div class="foot">PRESS ANY KEY</div></div></div>`);
    const done = () => { HL.save.letter = 1; HL.store(); J.close(); HL.ui.hint('<kbd>J</kbd> opens your quest journal · <kbd>M</kbd> the map · <kbd>ESC</kbd> the controls', 9); }; MG.onKey = () => done(); S2.querySelector('.letter').onclick = done; };
  J.open = function () { if (MG.state !== 'play' || HL.Q.on || (HL.duel && HL.duel.on) || !PLAYER.a || !PLAYER.a.alive) return; MG.state = 'journal'; J.sel = null; if (HL.SAY && HL.SAY.el) HL.SAY.el.style.opacity = 0; if (document.exitPointerLock) document.exitPointerLock(); J.render(); MG.onKey = (c) => { if (c === 'Escape' || c === 'KeyJ') J.close(); }; };
  J.close = function () { HL.ui.screen(''); MG.state = 'play'; MG.onKey = null; IN.buf = {}; HL.noPauseT = MG.rt + 0.25; };
});
