/* ==== p78m_hl_classes.js ==== */
/* HOGWARTS — three lessons with something to do in them, set into the story after the Library: a book in the
   Restricted Section that has to be read, a Wiggenweld to be brewed in Potions from what stands about the room, and
   three Mandrakes in the greenhouses that have outgrown their pots. Each thing is there to be seen and walked up to. */
(function () { const Q = HL.QUESTS, at = (id) => Q.findIndex((q) => q.id === id), F = () => HL.quest.flags, T = HL.TASKS = {};
  const near = (id, fb) => { const a = PLAYER.a, L2 = (T[id] || []).filter((s) => !s.got && !s.last); const list = L2.length ? L2 : (T[id] || []).filter((s) => !s.got); let b = null, bd = 1e9; for (const s of list) { const d = a ? Math.hypot(s.p[0] - a.x, s.p[2] - a.z) : 0; if (d < bd) { bd = d; b = s; } } return b ? [b.p[0], b.p[1] + 1.2, b.p[2]] : (fb || null); };
  Q.splice(at('class') + 1, 0,
    { id: 'restricted', t: 'THE LIBRARY ANNEX', n: 'The Restricted Section', o: 'A rope hangs across a doorway beyond the reading tables. Go through into the Restricted Section and read the book chained to the lectern  (<kbd>E</kbd>)', way: () => near('restricted'), done: () => !!F().restricted, pts: 15 },
    { id: 'potions', t: 'POTIONS', n: 'A Wiggenweld, properly made', o: () => (F().potions || 0) < 3 ? `In the Potions Classroom, take the three ingredients from the jars that stand about the room  (<kbd>E</kbd>)  ${F().potions || 0} / 3` : 'Now the great cauldron that stands apart from the benches: stir them in  (<kbd>E</kbd>)', way: () => near('potions'), done: () => !!F().brewed, pts: 15 },
    { id: 'herbs', t: 'HERBOLOGY', n: 'Mandrakes', o: () => `In the three greenhouses beyond the Bell Tower court, repot the Mandrakes that have outgrown their pots  (<kbd>E</kbd>)  ${F().herbs || 0} / 3`, way: () => near('herbs'), done: () => (F().herbs || 0) >= 3, pts: 15 });
  /* …and the book's last line is kept: late in the story the Room of Requirement can be looked for, and found */
  { const ror = () => { for (const k of HL.ALLK) { const P = HL.plan(k), c = P.comps.find((q) => q.name && /ROOM OF REQUIREMENT/.test(q.name)); if (c) return [P.X((c.R.i0 + c.R.i1 + 1) / 2), P.y + 2, P.Z((c.R.j0 + c.R.j1 + 1) / 2)]; } return null; };
    Q.splice(at('tour') + 1, 0, { id: 'need', t: 'THE ROOM OF REQUIREMENT', n: 'It comes to those who need it', o: 'The book in the Restricted Section drew a room that is on no map. Look for it on the second floor of the Astronomy Tower wing, in the north-west of the castle, under the Astronomy classroom', way: ror, done: (a) => { const Z = HL.zoneAt(a.x, a.y + 1, a.z); if (!(Z && /ROOM OF REQUIREMENT/.test(Z.name))) return false; if (!F().need) { F().need = 1; try { const Lt = HL.LOOT, u = (Lt.RANDOM_UNIQ || []).find((k) => !Lt.owned[k]); Lt.give(u ? Lt.unique(u) : Lt.make({ r: 3, il: 14 }), true); } catch (e) { /* the room is its own reward */ } HL.ui.toast('THE ROOM OF HIDDEN THINGS', 'A door where there was a wall. Inside: everything anyone ever hid at Hogwarts, piled to the rafters — and, on top of the nearest heap, something left for whoever needed it next. (Look in your pack: I.)', 10); } return true; }, pts: 40 }); }
  Object.assign(HL.STORY || (HL.STORY = {}), {
    restricted: ['CHAPTER II · A PROPER EDUCATION', 'nobody at all', 'Madam Scribner has gone to shout at a first-year. The rope across the doorway is only a rope. On a lectern at the back, under a chain, lies a book the Library catalogue says does not exist.'],
    potions: ['CHAPTER II · A PROPER EDUCATION', 'Professor Sharp', '“Wiggenweld. The potion you will drink more of than any other, so you will make it properly. Horklump juice, dittany, a pinch of salamander blood — find them, they are about the room — and then the cauldron. Do not improvise.”'],
    need: ['CHAPTER III · YOUR HOUSE', 'a book that does not exist', 'It was only a line of brown ink under a plan of a room: “It comes to those who need it.” Generations of students have hidden things at Hogwarts. They all hid them in the same place, and none of them could ever find it twice.'],
    herbs: ['CHAPTER II · A PROPER EDUCATION', 'Professor Garlick', '“Three of my Mandrakes are bursting their pots, one in each greenhouse. Lift, turn, set down in the larger pot, firm the soil. You will want the earmuffs. You will forget the earmuffs. Everyone does, once.”'] });
  HL.START.push(function (L) { const Y = HL.Y0; for (const k in T) delete T[k];
    const rm = (re) => { for (const k of HL.ALLK) { const P = HL.plan(k), c = P.comps.find((q) => q.name && re.test(q.name)); if (c) { const x0 = P.X(c.R.i1 + 1), x1 = P.X(c.R.i0), z0 = P.Z(c.R.j1 + 1), z1 = P.Z(c.R.j0); return { k, y: P.y, x0, x1, z0, z1, cx: (x0 + x1) / 2, cz: (z0 + z1) / 2 }; } } return null; };
    /* a free place near where it is wanted that the player can walk up to (flooded from the Clock Tower doors), a pace clear of the room's middle */
    const place = (R2, want, r, taken) => { const fl = HL.occ.flood(R2.k, R2.k === 0 ? -0.5 : R2.cx, R2.k === 0 ? 6 : R2.cz); for (let rr = 0; rr <= 9; rr += 1) for (let an = 0; an < 6.3; an += rr ? 0.7 : 7) { const x = want[0] + Math.sin(an) * rr, z = want[1] + Math.cos(an) * rr; if (x < R2.x0 + 1.2 || x > R2.x1 - 1.2 || z < R2.z0 + 1.2 || z > R2.z1 - 1.2) continue; if (Math.hypot(x - R2.cx, z - R2.cz) < 2.2) continue; if (taken.some((o) => Math.hypot(o[0] - x, o[1] - z) < 3.5)) continue; if (!HL.occ.free(R2.k, x, z, r, r, 0, 0.3) || !fl.near(x, z, r + 0.9)) continue; HL.occ.mark(R2.k, x, z, r, r, 0, 3); taken.push([x, z]); return [x, z]; } return null; };
    const std = (c, r, o) => new THREE.MeshStandardMaterial(Object.assign({ color: c, roughness: r === undefined ? 0.8 : r }, o || {})), M = { oak: std(0x4a3018), dark: std(0x1c1a18, 0.5, { metalness: 0.6 }), clay: std(0x9a5a34, 0.9), leaf: std(0x3a6a2a, 0.9), page: std(0xe8dcb8, 0.9), glass: std(0xcfe6e0, 0.1, { transparent: true, opacity: 0.45 }) };
    const add = (g, geo, m, x, y, z, rx) => { const me = new THREE.Mesh(geo, m); me.position.set(x, y, z); if (rx) me.rotation.x = rx; me.castShadow = false; me.receiveShadow = true; g.add(me); return me; };
    const thing = (id, kind, x, y, z, label, onUse, o) => { o = o || {}; const g = new THREE.Group(); g.position.set(x, y, z); if (o.tag) g.userData.tag = o.tag;
      if (kind === 'jar') { add(g, new THREE.CylinderGeometry(0.2, 0.24, 0.9, 10), M.oak, 0, 0.45, 0); add(g, new THREE.CylinderGeometry(0.11, 0.11, 0.26, 12), M.glass, 0, 1.03, 0); add(g, new THREE.CylinderGeometry(0.095, 0.095, 0.16, 12), KIT.emis(o.col || 0x60ff80, 1.6), 0, 0.99, 0); add(g, new THREE.CylinderGeometry(0.07, 0.08, 0.05, 10), M.oak, 0, 1.185, 0); }
      else if (kind === 'cauldron') { add(g, new THREE.CylinderGeometry(0.5, 0.56, 0.12, 14), M.dark, 0, 0.06, 0); add(g, new THREE.SphereGeometry(0.52, 16, 12, 0, TAU, HALF * 0.55, PI), M.dark, 0, 0.62, 0); add(g, new THREE.TorusGeometry(0.44, 0.045, 8, 20), M.dark, 0, 0.93, 0, HALF); g.userData.brew = add(g, new THREE.CylinderGeometry(0.42, 0.42, 0.02, 20), KIT.emis(0x3a8a5a, 0.8), 0, 0.9, 0); }
      else if (kind === 'mandrake') { add(g, new THREE.CylinderGeometry(0.17, 0.12, 0.26, 10), M.clay, 0, 0.13, 0); for (let q = 0; q < 6; q++) { const lf = add(g, new THREE.ConeGeometry(0.07, 0.42, 5), M.leaf, Math.sin(q * 1.05) * 0.07, 0.44, Math.cos(q * 1.05) * 0.07); lf.rotation.set(Math.cos(q * 1.05) * 0.5, 0, -Math.sin(q * 1.05) * 0.5); } add(g, new THREE.CylinderGeometry(0.26, 0.2, 0.34, 10), M.clay, 0.5, 0.17, 0); }
      else if (kind === 'lectern') { add(g, new THREE.CylinderGeometry(0.3, 0.36, 0.1, 8), M.oak, 0, 0.05, 0); add(g, new THREE.CylinderGeometry(0.06, 0.08, 1.0, 8), M.oak, 0, 0.6, 0); add(g, new THREE.BoxGeometry(0.62, 0.05, 0.46), M.oak, 0, 1.13, 0, 0.42); add(g, new THREE.BoxGeometry(0.5, 0.05, 0.36), std(0x3a1a14, 0.6), 0, 1.17, 0.01, 0.42); add(g, new THREE.BoxGeometry(0.46, 0.03, 0.32), M.page, 0, 1.2, 0.02, 0.42); for (let q = 0; q < 7; q++) add(g, new THREE.TorusGeometry(0.03, 0.008, 5, 8), M.dark, 0.3, 1.1 - q * 0.055, 0.2 - q * 0.02, q % 2 ? 0 : HALF); }
      const glow = HL.sprite(o.glow || [1.6, 1.25, 0.4], 1.0, 0.7); glow.position.set(0, o.gy || 1.25, 0); glow.visible = false; g.add(glow); LEVEL.add(g);
      const s = { id, p: [x, y, z], got: false, g, glow, last: !!o.last, when: o.when || (() => true) }; s.u = HL.interact([x, y + (o.gy || 1.1), z], o.r || 2.3, label, () => { if (s.got || !s.when()) return; s.got = true; s.u.off = true; glow.visible = false; FX.spark(V3(x, y + (o.gy || 1.1), z), null, 26, 5, [2.4, 1.9, 0.6], 0.5); onUse(s); HL.quest._o = null; }); s.u.off = true; (T[id] = T[id] || []).push(s); return s; };
    // ---- the Restricted Section: the book on the lectern
    { const R2 = rm(/RESTRICTED SECTION/); if (R2) { const sp = place(R2, [R2.cx + 2.6, R2.cz], 0.45, []) || HL.occ.spot(R2.k, R2.cx, R2.cz, 0.5, 6, 3) || [R2.cx, R2.cz]; thing('restricted', 'lectern', sp[0], R2.y, sp[1], 'Read the chained book', () => { F().restricted = 1; HL.ui.toast('THE BOOK', 'The pages are blank until you stop trying to read them. Then, in brown ink, a plan of a room that is on no map of the castle — and a line beneath: “It comes to those who need it. Seventh floor.”', 9); }, { tag: 'in' + R2.k, gy: 1.3 }); } }
    // ---- Potions: three jars about the room, then the great cauldron in the middle
    { const R2 = rm(/POTIONS CLASSROOM/); if (R2) { const names = ['Horklump juice', 'Dittany leaves', 'Salamander blood'], cols = [0x60ff80, 0x7ad040, 0xff5030], taken = [], w = R2.x1 - R2.x0, d = R2.z1 - R2.z0;
        const sc = place(R2, [R2.cx + (w > d ? 4 : 0), R2.cz + (w > d ? 0 : 4)], 0.6, taken) || [R2.cx + 3, R2.cz];
        [[R2.x0 + w * 0.2, R2.z0 + d * 0.3], [R2.x1 - w * 0.2, R2.z0 + d * 0.3], [R2.cx, R2.z1 - d * 0.22]].forEach((q, i) => { const sp = place(R2, q, 0.35, taken) || q; thing('potions', 'jar', sp[0], R2.y, sp[1], 'Take the ' + names[i].toLowerCase(), () => { F().potions = (F().potions || 0) + 1; HL.ui.pop(names[i].toUpperCase()); }, { tag: 'in' + R2.k, col: cols[i], gy: 1.1 }); });
        thing('potions', 'cauldron', sc[0], R2.y, sc[1], 'Stir the cauldron', (s) => { F().brewed = 1; s.g.userData.brew.material = KIT.emis(0x40ff90, 2.2); if (HL.LOOT && HL.LOOT.pots) HL.LOOT.pots.wiggen = (HL.LOOT.pots.wiggen || 0) + 2; HL.ui.toast('WIGGENWELD POTION', 'Green, as it should be, and it does not smell of feet. Two bottles for your pack — G drinks one.', 7); }, { tag: 'in' + R2.k, last: true, when: () => (F().potions || 0) >= 3, gy: 1.2, glow: [0.6, 1.8, 0.9], r: 2.6 }); PHY.cyl(sc[0], sc[1], 0.55, R2.y, R2.y + 1); } }
    // ---- Herbology: a Mandrake on the bench of each greenhouse
    (HL.GREEN || []).forEach((g, i) => { const x = i % 2 ? g.x1 - 1.05 : g.x0 + 1.05, z = lerp(g.z0, g.z1, 0.42 + i * 0.1); thing('herbs', 'mandrake', x, Y + 0.87, z, 'Repot the Mandrake', (s) => { F().herbs = (F().herbs || 0) + 1; FX.addShake(0.35); HL.ui.toast('MANDRAKE', F().herbs === 1 ? 'It screams. You were told about the earmuffs.' : F().herbs === 2 ? 'This one bites as well.' : 'Three Mandrakes in three larger pots, and your ears will ring until supper.', 5); s.g.visible = true; s.g.children.slice(1, 7).forEach((c) => { c.position.x += 0.5; c.position.y += 0.1; }); }, { gy: 0.5, r: 2.6 }); });
    // ---- magic at work in the classrooms: coloured steam off every cauldron in Potions; feathers kept aloft over the Charms class
    { const C = HL.CAULDRONS || []; if (C.length) { const per = 7, n = C.length * per, pos = new Float32Array(n * 3), ph = new Float32Array(n), col = new Float32Array(n * 3), rs = mulberry(515); let sx = 0, sz = 0; C.forEach((c, i) => { const k = new THREE.Color(c[3]); sx += c[0] / C.length; sz += c[2] / C.length; for (let q = 0; q < per; q++) { const j = i * per + q; pos[j * 3] = c[0]; pos[j * 3 + 1] = c[1]; pos[j * 3 + 2] = c[2]; ph[j] = rs() * 6.28; col[j * 3] = k.r; col[j * 3 + 1] = k.g; col[j * 3 + 2] = k.b; } });
        const g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.BufferAttribute(pos, 3)); g.setAttribute('aPh', new THREE.BufferAttribute(ph, 1)); g.setAttribute('aCol', new THREE.BufferAttribute(col, 3)); const U = { uT: { value: 0 } };
        const m = new THREE.ShaderMaterial({ uniforms: U, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, vertexShader: 'uniform float uT; attribute float aPh; attribute vec3 aCol; varying float vA; varying vec3 vC; void main() { float h = fract(uT * 0.22 + aPh * 0.159); vec3 p = position + vec3(sin(aPh * 3.0 + uT * 0.7) * 0.16 * (0.3 + h), h * 1.7, cos(aPh * 2.3 + uT * 0.6) * 0.16 * (0.3 + h)); vec4 mv = modelViewMatrix * vec4(p, 1.0); vA = sin(h * 3.14159) * 0.5; vC = aCol; gl_PointSize = clamp((90.0 + 160.0 * h) / -mv.z, 2.0, 80.0); gl_Position = projectionMatrix * mv; }', fragmentShader: 'varying float vA; varying vec3 vC; void main() { float d = length(gl_PointCoord - 0.5); float a = (1.0 - smoothstep(0.05, 0.5, d)) * vA; gl_FragColor = vec4(vC * 0.5 * a, a); }' });
        const pts = new THREE.Points(g, m); pts.frustumCulled = false; pts.userData.near = [sx, Y + 1, sz, 46, 7]; pts.visible = false; pts.renderOrder = 6; LEVEL.add(pts); (HL.NEAR = HL.NEAR || []).push(pts); L.updates.push((dt, tt) => { U.uT.value = tt; }); } }
    { const R2 = rm(/CHARMS CLASSROOM/); if (R2) { const n = 16, sh = new THREE.Shape(); sh.moveTo(0, -0.2); sh.quadraticCurveTo(0.07, -0.05, 0.045, 0.14); sh.quadraticCurveTo(0, 0.24, -0.045, 0.14); sh.quadraticCurveTo(-0.07, -0.05, 0, -0.2); const im = new THREE.InstancedMesh(new THREE.ShapeGeometry(sh, 4), new THREE.MeshStandardMaterial({ color: 0xf4f0e6, roughness: 0.9, side: THREE.DoubleSide, emissive: 0x2a2820 }), n), F2 = [], rs = mulberry(88), m4 = new THREE.Matrix4(), q4 = new THREE.Quaternion(), e = new THREE.Euler(), p = new THREE.Vector3(), s1 = new THREE.Vector3(1, 1, 1);
        for (let i = 0; i < n; i++) F2.push([lerp(R2.x0 + 2.5, R2.x1 - 2.5, rs()), 1.5 + rs() * 2.2, lerp(R2.z0 + 2.5, R2.z1 - 2.5, rs()), rs() * 6.28, 0.5 + rs()]); im.castShadow = false; im.frustumCulled = false; im.userData.near = [R2.cx, R2.y + 2, R2.cz, Math.max(R2.x1 - R2.x0, R2.z1 - R2.z0) / 2 + 26, 7]; im.visible = false; LEVEL.add(im); HL.NEAR.push(im);
        L.updates.push((dt, tt) => { if (!im.visible) return; for (let i = 0; i < n; i++) { const f = F2[i]; p.set(f[0] + Math.sin(tt * 0.31 * f[4] + f[3]) * 0.5, R2.y + f[1] + Math.sin(tt * 0.9 * f[4] + f[3] * 2) * 0.3, f[2] + Math.cos(tt * 0.27 * f[4] + f[3]) * 0.5); e.set(Math.sin(tt * 0.8 + f[3]) * 0.5 + 1.2, tt * 0.4 * f[4] + f[3], Math.sin(tt * 1.3 + f[3]) * 0.4); q4.setFromEuler(e); m4.compose(p, q4, s1); im.setMatrixAt(i, m4); } im.instanceMatrix.needsUpdate = true; }); } }
    L.updates.push((dt, tt) => { if (HL.PORT_U) HL.PORT_U.uT.value = tt; });   // the clock the painted sitters keep
    let t = 0; L.updates.push((dt) => { t -= dt; if (t > 0) return; t = 0.3; const cur = HL.quest.cur().id; for (const id in T) for (const s of T[id]) { const on = cur === id && !s.got && s.when(); s.u.off = !on; s.glow.visible = on; if (on) s.glow.material.opacity = 0.7 + 0.3 * Math.sin(MG.t * 3); } });
  });
})();
