/* ==== p78n_hl_village.js ==== */
/* HOGSMEADE, lived in. The Three Broomsticks is a real pub on the square: push the door and you are inside — a long bar
   with its kegs and bottles, a fire, round tables with people at them, Sirona behind the counter pulling Butterbeer.
   The high street is cobbled, hung with bunting from house to house, and has shopkeepers at their doors. */
HL.BUILD.push(async function village(L) { const V = HL.VIL, T = HL.TBLOT; if (!V || !T) return; const M = HL.M(), I = HL.IM(), rs = mulberry(1707);
  // ---- cobbles: the street from end to end, and the square
  { const strip = (xa, xb, za, zb, step) => { for (let x = xa; x < xb - 0.01; x += step) for (let z = za; z < zb - 0.01; z += step) { const x1 = Math.min(xb, x + step), z1 = Math.min(zb, z + step), y = (q, r) => HL.gy(q, r) + 0.07; HL.quad(M.cobble, [x, y(x, z1), z1], [x1, y(x1, z1), z1], [x1, y(x1, z), z], [x, y(x, z), z], [0, 1, 0], (p) => [p[0], p[2]]); } };
    strip(V.x - 74, V.x + 74, V.z - 6.6, V.z + 6.6, 4.4); strip(V.x - 12, V.x + 12, V.z - 27, V.z - 6.6, 4.4);
    /* a stone kerb and a gutter line either side */ for (const sd of [-1, 1]) for (let x = V.x - 74; x < V.x + 74; x += 6) { if (sd < 0 && Math.abs(x + 3 - V.x) < 12) continue; const z = V.z + sd * 6.3, y = HL.gy(x + 3, z); KIT.box(x, y - 0.2, z - 0.14, x + 6, y + 0.16, z + 0.14, M.trim, { col: false }); } }
  // ---- bunting from house to house across the street
  { const cols = [0x8a1818, 0xd8a326, 0x1c5a34, 0x1c3a7a, 0xd8d0c0], mats = cols.map((c) => { const m = new THREE.MeshStandardMaterial({ color: c, roughness: 0.9, side: THREE.DoubleSide }); m.userData.tscale = 1; return m; });
    for (let x = V.x - 62, q = 0; x <= V.x + 62; x += 15.5, q++) { const za = V.z - 6.6, zb = V.z + 6.6, y0 = HL.gy(x, V.z) + 5.4 + (q % 2) * 0.5, n = 15, skew = (rs() - 0.5) * 3; let prev = null; for (let i = 0; i <= n; i++) { const t = i / n, px = x + skew * (t - 0.5), pz = lerp(za, zb, t), py = y0 - Math.sin(t * PI) * 0.85; if (prev) { KIT.beam(prev, [px, py, pz], 0.025, M.woodD); const mx = (prev[0] + px) / 2, my = (prev[1] + py) / 2, mz = (prev[2] + pz) / 2, g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute([prev[0], prev[1], prev[2], px, py, pz, mx, my - 0.62, mz], 3)); g.setAttribute('uv', new THREE.Float32BufferAttribute([0, 1, 1, 1, 0.5, 0], 2)); g.computeVertexNormals(); KIT.geo(g, mats[(i + q) % mats.length], new THREE.Matrix4()); } prev = [px, py, pz]; } } }
  // ---- THE THREE BROOMSTICKS
  const x0 = T.x0, x1 = T.x1, z0 = T.z0, z1 = T.z1, y = Math.max(HL.gy(x0, z0), HL.gy(x1, z0), HL.gy((x0 + x1) / 2, z0)) + 0.12, h = 4.5, t = 0.5, dx = x0 + 4.2, U = (u) => x0 + u, W = (v) => z0 + v; HL.TB = { x0, x1, z0, z1, y, door: [dx, y, z0 - 1.2] };
  HL.shell(x0, z0, x1, z1, y, h, { t, mat: M.village, floor: M.wood, plinth: false, roof: 'x', rise: 5.2, inside: M.woodD,
    ops: { z: [{ p: dx, w: 1.9, s: 0, hd: 2.7 }, { p: U(8.2), w: 2.2, s: 1.0, hd: 2.9, bars: 1 }, { p: U(12.2), w: 2.2, s: 1.0, hd: 2.9, bars: 1 }, { p: U(1.5), w: 1.2, s: 1.0, hd: 2.9 }], Z: [{ p: U(12.6), w: 1.6, s: 1.3, hd: 2.9, bars: 1 }], x: [{ p: W(3.2), w: 1.8, s: 1.0, hd: 2.9, bars: 1 }], X: [] } });
  HL.zone('THE THREE BROOMSTICKS', x0 + 0.2, z0 + 0.2, x1 - 0.2, z1 - 0.2, y - 0.5, y + 9, { hemi: 0.34 }); HL.VILDOORS['THE THREE BROOMSTICKS'] = [dx, y, z0 - 1.4];
  /* outside: a step, a timber frame laid over the stone above the windows, the sign, three crossed broomsticks, lamps */
  KIT.box(dx - 1.3, y - 0.5, z0 - 1.0, dx + 1.3, y, z0, M.trim, { col: true });
  for (let u = 0; u <= 15.5 + 0.01; u += 15.5 / 8) KIT.box(U(u) - 0.11, y + 3.05, z0 - 0.07, U(u) + 0.11, y + h, z0, M.woodD, { col: false }); for (const yy of [3.05, h - 0.2]) KIT.box(x0, y + yy, z0 - 0.08, x1, y + yy + 0.2, z0, M.woodD, { col: false });
  for (const sx of [-1, 1]) KIT.box(dx + sx * 1.08 - 0.1, y, z0 - 0.1, dx + sx * 1.08 + 0.1, y + 2.9, z0, M.woodD, { col: false }); KIT.box(dx - 1.2, y + 2.7, z0 - 0.12, dx + 1.2, y + 2.95, z0, M.woodD, { col: false });
  { const tx = HL.signTex('THE THREE BROOMSTICKS', '#3a2412', '#e8c878'), sm = new THREE.MeshStandardMaterial({ map: tx, roughness: 0.8, side: THREE.DoubleSide, emissive: 0x2a1c0c }); sm.userData.tscale = 1; const m4 = new THREE.Matrix4().makeRotationY(PI); m4.setPosition(U(9.4), y + 3.75, z0 - 0.14); KIT.geo(new THREE.PlaneGeometry(4.6, 0.95), sm, m4); KIT.box(U(9.4) - 2.4, y + 3.22, z0 - 0.13, U(9.4) + 2.4, y + 4.28, z0 - 0.05, M.woodD, { col: false });
    for (const an of [-0.5, 0, 0.5]) { const a = [dx + Math.sin(an) * 0.2, y + 3.05, z0 - 0.2], b = [dx - Math.sin(an) * 1.5, y + 4.6, z0 - 0.2]; KIT.beam(a, b, 0.05, M.wood); for (let q = 0; q < 5; q++) KIT.beam([a[0] + (q - 2) * 0.03, a[1] + 0.1, a[2]], [a[0] + Math.sin(an) * 0.55 + (q - 2) * 0.09, a[1] - 0.5, a[2]], 0.035, M.thatch); } }
  for (const sx of [-1.5, 1.5]) HL.lantern(L, dx + sx, y + 2.6, z0 - 0.45, { i: 14, range: 11 });
  // ---- inside
  const oakD = I.oakD, oak = I.oak, brass = I.brass, P3 = (u, v) => [U(u), W(v)];
  /* the bar: a long counter before the back wall, a brass rail, pumps; bottles on the shelves behind; kegs racked at the end */
  KIT.box(U(2.0), y, W(7.5), U(10.2), y + 1.06, W(8.2), oakD, { col: true }); KIT.box(U(1.9), y + 1.06, W(7.38), U(10.3), y + 1.14, W(8.32), oak, { col: false }); KIT.beam([U(2.1), y + 0.22, W(7.36)], [U(10.1), y + 0.22, W(7.36)], 0.05, brass);
  KIT.box(U(10.2), y, W(7.5), U(10.9), y + 1.06, W(10.0), oakD, { col: true }); KIT.box(U(10.1), y + 1.06, W(7.38), U(11.0), y + 1.14, W(10.0), oak, { col: false });
  for (const u of [3.4, 5.2, 7.0, 8.8]) { KIT.cyl(U(u), y + 1.14, W(7.95), 0.035, 0.34, brass, { seg: 6, col: false }); KIT.box(U(u) - 0.03, y + 1.44, W(7.7), U(u) + 0.03, y + 1.5, W(7.98), brass, { col: false }); KIT.geo(new THREE.SphereGeometry(0.05, 6, 5), oakD, new THREE.Matrix4().makeTranslation(U(u), y + 1.5, W(7.68))); }
  { const glassM = [0x3a7a3a, 0x8a5a1c, 0x6a1c1c, 0x2c4a7a, 0xc8a84a].map((c) => { const m = new THREE.MeshStandardMaterial({ color: c, roughness: 0.25, emissive: c, emissiveIntensity: 0.25 }); m.userData.tscale = 1; return m; });
    for (let r = 0; r < 3; r++) { KIT.box(U(2.2), y + 1.35 + r * 0.62, W(9.62), U(9.9), y + 1.4 + r * 0.62, W(9.98), oakD, { col: false }); for (let u = 2.4; u < 9.8; u += 0.24 + rs() * 0.16) { if (rs() < 0.18) continue; const hh = 0.24 + rs() * 0.16; KIT.cyl(U(u), y + 1.4 + r * 0.62, W(9.8), 0.045, hh, glassM[(rs() * 5) | 0], { seg: 6, col: false }); KIT.cyl(U(u), y + 1.4 + r * 0.62 + hh, W(9.8), 0.018, 0.09, glassM[(rs() * 5) | 0], { seg: 5, col: false }); } }
    for (let q = 0; q < 3; q++) { const g = new THREE.CylinderGeometry(0.42, 0.42, 0.95, 12); g.rotateX(HALF); g.scale(1, 1, 1); KIT.geo(g, oak, new THREE.Matrix4().makeTranslation(U(11.9 + q * 1.0), y + 0.62, W(9.45)), { worldUV: true }); for (const e of [-0.3, 0.3]) KIT.geo(new THREE.TorusGeometry(0.43, 0.02, 5, 14), I.iron || M.iron, new THREE.Matrix4().makeTranslation(U(11.9 + q * 1.0), y + 0.62, W(9.45) + e)); KIT.box(U(11.5 + q * 1.0), y, W(9.0), U(12.3 + q * 1.0), y + 0.2, W(9.9), oakD, { col: false }); } PHY.box(U(11.4), y, W(8.95), U(14.4), y + 1.1, W(9.95)); }
  /* the hearth in the east wall, a settle and two armchairs by it */
  HL.GK.hearth(L, x1 - t, y, W(4.6), -1, 0, 3.0, 9);
  for (const [u, v, yw] of [[12.2, 3.0, 0.9], [12.2, 6.2, 2.2]]) HL.armchair(U(u), y, W(v), yw, I.leather);
  { const g2 = new THREE.CircleGeometry(1.9, 28); g2.rotateX(-HALF); KIT.geo(g2, HL.houseMats().rug, new THREE.Matrix4().makeTranslation(U(12.6), y + 0.012, W(4.6)), { uvs: 3 }); }
  /* round tables and chairs; a tankard for everyone, a candle on each */
  const seats = [], table = (u, v, n, r) => { const [tx, tz] = P3(u, v); KIT.cyl(tx, y, tz, 0.09, 0.72, oakD, { seg: 8, col: false }); KIT.cyl(tx, y, tz, 0.32, 0.05, oakD, { seg: 10, col: false }); KIT.cyl(tx, y + 0.72, tz, r, 0.06, oak, { seg: 18, col: false }); PHY.cyl(tx, tz, r * 0.9, y, y + 0.78); HL.candlestick(tx, y + 0.78, tz, 2);
    for (let q = 0; q < n; q++) { const an = q / n * TAU + u * 0.7, cx = tx + Math.sin(an) * (r + 0.45), cz = tz + Math.cos(an) * (r + 0.45), yw = an + PI; HL.chair(cx, y, cz, yw); seats.push([cx, cz, yw]); KIT.cyl(tx + Math.sin(an) * (r - 0.25), y + 0.78, tz + Math.cos(an) * (r - 0.25), 0.05, 0.13, brass, { seg: 7, col: false }); } };
  table(1.9, 5.6, 3, 0.62); table(7.3, 2.3, 4, 0.72); table(10.4, 4.7, 3, 0.62); table(7.2, 5.4, 4, 0.72); table(1.9, 8.4, 2, 0.5);
  for (const u of [5.6, 6.9, 8.2, 9.5]) { const [sx, sz] = P3(u, 6.75); KIT.cyl(sx, y, sz, 0.04, 0.72, oakD, { seg: 6, col: false }); KIT.cyl(sx, y + 0.72, sz, 0.19, 0.05, oak, { seg: 10, col: false }); KIT.geo(new THREE.TorusGeometry(0.15, 0.012, 4, 10).rotateX(HALF), brass, new THREE.Matrix4().makeTranslation(sx, y + 0.3, sz)); }
  /* a boarded ceiling on heavy joists (the roof space above is the landlady's) */
  KIT.box(x0 + t, y + h, z0 + t, x1 - t, y + h + 0.14, z1 - t, oak, { col: false }); for (let u = 1.4; u < 15; u += 2.05) KIT.box(U(u) - 0.13, y + h - 0.3, z0 + t, U(u) + 0.13, y + h, z1 - t, oakD, { col: false }); KIT.box(x0 + t, y + h - 0.42, W(5.25) - 0.16, x1 - t, y + h - 0.1, W(5.25) + 0.16, oakD, { col: false });
  /* a bench under the front windows; barrels and crates in the corner; light */
  KIT.box(U(6.9), y + 0.4, W(0.55), U(13.6), y + 0.47, W(1.0), oak, { col: false }); KIT.box(U(6.9), y, W(0.5), U(13.6), y + 1.05, W(0.58), oakD, { col: false }); PHY.box(U(6.9), y, W(0.5), U(13.6), y + 0.47, W(1.0));
  for (const [u, v, kd] of [[14.3, 0.9, 'barrel1'], [14.2, 1.9, 'barrel2'], [0.9, 9.6, 'crate']]) if (AST.info(kd)) { const me = AST.mesh(kd); me.position.set(U(u), y, W(v)); me.rotation.y = u; LEVEL.add(me); PHY.cyl(U(u), W(v), 0.45, y, y + 0.9); }
  for (const [u, v] of [[5.2, 4.2], [10.6, 2.6]]) HL.chandelier(L, U(u), y + 3.6, W(v), 0.85, 6, y + h + 2.2, { i: 16, range: 11 }); HL.sl(U(6), y + 2.4, W(8.8), 0xffb060, 9, 8); HL.sl(U(2), y + 2.6, W(3), 0xffc080, 7, 9); HL.sl(U(9), y + 3.4, W(5), 0xffc890, 9, 12);
  /* the ladder-back seats that are taken (the crowd draws them; their living selves when you come near) */
  { const N = HL.STUDENTS || [], adults = ['prof_a', 'prof_b'].filter((k) => CHAR.T[k]); seats.forEach((s, i) => { if (rs() < 0.34) return; const tpl = (i % 4 === 1 && adults.length) ? adults[i % adults.length] : N[(i * 5 + 3) % Math.max(1, N.length)]; if (!tpl || !CHAR.T[tpl]) return; const K = HL.SEAT.chair; (HL.SEATREC = HL.SEATREC || []).push({ tpl, x: s[0] + Math.sin(s[2]) * K[1], z: s[1] + Math.cos(s[2]) * K[1], yaw: s[2], y: y + K[0] - 0.47, sit: true, a: null, sx: s[0], sz: s[1], top: y + K[0] }); }); }
  // ---- HONEYDUKES, at the back of the square: a sweet shop you can walk into — jars to the ceiling, a counter, a table heaped with things that fizz
  { const R2 = HL.HDRECT, hx0 = R2.x0, hx1 = R2.x1, hz0 = R2.z0, hz1 = R2.z1, hy = Math.max(HL.gy(hx0, hz1), HL.gy(hx1, hz1), HL.gy((hx0 + hx1) / 2, hz1)) + 0.12, hh = 4.2, ht = 0.45, ddx = V.x - 1.0; HL.HD = { x0: hx0, x1: hx1, z0: hz0, z1: hz1, y: hy, door: [ddx, hy, hz1 + 1.3] };
    { const y = (q, r) => HL.gy(q, r) + 0.07; for (let x = V.x - 12; x < V.x + 12 - 0.01; x += 4) HL.quad(M.cobble, [x, y(x, hz1 + 0.1), hz1 + 0.1], [x + 4, y(x + 4, hz1 + 0.1), hz1 + 0.1], [x + 4, y(x + 4, V.z - 27), V.z - 27], [x, y(x, V.z - 27), V.z - 27], [0, 1, 0], (p) => [p[0], p[2]]); }
    HL.shell(hx0, hz0, hx1, hz1, hy, hh, { t: ht, mat: M.plaster, floor: I.marble, plinth: false, roof: 'x', rise: 4.4, inside: M.woodD, ops: { Z: [{ p: ddx, w: 1.8, s: 0, hd: 2.6 }, { p: hx0 + 2.3, w: 2.4, s: 0.9, hd: 2.8, bars: 1 }, { p: hx1 - 2.3, w: 2.4, s: 0.9, hd: 2.8, bars: 1 }], z: [], x: [], X: [{ p: hz0 + 4.6, w: 1.6, s: 1.2, hd: 2.8, bars: 1 }] } });
    HL.zone('HONEYDUKES', hx0 + 0.2, hz0 + 0.2, hx1 - 0.2, hz1 - 0.2, hy - 0.5, hy + 8, { hemi: 0.42 });
    KIT.box(ddx - 1.2, hy - 0.5, hz1, ddx + 1.2, hy, hz1 + 0.9, M.trim, { col: true }); KIT.box(hx0 + ht, hy + hh, hz0 + ht, hx1 - ht, hy + hh + 0.14, hz1 - ht, oak, { col: false }); for (let u = hx0 + 1.6; u < hx1 - 0.5; u += 2.2) KIT.box(u - 0.11, hy + hh - 0.26, hz0 + ht, u + 0.11, hy + hh, hz1 - ht, oakD, { col: false });
    /* the shop front: a painted fascia with the name, a striped awning over each window, a timber frame */
    { const tx = HL.signTex('HONEYDUKES', '#5a1c3a', '#ffd9e8'), sm = new THREE.MeshStandardMaterial({ map: tx, roughness: 0.7, emissive: 0x2a0c1c }); sm.userData.tscale = 1; const m4 = new THREE.Matrix4(); m4.setPosition((hx0 + hx1) / 2, hy + 3.5, hz1 + 0.14); KIT.geo(new THREE.PlaneGeometry(5.2, 1.0), sm, m4); KIT.box((hx0 + hx1) / 2 - 2.75, hy + 2.95, hz1 + 0.04, (hx0 + hx1) / 2 + 2.75, hy + 4.05, hz1 + 0.12, oakD, { col: false });
      const aw = [0xe86aa0, 0xfff0f4].map((c) => { const m = new THREE.MeshStandardMaterial({ color: c, roughness: 0.9, side: THREE.DoubleSide }); m.userData.tscale = 1; return m; }); for (const wx of [hx0 + 2.3, hx1 - 2.3]) for (let q = 0; q < 6; q++) { const xa = wx - 1.35 + q * 0.45; HL.quad(aw[q % 2], [xa, hy + 2.95, hz1 + 0.05], [xa + 0.45, hy + 2.95, hz1 + 0.05], [xa + 0.45, hy + 2.45, hz1 + 1.1], [xa, hy + 2.45, hz1 + 1.1], [0, 1, 0.4]); }
      for (const sx of [-1.3, 1.3]) HL.lantern(L, ddx + sx, hy + 2.5, hz1 + 0.45, { i: 12, range: 10 }); }
    /* jars: glass with something bright in it, shoulder to shoulder on four shelves round three walls */
    const candy = [0xff4a6a, 0xffb020, 0x5ad06a, 0x4aa8ff, 0xc060ff, 0xffe24a, 0xff7ad0, 0x40e0d0, 0xff6a2a, 0xf4f0e6].map((c) => { const m = new THREE.MeshStandardMaterial({ color: c, roughness: 0.35, emissive: c, emissiveIntensity: 0.3 }); m.userData.tscale = 1; return m; }), lid = I.brass, rj = mulberry(77);
    const jars = (ax, az, bx, bz, nx, nz) => { const Ln = Math.hypot(bx - ax, bz - az), n = Math.floor(Ln / 0.34); for (let r = 0; r < 4; r++) { const yy = hy + 0.95 + r * 0.66; KIT.box(Math.min(ax, bx) - (nx ? 0 : 0.05), yy - 0.05, Math.min(az, bz) - (nz ? 0 : 0.05), Math.max(ax, bx) + (nx ? 0.36 * Math.abs(nx) : 0.05), yy, Math.max(az, bz) + (nz ? 0.36 * Math.abs(nz) : 0.05), oak, { col: false }); for (let i = 0; i < n; i++) { if (rj() < 0.12) continue; const t = (i + 0.5) / n, jx = lerp(ax, bx, t) + nx * 0.18, jz = lerp(az, bz, t) + nz * 0.18, jh = 0.26 + rj() * 0.14; KIT.cyl(jx, yy, jz, 0.11, jh, candy[(rj() * candy.length) | 0], { seg: 7, col: false }); KIT.cyl(jx, yy + jh, jz, 0.115, 0.035, lid, { seg: 7, col: false }); } } };
    jars(hx0 + ht + 0.02, hz0 + 1.0, hx0 + ht + 0.02, hz1 - 1.2, 1, 0); jars(hx0 + 1.2, hz0 + ht + 0.02, hx1 - 4.4, hz0 + ht + 0.02, 0, 1); jars(hx1 - ht - 0.38, hz0 + 6.2, hx1 - ht - 0.38, hz1 - 1.2, 1, 0);
    PHY.box(hx0 + ht, hy, hz0 + 0.9, hx0 + ht + 0.42, hy + 3.2, hz1 - 1.1); PHY.box(hx0 + 1.1, hy, hz0 + ht, hx1 - 4.3, hy + 3.2, hz0 + ht + 0.42); PHY.box(hx1 - ht - 0.42, hy, hz0 + 6.1, hx1 - ht, hy + 3.2, hz1 - 1.1);
    /* the counter in the back corner with its brass till; the table in the middle, heaped */
    KIT.box(hx1 - 4.0, hy, hz0 + 2.3, hx1 - 0.9, hy + 1.02, hz0 + 3.0, oakD, { col: true }); KIT.box(hx1 - 4.1, hy + 1.02, hz0 + 2.2, hx1 - 0.8, hy + 1.1, hz0 + 3.1, oak, { col: false }); KIT.box(hx1 - 1.9, hy + 1.1, hz0 + 2.45, hx1 - 1.3, hy + 1.5, hz0 + 2.9, lid, { col: false }); for (let q = 0; q < 5; q++) KIT.cyl(hx1 - 3.7 + q * 0.34, hy + 1.1, hz0 + 2.65, 0.1, 0.3, candy[q * 2 % candy.length], { seg: 7, col: false });
    { const tx2 = (hx0 + hx1) / 2 - 0.6, tz2 = hz0 + 5.3; KIT.cyl(tx2, hy, tz2, 0.5, 0.8, oakD, { seg: 10, col: false }); KIT.cyl(tx2, hy + 0.8, tz2, 1.15, 0.07, oak, { seg: 20, col: false }); PHY.cyl(tx2, tz2, 1.1, hy, hy + 0.9); for (let tier = 0; tier < 3; tier++) { const rr = 0.85 - tier * 0.3, ty = hy + 0.87 + tier * 0.34; KIT.cyl(tx2, ty + 0.2, tz2, rr, 0.03, lid, { seg: 16, col: false }); KIT.cyl(tx2, ty, tz2, 0.04, 0.34, lid, { seg: 6, col: false }); const nn = Math.max(4, Math.round(rr * 12)); for (let q = 0; q < nn; q++) { const an = q / nn * TAU + tier; KIT.geo(new THREE.SphereGeometry(0.075 + rj() * 0.03, 7, 5), candy[(q + tier * 3) % candy.length], new THREE.Matrix4().makeTranslation(tx2 + Math.sin(an) * rr * 0.78, ty + 0.3, tz2 + Math.cos(an) * rr * 0.78)); } } }
    for (const [u, v, kd] of [[hx0 + 1.3, hz1 - 1.2, 'barrel1'], [hx1 - 1.3, hz1 - 1.3, 'barrel2']]) if (AST.info(kd)) { const me = AST.mesh(kd); me.position.set(u, hy, v); LEVEL.add(me); PHY.cyl(u, v, 0.45, hy, hy + 0.9); for (let q = 0; q < 7; q++) KIT.geo(new THREE.SphereGeometry(0.1, 7, 5), candy[(q * 3) % candy.length], new THREE.Matrix4().makeTranslation(u + Math.sin(q) * 0.22, hy + 0.98 + (q % 2) * 0.08, v + Math.cos(q * 1.7) * 0.22)); }
    HL.chandelier(L, (hx0 + hx1) / 2, hy + 3.4, hz0 + 4.6, 0.8, 6, hy + hh, { i: 18, range: 11 }); HL.sl(hx0 + 2.2, hy + 2.6, hz1 - 2, 0xffd0e0, 7, 8); HL.sl(hx1 - 2.4, hy + 2.4, hz0 + 3, 0xffe0b0, 7, 8);
    HL.VILDOORS['HONEYDUKES'] = [hx1 - 2.5, hy, hz0 + 3.9]; HL.HD.keep = [hx1 - 2.5, hz0 + 1.5]; }
  /* shopkeepers at their doors along the street */
  HL.VILKEEP = []; { const lines = { 'HONEYDUKES': ['Mr Flume', 'Sugar quills, Fizzing Whizzbees, Chocolate Frogs — mind, the frogs jump.'], 'OLLIVANDERS': ['Mr Ollivander', 'Ah. I wondered when I should be seeing you.'], 'ZONKO’S': ['Mr Zonko', 'Dungbombs are two for a Sickle. I didn’t sell them to you.'], 'SPINTWITCHES': ['Mr Spintwitch', 'She’ll do sixty with the wind behind her.'], 'GLADRAGS': ['Madam Gladrag', 'Robes let out, taken in, or made to forget the whole thing.'], 'TOMES & SCROLLS': ['Mr Tome', 'No reading the stock without buying it. I can tell.'], 'DERVISH & BANGES': ['Mr Banges', 'Bring it back if it starts ticking backwards.'], 'THE HOG’S HEAD': ['The barman', 'We don’t ask names here. Don’t give yours.'] };
    for (const nm in lines) { const d = HL.VILDOORS[nm]; if (d && nm !== 'HONEYDUKES') HL.VILKEEP.push([nm, d, lines[nm]]); } HL.FLUME = lines['HONEYDUKES']; }
});
HL.START.push(function (L) { const T = HL.TB; if (!T) return; const N = HL.STUDENTS || [], y = T.y, U = (u) => T.x0 + u, W = (v) => T.z0 + v, still = (a) => { a.dyMax = 8.5; return a; };
  // ---- Sirona behind the bar; the Butterbeer is ordered across the counter
  const bt = CHAR.T.prof_b ? 'prof_b' : N[0]; if (CHAR.T[bt]) { const a = HL.npc(bt, U(6.2), W(8.9), PI, { y, name: 'Sirona Ryan', base: 'calm', far: 40, talk: ['Speak with Sirona', 'Welcome to the Three Broomsticks! Find a seat if you can — it’s a Hogsmeade weekend.', 'Mind the corner table. They’ve been arguing about Quidditch since noon.'] }); a.x = U(6.2); a.z = W(8.9); a.yaw = PI; HL.TBKEEP = a; }
  HL.interact([U(6.2), y + 1.1, W(7.2)], 2.6, 'Order a Butterbeer', () => { const a = PLAYER.a; a.hp = a.hpMax; HL.P.ancient = Math.min(100, HL.P.ancient + 25); (HL.ui.say || HL.ui.toast)('Sirona Ryan', 'One Butterbeer! Mind the foam. — She slides a tankard down the bar: warm, sweet and frothy. You feel entirely restored.', 5, HL.TBKEEP); HL.ui.pop('BUTTERBEER'); HL.quest.flags.beer = 1; (HL.save.met = HL.save.met || {})['Sirona Ryan'] = 1; FX.spark(V3(U(6.2), y + 1.3, W(7.6)), null, 14, 3, [3, 2.2, 0.8], 0.4); });
  // ---- two at the bar, one warming at the fire, a knot of students outside the door
  for (const [u, v, yw, b] of [[7.6, 6.9, 0.2, 'talk'], [8.6, 6.95, -0.3, 'idle'], [13.2, 4.6, HALF, 'calm']]) { const t = N[((u * 3) | 0) % Math.max(1, N.length)]; if (CHAR.T[t]) { const a = still(HL.npc(t, U(u), W(v), yw, { y, base: b, far: 30 })); a.x = U(u); a.z = W(v); a.yaw = yw; } }
  if (HL.HD && CHAR.T.prof_a) { const D = HL.HD, a = still(HL.npc('prof_a', D.keep[0], D.keep[1], 0, { y: D.y, name: 'Mr Flume', base: 'calm', far: 40, talk: ['Speak with Mr Flume', HL.FLUME ? HL.FLUME[1] : 'Welcome to Honeydukes!', 'Try the Pepper Imps. Smoke comes out of your ears.'] })); a.x = D.keep[0]; a.z = D.keep[1]; a.yaw = 0; for (const [u, v, yw, b] of [[D.x0 + 2.0, D.z0 + 4.4, -HALF, 'idle'], [D.x0 + 4.2, D.z0 + 6.9, 2.6, 'talk'], [D.x0 + 5.3, D.z0 + 7.3, -2.2, 'calm']]) { const t = N[((u * 5) | 0) % Math.max(1, N.length)]; if (CHAR.T[t]) { const c2 = still(HL.npc(t, u, v, yw, { y: D.y, base: b, far: 30 })); c2.x = u; c2.z = v; c2.yaw = yw; } } }
  for (const [nm, d, ln] of HL.VILKEEP || []) { const t = CHAR.T.prof_a && (nm.length % 2) ? 'prof_a' : CHAR.T.prof_b ? 'prof_b' : null; if (!t) continue; const V = HL.VIL, side = d[2] > V.z ? -1 : 1, x = d[0] + 1.5, z = d[2] + side * 0.2, a = still(HL.npc(t, x, z, side > 0 ? 0 : PI, { y: HL.gy(x, z), name: ln[0], base: 'calm', far: 60, talk: ['Speak with ' + ln[0], ln[1], 'Good day to you.'] })); a.x = x; a.z = z; }
});
