/* ==== p78o_hl_grounds.js ==== */
/* THE GROUNDS — fingerposts where the paths fork, and the Whomping Willow on the lawn below the castle: it sways
   until you come near, then it thrashes, and anyone who walks under it is thrown clear. */
HL.BUILD.push(async function grounds(L) { const M = HL.M(), post = (x, z, arms) => { const y = HL.gy(x, z), h0 = HL.h(x, z); /* only on level, open ground (the old paths near the castle now run into its gorge) */ if (HL.inFoot(x, z, 2) || HL.gorge(x, z) > 0.1 || h0 < 3 || Math.abs(HL.h(x + 2, z) - h0) + Math.abs(HL.h(x, z + 2) - h0) > 0.7 || Math.abs(y - h0) > 0.5) return; HL._posts = (HL._posts || 0) + 1; KIT.cyl(x, y - 0.3, z, 0.09, 3.3, M.woodD, { seg: 7, col: false }); KIT.geo(new THREE.ConeGeometry(0.14, 0.26, 7), M.woodD, new THREE.Matrix4().makeTranslation(x, y + 3.13, z)); PHY.cyl(x, z, 0.16, y, y + 3);
      arms.forEach(([txt, yaw], i) => { const tx = HL.signTex(txt, '#3a2a18', '#ecd9a6'), sm = new THREE.MeshStandardMaterial({ map: tx, roughness: 0.85, side: THREE.DoubleSide }); sm.userData.tscale = 1; const yy = y + 2.72 - i * 0.44, cx = x + Math.sin(yaw) * 0.78, cz = z + Math.cos(yaw) * 0.78, m4 = new THREE.Matrix4().makeRotationY(yaw - HALF); m4.setPosition(cx, yy, cz); KIT.geo(new THREE.PlaneGeometry(1.5, 0.36), sm, m4); const sh = new THREE.Shape(); sh.moveTo(-0.76, -0.19); sh.lineTo(0.62, -0.19); sh.lineTo(0.84, 0); sh.lineTo(0.62, 0.19); sh.lineTo(-0.76, 0.19); sh.closePath(); const g = new THREE.ExtrudeGeometry(sh, { depth: 0.035, bevelEnabled: false }); g.translate(0, 0, -0.0175 - 0.022); KIT.geo(g, M.woodD, m4, { worldUV: true }); }); };
  const to = (x, z, tx, tz) => Math.atan2(tx - x, tz - z), V = HL.VIL, C = HL.PITCH, H = HL.HUT;
  post(5.5, 133, [['QUIDDITCH PITCH', to(5.5, 133, 60, 190)], ['GAMEKEEPER', to(5.5, 133, -20, 170)], ['CASTLE', to(5.5, 133, 0, 92)]]);
  post(-113, 236, [['FORBIDDEN FOREST', to(-113, 236, -170, 320)], ['CASTLE', to(-113, 236, -70, 215)], ['OUT OF BOUNDS', to(-113, 236, -170, 320)]]);
  post(-34, -339, [['HOGSMEADE', to(-34, -339, -90, -380)], ['HOGWARTS', to(-34, -339, 0, -240)]]); post(6.5, -300, [['HOGSMEADE', to(6.5, -300, -30, -335)], ['HOGWARTS', to(6.5, -300, 0, -200)]]);
  post(-262, -446, [['HIGH STREET', to(-262, -446, -335, -450)], ['HOGWARTS', to(-262, -446, -190, -428)]]);
  { const Rf = HL.Q && HL.Q.REF; if (Rf) post(Rf[0] - 4, Rf[2] - 5, [['PITCH GATE', to(Rf[0] - 4, Rf[2] - 5, C.x, C.z)], ['HOGWARTS', to(Rf[0] - 4, Rf[2] - 5, 60, 150)]]); }
  for (const [px, pz] of [[H.x + 18, H.z + 12], [H.x + 22, H.z + 16], [H.x + 4, H.z - 12], [H.x + 26, H.z + 20]]) { const n0 = (HL._posts = HL._posts || 0); post(px, pz, [['FORBIDDEN FOREST', to(px, pz, -170, 320)], ['OUT OF BOUNDS', to(px, pz, -170, 320)], ['HOGWARTS', to(px, pz, 0, 150)]]); if (HL._posts > n0) break; }
  // ---- the Whomping Willow
  /* it stands on open lawn: outside the castle, clear of the paths, the hut and the trees, on ground that is nearly level */
  let wx = -70, wz = 290, best = -1; for (let r = 36; r <= 90 && best < 0; r += 9) for (let q = 0; q < 16; q++) { const an = q / 16 * TAU, x = H.x + Math.cos(an) * r, z = H.z + Math.sin(an) * r, h0 = HL.h(x, z); if (HL.inFoot(x, z, 16) || h0 < 6 || HL.pathD(x, z) < 12 || HL.forest(x, z) > 0.25 || Math.abs(HL.h(x + 4, z) - h0) + Math.abs(HL.h(x, z + 4) - h0) > 1.6 || HL.gorge(x, z) > 0.2) continue; const sc = -Math.hypot(x - 20, z - 150); if (best < 0 || sc > best) { best = 1; wx = x; wz = z; break; } }
  const wy = HL.gy(wx, wz); HL.foot(wx - 3, wz - 3, wx + 3, wz + 3);
  const bk = TEX.sets.bark, bark = new THREE.MeshStandardMaterial(bk ? { map: bk.map, normalMap: bk.normalMap, color: 0x9a8c78, roughness: 0.97, envMapIntensity: 0.3 } : { color: 0x4a3c2e, roughness: 1 }), leaf = new THREE.MeshLambertMaterial({ map: WORLD.leafTex(), alphaTest: 0.34, side: THREE.DoubleSide, color: 0x8a9a3a }), root = new THREE.Group(); const tuft = (par, y) => { for (let t = 0; t < 3; t++) { const pl = new THREE.Mesh(new THREE.PlaneGeometry(1.5, 1.5), leaf); pl.position.y = y - 0.2; pl.rotation.set(0.5, t * 1.05, 0.2); par.add(pl); } }; root.position.set(wx, wy - 0.3, wz); LEVEL.add(root);
  { const trunk = new THREE.CylinderGeometry(0.75, 1.5, 5.2, 10, 6), p = trunk.attributes.position; for (let i = 0; i < p.count; i++) { const yy = p.getY(i), an = Math.atan2(p.getZ(i), p.getX(i)), k = 1 + 0.16 * Math.sin(an * 5 + yy * 1.3) + 0.1 * Math.sin(an * 3 - yy * 2.1); p.setXYZ(i, p.getX(i) * k + Math.sin(yy * 0.7) * 0.25, yy, p.getZ(i) * k); } trunk.translate(0, 2.6, 0); trunk.computeVertexNormals(); const tm = new THREE.Mesh(trunk, bark); tm.castShadow = true; root.add(tm);
    for (let q = 0; q < 6; q++) { const an = q / 6 * TAU + 0.3, g = new THREE.CylinderGeometry(0.16, 0.5, 2.6, 6); g.translate(0, 1.3, 0); const rm = new THREE.Mesh(g, bark); rm.position.set(Math.cos(an) * 0.9, 0.5, Math.sin(an) * 0.9); rm.rotation.set(0, -an, -1.95, 'YXZ'); root.add(rm); } }
  const limbs = []; for (let b = 0; b < 11; b++) { const an = b / 11 * TAU + (b % 2) * 0.25, base = new THREE.Group(); base.position.set(Math.cos(an) * 0.35, 4.7 + (b % 3) * 0.25, Math.sin(an) * 0.35); base.rotation.y = -an; root.add(base); let par = base; const segs = []; for (let s = 0; s < 4; s++) { const len = 2.5 - s * 0.38, r0 = 0.46 - s * 0.09, r1 = 0.38 - s * 0.09, piv = new THREE.Group(); piv.position.set(0, s ? 2.5 - (s - 1) * 0.38 : 0, 0); par.add(piv); const g = new THREE.CylinderGeometry(Math.max(0.05, r1), r0, len, 6); g.translate(0, len / 2, 0); const m = new THREE.Mesh(g, bark); m.castShadow = true; piv.add(m); if (s === 3) { const kn = new THREE.Mesh(new THREE.SphereGeometry(0.34, 7, 5), bark); kn.scale.set(1, 1.25, 1); kn.position.y = len; piv.add(kn); tuft(piv, len + 0.3); } if (s === 2) tuft(piv, len * 0.8); segs.push(piv); par = piv; } limbs.push({ segs, ph: b * 1.7, an }); }
  PHY.cyl(wx, wz, 1.3, wy - 1, wy + 6); HL.WILLOW = { x: wx, z: wz, y: wy, rage: 0, hitT: 0, root };
  L.updates.push((dt, t) => { const W = HL.WILLOW, P = PLAYER.a; if (!P) return; const d = Math.hypot(P.x - wx, P.z - wz), near = d < 16 && Math.abs(P.y - wy) < 9 && PLAYER.state !== 'fly'; if (d > 220) return; W.rage = damp(W.rage, near ? 1 : 0, near ? 2.5 : 0.8, dt);
    for (const lb of limbs) { const sp = 0.7 + W.rage * 5.2, amp = 0.07 + W.rage * 0.42; lb.segs.forEach((piv, s) => { piv.rotation.z = (s === 0 ? 0.95 : 0.34) + Math.sin(t * sp + lb.ph + s * 0.9) * amp * (0.5 + s * 0.35); piv.rotation.x = Math.sin(t * sp * 0.8 + lb.ph * 1.7 + s) * amp * 0.7; }); }
    W.hitT -= dt; if (near && d < 7.2 && W.rage > 0.6 && W.hitT <= 0 && P.alive) { W.hitT = 1.6; const dx = (P.x - wx) / (d || 1), dz = (P.z - wz) / (d || 1); COMBAT.damage(P, 9, { src: null, kind: 'blast', dir: V3(dx, 0, dz), heavy: true, unblockable: true, p: P.chest(new THREE.Vector3()) }); FX.addShake(0.4); if (!W.told || MG.rt - W.told > 20) { W.told = MG.rt; HL.ui.toast('THE WHOMPING WILLOW', 'It does not like visitors. It has never liked visitors.', 4); (HL.save.met = HL.save.met || {})['The Whomping Willow'] = 1; } } });
});
