/* ==== p78r_hl_air.js ==== */
/* THE AIR OUT OF DOORS, toward evening: leaves coming down off the courtyard trees, turning as they fall, lit by the low
   sun; and rooks going home across the sky over the bridge and the towers. */
HL.START.push(function (L) {
  /* the characters' own fill and rim light are for dim rooms; in the low sun out of doors they burned faces and necks white. They are turned down in the open and up again under a roof. */
  { let k = 1; L.updates.push((dt) => { const a = PLAYER.a; if (!a) return; const inside = !!HL.zoneAt(a.x, a.y + 1, a.z) || a.y < HL.Y0 - 4; k = damp(k, inside ? 1 : 0, 3, dt); CM.fillU.value.setRGB(lerp(0.13, 0.46, k), lerp(0.13, 0.46, k), lerp(0.16, 0.5, k)); CM.rimU.value.setRGB(lerp(0.3, 0.8, k), lerp(0.19, 0.5, k), lerp(0.1, 0.28, k)); }); }
  // ---- falling leaves: a cloud that stays about the camera out of doors, each leaf a small tumbling quad drawn as a point
  { const N = 260, B = 44, HB = 16, pos = new Float32Array(N * 3), ph = new Float32Array(N), rs = mulberry(808); for (let i = 0; i < N; i++) { pos[i * 3] = rs() * B; pos[i * 3 + 1] = rs() * HB; pos[i * 3 + 2] = rs() * B; ph[i] = rs() * 6.28; }
    const g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.BufferAttribute(pos, 3)); g.setAttribute('aPh', new THREE.BufferAttribute(ph, 1));
    const U = { uT: { value: 0 }, uC: { value: new THREE.Vector3() }, uK: { value: 0 } };
    const m = new THREE.ShaderMaterial({ uniforms: U, transparent: true, depthWrite: false,
      vertexShader: 'uniform float uT; uniform vec3 uC; attribute float aPh; varying float vA; varying float vPh; varying float vSp; void main() { float fall = uT * (0.55 + 0.35 * fract(aPh * 3.7)); vec3 p = position + vec3(sin(uT * 0.5 + aPh) * 1.6 + uT * 0.35, -fall + sin(uT * 1.3 + aPh * 2.0) * 0.25, cos(uT * 0.37 + aPh * 1.3) * 1.6); p.xz = mod(p.xz - uC.xz + 22.0, 44.0) - 22.0 + uC.xz; p.y = mod(p.y - uC.y + 6.0, 16.0) - 6.0 + uC.y; vec4 mv = modelViewMatrix * vec4(p, 1.0); float d = -mv.z; vA = smoothstep(1.0, 3.5, d) * (1.0 - smoothstep(22.0, 34.0, d)); vPh = aPh; vSp = uT * (2.0 + fract(aPh * 5.1) * 3.0) + aPh * 4.0; gl_PointSize = clamp(210.0 / d, 2.0, 30.0); gl_Position = projectionMatrix * mv; }',
      fragmentShader: 'uniform float uK; varying float vA; varying float vPh; varying float vSp; void main() { vec2 q = gl_PointCoord - 0.5; float cs = cos(vSp), sn = sin(vSp); q = vec2(q.x * cs - q.y * sn, q.x * sn + q.y * cs); q.y /= max(0.18, abs(sin(vSp * 0.6))); float lf = 1.0 - smoothstep(0.16, 0.2, length(q * vec2(1.0, 1.9))); if (lf * vA * uK < 0.02) discard; float k = fract(vPh * 1.9); vec3 col = mix(mix(vec3(0.95, 0.52, 0.10), vec3(0.98, 0.78, 0.16), k), vec3(0.72, 0.22, 0.08), smoothstep(0.7, 1.0, k)); col *= 0.75 + 0.5 * abs(sin(vSp * 0.6)); gl_FragColor = vec4(col, lf * vA * uK); }' });
    const pts = new THREE.Points(g, m); pts.frustumCulled = false; pts.renderOrder = 3; LEVEL.add(pts); HL.LEAVES = pts;
    L.updates.push((dt, t) => { const a = PLAYER.a, c = R.camera.position; U.uT.value = t; U.uC.value.copy(c); /* out of doors, about the castle and its lawns (not over the lake, not in the forest's dark, not in a match) */ const out = !!a && !HL.Q.on && !HL.zoneAt(c.x, c.y, c.z) && !HL.zoneAt(a.x, a.y + 1, a.z) && c.y > 20 && c.y < HL.Y0 + 60 && Math.hypot(c.x - 20, c.z - 60) < 420 && !(a.y < HL.Y0 - 4 && HL.inFoot(a.x, a.z, 0)); U.uK.value = damp(U.uK.value, out ? 1 : 0, out ? 1.5 : 7, dt); /* (gone within a breath of stepping under a roof: the cloud follows the eye, and would follow it indoors) */ pts.visible = U.uK.value > 0.01; }); }
  // ---- rooks going home: two loose flights crossing high over the bridge and the Clock Tower, wings beating
  { const g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute([0, 0, 0.32, 0.95, 0.3, -0.12, 0, 0, -0.26, 0, 0, 0.32, 0, 0, -0.26, -0.95, 0.3, -0.12], 3)); g.computeVertexNormals();
    const n = 34, im = new THREE.InstancedMesh(g, new THREE.MeshBasicMaterial({ color: 0x15131a, side: THREE.DoubleSide, fog: true }), n), m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), e = new THREE.Euler(), rs = mulberry(4040), B = []; im.frustumCulled = false; im.castShadow = false; LEVEL.add(im); HL.ROOKS = im;
    for (let i = 0; i < n; i++) B.push({ fl: i < 20 ? 0 : 1, ox: (rs() - 0.5) * 46, oy: (rs() - 0.5) * 10, oz: (rs() - 0.5) * 30, ph: rs() * 6.28, sp: 0.9 + rs() * 0.25 });
    const paths = [{ c: [0, HL.Y0 + 62, -40], rx: 230, rz: 120, w: 0.062, a0: 0 }, { c: [-40, HL.Y0 + 84, 110], rx: 190, rz: 240, w: -0.045, a0: 2.2 }];
    L.updates.push((dt, t) => { if (HL.Q.on) { if (im.visible) im.visible = false; return; } im.visible = true; for (let i = 0; i < n; i++) { const b = B[i], P = paths[b.fl], an = P.a0 + t * P.w * b.sp + b.ph * 0.02, x = P.c[0] + Math.cos(an) * P.rx + b.ox, z = P.c[2] + Math.sin(an) * P.rz + b.oz, y = P.c[1] + b.oy + Math.sin(t * 0.4 + b.ph) * 2.5, hx = -Math.sin(an) * P.rx * P.w, hz = Math.cos(an) * P.rz * P.w, fl = Math.sin(t * 9 + b.ph); e.set(0, Math.atan2(hx, hz), fl * 0.12); q.setFromEuler(e); m4.compose(V3(x, y, z), q, V3(1.5, fl * 1.7 + 0.2, 1.5)); im.setMatrixAt(i, m4); } im.instanceMatrix.needsUpdate = true; }); }
});
/* THE GIANT SQUID, off the long bridge: a few arms lifted lazily out of the loch where anyone crossing can see them. */
HL.BUILD.push(async function squid(L) { let sx = 0, sz = 0, best = 1e9; for (let z = -230; z <= -100; z += 10) for (const x of [34, 46, 58, 70, -34, -46, -58, -70]) { if (HL.lake(x, z) < 0.92 || HL.h(x, z) > -6) continue; const d = Math.abs(Math.abs(x) - 44) + Math.abs(z + 150) * 0.4; if (d < best) { best = d; sx = x; sz = z; } } if (best > 1e8) return;
  const skin = new THREE.MeshStandardMaterial({ color: 0x4e2a30, roughness: 0.36, metalness: 0.05, envMapIntensity: 1.0 }), pale = new THREE.MeshStandardMaterial({ color: 0xc8a79a, roughness: 0.4 }), root = new THREE.Group(); root.position.set(sx, -0.6, sz); root.scale.setScalar(2.3); LEVEL.add(root);
  const arms = []; for (let b = 0; b < 6; b++) { const an = b / 6 * TAU + 0.4, rad = 2.5 + (b % 3) * 2.2, base = new THREE.Group(); base.position.set(Math.cos(an) * rad, 0, Math.sin(an) * rad); base.rotation.y = -an + HALF; root.add(base); let par = base; const segs = [], big = b % 2 === 0, n = big ? 8 : 6; for (let s = 0; s < n; s++) { const len = (big ? 1.7 : 1.2) * (1 - s * 0.045), r0 = (big ? 0.55 : 0.36) * (1 - s / n * 0.86), r1 = (big ? 0.55 : 0.36) * (1 - (s + 1) / n * 0.86), piv = new THREE.Group(); piv.position.y = s ? (big ? 1.7 : 1.2) * (1 - (s - 1) * 0.045) : 0; par.add(piv); const g = new THREE.CylinderGeometry(Math.max(0.03, r1), r0, len, 8); g.translate(0, len / 2, 0); const m = new THREE.Mesh(g, skin); m.castShadow = true; piv.add(m); if (s > 1 && s < n - 1) for (const k of [0.3, 0.7]) { const sk = new THREE.Mesh(new THREE.SphereGeometry(r0 * 0.3, 6, 4), pale); sk.position.set(0, len * k, r0 * 0.82); piv.add(sk); } segs.push(piv); par = piv; } arms.push({ segs, ph: b * 1.9, big }); }
  HL.SQUID = { x: sx, z: sz, seen: 0 }; const v = new THREE.Vector3(), f = new THREE.Vector3();
  L.updates.push((dt, t) => { const c = R.camera.position, d = Math.hypot(c.x - sx, c.z - sz); root.visible = d < 420 && !HL.Q.on; if (!root.visible) return; const rise = 0.5 + 0.5 * Math.sin(t * 0.21); root.position.y = -5.5 + rise * 4.2;
    for (const a of arms) a.segs.forEach((piv, s) => { const w = a.big ? 0.9 : 1.3; piv.rotation.z = (s === 0 ? 0.25 : 0.2) + Math.sin(t * 0.6 * w + a.ph + s * 0.55) * (0.16 + s * 0.035); piv.rotation.x = Math.sin(t * 0.43 * w + a.ph * 1.3 + s * 0.4) * 0.14; });
    const P = PLAYER.a, S = HL.SQUID; if (P && !S.told && d < 150 && MG.state === 'play' && !CAM.cine) { R.camera.getWorldDirection(f); v.set(sx - c.x, 2 - c.y, sz - c.z).normalize(); S.seen = f.dot(v) > 0.93 ? S.seen + dt : 0; if (S.seen > 1.6) { S.told = 1; HL.ui.toast('THE GIANT SQUID', 'It waves at the first-years every September. One or two of them wave back.', 5.5); (HL.save.met = HL.save.met || {})['The Giant Squid'] = 1; } } });
});
