/* ==== p78y_hl_crowd.js ==== */
/* HOGWARTS — the crowd. Only the nearest couple of dozen people are whole animated characters. Everyone else who stays
   where they are (at table, at a desk, in a knot of talk) is drawn as a still figure: baked once from the same character
   in the same attitude — its colours photographed from nine sides onto its vertices, its mesh thinned — and instanced,
   so a hall of a hundred and fifty costs a couple of dozen draw calls. A still figure gives way to its living character
   when you come near, and takes over again when you leave. */
HL.START.push(function (L) { if (!HL.npcs || !HL.npcs.length || MG.flags.nocrowd) return; const t00 = performance.now();
  const walk = new Set((HL.walkers || []).map((w) => w.a)), v = new THREE.Vector3(), v2 = new THREE.Vector3(), SKIP = /^(eyes|brows)$/, r = R.renderer;
  // ---- the photographer: nine orthographic views of a figure standing at the origin, colour and depth
  const W = 320, EXT = 1.3, NEARZ = 0.2, FARZ = 6, f32 = !!(r.capabilities.isWebGL2 && r.extensions.has('EXT_color_buffer_float'));
  const rtC = new THREE.WebGLRenderTarget(W, W, { type: f32 ? THREE.FloatType : THREE.UnsignedByteType }), rtD = new THREE.WebGLRenderTarget(W, W), sc = new THREE.Scene(), amb = new THREE.AmbientLight(0xffffff, Math.PI); sc.add(amb);
  const depthMat = new THREE.MeshDepthMaterial({ depthPacking: THREE.RGBADepthPacking, side: THREE.DoubleSide });
  const views = [[0, 0, 1], [0, 0, -1], [1, 0, 0], [-1, 0, 0], [0, 1, 0], [0.62, 0.48, 0.62], [-0.62, 0.48, 0.62], [0.62, 0.48, -0.62], [-0.62, 0.48, -0.62]].map((d) => { const dir = new THREE.Vector3(d[0], d[1], d[2]).normalize(), cam = new THREE.OrthographicCamera(-EXT, EXT, EXT, -EXT, NEARZ, FARZ); if (d[1] === 1) cam.up.set(0, 0, 1); cam.position.copy(dir).multiplyScalar(3).add(v.set(0, 1, 0)); cam.lookAt(0, 1, 0); cam.updateMatrixWorld(true); cam.updateProjectionMatrix();
    return { dir, cam, col: f32 ? new Float32Array(W * W * 4) : new Uint8Array(W * W * 4), dep: new Uint8Array(W * W * 4) }; });
  const prt = r.getRenderTarget(), pcc = new THREE.Color(); r.getClearColor(pcc); const pca = r.getClearAlpha(), pac = r.autoClear, fill0 = CM.fillU.value.clone(), rim0 = CM.rimU.value.clone(); CM.fillU.value.setRGB(0, 0, 0); CM.rimU.value.setRGB(0, 0, 0); r.autoClear = true;
  const shoot = () => { for (const vw of views) { r.setRenderTarget(rtC); r.setClearColor(0x000000, 0); sc.overrideMaterial = null; r.render(sc, vw.cam); r.readRenderTargetPixels(rtC, 0, 0, W, W, vw.col); r.setRenderTarget(rtD); r.setClearColor(0xffffff, 1); sc.overrideMaterial = depthMat; r.render(sc, vw.cam); r.readRenderTargetPixels(rtD, 0, 0, W, W, vw.dep); } sc.overrideMaterial = null; };
  /* white of known albedo, to turn what is read back into albedo */
  let gain = 1; { const ref = new THREE.Mesh(new THREE.SphereGeometry(0.5, 12, 8), new THREE.MeshStandardMaterial({ color: 0xffffff, roughness: 1, metalness: 0 })); ref.position.y = 1; sc.add(ref); shoot(); const o = ((W >> 1) * W + (W >> 1)) * 4, c = views[0].col[o] / (f32 ? 1 : 255); gain = c > 0.01 ? 1 / c : 1; sc.remove(ref); ref.geometry.dispose(); ref.material.dispose(); }
  const order = views.map((_, i) => i), dots = new Float32Array(views.length), UD = 255 / 256, cs = f32 ? 1 : 1 / 255;
  const colourAt = (p, n, out) => { for (let i = 0; i < views.length; i++) dots[i] = views[i].dir.dot(n); order.sort((a, b) => dots[b] - dots[a]); let got = false;
    for (const i of order) { if (dots[i] < 0.1 && got) break; const vw = views[i]; v2.copy(p).project(vw.cam); const px = Math.round((v2.x * 0.5 + 0.5) * W - 0.5), py = Math.round((v2.y * 0.5 + 0.5) * W - 0.5); if (px < 0 || py < 0 || px >= W || py >= W) continue; const o = (py * W + px) * 4; if (vw.col[o + 3] * cs < 0.5) continue;
      if (!got) { out[0] = vw.col[o] * cs * gain; out[1] = vw.col[o + 1] * cs * gain; out[2] = vw.col[o + 2] * cs * gain; got = true; }
      const d = UD * (vw.dep[o] / 255 / 16777216 + vw.dep[o + 1] / 255 / 65536 + vw.dep[o + 2] / 255 / 256 + vw.dep[o + 3] / 255); if (Math.abs(d - (v2.z * 0.5 + 0.5)) * (FARZ - NEARZ) < 0.03) { out[0] = vw.col[o] * cs * gain; out[1] = vw.col[o + 1] * cs * gain; out[2] = vw.col[o + 2] * cs * gain; return true; } }
    return got; };
  /* a posed character → one thinned mesh in its own frame (feet at the origin, facing +Z), colours on its vertices */
  const bake = (a) => { const cl = a.inst.cloth, cv = cl && cl.visible; if (cl) { cl.visible = true; cl.reset(); } /* a hidden character's robes are not simulated: let them fall into their hang first */ const hy = ((a.x * 7.3 + a.z * 3.1) % 2 + 2) % 2 < 1 ? 1 : -1; a.lookYaw = -0.42 * hy; for (let q = 0; q < 5; q++) { a.animate(0.21); a.pose3D(0.05); } a.root.updateMatrixWorld(true); if (a.inst.cloth) a.inst.cloth.group.updateMatrixWorld(true);
    const inv = new THREE.Matrix4().makeRotationY(a.yaw).setPosition(a.x, a.y, a.z).invert(), meshes = [], tmp = [], full = [];
    a.root.traverse((q) => { if (q.isMesh && !SKIP.test(q.name || '')) meshes.push(q); }); if (a.inst.cloth) a.inst.cloth.group.traverse((q) => { if (q.isMesh) meshes.push(q); });
    for (const q of meshes) { const g = q.geometry, pa = g.attributes.position, na = g.attributes.normal; if (!pa || !na) continue; const n = pa.count, P = new Float32Array(n * 3), N = new Float32Array(n * 3), mw = q.matrixWorld, sk = q.isSkinnedMesh && q.skeleton, abt = q.applyBoneTransform || q.boneTransform;
      for (let i = 0; i < n; i++) { v.fromBufferAttribute(pa, i); v2.fromBufferAttribute(na, i).multiplyScalar(0.01).add(v); /* weights that do not sum to one scale the vertex about the WORLD origin (the bones are world matrices): divide it back out */ let ws = 1; if (sk) { abt.call(q, i, v); abt.call(q, i, v2); const w4 = g.attributes.skinWeight; ws = 1 / ((w4.getX(i) + w4.getY(i) + w4.getZ(i) + w4.getW(i)) || 1); } v.applyMatrix4(mw).multiplyScalar(ws).applyMatrix4(inv); v2.applyMatrix4(mw).multiplyScalar(ws).applyMatrix4(inv).sub(v).normalize(); P[i * 3] = v.x; P[i * 3 + 1] = v.y; P[i * 3 + 2] = v.z; N[i * 3] = v2.x; N[i * 3 + 1] = v2.y; N[i * 3 + 2] = v2.z; }
      /* the faces that are really drawn: within the draw range, and not the skin a garment hides (its vertices carry no weight and collapse to a point) */
      const sw = sk ? g.attributes.skinWeight : null, live = (i) => !sw || sw.getX(i) + sw.getY(i) + sw.getZ(i) + sw.getW(i) > 0.01, gi = g.index ? g.index.array : null, total = gi ? gi.length : n, d0 = g.drawRange.start || 0, d1 = Math.min(total, d0 + (isFinite(g.drawRange.count) ? g.drawRange.count : total)), idx2 = [], grp = [];
      for (const gr of (Array.isArray(q.material) && g.groups.length ? g.groups : [{ start: 0, count: total, materialIndex: 0 }])) { const s0 = idx2.length; for (let t = Math.max(gr.start, d0); t + 2 < Math.min(gr.start + gr.count, d1); t += 3) { const a2 = gi ? gi[t] : t, b2 = gi ? gi[t + 1] : t + 1, c2 = gi ? gi[t + 2] : t + 2; if (live(a2) && live(b2) && live(c2)) idx2.push(a2, b2, c2); } grp.push([s0, idx2.length - s0, gr.materialIndex]); }
      if (!idx2.length || q.visible === false) continue;
      const g2 = new THREE.BufferGeometry(); for (const nm in g.attributes) if (!/^(position|normal|skinIndex|skinWeight)$/.test(nm)) g2.setAttribute(nm, g.attributes[nm]); g2.setAttribute('position', new THREE.BufferAttribute(P, 3)); g2.setAttribute('normal', new THREE.BufferAttribute(N, 3)); g2.setIndex(n > 65535 ? new THREE.Uint32BufferAttribute(idx2, 1) : new THREE.Uint16BufferAttribute(idx2, 1)); if (Array.isArray(q.material)) for (const gr of grp) g2.addGroup(gr[0], gr[1], gr[2]);
      const m = new THREE.Mesh(g2, q.material); m.frustumCulled = false; sc.add(m); tmp.push(m); full.push({ q, P, N, idx: idx2, n, cell: /head|hair/i.test(q.name || '') ? 0.03 : sk ? 0.065 : 0.07 }); }
    shoot(); for (const m of tmp) { sc.remove(m); m.geometry.dispose(); }
    /* the second attitude of the same figure: a moment later in its movement, the head turned the other way. A still figure is drawn easing between the two (each in its own time), so a hall of them is never frozen */
    { a.lookYaw = 0.5 * hy; for (let q = 0; q < 6; q++) { a.animate(0.27); a.pose3D(0.05); } a.root.updateMatrixWorld(true); if (a.inst.cloth) a.inst.cloth.group.updateMatrixWorld(true);
      for (const f of full) { const q = f.q, g = q.geometry, pa = g.attributes.position, mw = q.matrixWorld, sk = q.isSkinnedMesh && q.skeleton, abt = q.applyBoneTransform || q.boneTransform, P2 = f.P2 = new Float32Array(f.n * 3), w4 = sk ? g.attributes.skinWeight : null; for (let i = 0; i < f.n; i++) { v.fromBufferAttribute(pa, i); let ws = 1; if (sk) { abt.call(q, i, v); ws = 1 / ((w4.getX(i) + w4.getY(i) + w4.getZ(i) + w4.getW(i)) || 1); } v.applyMatrix4(mw).multiplyScalar(ws).applyMatrix4(inv); /* never far from the first attitude: a vertex that would fly (cloth re-settling) stays put */ const dx = v.x - f.P[i * 3], dy = v.y - f.P[i * 3 + 1], dz = v.z - f.P[i * 3 + 2], d = Math.hypot(dx, dy, dz), k = d > 0.3 ? 0.3 / d : 1; P2[i * 3] = f.P[i * 3] + dx * k; P2[i * 3 + 1] = f.P[i * 3 + 1] + dy * k; P2[i * 3 + 2] = f.P[i * 3 + 2] + dz * k; } }
      a.lookYaw = 0; if (cl) cl.visible = cv; }
    // thin: vertices of one part in the same small cell, facing the same way, become one
    const oP = [], oQ = [], oN = [], oC = [], oI = [], c3 = [0, 0, 0]; for (const f of full) { const map = new Map(), re = new Int32Array(f.n).fill(-1), cnt = [], base = oP.length / 3, cell = f.cell, P = f.P, N = f.N, P2 = f.P2 || f.P;
      const id = (i) => { if (re[i] >= 0) return re[i]; const o = (N[i * 3] > 0 ? 1 : 0) + (N[i * 3 + 2] > 0 ? 4 : 0), key = (((Math.round(P[i * 3] / cell) + 512) * 1024 + Math.round(P[i * 3 + 1] / cell) + 512) * 1024 + Math.round(P[i * 3 + 2] / cell) + 512) * 8 + o; let j = map.get(key); if (j === undefined) { j = cnt.length; map.set(key, j); cnt.push(0); oP.push(0, 0, 0); oQ.push(0, 0, 0); oN.push(0, 0, 0); oC.push(0, 0, 0); }
        v.set(P[i * 3], P[i * 3 + 1], P[i * 3 + 2]); const nn = new THREE.Vector3(N[i * 3], N[i * 3 + 1], N[i * 3 + 2]); if (!colourAt(v, nn, c3)) { c3[0] = c3[1] = c3[2] = 0.05; } const s = (base + j) * 3; cnt[j]++; for (let c = 0; c < 3; c++) { oP[s + c] += P[i * 3 + c]; oQ[s + c] += P2[i * 3 + c]; oN[s + c] += N[i * 3 + c]; oC[s + c] += c3[c]; } return (re[i] = j); };
      const tot = f.idx ? f.idx.length : f.n; for (let t = 0; t + 2 < tot; t += 3) { const a2 = id(f.idx ? f.idx[t] : t), b = id(f.idx ? f.idx[t + 1] : t + 1), c = id(f.idx ? f.idx[t + 2] : t + 2); if (a2 !== b && b !== c && a2 !== c) oI.push(base + a2, base + b, base + c); }
      for (let j = 0; j < cnt.length; j++) { const s = (base + j) * 3, l = Math.hypot(oN[s], oN[s + 1], oN[s + 2]) || 1; for (let c = 0; c < 3; c++) { oP[s + c] /= cnt[j]; oQ[s + c] /= cnt[j]; oN[s + c] /= l; oC[s + c] /= cnt[j]; } } }
    const g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(oP, 3)); g.setAttribute('normal', new THREE.Float32BufferAttribute(oN, 3)); g.setAttribute('color', new THREE.Float32BufferAttribute(oC, 3)); g.setAttribute('aPos2', new THREE.Float32BufferAttribute(oQ, 3)); g.setIndex(oP.length / 3 > 65535 ? new THREE.Uint32BufferAttribute(oI, 1) : new THREE.Uint16BufferAttribute(oI, 1)); g.computeBoundingSphere();
    return { g, tris: oI.length / 3 }; };
  // ---- the one material every still figure wears: its photographed colours, the characters' own fill light, and a slow sway of the shoulders so a full table is never quite still
  const U = { uCT: { value: 0 } }, mat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.86, metalness: 0, side: THREE.DoubleSide, envMapIntensity: 0.8 });
  mat.onBeforeCompile = (sh) => { sh.uniforms.uCT = U.uCT; sh.uniforms.uFill = CM.fillU; sh.uniforms.uRim = CM.rimU;
    sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nuniform float uCT; attribute vec3 aPos2;').replace('#include <begin_vertex>', '#include <begin_vertex>\n#ifdef USE_INSTANCING\n{ float ph = instanceMatrix[3].x * 3.1 + instanceMatrix[3].z * 5.7, up = smoothstep(0.55, 1.5, position.y); float w2 = smoothstep(0.18, 0.82, 0.5 + 0.5 * sin(uCT * (0.38 + 0.5 * fract(ph * 0.37)) + ph * 2.0)); transformed = mix(transformed, aPos2, w2); transformed.x += sin(uCT * 0.9 + ph) * 0.016 * up; transformed.z += sin(uCT * 0.63 + ph * 1.7) * 0.02 * up; }\n#endif');
    sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\nuniform vec3 uFill; uniform vec3 uRim;').replace('#include <aomap_fragment>', '#include <aomap_fragment>\n' + CM.FILL); };
  mat.customProgramCacheKey = () => 'hlfigures2';
  // ---- who stands still: everyone indoors (and at table) who is not a walker or a ghost
  const who = HL.npcs.filter((a) => a.tplN && !a.seatRec && !a.ghost && !a.noProxy && !walk.has(a) && !a.dead && (a.sitY !== undefined || a.dyMax === 8.5)).map((a) => ({ a, tpl: a.tplN, x: a.x, z: a.z, yaw: a.yaw, y: a.sitY !== undefined ? a.sitY : a.y, sit: a.sitY !== undefined })).concat(HL.SEATREC || []);
  const baked = {}, buckets = {}, zero = new THREE.Matrix4().makeScale(0, 0, 0), stat = { people: who.length, kinds: 0, tris: 0, per: 0, draws: 0, ms: 0, f32 };
  const first = {}; for (const r of who) if (r.a && !first[r.tpl + (r.sit ? '|s' : '|u')]) first[r.tpl + (r.sit ? '|s' : '|u')] = r.a;
  for (const a of who) { const k = HL.kAt(a.y + 0.5), P = HL.plan(k), i = Math.floor(HL.PL.X0 - a.x), j = Math.floor(HL.PL.Z0 - a.z), cid = i >= 0 && j >= 0 && i < P.NX && j < P.NZ ? P.comp[j * P.NX + i] : -1;
    const room = a.y < HL.Y0 - 3 ? 'd' + Math.round(a.x / 40) + '_' + Math.round(a.z / 40) : cid >= 0 && /^(room|corr|court)$/.test(P.comps[cid].kind || '') ? k + ':' + cid : 'o' + k + '_' + Math.round(a.x / 50) + '_' + Math.round(a.z / 50);
    const kind = a.tpl + (a.sit ? '|s' : '|u'), key = kind + '|' + room; if (!baked[kind]) { baked[kind] = bake(first[kind] || HL.seatWake(a)); stat.kinds++; stat.per += baked[kind].tris; } (buckets[key] = buckets[key] || { kind, acts: [] }).acts.push(a); }
  r.setRenderTarget(prt); r.setClearColor(pcc, pca); r.autoClear = pac; CM.fillU.value.copy(fill0); CM.rimU.value.copy(rim0); rtC.dispose(); rtD.dispose(); depthMat.dispose();
  /* the living character only takes a figure's place close by; beyond that the still figure stands in (walkers keep their own range) */ for (const r2 of who) if (r2.a) r2.a.farD = Math.min(r2.a.farD, r2.a.clubFar || 10.5);
  HL.NEAR = HL.NEAR || []; const all = [];
  for (const key in buckets) { const b = buckets[key], B = baked[b.kind], n = b.acts.length; let x0 = 1e9, x1 = -1e9, z0 = 1e9, z1 = -1e9, y = 0; b.mats = b.acts.map((a) => { x0 = Math.min(x0, a.x); x1 = Math.max(x1, a.x); z0 = Math.min(z0, a.z); z1 = Math.max(z1, a.z); y += a.y / n; return new THREE.Matrix4().makeRotationY(a.yaw).setPosition(a.x, a.y, a.z); });
    b.shown = new Uint8Array(n).fill(1); const im = new THREE.InstancedMesh(B.g, mat, n); b.mats.forEach((m, i) => im.setMatrixAt(i, m)); im.instanceMatrix.needsUpdate = true; if (im.computeBoundingSphere) im.computeBoundingSphere(); else im.frustumCulled = false; im.castShadow = false; im.receiveShadow = true; im.userData.near = [(x0 + x1) / 2, y + 1, (z0 + z1) / 2, Math.max(x1 - x0, z1 - z0) / 2 + 34, 7.5]; im.visible = false; LEVEL.add(im); HL.NEAR.push(im); b.im = im; stat.draws++; stat.tris += B.tris * n; all.push(b); }
  stat.per = Math.round(stat.per / Math.max(1, stat.kinds)); stat.ms = Math.round(performance.now() - t00); HL.CROWD = stat; HL._crowdMat = mat; let t = 0;
  L.updates.push((dt, tt) => { U.uCT.value = tt; t -= dt; if (t > 0) return; t = 0.2; const cp = R.camera.position; let wake = 1; /* one sleeper a tick is given its living character */ for (const b of all) { if (!b.im.visible) continue; let dirty = false; const O = HL.stillOut; for (let i = 0; i < b.acts.length; i++) { const rc = b.acts[i], gone = O && rc.x > O.x0 && rc.x < O.x1 && rc.z > O.z0 && rc.z < O.z1 && Math.abs(rc.y - O.y) < 3; /* (a scene can empty a room: its sitters neither wake nor stand in) */ if (!gone && !rc.a && wake > 0 && Math.abs(rc.y - cp.y) < 5 && Math.hypot(rc.x - cp.x, rc.z - cp.z) < 9.5) { HL.seatWake(rc); wake--; } const want = gone ? 0 : !rc.a || rc.a.hiddenN ? 1 : 0; if (want !== b.shown[i]) { b.shown[i] = want; dirty = true; b.im.setMatrixAt(i, want ? b.mats[i] : zero); } } if (dirty) b.im.instanceMatrix.needsUpdate = true; } });
});
