/* ==== p80_hl_loot.js ==== */
/* HOGWARTS — gear, loot and the inventory (after the GRIMHOLD kit's LOOT): wands, robes, brooms and charms in four
   rarities (common · magic · rare · legendary) with rolled affixes and a handful of named legendaries; potions; galleons;
   drops from the fallen and from chests about the grounds, each with a pillar of rarity light; shops in Hogsmeade;
   the inventory (worn items · 30-slot pack · live stats · compare on hover) on I / Tab. Bonuses are summed into HL.G. */
Object.assign(IN.ACT, { inv: { k: ['KeyI', 'Tab'], p: 86 }, potion: { k: ['KeyG'], p: 85 } });
const LOOTH = { bag: [], BAG: 30, eq: {}, pots: { wiggen: 2, edurus: 0, maxima: 0, focus: 0 }, gold: 0, nid: 1, owned: {}, drops: [], chests: [], buffs: {} };
HL.LOOT = LOOTH; HL.G = { power: 0, haste: 0, crit: 0.05, hp: 0, ward: 0, regen: 0, ancient: 0, speed: 0, boost: 0, luck: 0 };
LOOTH.SLOTS = ['wand', 'robe', 'broom', 'charm', 'charm2']; LOOTH.SLOTN = { wand: 'Wand', robe: 'Robes', broom: 'Broom', charm: 'Charm', charm2: 'Charm' };
LOOTH.RAR = [{ n: 'Common', c: '#d8d2c4', g: [0.9, 0.84, 0.72] }, { n: 'Magic', c: '#86a2ff', g: [0.32, 0.5, 1.7] }, { n: 'Rare', c: '#ffd75e', g: [1.7, 1.25, 0.28] }, { n: 'Legendary', c: '#ff8f33', g: [2.3, 0.78, 0.14] }];
LOOTH.BASE = {
  wand: [{ b: 'Ash Wand', wood: 0xc8b494, power: 0 }, { b: 'Willow Wand', wood: 0xa88a5c, power: 4 }, { b: 'Holly Wand', wood: 0x5a3a22, power: 8 }, { b: 'Blackthorn Wand', wood: 0x1e1814, power: 12 }, { b: 'Yew Wand', wood: 0x7a2e1c, power: 16 }, { b: 'Elder Wand', wood: 0xd8d0c0, power: 22 }],
  robe: [{ b: 'School Robes', hp: 0, look: 'school' }, { b: 'Travelling Cloak', hp: 12, look: 'school' }, { b: 'Duelling Robes', hp: 22, look: 'duel' }, { b: 'Dragonhide Coat', hp: 36, look: 'duel' }],
  broom: [{ b: 'Shooting Star', speed: 0, col: 0x5a3a20 }, { b: 'Cleansweep', speed: 6, col: 0x6a4a28 }, { b: 'Comet', speed: 10, col: 0x4a2c18 }, { b: 'Nimbus', speed: 16, col: 0x2a1a12 }, { b: 'Firebolt', speed: 24, col: 0x7a2a12 }],
  charm: [{ b: 'Charm', gem: 0x6aa0ff }, { b: 'Amulet', gem: 0x60d080 }, { b: 'Signet Ring', gem: 0xff6a5a }, { b: 'Talisman', gem: 0xd8a0ff }],
};
LOOTH.AFX = {
  power: { p: 'Potent', s: 'of Force', lo: 4, hi: 24, f: '+{v}% spell damage', on: 'wand charm robe' },
  haste: { p: 'Quick', s: 'of Haste', lo: 3, hi: 16, f: '−{v}% spell cooldowns', on: 'wand charm' },
  crit: { p: 'Keen', s: 'of the Hawk', lo: 2, hi: 12, f: '+{v}% critical cast chance', on: 'wand charm' },
  hp: { p: 'Hale', s: 'of the Bear', lo: 8, hi: 50, f: '+{v} maximum health', on: 'robe charm' },
  ward: { p: 'Warded', s: 'of Shielding', lo: 3, hi: 18, f: '−{v}% damage taken', on: 'robe charm' },
  regen: { p: 'Mending', s: 'of Renewal', lo: 1, hi: 5, f: '+{v} health per second', on: 'robe charm' },
  ancient: { p: 'Ancient', s: 'of the Old Ways', lo: 6, hi: 40, f: '+{v}% Ancient Magic gained', on: 'wand charm' },
  speed: { p: 'Swift', s: 'of the Gale', lo: 3, hi: 14, f: '+{v}% broom speed', on: 'broom charm' },
  boost: { p: 'Tireless', s: 'of Endurance', lo: 8, hi: 40, f: '+{v}% boost reserve', on: 'broom' },
  luck: { p: 'Lucky', s: 'of Fortune', lo: 6, hi: 40, f: '+{v}% galleons found', on: 'charm robe' },
};
LOOTH.W1 = ['Phoenix', 'Dragon', 'Unicorn', 'Thestral', 'Founder’s', 'Midnight', 'Sorcerer’s', 'Runic', 'Gilded', 'Whispering', 'Storm', 'Ember'];
LOOTH.W2 = { wand: ['Wand', 'Core', 'Spire'], robe: ['Mantle', 'Vestment', 'Shroud'], broom: ['Comet', 'Arrow', 'Gale'], charm: ['Seal', 'Locket', 'Eye'], charm2: ['Seal', 'Locket', 'Eye'] };
LOOTH.UNIQ = {
  elder: { slot: 'wand', b: 'Elder Wand', wood: 0xe4dccc, name: 'The Deathstick', r: 3, power: 30, fx: { power: 20, crit: 12, ancient: 30 }, flav: 'Elder and thestral hair. It has never lost a duel for its true master.' },
  holly: { slot: 'wand', b: 'Holly Wand', wood: 0x6a4428, name: 'Holly and Phoenix Feather', r: 3, power: 18, fx: { haste: 16, ancient: 40, crit: 6 }, flav: 'Eleven inches, nice and supple. The wand chooses the wizard.' },
  firebolt: { slot: 'broom', b: 'Firebolt', col: 0x8a2a10, name: 'Firebolt Supreme', r: 3, speed: 30, fx: { speed: 12, boost: 40 }, flav: 'Ash handle, diamond-hard polish. Nought to a hundred and fifty in ten seconds.' },
  cloak: { slot: 'robe', b: 'Dragonhide Coat', look: 'duel', name: 'Cloak of the Marauder', r: 3, hp: 45, fx: { ward: 16, regen: 4, luck: 30 }, flav: 'Mischief managed.' },
  turner: { slot: 'charm', b: 'Talisman', gem: 0xffd060, name: 'The Time-Turner', r: 3, fx: { haste: 22, ancient: 30 }, flav: 'An hourglass on a fine gold chain. Three turns should do it.' },
  stone: { slot: 'charm', b: 'Signet Ring', gem: 0xc02a2a, name: 'Resurrection Stone', r: 3, fx: { hp: 60, regen: 5, ward: 8 }, flav: 'Cracked down the middle. It still remembers.' },
};
LOOTH.RANDOM_UNIQ = ['holly', 'firebolt', 'cloak', 'turner'];
LOOTH.POT = { wiggen: { n: 'Wiggenweld Potion', d: 'Restores 70 health', c: '#58d06a', price: 40 }, edurus: { n: 'Edurus Potion', d: 'Halves damage taken for 20 s', c: '#c8a060', price: 70 }, maxima: { n: 'Maxima Potion', d: '+50% spell damage for 20 s', c: '#e05a4a', price: 90 }, focus: { n: 'Focus Potion', d: 'Cooldowns twice as fast for 15 s', c: '#5a9aff', price: 90 } };
LOOTH.rollR = function (bias) { const w = [[58, 30, 10, 2], [22, 44, 28, 6], [0, 48, 40, 12], [0, 0, 60, 40]][bias || 0]; let x = rnd(0, w[0] + w[1] + w[2] + w[3]); for (let i = 0; i < 4; i++) { x -= w[i]; if (x <= 0) return i; } return 0; };
LOOTH.make = function (o) {
  o = o || {}; const slot0 = o.slot || ['wand', 'robe', 'broom', 'charm', 'charm', 'wand'][rndi(0, 5)], slot = slot0 === 'charm2' ? 'charm' : slot0;
  let r = o.r !== undefined ? o.r : LOOTH.rollR(o.bias || 0); if (r === 3) { const u = LOOTH.RANDOM_UNIQ.filter((k) => !LOOTH.owned[k] && (!o.slot || LOOTH.UNIQ[k].slot === slot)); if (u.length) return LOOTH.unique(u[rndi(0, u.length - 1)]); r = 2; }
  const il = o.il || clamp(2 + Math.floor((HL.save.points || 0) / 60) + rndi(0, 2), 1, 10), bases = LOOTH.BASE[slot], bi = Math.min(bases.length - 1 - (slot === 'wand' ? 1 : 0), Math.max(0, Math.floor(rnd(0, bases.length) * lerp(0.5, 1, clamp(il / 8, 0, 1)) + (r >= 2 ? 0.6 : 0)))), B = bases[bi], rk = [1, 1.06, 1.12, 1.2][r];
  const it = { id: LOOTH.nid++, slot, b: B.b, r, il, fx: {} }; for (const k of ['wood', 'look', 'col', 'gem']) if (B[k] !== undefined) it[k] = B[k];
  if (B.power !== undefined) it.power = Math.round(B.power * rk + il * 0.6); if (B.hp !== undefined) it.hp = Math.round(B.hp * rk + il); if (B.speed !== undefined) it.speed = Math.round(B.speed * rk + il * 0.3);
  const n = [0, rndi(1, 2), rndi(2, 3), 0][r], pool = Object.keys(LOOTH.AFX).filter((k) => LOOTH.AFX[k].on.split(' ').includes(slot)), picked = [];
  for (let i = 0; i < n && pool.length; i++) { const k = pool.splice(rndi(0, pool.length - 1), 1)[0], a = LOOTH.AFX[k]; picked.push(k); it.fx[k] = Math.max(1, Math.round(lerp(a.lo, a.hi, clamp(il / 10, 0.1, 1)) * rnd(0.62, 1.0) * rk)); }
  if (r === 0) it.name = B.b; else if (r === 1) it.name = (picked[0] ? LOOTH.AFX[picked[0]].p + ' ' : '') + B.b + (picked[1] ? ' ' + LOOTH.AFX[picked[1]].s : ''); else it.name = LOOTH.W1[rndi(0, LOOTH.W1.length - 1)] + ' ' + LOOTH.W2[slot][rndi(0, 2)];
  return it;
};
LOOTH.unique = function (key) { const U_ = LOOTH.UNIQ[key], it = Object.assign({ id: LOOTH.nid++, uq: key, il: 9, fx: {} }, JSON.parse(JSON.stringify(U_))); LOOTH.owned[key] = 1; return it; };
LOOTH.value = (it) => Math.round((10 + (it.il || 1) * 4) * [1, 2.2, 4.5, 12][it.r] + Object.keys(it.fx).length * 6);
LOOTH.sum = function () { const G = HL.G; Object.assign(G, { power: 0, haste: 0, crit: 5, hp: 0, ward: 0, regen: 0, ancient: 0, speed: 0, boost: 0, luck: 0 });
  for (const s of LOOTH.SLOTS) { const it = LOOTH.eq[s]; if (!it) continue; if (it.power) G.power += it.power; if (it.hp) G.hp += it.hp; if (it.speed) G.speed += it.speed; for (const k in it.fx) G[k] += it.fx[k]; }
  const B = LOOTH.buffs; if (B.maxima > 0) G.power += 50; if (B.edurus > 0) G.ward += 50; if (B.focus > 0) G.haste += 50;
  for (const k of ['power', 'haste', 'crit', 'ward', 'ancient', 'speed', 'boost', 'luck']) G[k] /= 100; G.haste = Math.min(0.7, G.haste); G.ward = Math.min(0.75, G.ward);
  const a = PLAYER.a; if (a) { const m = 100 + G.hp, f = a.hp / a.hpMax; a.hpMax = m; a.hp = Math.min(m, Math.max(a.hp, f * m)); } return G; };
LOOTH.store = function () { HL.save.inv = { bag: LOOTH.bag, eq: LOOTH.eq, pots: LOOTH.pots, gold: LOOTH.gold, nid: LOOTH.nid, owned: LOOTH.owned, opened5: LOOTH.chests.filter((c) => c.open).map((c) => c.id) }; HL.store(); };
LOOTH.restore = function (fresh) { const s = HL.save.inv; if (s && !fresh) { LOOTH.bag = s.bag || []; LOOTH.eq = s.eq || {}; LOOTH.pots = Object.assign({ wiggen: 0, edurus: 0, maxima: 0, focus: 0 }, s.pots); LOOTH.gold = s.gold || 0; LOOTH.nid = s.nid || 1; LOOTH.owned = s.owned || {}; for (const c of LOOTH.chests) LOOTH.setChest(c, (s.opened5 || []).includes(c.id)); }
  else { LOOTH.bag = []; LOOTH.eq = { wand: { id: LOOTH.nid++, slot: 'wand', b: 'Ash Wand', name: 'Ash Wand', r: 0, il: 1, fx: {}, wood: 0xc8b494, power: 0 }, robe: { id: LOOTH.nid++, slot: 'robe', b: 'School Robes', name: 'School Robes', r: 0, il: 1, fx: {}, hp: 0, look: 'school' }, broom: { id: LOOTH.nid++, slot: 'broom', b: 'Shooting Star', name: 'Shooting Star', r: 0, il: 1, fx: {}, speed: 0, col: 0x5a3a20 } }; LOOTH.pots = { wiggen: 2, edurus: 0, maxima: 0, focus: 0 }; LOOTH.gold = 30; LOOTH.owned = {}; for (const c of LOOTH.chests) LOOTH.setChest(c, false); }
  LOOTH.sum(); LOOTH.wear(); };
/* what you wear shows: the wand in your hand, the broom you ride */
LOOTH.wear = function () { const a = PLAYER.a; if (!a) return; const w = LOOTH.eq.wand; if (a.wand && a.wand.parent) a.wand.parent.remove(a.wand); a.wand = HL.wand(w ? w.wood : 0x2e1c12); if (w && w.r >= 2) a.wand.userData.rare = 1; R.scene.add(a.wand); if (PLAYER.state === 'fly') a.wand.visible = false; };
LOOTH.give = function (it, quiet) { if (!it) return false; const slot = it.slot === 'charm' && LOOTH.eq.charm && !LOOTH.eq.charm2 ? 'charm2' : it.slot; if (!LOOTH.eq[slot]) { LOOTH.eq[slot] = it; LOOTH.sum(); LOOTH.wear(); } else if (LOOTH.bag.length < LOOTH.BAG) LOOTH.bag.push(it); else { LOOTH.gold += LOOTH.value(it); if (!quiet) HL.ui.toast('', 'Pack full — ' + it.name + ' sold for ' + LOOTH.value(it) + ' galleons'); return true; }
  if (!quiet) { const rr = LOOTH.RAR[it.r]; HL.ui.itemPop(it); if (it.r >= 2) { FX.addShake(0.1); } } LOOTH.fresh = (LOOTH.fresh || 0) + 1; LOOTH.store(); return true; };
LOOTH.equip = function (i) { const it = LOOTH.bag[i]; if (!it) return; let slot = it.slot; if (slot === 'charm' && LOOTH.eq.charm && !LOOTH.eq.charm2) slot = 'charm2'; const cur = LOOTH.eq[slot]; LOOTH.eq[slot] = it; if (cur) LOOTH.bag[i] = cur; else LOOTH.bag.splice(i, 1); LOOTH.sum(); LOOTH.wear(); LOOTH.store(); };
LOOTH.unequip = function (slot) { const it = LOOTH.eq[slot]; if (!it || slot === 'wand' || LOOTH.bag.length >= LOOTH.BAG) return; delete LOOTH.eq[slot]; LOOTH.bag.push(it); LOOTH.sum(); LOOTH.store(); };
LOOTH.sell = function (i) { const it = LOOTH.bag[i]; if (!it) return; LOOTH.gold += LOOTH.value(it); LOOTH.bag.splice(i, 1); LOOTH.store(); };
LOOTH.drink = function (k) { const a = PLAYER.a; if (!a || !a.alive || !(LOOTH.pots[k] > 0)) { HL.ui.pop('NO POTIONS'); return; } if (k === 'wiggen' && a.hp >= a.hpMax) return; LOOTH.pots[k]--; const P = LOOTH.POT[k];
  if (k === 'wiggen') a.hp = Math.min(a.hpMax, a.hp + 70); else { LOOTH.buffs[k] = k === 'focus' ? 15 : 20; LOOTH.sum(); }
  const c = new THREE.Color(P.c); FX.puff(V3(a.x, a.y + 1.2, a.z), 14, { add: true, size: 0.25, grow: 2, col: [c.r * 2, c.g * 2, c.b * 2], a: 0.7, life: 0.9, spread: 1.4, rise: 1.2 }); HL.ui.spellName(P.n); LOOTH.store(); };
/* ------------------------------------------------------------------ icons: drawn, tinted by the item */
LOOTH.icons = {};
LOOTH.icon = function (it) { const key = it.slot[0] + (it.wood || it.col || it.gem || it.look || '') + it.r + (it.uq || ''); if (LOOTH.icons[key]) return LOOTH.icons[key];
  const N = 128, c = document.createElement('canvas'); c.width = c.height = N; const x = c.getContext('2d'), rr = LOOTH.RAR[it.r], hex = (v) => '#' + new THREE.Color(v).getHexString();
  const g = x.createRadialGradient(64, 64, 6, 64, 64, 64); g.addColorStop(0, `rgba(${rr.g.map((v) => Math.min(255, v * 110 | 0)).join(',')},${0.22 + it.r * 0.12})`); g.addColorStop(1, 'rgba(0,0,0,0)'); x.fillStyle = g; x.fillRect(0, 0, N, N); x.lineCap = 'round'; x.lineJoin = 'round';
  if (it.slot === 'wand') { x.save(); x.translate(64, 64); x.rotate(-0.78); const w = hex(it.wood); const lg = x.createLinearGradient(-50, 0, 54, 0); lg.addColorStop(0, w); lg.addColorStop(1, '#fff'); x.fillStyle = w; x.strokeStyle = 'rgba(0,0,0,0.6)'; x.lineWidth = 2; x.beginPath(); x.moveTo(-52, -6); x.lineTo(-22, -5.5); x.lineTo(54, -1.2); x.lineTo(54, 1.2); x.lineTo(-22, 5.5); x.lineTo(-52, 6); x.closePath(); x.fill(); x.stroke();
    x.fillStyle = 'rgba(0,0,0,0.3)'; for (const u of [-46, -38, -30]) x.fillRect(u, -6, 2.5, 12); x.fillStyle = 'rgba(255,255,255,0.3)'; x.fillRect(-50, -4.5, 102, 1.6); if (it.r >= 1) { x.fillStyle = rr.c; x.beginPath(); x.arc(-22, 0, 4, 0, TAU); x.fill(); }
    x.restore(); x.fillStyle = '#fff'; x.shadowColor = rr.c; x.shadowBlur = 14; for (const [sx, sy, s] of [[104, 22, 4], [112, 36, 2], [94, 14, 2.4]]) { x.beginPath(); x.moveTo(sx, sy - s * 2); x.lineTo(sx + s * 0.5, sy - s * 0.5); x.lineTo(sx + s * 2, sy); x.lineTo(sx + s * 0.5, sy + s * 0.5); x.lineTo(sx, sy + s * 2); x.lineTo(sx - s * 0.5, sy + s * 0.5); x.lineTo(sx - s * 2, sy); x.lineTo(sx - s * 0.5, sy - s * 0.5); x.fill(); } }
  else if (it.slot === 'broom') { x.save(); x.translate(64, 64); x.rotate(-0.7); x.strokeStyle = hex(it.col); x.lineWidth = 6; x.beginPath(); x.moveTo(-10, 0); x.quadraticCurveTo(24, -5, 56, 2); x.stroke(); x.strokeStyle = '#c8a058'; x.lineWidth = 1.6; for (let i = 0; i < 16; i++) { const a = (i / 15 - 0.5) * 0.9; x.beginPath(); x.moveTo(-10, 0); x.lineTo(-10 - Math.cos(a) * (40 + (i % 3) * 6), Math.sin(a) * 30); x.stroke(); } x.fillStyle = '#d8b050'; x.fillRect(-16, -7, 5, 14); x.fillRect(-26, -10, 4, 20); x.restore(); }
  else if (it.slot === 'robe') { const col = it.look === 'duel' ? '#3a2018' : '#16161c', H = HL.H(); x.fillStyle = col; x.strokeStyle = 'rgba(255,255,255,0.25)'; x.lineWidth = 2; x.beginPath(); x.moveTo(64, 14); x.lineTo(84, 22); x.lineTo(110, 50); x.lineTo(98, 62); x.lineTo(88, 52); x.lineTo(94, 114); x.lineTo(34, 114); x.lineTo(40, 52); x.lineTo(30, 62); x.lineTo(18, 50); x.lineTo(44, 22); x.closePath(); x.fill(); x.stroke();
    x.fillStyle = H.css; x.beginPath(); x.moveTo(56, 18); x.lineTo(64, 34); x.lineTo(72, 18); x.lineTo(76, 22); x.lineTo(68, 114); x.lineTo(60, 114); x.lineTo(52, 22); x.closePath(); x.fill(); x.fillStyle = H.css2; x.fillRect(61, 40, 6, 3); x.fillRect(61, 52, 6, 3); }
  else { x.strokeStyle = '#d8b050'; x.lineWidth = 3; x.beginPath(); x.arc(64, 44, 26, 0.3 * PI, 0.7 * PI, true); x.stroke(); x.fillStyle = '#d8b050'; x.beginPath(); x.arc(64, 82, 21, 0, TAU); x.fill(); const gg = x.createRadialGradient(58, 76, 2, 64, 82, 16); gg.addColorStop(0, '#fff'); gg.addColorStop(0.3, hex(it.gem || 0x6aa0ff)); gg.addColorStop(1, '#101018'); x.fillStyle = gg; x.beginPath(); x.arc(64, 82, 15, 0, TAU); x.fill(); }
  return (LOOTH.icons[key] = c.toDataURL()); };
/* ------------------------------------------------------------------ on the ground: a turning token under a pillar of light */
LOOTH.drop = function (it, x, y, z, gold) { const g = new THREE.Group(), rr = it ? LOOTH.RAR[it.r].g : [1.6, 1.2, 0.3]; const core = HL.sprite(rr, 3, 0.7); core.position.y = 0.5; g.add(core);
  const beam = new THREE.Mesh(new THREE.CylinderGeometry(0.05, 0.16, it ? 3 + it.r * 2.2 : 1.4, 8, 1, true), new THREE.MeshBasicMaterial({ color: new THREE.Color(rr[0] * 1.6, rr[1] * 1.6, rr[2] * 1.6), transparent: true, opacity: it ? 0.3 + it.r * 0.12 : 0.25, blending: THREE.AdditiveBlending, depthWrite: false, toneMapped: false, side: THREE.DoubleSide })); beam.position.y = (it ? 3 + it.r * 2.2 : 1.4) / 2; g.add(beam);
  g.position.set(x, y, z); R.scene.add(g); LOOTH.drops.push({ g, it, gold: gold || 0, x, y, z, t: 0, vy: 4 }); };
LOOTH.dropFrom = function (e) { const big = e.big || e.type === 'darkmage', y = HL.gy(e.x, e.z); LOOTH.drop(null, e.x + rnd(-0.6, 0.6), y, e.z + rnd(-0.6, 0.6), Math.round(rnd(6, 16) * (big ? 5 : 1) * (1 + HL.G.luck)));
  if (big || RNG() < 0.42) LOOTH.drop(LOOTH.make({ bias: big ? 2 : 0 }), e.x + rnd(-1, 1), y, e.z + rnd(-1, 1)); if (RNG() < 0.3) { LOOTH.pots.wiggen++; HL.ui.pop('+1 WIGGENWELD'); } };
/* chests: [id, x, y (null = ground), z, yaw, tier] */
LOOTH.CH = [];
LOOTH.setChest = function (c, open) { c.open = open; if (c.glow) c.glow.visible = !open; if (c.use) c.use.off = open; };
LOOTH.placeChests = function (L) { LOOTH.chests = [];
  for (const d of LOOTH.CH) { if (HL.occ && d[2] !== null && d[2] > HL.Y0 - 3 && d[0] !== 'first' && HL.inFoot(d[1], d[3], 0) && d[3] > -40) { const sp = HL.occ.spot(HL.kAt(d[2] + 0.5), d[1], d[3], 0.6, 7, 3); if (sp) { d[1] = sp[0]; d[3] = sp[1]; } }
    const y = d[2] !== null ? d[2] : HL.dropY(d[1], d[3], 60), me = AST.mesh('chest'); me.position.set(d[1], y, d[3]); me.rotation.y = d[4]; if (HL.inFoot && HL.kAt && HL.inFoot(d[1], d[3], 0) && Math.abs(d[1]) < 140 && d[3] > -56) { const tg = y < HL.Y0 - 3 ? 'in' : 'pr' + HL.kAt(y + 0.5); me.traverse((o) => { if (o.isMesh) { o.userData.tag = tg; o.castShadow = false; } }); } LEVEL.add(me); PHY.cyl(d[1], d[3], 0.5, y, y + 0.8);
    const tier = d[5], gc = tier >= 3 ? [2.3, 0.9, 0.2] : tier === 2 ? [1.7, 1.3, 0.3] : [0.5, 0.7, 1.6], glow = HL.sprite(gc, 1.6, 1.8); glow.position.set(d[1], y + 0.9, d[3]); LEVEL.add(glow);
    const c = { id: d[0], x: d[1], y, z: d[3], tier, glow, open: false }; c.use = HL.interact([d[1], y + 0.6, d[3]], 2.4, tier >= 3 ? 'Unlock the great chest (a charmed lock)' : 'Unlock the chest (a charmed lock)', () => LOOTH.openChest(c)); LOOTH.chests.push(c); } };
LOOTH.openChest = function (c) { if (c.open) return; LOOTH.setChest(c, true); const n = c.tier >= 3 ? 3 : c.tier === 2 ? 2 : 1; FX.spark(V3(c.x, c.y + 0.8, c.z), V3(0, 1, 0), 30, 6, [3, 2.4, 1], 0.8); FX.flashLight(V3(c.x, c.y + 1, c.z), [1, 0.8, 0.4], 20, 12, 0.4);
  for (let i = 0; i < n; i++) { const a = rnd(0, TAU); LOOTH.drop(i === 0 && c.tier >= 3 ? LOOTH.make({ r: 3 }) : LOOTH.make({ bias: c.tier >= 2 ? 2 : 1 }), c.x + Math.cos(a) * 1.3, c.y, c.z + Math.sin(a) * 1.3); }
  LOOTH.drop(null, c.x, c.y, c.z + 1.0, Math.round(rnd(30, 60) * c.tier * (1 + HL.G.luck))); if (RNG() < 0.6) { const k = ['wiggen', 'edurus', 'maxima', 'focus'][rndi(0, 3)]; LOOTH.pots[k]++; HL.ui.pop('+1 ' + LOOTH.POT[k].n.toUpperCase()); } HL.save.points = (HL.save.points || 0) + 5 * c.tier; LOOTH.store(); };
LOOTH.update = function (dt) { const a = PLAYER.a; if (!a) return; const B = LOOTH.buffs; let ch = false; for (const k in B) if (B[k] > 0) { B[k] -= dt; if (B[k] <= 0) ch = true; } if (ch) LOOTH.sum();
  if (HL.G.regen && a.alive && a.hp < a.hpMax) a.hp = Math.min(a.hpMax, a.hp + HL.G.regen * dt);
  for (let i = LOOTH.drops.length - 1; i >= 0; i--) { const d = LOOTH.drops[i]; d.t += dt; d.g.rotation.y += dt * 2; d.g.children[0].position.y = 0.5 + Math.sin(d.t * 3) * 0.08; if (d.t > 0.4 && Math.hypot(a.x - d.x, a.z - d.z) < 1.7 && Math.abs(a.y - d.y) < 3) {
      if (d.it) { if (!LOOTH.give(d.it)) continue; } else { LOOTH.gold += d.gold; HL.ui.pop('+' + d.gold + ' GALLEONS'); LOOTH.store(); } R.scene.remove(d.g); LOOTH.drops.splice(i, 1); FX.spark(V3(d.x, d.y + 0.6, d.z), null, 12, 4, [3, 2.4, 1], 0.4); } }
  if (IN.take('potion')) LOOTH.drink('wiggen'); };
/* ------------------------------------------------------------------ the inventory screen */
LOOTH.css = `
.hlInv { position: absolute; inset: 0; background: radial-gradient(ellipse at 50% 45%, rgba(14,10,6,.55), rgba(0,0,0,.92) 78%); display: flex; align-items: center; justify-content: center; }
.hlInv .box { position: relative; width: min(1180px, 96vw); display: grid; grid-template-columns: 250px 300px 1fr; gap: 0 28px; padding: 22px 30px 22px; background: linear-gradient(180deg, rgba(30,23,15,.97), rgba(12,9,6,.98)); border: 1px solid #6a5436; box-shadow: 0 0 0 1px #000, 0 30px 80px #000; }
.hlInv .box:before { content: ''; position: absolute; inset: 8px; border: 1px solid rgba(201,164,92,.18); pointer-events: none; }
.hlInv h2 { grid-column: 1 / -1; font-family: 'HLA', serif; font-weight: 500; letter-spacing: .44em; font-size: 24px; margin: 0 0 14px; text-align: center; color: #e2c07a; }
.hlInv .sh { font-family: 'HLA', serif; font-size: 12px; letter-spacing: .3em; color: rgba(232,207,148,.7); padding-bottom: 6px; margin-bottom: 12px; border-bottom: 1px solid rgba(201,164,92,.22); display: flex; justify-content: space-between; }
.hlInv .st { display: flex; justify-content: space-between; padding: 3.5px 2px; border-bottom: 1px solid rgba(201,164,92,.08); color: rgba(233,223,201,.66); font-size: 15px; } .hlInv .st b { font-family: 'HLA', serif; color: #efe5cf; font-size: 14px; font-weight: 400; }
.hlInv .gold { margin-top: 14px; font-family: 'HLA', serif; font-size: 20px; color: #f0cf7a; text-align: center; } .hlInv .gold:before { content: ''; display: inline-block; width: 18px; height: 18px; margin-right: 8px; vertical-align: -3px; border-radius: 50%; background: radial-gradient(circle at 35% 30%, #fff2c0, #d8a840 45%, #7a5412 80%); }
.hlSlot { position: relative; width: 72px; height: 72px; background: rgba(0,0,0,.45); border: 1px solid #4a3a26; cursor: pointer; pointer-events: auto; } .hlSlot i { position: absolute; inset: 3px; background-size: contain; background-repeat: no-repeat; background-position: center; }
.hlSlot:hover { border-color: #fff3c4; } .hlSlot.r0.full { border-color: #8a8272; } .hlSlot.r1.full { border-color: #86a2ff; box-shadow: inset 0 0 14px rgba(80,120,255,.35); } .hlSlot.r2.full { border-color: #ffd75e; box-shadow: inset 0 0 14px rgba(255,200,60,.35); } .hlSlot.r3.full { border-color: #ff8f33; box-shadow: inset 0 0 18px rgba(255,120,30,.5); }
.hlSlot span { position: absolute; left: 0; right: 0; bottom: -17px; text-align: center; font-size: 11px; letter-spacing: .12em; color: rgba(233,223,201,.5); font-family: 'HLA', serif; } .hlSlot em { position: absolute; right: 3px; bottom: 1px; font-style: normal; font-family: 'HLA', serif; font-size: 14px; color: #fff; text-shadow: 0 1px 3px #000; }
.hlEq { display: grid; grid-template-columns: repeat(3, 72px); gap: 30px 22px; justify-content: center; margin-bottom: 26px; } .hlBag { display: grid; grid-template-columns: repeat(6, 72px); gap: 7px; } .hlPots { display: flex; gap: 12px; justify-content: center; margin-top: 8px; }
.hlInv .hint { grid-column: 1 / -1; margin-top: 16px; font-size: 13px; color: rgba(233,223,201,.5); font-style: italic; text-align: center; } .hlInv .hint b { font-style: normal; color: #e2c07a; }
#hlTip { position: fixed; z-index: 60; display: none; width: 300px; padding: 12px 14px; background: linear-gradient(180deg, rgba(26,19,12,.985), rgba(9,7,5,.99)); border: 1px solid #6a5436; box-shadow: 0 0 0 1px #000, 0 18px 50px #000; pointer-events: none; font-size: 15px; color: #e6dcc6; }
#hlTip .tn { font-family: 'HLA', serif; font-size: 18px; line-height: 1.2; } #hlTip .tt { font-style: italic; color: rgba(233,223,201,.56); font-size: 13px; margin: 2px 0 8px; } #hlTip .tb div { display: flex; justify-content: space-between; } #hlTip .tb b { color: #fff; font-family: 'HLA', serif; font-weight: 400; }
#hlTip .ta div { color: #a4b8ff; padding-left: 12px; position: relative; } #hlTip .ta div:before { content: ''; position: absolute; left: 1px; top: .6em; width: 5px; height: 5px; transform: rotate(45deg); background: currentColor; } #hlTip .tf { margin-top: 8px; font-style: italic; color: #c8a878; font-size: 13.5px; } #hlTip .tk { margin-top: 8px; font-size: 12.5px; color: rgba(233,223,201,.5); } #hlTip .up { color: #86e07e; } #hlTip .dn { color: #ff7d6c; }
#hlGold { position: absolute; right: 34px; top: 84px; font-family: 'HLA', serif; font-size: 16px; color: #f0cf7a; text-shadow: 0 1px 4px #000; } #hlPot { position: absolute; left: 104px; bottom: 96px; font-size: 13px; letter-spacing: .1em; text-shadow: 0 1px 4px #000; font-family: 'HLA', serif; color: #bfe8c4; }
#hlItem { position: absolute; left: 34px; top: 40%; width: 300px; padding: 10px 14px 10px 86px; min-height: 76px; background: linear-gradient(90deg, rgba(10,8,6,.85), rgba(10,8,6,0)); border-left: 3px solid var(--rc, #d8d2c4); opacity: 0; transition: opacity .4s; } #hlItem.on { opacity: 1; } #hlItem i { position: absolute; left: 8px; top: 6px; width: 68px; height: 68px; background-size: contain; background-repeat: no-repeat; } #hlItem .a { font-family: 'HLA', serif; font-size: 17px; color: var(--rc); } #hlItem .b { font-size: 13px; color: #cfc6b0; font-style: italic; }
`;
LOOTH.lines = function (it) { const out = []; if (it.slot === 'wand') out.push(['Spell power', '+' + (it.power || 0) + '%']); if (it.hp !== undefined && it.slot === 'robe') out.push(['Health', '+' + it.hp]); if (it.slot === 'broom') out.push(['Speed', '+' + (it.speed || 0) + '%']); return out; };
LOOTH.score = (it) => !it ? 0 : (it.power || 0) + (it.hp || 0) * 0.5 + (it.speed || 0) + Object.values(it.fx).reduce((s, v) => s + v, 0);
LOOTH.tipHtml = function (it, mode, price) { const rr = LOOTH.RAR[it.r]; let h = `<div class="tn" style="color:${rr.c}">${it.name}</div><div class="tt">${rr.n} ${it.b} · item level ${it.il}</div><div class="tb">${LOOTH.lines(it).map(([k, v]) => `<div><span>${k}</span><b>${v}</b></div>`).join('')}</div>`;
  const fx = Object.keys(it.fx || {}); if (fx.length) h += '<div class="ta">' + fx.map((k) => '<div>' + LOOTH.AFX[k].f.replace('{v}', it.fx[k]) + '</div>').join('') + '</div>'; if (it.flav) h += `<div class="tf">${it.flav}</div>`;
  if (mode === 'bag' || mode === 'shop') { const cur = LOOTH.eq[it.slot], d = Math.round(LOOTH.score(it) - LOOTH.score(cur)); if (cur) h += `<div class="tk ${d >= 0 ? 'up' : 'dn'}">${d >= 0 ? '▲ better than' : '▼ weaker than'} ${cur.name}</div>`; }
  h += `<div class="tk">${mode === 'bag' ? '<b>Click</b> equip · <b>Right-click</b> sell for ' + LOOTH.value(it) + ' galleons' : mode === 'eq' ? (it.slot === 'wand' ? 'A wizard keeps a wand in hand' : '<b>Click</b> take off') : mode === 'shop' ? '<b>Click</b> buy for ' + price + ' galleons' : ''}</div>`; return h; };
LOOTH.tip = function (el, html) { let t = document.getElementById('hlTip'); if (!t) { t = document.createElement('div'); t.id = 'hlTip'; HL.ui.root.appendChild(t); } if (!html) { t.style.display = 'none'; return; } t.innerHTML = html; t.style.display = 'block'; const r = el.getBoundingClientRect(); let x = r.right + 12, y = r.top; if (x + 310 > innerWidth) x = r.left - 312; if (y + t.offsetHeight > innerHeight - 8) y = innerHeight - t.offsetHeight - 8; t.style.left = x + 'px'; t.style.top = Math.max(8, y) + 'px'; };
LOOTH.slotHtml = (it, attr, label, n) => `<div class="hlSlot ${it ? 'full r' + it.r : ''}" ${attr}>${it ? `<i style="background-image:url(${LOOTH.icon(it)})"></i>` : ''}${label ? `<span>${label}</span>` : ''}${n !== undefined ? `<em>${n}</em>` : ''}</div>`;
LOOTH.open = function () { if (MG.state !== 'play' || HL.Q.on || !PLAYER.a || !PLAYER.a.alive) return; MG.state = 'inv'; LOOTH.fresh = 0; if (document.exitPointerLock) document.exitPointerLock(); LOOTH.render(); MG.onKey = (c) => { if (c === 'Escape' || c === 'KeyI' || c === 'Tab') LOOTH.close(); }; };
LOOTH.close = function () { HL.ui.screen(''); LOOTH.tip(null); MG.state = 'play'; MG.onKey = null; IN.buf = {}; HL.noPauseT = MG.rt + 0.25; };
LOOTH.render = function () { const G = HL.G, a = PLAYER.a, pct = (v) => Math.round(v * 100) + '%', row = (k, v) => `<div class="st"><span>${k}</span><b>${v}</b></div>`;
  let bag = ''; for (let i = 0; i < LOOTH.BAG; i++) bag += LOOTH.slotHtml(LOOTH.bag[i], `data-bag="${i}"`);
  const S = HL.ui.screen(`<div class="hlInv"><div class="box"><h2>${HL.H().name.toUpperCase()} · YOUR THINGS</h2>
    <div><div class="sh"><span>STATISTICS</span></div>${row('Health', Math.round(a.hp) + ' / ' + a.hpMax)}${row('Spell damage', '+' + pct(G.power))}${row('Cooldowns', '−' + pct(G.haste))}${row('Critical casts', pct(G.crit))}${row('Damage taken', '−' + pct(G.ward))}${row('Health regeneration', G.regen + ' /s')}${row('Ancient Magic gain', '+' + pct(G.ancient))}${row('Broom speed', '+' + pct(G.speed))}${row('Boost reserve', '+' + pct(G.boost))}${row('Fortune', '+' + pct(G.luck))}${row('House points', HL.save.points || 0)}<div class="gold">${LOOTH.gold} galleons</div></div>
    <div><div class="sh"><span>WORN</span></div><div class="hlEq">${LOOTH.SLOTS.map((s) => LOOTH.slotHtml(LOOTH.eq[s], `data-eq="${s}"`, LOOTH.SLOTN[s].toUpperCase())).join('')}</div><div class="sh"><span>POTIONS</span><span><b>G</b> drinks Wiggenweld</span></div><div class="hlPots">${Object.keys(LOOTH.POT).map((k) => `<div class="hlSlot ${LOOTH.pots[k] ? 'full r1' : ''}" data-pot="${k}"><i style="background:radial-gradient(circle at 50% 62%, ${LOOTH.POT[k].c} 0 34%, transparent 36%), linear-gradient(#0000 0 22%, #cfc6b0 22% 34%, #0000 34%) 50% 0 / 22% 100% no-repeat"></i><em>${LOOTH.pots[k]}</em></div>`).join('')}</div></div>
    <div><div class="sh"><span>PACK</span><span>${LOOTH.bag.length} / ${LOOTH.BAG}</span></div><div class="hlBag">${bag}</div></div>
    <div class="hint"><b>Click</b> to wear or take off · <b>Right-click</b> to sell · <b>I</b> / <b>Tab</b> / <b>Esc</b> to close · <b>M</b> opens the map</div></div></div>`);
  S.querySelectorAll('.hlSlot').forEach((el) => { const b = el.dataset.bag, e = el.dataset.eq, p = el.dataset.pot;
    el.onmouseenter = () => { if (p) return LOOTH.tip(el, `<div class="tn" style="color:${LOOTH.POT[p].c}">${LOOTH.POT[p].n}</div><div class="tt">${LOOTH.POT[p].d}</div><div class="tk"><b>Click</b> drink</div>`); const it = b !== undefined ? LOOTH.bag[+b] : LOOTH.eq[e]; LOOTH.tip(el, it ? LOOTH.tipHtml(it, b !== undefined ? 'bag' : 'eq') : null); }; el.onmouseleave = () => LOOTH.tip(null);
    el.onclick = () => { if (p) { LOOTH.drink(p); } else if (b !== undefined) LOOTH.equip(+b); else LOOTH.unequip(e); LOOTH.tip(null); LOOTH.render(); }; el.oncontextmenu = (ev) => { ev.preventDefault(); if (b !== undefined) { LOOTH.sell(+b); LOOTH.tip(null); LOOTH.render(); } }; }); };
/* ------------------------------------------------------------------ shops */
LOOTH.SHOPS = { 'OLLIVANDERS': { slot: 'wand', say: 'The wand chooses the wizard.' }, 'SPINTWITCHES': { slot: 'broom', say: 'Finest racing brooms north of London.' }, 'GLADRAGS': { slot: 'robe', say: 'Robes for all occasions.' }, 'DERVISH & BANGES': { slot: 'charm', say: 'Charms, curios and repairs.' }, 'HONEYDUKES': { pots: 1, say: 'Potions and sweets — settle up at the counter.' } };
LOOTH.shop = function (name) { const D = LOOTH.SHOPS[name]; if (!D.stock) { D.stock = []; for (let i = 0; i < 6; i++) D.stock.push(D.pots ? null : LOOTH.make({ slot: D.slot, bias: i < 2 ? 2 : 1, il: 3 + i })); } MG.state = 'inv'; if (document.exitPointerLock) document.exitPointerLock();
  const draw = () => { const items = D.pots ? Object.keys(LOOTH.POT).map((k) => `<div class="hlSlot full r1" data-pot="${k}"><i style="background:radial-gradient(circle at 50% 62%, ${LOOTH.POT[k].c} 0 34%, transparent 36%)"></i><span>${LOOTH.POT[k].price} g</span></div>`).join('') : D.stock.map((it, i) => it ? LOOTH.slotHtml(it, `data-s="${i}"`, LOOTH.value(it) * 3 + ' g') : '<div class="hlSlot"></div>').join('');
    let bag = ''; for (let i = 0; i < LOOTH.BAG; i++) bag += LOOTH.slotHtml(LOOTH.bag[i], `data-bag="${i}"`);
    const S = HL.ui.screen(`<div class="hlInv"><div class="box" style="grid-template-columns: 1fr 1fr"><h2>${name}</h2><div><div class="sh"><span>FOR SALE</span><span>“${D.say}”</span></div><div class="hlBag" style="gap:26px 7px;margin-bottom:26px">${items}</div><div class="gold">${LOOTH.gold} galleons</div></div>
      <div><div class="sh"><span>YOUR PACK</span><span>click to sell</span></div><div class="hlBag">${bag}</div></div><div class="hint"><b>Click</b> an item to buy or sell · <b>Esc</b> to leave</div></div></div>`);
    S.querySelectorAll('.hlSlot').forEach((el) => { const s = el.dataset.s, b = el.dataset.bag, p = el.dataset.pot; el.onmouseenter = () => { if (p) return LOOTH.tip(el, `<div class="tn" style="color:${LOOTH.POT[p].c}">${LOOTH.POT[p].n}</div><div class="tt">${LOOTH.POT[p].d}</div><div class="tk"><b>Click</b> buy for ${LOOTH.POT[p].price} galleons · you have ${LOOTH.pots[p]}</div>`); const it = s !== undefined ? D.stock[+s] : LOOTH.bag[+b]; LOOTH.tip(el, it ? LOOTH.tipHtml(it, s !== undefined ? 'shop' : 'bag', it ? LOOTH.value(it) * 3 : 0) : null); }; el.onmouseleave = () => LOOTH.tip(null);
      el.onclick = () => { if (p) { if (LOOTH.gold >= LOOTH.POT[p].price) { LOOTH.gold -= LOOTH.POT[p].price; LOOTH.pots[p]++; } } else if (s !== undefined) { const it = D.stock[+s], pr = it ? LOOTH.value(it) * 3 : 0; if (it && LOOTH.gold >= pr && LOOTH.bag.length < LOOTH.BAG) { LOOTH.gold -= pr; D.stock[+s] = null; LOOTH.bag.push(it); } } else if (b !== undefined) LOOTH.sell(+b); LOOTH.store(); LOOTH.tip(null); draw(); }; }); };
  draw(); MG.onKey = (c) => { if (c === 'Escape' || c === 'KeyE') LOOTH.close(); }; };
/* ------------------------------------------------------------------ hooks */
HL.ui.itemPop = function (it) { let e = HL.ui.el.Item; if (!e) { e = document.createElement('div'); e.id = 'hlItem'; e.innerHTML = '<i></i><div class="a f"></div><div class="b"></div>'; HL.ui.el.Hud.appendChild(e); HL.ui.el.Item = e; } const rr = LOOTH.RAR[it.r]; e.style.setProperty('--rc', rr.c); e.querySelector('i').style.backgroundImage = `url(${LOOTH.icon(it)})`; e.querySelector('.a').textContent = it.name; e.querySelector('.b').textContent = rr.n + ' ' + it.b + ' — press I'; e.classList.add('on'); clearTimeout(HL.ui._ipT); HL.ui._ipT = setTimeout(() => e.classList.remove('on'), 4200); };
(function () {
  const b0 = HL.ui.build; HL.ui.build = function () { const first = !HL.ui.root; b0(); if (first) { const st = document.createElement('style'); st.textContent = LOOTH.css; document.head.appendChild(st); const g = document.createElement('div'); g.id = 'hlGold'; HL.ui.el.Hud.appendChild(g); HL.ui.el.Gold = g; const p = document.createElement('div'); p.id = 'hlPot'; HL.ui.el.Hud.appendChild(p); HL.ui.el.Pot = p; } };
  const u0 = HL.ui.update; HL.ui.update = function (dt) { u0(dt); if (!HL.ui.el.Gold) return; HL.ui.setText('gold', HL.ui.el.Gold, LOOTH.gold + ' galleons'); const B = LOOTH.buffs, bf = (B.maxima > 0 ? ' · MAXIMA ' + Math.ceil(B.maxima) : '') + (B.edurus > 0 ? ' · EDURUS ' + Math.ceil(B.edurus) : '') + (B.focus > 0 ? ' · FOCUS ' + Math.ceil(B.focus) : ''); HL.ui.setText('pot', HL.ui.el.Pot, 'G  WIGGENWELD ×' + LOOTH.pots.wiggen + bf); };
  const h0 = HL.hitActor; HL.hitActor = function (b, t, p, dir) { if (b.team === 'hero' && !b._g) { b._g = 1; const G = HL.G; let m = 1 + G.power; if (RNG() < G.crit) { m *= 2; HL.ui.pop('CRITICAL'); } b.mul *= m; const a0 = HL.P.ancient; h0(b, t, p, dir); if (HL.P.ancient > a0) HL.P.ancient = Math.min(100, a0 + (HL.P.ancient - a0) * (1 + G.ancient)); return; } h0(b, t, p, dir); };
  const c0 = PLAYER.cast; PLAYER.cast = function (id, force) { const r = c0(id, force); if (r && HL.SPELLS[id].cd) HL.P.cd[id] = HL.SPELLS[id].cd * (1 - HL.G.haste); return r; };
  const d0 = PLAYER.onDamage; PLAYER.onDamage = function (amt, info) { const r = d0(amt, info); return typeof r === 'number' ? r * (1 - HL.G.ward) : r; };
  const s0 = PLAYER.spawn; PLAYER.spawn = function (x, y, z, yaw) { const a = s0(x, y, z, yaw); LOOTH.sum(); a.hp = a.hpMax; LOOTH.wear(); return a; };
  const f0 = HL.onFoeDown; HL.onFoeDown = function (f) { LOOTH.dropFrom(f); f0(f); };
  const w0 = HL.worldUpdate; HL.worldUpdate = function (dt) { w0(dt); LOOTH.update(dt); if (IN.take('inv')) LOOTH.open(); };
  const q0 = HL.quest.start; HL.quest.start = function (cont) { q0(cont); LOOTH.restore(!cont); };
})();
HL.BUILD.push(async function chests(L) { const Y = HL.Y0, C = HL.CAMP, V = HL.VIL, H = HL.HUT;
  { const P = HL.plan(0), sp = [], G2 = HL.GHR, E2 = HL.EHR, CT = HL.COURT; for (const c of P.comps) { if (c.kind !== 'room' || !c.name || !P.seen.has(c.id)) continue; const x = P.X(c.R.i1 + 1) + 1.1, z = P.Z(c.R.j1 + 1) + 1.1; sp.push([c.type, x, z, c.id]); }
    const step = Math.max(1, Math.floor(sp.length / 26));
    LOOTH.CH = [['first', 3.4, Y, -157, -2.2, 1], ['quad', CT ? CT.x0 + 4 : -100, Y, CT ? CT.z0 + 4 : 132, 1.2, 1], ['hall', G2 ? G2.x0 + 3 : -90, Y + 0.45, G2 ? G2.z0 + 3 : 20, 0.8, 2], ['entrance', E2 ? E2.x0 + 3 : -95, Y, E2 ? E2.z0 + 12 : 110, HALF, 1], ['viaduct', 3.9, null, -244.4, -HALF, 1], ['headland', -52, null, -350, 1, 1],
      ...sp.filter((q, n) => n % step === 0).slice(0, 26).map((q, n) => ['rm' + q[3], q[1], Y, q[2], 0.8, /lounge|trophy|library/.test(q[0]) ? 3 : n % 3 === 0 ? 2 : 1]),
    ['village', V.x + 30, null, V.z - 24, 0.4, 2], ['hut', H.x + 9.5, null, H.z + 3.4, -1.2, 1], ['boat', (HL.BOAT ? HL.BOAT[0] : 150) + 12, 1.2, (HL.BOAT ? HL.BOAT[1] : 46) + 4.4, HALF, 2], ['owlery', HL.OWLERY ? HL.OWLERY[0] - 9 : 195, null, HL.OWLERY ? HL.OWLERY[2] + 4 : 180, 0.9, 2], ['camp', C.x - 7, null, C.z + 6, 0.5, 2], ['stones', HL.MAGE[0], null, HL.MAGE[1] + 4, 0, 3], ['troll', HL.TROLL[0] + 8, null, HL.TROLL[1] + 9, 2, 3], ['pitch', HL.PITCH.x + 40, null, HL.PITCH.z - 96, 0.2, 1], ['north', 35, Y, 197, 0.4, 1]];
    for (const k of HL.ALLK) { if (!k) continue; const P2 = HL.plan(k), rooms = P2.comps.filter((c) => c.kind === 'room' && c.name && c.type !== 'ring' && P2.seen.has(c.id)), step = Math.max(1, Math.floor(rooms.length / 6)); let n = 0;
      for (let q = 0; q < rooms.length && n < 6; q += step) { const c = rooms[q], x = P2.X(c.R.i1 + 1) + 1.1, z = P2.Z(c.R.j1 + 1) + 1.1; LOOTH.CH.push(['lv' + k + '_' + n, x, P2.y, z, 0.8, /lounge|trophy|library|head/.test(c.type) ? 3 : 2]); n++; } }
  }
  if (HL.DUN && HL.DUN.sly) { const D = HL.DUN, yd = HL.Y0 - D.d; LOOTH.CH.push(['dun_sly', D.sly.x1 - 1, yd, D.sly.z0 + 1.2, -2.2, 3], ['dun_kit', D.kitchen.x1 - 1.6, yd, D.kitchen.z1 - 1.2, 2.4, 2], ['dun_huf', D.huf.x0 + 1, yd, D.huf.z0 + 1.2, 0.8, 3], ['dun_cell', -70.6, yd, 45.4, 2.6, 2], ['dun_under', -96.8, yd, 89.8, 0.9, 1]); }
  LOOTH.placeChests(L);
  for (const nm in LOOTH.SHOPS) { const d = HL.VILDOORS && HL.VILDOORS[nm]; if (d) HL.interact(d, 3, 'Browse ' + nm[0] + nm.slice(1).toLowerCase(), () => LOOTH.shop(nm)); }
});
