/* ==== p80b_hl_inv2.js ==== */
/* HOGWARTS — the inventory in the dress of the dungeon-crawler kit: an ornate framed box, the character turning on a
   stage between the worn slots, studio-rendered models for icons, a tooltip with a header plate. And the charmed
   locks on chests: a sequence of spells to cast on the hotkeys before the charm re-seals. */
(function () { const LOOTH = HL.LOOT;
  LOOTH.css2 = `.hlInv .box { position: relative; width: 1230px; flex: none; display: grid; grid-template-columns: 232px auto minmax(360px, 1fr); grid-template-rows: auto 1fr; gap: 0 30px; padding: 22px 32px 24px; box-sizing: border-box;
  background-color: #140e09; border: 1px solid #7a5c32; box-shadow: 0 0 0 1px #000, 0 0 0 6px #16100a, 0 0 0 7px #5e4626, 0 0 0 8px #000, 0 40px 120px rgba(0,0,0,.92), inset 0 0 140px rgba(0,0,0,.75); animation: invIn .24s cubic-bezier(.2,.9,.3,1.08); }
@keyframes invIn { from { opacity: 0; transform: translateY(10px) scale(.975); } to { opacity: 1; transform: none; } }
.hlInv .box:before { content: ''; position: absolute; inset: 9px; border: 1px solid rgba(201,164,92,.17); pointer-events: none; }
.hlInv .cn { position: absolute; width: 72px; height: 72px; background: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 72 72'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='%23fbe7b0'/><stop offset='.45' stop-color='%23c29a4e'/><stop offset='1' stop-color='%235e421a'/></linearGradient></defs><path d='M5 70 V18 Q5 5 18 5 H70' fill='none' stroke='url(%23g)' stroke-width='3.2'/><path d='M12 70 V22 Q12 12 22 12 H70' fill='none' stroke='url(%23g)' stroke-width='1.1' opacity='.75'/><path d='M17 17 C27 17 33 23 33 33 C25 32 18 26 17 17 Z' fill='url(%23g)'/><path d='M24 38 q8 -4 14 4 M38 24 q-4 8 4 14' stroke='url(%23g)' stroke-width='1.4' fill='none'/><rect x='-1' y='-1' width='12' height='12' transform='translate(5 5) rotate(45)' fill='url(%23g)' stroke='%23000' stroke-width='.8'/></svg>") no-repeat; pointer-events: none; z-index: 3; filter: drop-shadow(0 2px 2px #000); }
.hlInv .cn.tl { left: -11px; top: -11px; } .hlInv .cn.tr { right: -11px; top: -11px; transform: scaleX(-1); } .hlInv .cn.bl { left: -11px; bottom: -11px; transform: scaleY(-1); } .hlInv .cn.br { right: -11px; bottom: -11px; transform: scale(-1, -1); }
.hlInv .hd { grid-column: 1 / -1; display: flex; align-items: center; justify-content: center; gap: 20px; padding: 0 0 12px; }
.hlInv .hd h2 { font-family: 'HLA', serif; font-weight: 700; letter-spacing: .44em; padding-left: .44em; font-size: 25px; margin: 0; background: linear-gradient(180deg, #fff4d2 10%, #e2c07a 50%, #94702f 92%); -webkit-background-clip: text; background-clip: text; color: transparent; filter: drop-shadow(0 2px 2px #000); }
.hlInv .hd .fl { flex: 0 1 250px; height: 1px; background: linear-gradient(90deg, transparent, #c9a45c); position: relative; } .hlInv .hd .fl.r { transform: scaleX(-1); }
.hlInv .hd .fl:after { content: ''; position: absolute; right: -4px; top: -4px; width: 7px; height: 7px; transform: rotate(45deg); border: 1px solid #c9a45c; background: rgba(201,164,92,.35); }
#invClose { position: absolute; right: 26px; top: 20px; cursor: pointer; font-family: 'HLA', serif; font-size: 12px; letter-spacing: .2em; color: rgba(233,223,201,.62); padding: 5px 11px; border: 1px solid rgba(201,164,92,.32); background: rgba(0,0,0,.25); z-index: 4; }
#invClose:hover { color: #fff; background: rgba(201,164,92,.16); }
.hlInv .sh { display: flex; justify-content: space-between; align-items: baseline; font-family: 'HLA', serif; font-size: 12px; letter-spacing: .3em; color: rgba(232,207,148,.7); padding-bottom: 7px; margin-bottom: 14px; border-bottom: 1px solid rgba(201,164,92,.22); }
.hlInv .ccol, .hlInv .dcol, .hlInv .rcol { display: flex; flex-direction: column; min-width: 0; }
#invWho { text-align: center; padding: 2px 0 14px; } #invWho .lv { font-family: 'HLA', serif; font-weight: 700; font-size: 13px; letter-spacing: .3em; color: rgba(233,223,201,.55); }
#invWho .lv b { display: block; font-size: 34px; letter-spacing: .06em; line-height: 1.1; background: linear-gradient(180deg, #fff4d2, #d8b46a 60%, #8a6428); -webkit-background-clip: text; background-clip: text; color: transparent; filter: drop-shadow(0 2px 1px #000); }
#invWho .xp { position: relative; height: 7px; margin: 9px 10px 3px; background: #070504; border: 1px solid #4a3a26; box-shadow: inset 0 1px 3px #000; } #invWho .xp i { position: absolute; left: 0; top: 0; bottom: 0; background: linear-gradient(90deg, #7a5a24, #f0d696); box-shadow: 0 0 8px rgba(232,207,148,.5); }
#invWho .xpn { font-size: 12.5px; font-style: italic; color: rgba(233,223,201,.45); }
#invStats { display: flex; flex-direction: column; }
#invStats .st { display: flex; justify-content: space-between; align-items: baseline; gap: 8px; padding: 3.5px 2px; border-bottom: 1px solid rgba(201,164,92,.08); color: rgba(233,223,201,.62); white-space: nowrap; font-size: 15px; }
#invStats .st b { font-family: 'HLA', serif; font-weight: 700; color: #efe5cf; font-size: 14px; } #invStats .st.hi b { color: #e8cf94; } #invStats i { color: rgba(233,223,201,.4); font-size: .8em; margin-left: 5px; }
#invStats .gap { height: 9px; }
#invStats .st .up { color: #86e07e; font-style: normal; font-size: .82em; margin-left: 6px; } #invStats .st .dn { color: #ff7d6c; font-style: normal; font-size: .82em; margin-left: 6px; }
#invGold { margin-top: auto; padding-top: 12px; display: flex; align-items: center; justify-content: center; gap: 10px; font-family: 'HLA', serif; font-size: 21px; font-weight: 700; color: #e8cf94; text-shadow: 0 2px 2px #000; }
#invGold:before { content: ''; width: 20px; height: 20px; border-radius: 50%; background: radial-gradient(circle at 35% 30%, #fff2c0, #d8a840 45%, #7a5412 80%); box-shadow: 0 0 0 1px #3a2608, 0 2px 4px #000, inset 0 0 0 2px rgba(255,236,170,.35); }
#invDoll { position: relative; display: grid; grid-template-columns: 72px 236px 72px; grid-template-rows: repeat(5, 72px); gap: 11px 14px; grid-template-areas: "helm stage amulet" "chest stage ring" "gloves stage ." "boots stage shield" "weapon stage weapon2"; }
#invDoll .stage { grid-area: stage; position: relative; border-radius: 4px; background: radial-gradient(ellipse 62% 52% at 50% 40%, rgba(255,210,140,.14), rgba(255,210,140,.03) 55%, transparent 72%), radial-gradient(ellipse 46% 7% at 50% 94%, rgba(0,0,0,.55), transparent); }
#invDoll .stage:after { content: 'drag to turn'; position: absolute; left: 0; right: 0; bottom: -2px; text-align: center; font-size: 11.5px; font-style: italic; color: rgba(233,223,201,.28); pointer-events: none; }
#invStand { position: absolute; left: -40px; top: -18px; width: calc(100% + 80px); height: calc(100% + 16px); cursor: grab; z-index: 0; } #invStand:active { cursor: grabbing; }
#invDoll .islot { z-index: 1; }
#invBag { display: grid; grid-template-columns: repeat(6, 1fr); gap: 7px; }
.hlInv .hint { margin-top: auto; padding-top: 12px; font-size: 13px; color: rgba(233,223,201,.46); font-style: italic; line-height: 1.5; } .hlInv .hint b { font-style: normal; color: #e8cf94; font-weight: 600; }
#invSay { position: absolute; left: 50%; bottom: 10px; transform: translateX(-50%); font-size: 15px; font-style: italic; color: #efe6d2; white-space: nowrap; opacity: 0; transition: opacity .3s; text-shadow: 0 1px 3px #000; z-index: 5; } #invSay em { font-style: normal; font-family: 'HLA', serif; }
.islot { position: relative; width: 100%; aspect-ratio: 1; box-sizing: border-box; cursor: pointer; border-radius: 3px; border: 1px solid #55432c;
  background: radial-gradient(ellipse at 50% 36%, #2a2016 0%, #130e0a 60%, #080605 100%);
  box-shadow: 0 0 0 1px #000, inset 0 0 0 1px rgba(255,226,170,.05), inset 0 -12px 18px rgba(0,0,0,.55), 0 3px 6px rgba(0,0,0,.55); transition: filter .12s, box-shadow .15s; }
.islot:before { content: ''; position: absolute; inset: 3px; border: 1px solid rgba(255,220,160,.07); border-radius: 2px; pointer-events: none; }
.islot .ic { position: absolute; inset: 5%; background-size: contain; background-repeat: no-repeat; background-position: center; filter: drop-shadow(0 3px 3px rgba(0,0,0,.85)); transition: transform .14s; }
.islot:hover { filter: brightness(1.2); } .islot:hover .ic { transform: scale(1.07); }
.islot.r0 { border-color: #7a6e5a; }
.islot.r1 { border-color: #4966d0; background: radial-gradient(ellipse at 50% 58%, rgba(80,120,255,.34), rgba(24,32,70,.4) 46%, #08070a 86%); box-shadow: 0 0 0 1px #000, inset 0 0 14px rgba(80,120,255,.22), 0 3px 6px rgba(0,0,0,.55); }
.islot.r2 { border-color: #d0a634; background: radial-gradient(ellipse at 50% 58%, rgba(255,204,80,.32), rgba(66,48,12,.42) 46%, #080605 86%); box-shadow: 0 0 0 1px #000, inset 0 0 14px rgba(255,204,80,.2), 0 3px 6px rgba(0,0,0,.55); }
.islot.r3 { border-color: #f08a34; background: radial-gradient(ellipse at 50% 58%, rgba(255,128,36,.42), rgba(86,32,8,.48) 46%, #0a0504 86%); animation: invLeg 2.6s ease-in-out infinite; }
@keyframes invLeg { 0%, 100% { box-shadow: 0 0 0 1px #000, inset 0 0 14px rgba(255,120,30,.3), 0 0 10px rgba(255,120,30,.3); } 50% { box-shadow: 0 0 0 1px #000, inset 0 0 20px rgba(255,140,40,.45), 0 0 22px rgba(255,130,40,.6); } }
.islot.eq:not(.full) .ic { opacity: .13; filter: grayscale(1) brightness(1.7); }
.islot .lab { position: absolute; left: 0; right: 0; bottom: 4px; text-align: center; font-size: 8.5px; letter-spacing: .13em; color: rgba(233,223,201,.4); font-family: 'HLA', serif; pointer-events: none; text-transform: uppercase; line-height: 1.15; }
.islot.eq.full .lab { display: none; }
.islot.hand:after { content: ''; position: absolute; right: 4px; top: 4px; width: 7px; height: 7px; transform: rotate(45deg); background: #e8cf94; box-shadow: 0 0 6px #c9a45c, 0 0 0 1px #000; }
.islot.focus { outline: 2px solid #fff1c8; outline-offset: 2px; box-shadow: 0 0 0 1px #000, 0 0 18px rgba(255,220,150,.55); }
.islot.try { outline: 1px dashed rgba(255,241,200,.6); outline-offset: 3px; }
#hlTip { position: fixed; z-index: 60; display: none; width: 322px; background: linear-gradient(180deg, rgba(26,19,12,.985), rgba(9,7,5,.99)); border: 1px solid var(--rc3, #6a5436); box-shadow: 0 0 0 1px #000, 0 0 24px var(--rcg, transparent), 0 18px 50px rgba(0,0,0,.9); pointer-events: none; font-size: 15px; line-height: 1.38; color: #e9dfc9; overflow: hidden; }
#hlTip .th { position: relative; padding: 12px 88px 11px 15px; min-height: 70px; box-sizing: border-box; background: linear-gradient(180deg, var(--rc2, rgba(255,255,255,.05)), transparent 92%); border-bottom: 1px solid var(--rc3, #4a3a26); }
#hlTip .ti { position: absolute; right: 8px; top: 5px; width: 74px; height: 74px; background-size: contain; background-repeat: no-repeat; background-position: center; filter: drop-shadow(0 4px 4px #000); }
#hlTip .tn { font-family: 'HLA', serif; font-weight: 700; font-size: 18px; letter-spacing: .02em; line-height: 1.18; color: var(--rc); text-shadow: 0 1px 2px #000, 0 0 12px rgba(0,0,0,.6); } #hlTip .tt { font-style: italic; color: rgba(233,223,201,.56); font-size: 13.5px; margin-top: 3px; }
#hlTip .tbd { padding: 9px 15px 11px; }
#hlTip .tb div { display: flex; justify-content: space-between; align-items: baseline; color: rgba(233,223,201,.74); } #hlTip .tb b { font-family: 'HLA', serif; color: #fff; font-size: 17px; font-weight: 700; }
#hlTip .ta { margin-top: 2px; } #hlTip .ta div { position: relative; padding-left: 15px; color: #a4b8ff; } #hlTip .ta div:before { content: ''; position: absolute; left: 2px; top: .62em; width: 5px; height: 5px; transform: rotate(45deg); background: currentColor; opacity: .75; }
#hlTip .sep { height: 1px; margin: 8px 0 7px; background: linear-gradient(90deg, transparent, rgba(201,164,92,.4), transparent); }
#hlTip .tf { color: #eb9a48; font-style: italic; font-size: 14.5px; }
#hlTip .tc { font-size: 14px; } #hlTip .tch { color: rgba(233,223,201,.5); font-style: italic; } #hlTip .up { color: #86e07e; } #hlTip .dn { color: #ff7d6c; }
#hlTip .tk { margin-top: 8px; font-size: 12.5px; color: rgba(233,223,201,.5); } #hlTip .tk b { color: #e8cf94; font-weight: 600; }
.hlInv { backdrop-filter: blur(4px) saturate(.75); }
.hlInv #invDoll { grid-template-areas: "wand stage charm" "robe stage charm2" "broom stage p0" ". stage p1" ". stage p2"; }
.hlInv #invStand { left: -34px; top: -10px; width: calc(100% + 68px); height: calc(100% + 10px); cursor: default; }
.hlInv #invDoll .stage:after { content: ''; }
.hlInv .islot em { position: absolute; right: 5px; bottom: 2px; font-style: normal; font-family: 'HLA', serif; font-size: 15px; color: #fff; text-shadow: 0 1px 3px #000; }
.hlInv .islot.pot .ic { inset: 16%; }
.hlLock { position: absolute; inset: 0; display: flex; align-items: flex-end; justify-content: center; padding-bottom: 15vh; background: radial-gradient(ellipse at 50% 60%, rgba(0,0,0,0), rgba(0,0,0,.55) 80%); }
.hlLock .lk { position: relative; padding: 22px 46px 20px; text-align: center; background: linear-gradient(180deg, rgba(26,19,12,.94), rgba(9,7,5,.96)); border: 1px solid #7a5c32; box-shadow: 0 0 0 1px #000, 0 0 0 5px #16100a, 0 0 0 6px #5e4626, 0 30px 80px #000; }
.hlLock .lk.bad { animation: lkBad .35s; } @keyframes lkBad { 20% { transform: translateX(-12px); } 50% { transform: translateX(10px); } 80% { transform: translateX(-5px); } }
.hlLock .ttl { font-family: 'HLA', serif; letter-spacing: .44em; padding-left: .44em; font-size: 22px; color: #e2c07a; } .hlLock .sub { font-style: italic; color: rgba(233,223,201,.62); font-size: 15px; margin: 4px 0 26px; }
.hlLock .runes { display: flex; gap: 14px; justify-content: center; margin: 0 8px 24px; }
.hlLock .rn { position: relative; width: 62px; height: 62px; transform: rotate(45deg); border: 1.5px solid rgba(201,164,92,.4); background: rgba(0,0,0,.5); transition: all .18s; opacity: .55; }
.hlLock .rn svg { position: absolute; inset: 11px; width: 38px; height: 38px; transform: rotate(-45deg); }
.hlLock .rw { display: flex; flex-direction: column; align-items: center; gap: 20px; width: 92px; } .hlLock .rw span { font-size: 11.5px; letter-spacing: .12em; color: rgba(233,223,201,.66); font-family: 'HLA', serif; white-space: nowrap; } .hlLock .rw b { font-family: 'HLA', serif; font-size: 18px; color: #efe5cf; border: 1px solid rgba(201,164,92,.4); width: 26px; line-height: 26px; background: rgba(0,0,0,.4); }
.hlLock .rn.cur { opacity: 1; border-color: var(--c); box-shadow: 0 0 22px var(--c), inset 0 0 14px var(--c); animation: lkP 0.9s ease-in-out infinite; } @keyframes lkP { 50% { box-shadow: 0 0 8px var(--c), inset 0 0 6px var(--c); } }
.hlLock .rn.ok { opacity: 1; border-color: #fff; background: var(--c); box-shadow: 0 0 26px var(--c); } .hlLock .rn.ok svg { stroke: #fff; }
.hlLock .bar { height: 6px; background: #070504; border: 1px solid #4a3a26; margin: 0 6px 12px; } .hlLock .bar i { display: block; height: 100%; width: 100%; background: linear-gradient(90deg, #7a5a24, #f0d696); box-shadow: 0 0 8px rgba(232,207,148,.5); transform-origin: left; }
.hlLock .hint { font-size: 13px; color: rgba(233,223,201,.5); font-style: italic; } .hlLock .hint b { font-style: normal; color: #e8cf94; }
`;
  { const b0 = HL.ui.build; HL.ui.build = function () { const first = !HL.ui.root; b0(); if (first) { const st = document.createElement('style'); st.textContent = LOOTH.css2; document.head.appendChild(st); } }; }
  /* ---------------------------------------------------------------- studio-rendered icons of the real models */
  LOOTH.model = function (it) { const g = new THREE.Group(), gold = new THREE.MeshStandardMaterial({ color: 0xd8b050, metalness: 1, roughness: 0.3 });
    if (it.slot === 'wand') { const w = HL.wand(it.wood); w.rotation.z = -0.85; w.scale.setScalar(1); g.add(w); if (it.r >= 1) { const s = new THREE.Mesh(new THREE.SphereGeometry(0.012, 8, 6), new THREE.MeshBasicMaterial({ color: LOOTH.RAR[it.r].c })); s.position.set(0.228, 0.26, 0); g.add(s); } }
    else if (it.slot === 'broom') { const b = HL.broom(it.col); b.rotation.set(0, HALF + 0.5, 0); const h = new THREE.Group(); h.add(b); h.rotation.z = 0.6; g.add(h); }
    else if (it.slot === 'robe') { const col = it.look === 'duel' ? 0x4a2a1e : 0x202028, cm = new THREE.MeshStandardMaterial({ color: col, roughness: 0.85, side: THREE.DoubleSide }), hm = new THREE.MeshStandardMaterial({ color: HL.H().col, roughness: 0.8 });
      const body = new THREE.Mesh(new THREE.LatheGeometry([[0.11, 1.5], [0.2, 1.42], [0.21, 1.2], [0.19, 0.95], [0.24, 0.5], [0.33, 0.05], [0.34, 0]].map((p) => new THREE.Vector2(p[0], p[1])), 20), cm); body.scale.z = 0.62; g.add(body);
      for (const s of [-1, 1]) { const arm = new THREE.Mesh(new THREE.CylinderGeometry(0.07, 0.13, 0.62, 10, 1, true), cm); arm.position.set(s * 0.3, 1.14, 0); arm.rotation.z = s * 0.5; g.add(arm); const lap = new THREE.Mesh(new THREE.BoxGeometry(0.05, 1.36, 0.02), hm); lap.position.set(s * 0.045, 0.74, 0.137 + 0.03); lap.rotation.z = -s * 0.03; g.add(lap); }
      const hood = new THREE.Mesh(new THREE.SphereGeometry(0.15, 12, 8, 0, TAU, 0, 1.9), cm); hood.position.set(0, 1.52, -0.06); hood.rotation.x = -0.5; g.add(hood); const st = new THREE.Mesh(new THREE.CylinderGeometry(0.02, 0.02, 0.3, 6), gold); st.position.y = 1.62; g.add(st); }
    else { const ch = new THREE.Mesh(new THREE.TorusGeometry(0.2, 0.012, 6, 30, PI * 1.3), gold); ch.rotation.z = -PI * 0.15 + PI; ch.position.y = 0.2; g.add(ch); const disc = new THREE.Mesh(new THREE.CylinderGeometry(0.11, 0.11, 0.03, 20), gold); disc.rotation.x = HALF; g.add(disc);
      const gem = new THREE.Mesh(new THREE.SphereGeometry(0.07, 14, 10), new THREE.MeshStandardMaterial({ color: it.gem || 0x6aa0ff, emissive: it.gem || 0x6aa0ff, emissiveIntensity: 0.6, roughness: 0.1, metalness: 0.2 })); gem.scale.z = 0.6; gem.position.z = 0.02; g.add(gem); for (let i = 0; i < 8; i++) { const p = new THREE.Mesh(new THREE.SphereGeometry(0.014, 6, 5), gold); p.position.set(Math.cos(i / 8 * TAU) * 0.095, Math.sin(i / 8 * TAU) * 0.095, 0.018); g.add(p); } }
    return g; };
  const icon0 = LOOTH.icon; LOOTH.icons3 = {};
  LOOTH.icon = function (it) { const key = it.slot[0] + (it.wood || it.col || it.gem || it.look || '') + it.r + (it.uq || '') + (it.slot === 'robe' ? HL.house : ''); if (LOOTH.icons3[key]) return LOOTH.icons3[key]; try { return (LOOTH.icons3[key] = ICON.render(LOOTH.model(it), {})); } catch (e) { return icon0(it); } };
  /* ---------------------------------------------------------------- the stage: the wearer, turning */
  LOOTH.dollDraw = function () { const cv = document.getElementById('invStand'), a = PLAYER.a; if (!cv || !a) return; const r = R.renderer, W = 304, H = 432;
    if (!LOOTH.dRT) { LOOTH.dRT = new THREE.WebGLRenderTarget(W, H, { depthBuffer: true, samples: 4 }); LOOTH.dCam = new THREE.PerspectiveCamera(24, W / H, 0.1, 80); LOOTH.dCam.layers.set(5); LOOTH.dPx = new Uint8Array(W * H * 4); LOOTH.dIm = new ImageData(W, H); R.hemi.layers.enable(5); if (R.sun) R.sun.layers.enable(5); }
    a.root.traverse((m) => m.layers.enable(5)); if (a.inst.cape && a.inst.cape.group) a.inst.cape.group.traverse((m) => m.layers.enable(5)); if (a.inst.cloth && a.inst.cloth.group) a.inst.cloth.group.traverse((m) => m.layers.enable(5));
    const t = MG.rt * 0.45 + a.yaw, cam = LOOTH.dCam; cam.position.set(a.x + Math.sin(t) * 5.3, a.y + 1.3, a.z + Math.cos(t) * 5.3); cam.lookAt(a.x, a.y + 0.96, a.z);
    const bg = R.scene.background, hi = R.hemi.intensity, hc = R.hemi.color.getHex(), hg = R.hemi.groundColor.getHex(), prev = r.getRenderTarget(), ca = r.getClearAlpha(), cc = r.getClearColor(new THREE.Color()), au = r.shadowMap.autoUpdate;
    R.scene.background = null; R.hemi.intensity = 4.2; R.hemi.color.set(0xfff0dc); R.hemi.groundColor.set(0x8a7460); r.shadowMap.autoUpdate = false; r.setRenderTarget(LOOTH.dRT); r.setClearColor(0x000000, 0); r.clear(true, true, true); r.render(R.scene, cam);
    r.readRenderTargetPixels(LOOTH.dRT, 0, 0, W, H, LOOTH.dPx); r.setRenderTarget(prev); r.setClearColor(cc, ca); R.scene.background = bg; R.hemi.intensity = hi; R.hemi.color.set(hc); R.hemi.groundColor.set(hg); r.shadowMap.autoUpdate = au;
    const px = LOOTH.dPx, d = LOOTH.dIm.data, G = LOOTH.gam || (LOOTH.gam = Uint8Array.from({ length: 256 }, (_, i) => Math.pow(i / 255, 1 / 2.2) * 255)); for (let j = 0; j < H; j++) { const s0 = (H - 1 - j) * W * 4, t0 = j * W * 4; for (let i = 0; i < W * 4; i += 4) { d[t0 + i] = G[px[s0 + i]]; d[t0 + i + 1] = G[px[s0 + i + 1]]; d[t0 + i + 2] = G[px[s0 + i + 2]]; d[t0 + i + 3] = px[s0 + i + 3]; } }
    if (cv.width !== W) { cv.width = W; cv.height = H; } cv.getContext('2d').putImageData(LOOTH.dIm, 0, 0); };
  { const r0 = R.render; R.render = function (dt) { r0(dt); if (MG.state === 'inv' && document.getElementById('invStand')) { try { LOOTH.dollDraw(); } catch (e) { if (!LOOTH._de) { LOOTH._de = 1; console.warn('doll', e); } } } }; }
  /* ---------------------------------------------------------------- the screen */
  LOOTH.tipHtml0 = LOOTH.tipHtml;
  LOOTH.tipHtml = function (it, mode, price) { const rr = LOOTH.RAR[it.r], h = LOOTH.tipHtml0(it, mode, price), cut = h.indexOf('<div class="tb">'); return `<div class="th" style="background:linear-gradient(180deg, ${rr.c}26, transparent 92%)"><i class="ti" style="background-image:url(${LOOTH.icon(it)})"></i><div class="tn" style="color:${rr.c}">${it.name}</div><div class="tt">${rr.n} ${it.b} · item level ${it.il}</div></div><div class="tbd">${h.slice(cut)}</div>`; };
  const slot = (it, attr, lab, cls, n) => `<div class="islot ${cls || ''} ${it ? 'full r' + it.r : ''}" ${attr}>${it ? `<div class="ic" style="background-image:url(${LOOTH.icon(it)})"></div>` : ''}${lab ? `<div class="lab">${lab}</div>` : ''}${n !== undefined ? `<em>${n}</em>` : ''}</div>`;
  LOOTH.render = function () { const G = HL.G, a = PLAYER.a, H = HL.H(), pct = (v) => Math.round(v * 100) + '%', row = (k, v, hi) => `<div class="st ${hi ? 'hi' : ''}"><span>${k}</span><b>${v}</b></div>`, pts = HL.save.points || 0;
    let bag = ''; for (let i = 0; i < LOOTH.BAG; i++) bag += slot(LOOTH.bag[i], `data-bag="${i}"`);
    const pk = Object.keys(LOOTH.POT), pots = pk.slice(0, 3).map((k, i) => `<div class="islot pot ${LOOTH.pots[k] ? 'full r1' : ''}" data-pot="${k}" style="grid-area:p${i}"><div class="ic" style="background:radial-gradient(circle at 50% 64%, ${LOOTH.POT[k].c} 0 36%, transparent 38%), linear-gradient(#0000 0 14%, #cfc6b0 14% 30%, #0000 30%) 50% 0 / 24% 100% no-repeat"></div><em>${LOOTH.pots[k] || 0}</em></div>`).join('');
    const S = HL.ui.screen(`<div class="hlInv"><div class="box"><i class="cn tl"></i><i class="cn tr"></i><i class="cn bl"></i><i class="cn br"></i><div class="hd"><span class="fl"></span><h2>INVENTORY</h2><span class="fl r"></span></div><span id="invClose">CLOSE ✕</span>
      <div class="ccol"><div class="sh"><span>CHARACTER</span></div><div id="invWho"><div class="lv">${a && a.T && /_f/.test(a.T.name) ? 'WITCH' : 'WIZARD'} OF<b style="font-size:26px;letter-spacing:.1em">${H.name.toUpperCase()}</b></div><div class="xp"><i style="width:${Math.min(100, pts % 100)}%"></i></div><div class="xpn">${pts} house points</div></div>
        <div id="invStats">${row('Health', Math.round(a.hp) + ' / ' + a.hpMax, 1)}${row('Spell damage', '+' + pct(G.power), 1)}${row('Cooldowns', '−' + pct(G.haste))}${row('Critical casts', pct(G.crit))}<div class="gap"></div>${row('Damage taken', '−' + pct(G.ward))}${row('Health regeneration', G.regen + ' /s')}${row('Ancient Magic gain', '+' + pct(G.ancient))}<div class="gap"></div>${row('Broom speed', '+' + pct(G.speed))}${row('Boost reserve', '+' + pct(G.boost))}${row('Fortune', '+' + pct(G.luck))}</div><div id="invGold">${LOOTH.gold}</div></div>
      <div class="dcol"><div class="sh"><span>EQUIPPED</span><span></span></div><div id="invDoll"><div class="stage"><canvas id="invStand"></canvas></div>${LOOTH.SLOTS.map((s) => slot(LOOTH.eq[s], `data-eq="${s}" style="grid-area:${s}"`, LOOTH.SLOTN[s], 'eq')).join('')}${pots}</div></div>
      <div class="rcol"><div class="sh"><span>PACK</span><span id="invCount">${LOOTH.bag.length} / ${LOOTH.BAG}</span></div><div id="invBag">${bag}</div><div class="hint"><b>Click</b> to wear or take off · <b>Right-click</b> to sell · click a potion to drink it (<b>G</b> drinks Wiggenweld)<br><b>I</b> / <b>Tab</b> / <b>Esc</b> close · <b>M</b> opens the map</div></div></div></div>`);
    const box = S.querySelector('.box'); box.style.zoom = Math.min(1, innerWidth / 1300, innerHeight / 700); S.querySelector('#invClose').onclick = () => LOOTH.close();
    S.querySelectorAll('.islot').forEach((el) => { const b = el.dataset.bag, e = el.dataset.eq, p = el.dataset.pot;
      el.onmouseenter = () => { if (p) return LOOTH.tip(el, `<div class="th"><div class="tn" style="color:${LOOTH.POT[p].c}">${LOOTH.POT[p].n}</div><div class="tt">${LOOTH.POT[p].d}</div></div><div class="tbd"><div class="tk"><b>Click</b> drink</div></div>`); const it = b !== undefined ? LOOTH.bag[+b] : LOOTH.eq[e]; LOOTH.tip(el, it ? LOOTH.tipHtml(it, b !== undefined ? 'bag' : 'eq') : null); }; el.onmouseleave = () => LOOTH.tip(null);
      el.onclick = () => { if (p) LOOTH.drink(p); else if (b !== undefined) LOOTH.equip(+b); else LOOTH.unequip(e); LOOTH.tip(null); LOOTH.render(); }; el.oncontextmenu = (ev) => { ev.preventDefault(); if (b !== undefined) { LOOTH.sell(+b); LOOTH.tip(null); LOOTH.render(); } }; }); };
  /* ---------------------------------------------------------------- charmed locks */
  const open0 = LOOTH.openChest;
  /* The lock is worked in the world, not in a menu: the sequence hangs in the air over the chest while the game goes on round you. Each rune you cast lights, and a thread of light runs from it to the next; a wrong one snaps the chain back to the start; walk away (or Esc) and it fades. */
  LOOTH.lockCss = `#hlLockW{position:absolute;left:0;top:0;transform:translate(-50%,-100%);pointer-events:none;opacity:0;transition:opacity .25s;z-index:5;text-align:center;font-family:HLA,Georgia,serif;filter:drop-shadow(0 4px 14px rgba(0,0,0,.75))}
#hlLockW.on{opacity:1}#hlLockW .row{display:flex;align-items:center;justify-content:center}#hlLockW .rw{display:flex;flex-direction:column;align-items:center;gap:4px}
#hlLockW .rn{width:50px;height:50px;border-radius:50%;border:2px solid rgba(255,255,255,.28);background:radial-gradient(circle,rgba(20,16,12,.88),rgba(8,6,4,.78));display:flex;align-items:center;justify-content:center;transition:all .18s;opacity:.7}
#hlLockW .rn svg{width:28px;height:28px;opacity:.75}#hlLockW .rn.cur{border-color:var(--c);opacity:1;transform:scale(1.14);box-shadow:0 0 16px var(--c);animation:hlLkP .8s ease-in-out infinite}
#hlLockW .rn.ok{border-color:var(--c);background:radial-gradient(circle,var(--c),rgba(30,20,8,.9) 78%);opacity:1;box-shadow:0 0 22px var(--c),0 0 6px #fff inset}#hlLockW .rn.ok svg{stroke:#fff;opacity:1}
#hlLockW b{font-size:13px;color:#e8dcc0;letter-spacing:.06em;background:rgba(0,0,0,.55);border:1px solid rgba(217,184,106,.6);border-radius:3px;min-width:18px;padding:0 4px}#hlLockW .rw.done b{color:#fff;border-color:#fff}
#hlLockW .ln{width:30px;height:4px;margin:0 3px 22px;background:rgba(255,255,255,.14);border-radius:2px;overflow:hidden}#hlLockW .ln i{display:block;height:100%;width:100%;transform:scaleX(0);transform-origin:left;transition:transform .28s ease-out;background:linear-gradient(90deg,var(--a),var(--b));box-shadow:0 0 10px var(--b)}#hlLockW .ln.ok i{transform:scaleX(1)}
#hlLockW .nm{margin-top:7px;font-size:13px;letter-spacing:.24em;color:#f3ead6;text-shadow:0 1px 3px #000,0 0 8px #000}#hlLockW .nm em{font-style:normal;color:var(--gold,#d9b86a)}
#hlLockW .bar{width:70%;height:3px;margin:7px auto 0;background:rgba(0,0,0,.6)}#hlLockW .bar i{display:block;height:100%;transform-origin:left;background:linear-gradient(90deg,#d9b86a,#fff3c4)}
#hlLockW.bad .row{animation:hlLkS .3s}#hlLockW.won .rn{transform:scale(1.2)}@keyframes hlLkP{50%{box-shadow:0 0 26px var(--c)}}@keyframes hlLkS{25%{transform:translateX(-7px)}75%{transform:translateX(7px)}}`;
  LOOTH.openChest = function (c) { if (c.open || MG.state !== 'play' || LOOTH.lk) return; const n = 3 + Math.min(3, c.tier || 1), seq = []; while (seq.length < n) { const k = (RNG() * HL.BAR.length) | 0; if (k !== seq[seq.length - 1]) seq.push(k); }
    const K = LOOTH.lk = { c, seq, pos: 0, T: 6 + n * 1.8, t: 0, t0: performance.now() }; K.t = K.T; for (let q = 1; q <= 8; q++) delete IN.buf['s' + q]; if (c.use) c.use.off = true;   // (its 'press E' prompt steps aside while the lock is being worked)
    if (!document.getElementById('hlLockCss')) { const st = document.createElement('style'); st.id = 'hlLockCss'; st.textContent = LOOTH.lockCss; document.head.appendChild(st); }
    let el = document.getElementById('hlLockW'); if (!el) { el = document.createElement('div'); el.id = 'hlLockW'; (HL.ui.el.Hud || HL.ui.root).appendChild(el); }
    const rgb = (S, m) => `rgb(${S.col.map((v) => Math.round(Math.min(1, v * m + (1 - m) * 0.4) * 255)).join(',')})`, sp = (i) => HL.SPELLS[HL.BAR[seq[i]]];
    el.className = ''; el.innerHTML = `<div class="row">${seq.map((k, i) => { const Sp = sp(i); return (i ? `<div class="ln" style="--a:${rgb(sp(i - 1), 1)};--b:${rgb(Sp, 1)}"><i></i></div>` : '') + `<div class="rw"><div class="rn ${i ? '' : 'cur'}" style="--c:${rgb(Sp, 1)}"><svg viewBox="0 0 24 24" fill="none" stroke="${rgb(Sp, 0.7)}" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${HL.ui.GLYPH[HL.BAR[k]]}"/></svg></div><b>${k + 1}</b></div>`; }).join('')}</div><div class="nm"></div><div class="bar"><i></i></div>`;
    const runes = [...el.querySelectorAll('.rn')], rws = [...el.querySelectorAll('.rw')], links = [...el.querySelectorAll('.ln')], bar = el.querySelector('.bar i'), nm = el.querySelector('.nm'), at = V3(c.x, c.y + 0.7, c.z), v = new THREE.Vector3(), au = HL.AU;
    const name = () => { const Sp = sp(Math.min(K.pos, n - 1)); nm.innerHTML = K.done ? '<em>UNLOCKED</em>' : `${Sp.name.toUpperCase()} &nbsp;<em>${seq[Math.min(K.pos, n - 1)] + 1}</em>`; }; name(); requestAnimationFrame(() => el.classList.add('on'));
    const end = (ok) => { if (LOOTH.lk !== K) return; cancelAnimationFrame(K.raf); LOOTH.lk = null; MG.onKey = null; el.classList.remove('on'); HL.noPauseT = MG.rt + 0.25; if (c.use && !ok) c.use.off = false; if (ok) { open0(c); HL.ui.pop('UNLOCKED'); } else if (ok === false) { FX.spark(at, V3(0, 1, 0), 26, 7, [3, 0.4, 0.3], 0.6); HL.ui.pop('THE CHARM RE-SEALS'); } };
    K.end = end; K.press = (k) => { if (K.done) return; if (k === seq[K.pos]) { const Sp = sp(K.pos), col = Sp.col.map((q) => q * 3); runes[K.pos].classList.remove('cur'); runes[K.pos].classList.add('ok'); rws[K.pos].classList.add('done'); if (links[K.pos]) links[K.pos].classList.add('ok'); FX.spark(at, V3(0, 1, 0), 18, 5, col, 0.5); FX.flashLight(at, Sp.col, 14, 9, 0.3); if (au && au.play) au.play('ring', { vol: 0.6, vary: false, gap: 0.03, rate: Math.pow(2, (K.pos * 2) / 12) }); K.pos++;
        if (K.pos >= n) { K.done = 1; el.classList.add('won'); name(); setTimeout(() => { if (LOOTH.lk === K) end(true); }, 420); } else { runes[K.pos].classList.add('cur'); name(); } }
      else { K.pos = 0; K.t0 -= 1200; runes.forEach((r, i) => { r.classList.remove('ok'); r.classList.toggle('cur', i === 0); }); rws.forEach((r) => r.classList.remove('done')); links.forEach((l) => l.classList.remove('ok')); el.classList.remove('bad'); void el.offsetWidth; el.classList.add('bad'); name(); if (au && au.play) au.play('protego_block', { vol: 0.5, gap: 0.05, rate: 0.7 }); } };
    /* the spell keys work the lock while it is up (and cast nothing) */ MG.onKey = K.key = (code) => { if (code === 'Escape') return end(); const m = /^(?:Digit|Numpad)([1-8])$/.exec(code); if (m) { delete IN.buf['s' + m[1]]; K.press(+m[1] - 1); } };
    const tick = () => { if (LOOTH.lk !== K) return; K.raf = requestAnimationFrame(tick); const a = PLAYER.a; if (MG.state === 'play' && MG.onKey !== K.key) MG.onKey = K.key;   /* (a pause in the middle hands the keys back afterwards) */ if (MG.state !== 'play' && MG.state !== 'pause') return end(); if (!a || !a.alive || Math.hypot(a.x - c.x, a.z - c.z) > 6.5) return end();
      v.set(c.x, c.y + 1.55, c.z).project(R.camera); const vis = v.z < 1 && Math.abs(v.x) < 1.1 && Math.abs(v.y) < 1.1; el.style.visibility = vis ? '' : 'hidden'; el.style.left = ((v.x * 0.5 + 0.5) * innerWidth).toFixed(1) + 'px'; el.style.top = ((-v.y * 0.5 + 0.5) * innerHeight).toFixed(1) + 'px';
      if (!K.done && MG.state === 'play') { K.t = K.T - (performance.now() - K.t0) / 1000; bar.style.transform = `scaleX(${Math.max(0, K.t / K.T)})`; if (K.t <= 0) end(false); } else if (MG.state === 'pause') K.t0 += 16; };
    K.raf = requestAnimationFrame(tick); };
  /* the first time a chest is near, say how its lock works */
  { const u0 = LOOTH.update; let tt = 0; LOOTH.update = function (dt) { u0(dt); tt -= dt; if (tt > 0 || !PLAYER.a || MG.state !== 'play' || HL.save.lockHint) return; tt = 0.5; const a = PLAYER.a; for (const c of LOOTH.chests || []) if (!c.open && Math.hypot(c.x - a.x, c.z - a.z) < 14 && Math.abs(c.y - a.y) < 6) { HL.save.lockHint = 1; HL.store(); if (HL.ui.hint) HL.ui.hint('That chest is sealed by a <b>charmed lock</b> &nbsp; press <kbd>E</kbd> beside it, then cast the spells it shows, in order, on <kbd>1</kbd> – <kbd>8</kbd>', 11); break; } }; }
})();
