/* ==== p81b_hl_planmap.js ==== */
/* HOGWARTS — the floor plan on M when you are in the castle: each storey drawn from the blueprint, its rooms named,
   you, your errand, opened chests; tabs (or 1 2 3) change storey, G unfolds the map of the grounds. */
(function () { const M = HL.map, open0 = M.open; M.planUrls = [];
  M.planUrl = function (k) { if (M.planUrls[k]) return M.planUrls[k]; if (k < 0) { const P = HL.plan(0), S = 6, c = document.createElement('canvas'); c.width = P.NX * S; c.height = P.NZ * S; const x = c.getContext('2d'); x.fillStyle = '#cdbd96'; x.fillRect(0, 0, c.width, c.height);
      for (let j = 0; j < P.NZ; j++) for (let i = 0; i < P.NX; i++) { const ch = P.at(i, j); x.fillStyle = ch === 'w' ? '#9fb0ae' : P.rf(i, j) || ch === '#' ? '#bfae86' : '#cdbd96'; x.fillRect(i * S, j * S, S, S); }
      x.textAlign = 'center'; x.textBaseline = 'middle'; for (const r of HL.DUN.rooms) { const ax = (HL.PL.X0 - r.x1) * S, az = (HL.PL.Z0 - r.z1) * S, w = (r.x1 - r.x0) * S, h = (r.z1 - r.z0) * S; x.fillStyle = '#3a2a18'; x.fillRect(ax - 4, az - 4, w + 8, h + 8); x.fillStyle = /PASSAGE|UNDERCROFT/.test(r.name) ? '#e6cc92' : '#f2e6c6'; x.fillRect(ax, az, w, h); const nm = r.name.replace(/^THE /, ''), words = nm.split(' '), fs = 11; x.font = fs + 'px HLA, Georgia, serif'; x.fillStyle = 'rgba(52,32,10,0.9)'; if (w < 30) continue; words.forEach((wd, n) => x.fillText(wd, ax + w / 2, az + h / 2 + (n - (words.length - 1) / 2) * fs * 1.1)); }
      { const h = HL.DUN.hole, ax = (HL.PL.X0 - h[2]) * S, az = (HL.PL.Z0 - h[3]) * S; x.fillStyle = '#fffaf0'; x.fillRect(ax, az, (h[2] - h[0]) * S, (h[3] - h[1]) * S); x.strokeStyle = '#3a2a18'; x.lineWidth = 1; for (let q = 0; q < 12; q++) { x.beginPath(); x.moveTo(ax + q * S, az); x.lineTo(ax + q * S, az + 3 * S); x.stroke(); } }
      x.strokeStyle = 'rgba(60,36,14,0.8)'; x.lineWidth = 5; x.strokeRect(6, 6, c.width - 12, c.height - 12); return (M.planUrls[k] = c.toDataURL('image/jpeg', 0.9)); }
    const P = HL.plan(k), S = 6, c = document.createElement('canvas'); c.width = P.NX * S; c.height = P.NZ * S; const x = c.getContext('2d'); x.fillStyle = '#d6c69e'; x.fillRect(0, 0, c.width, c.height);
    const col = { F: '#f2e6c6', c: '#e6cc92', e: '#e6cc92', s: '#fffaf0' };
    for (let j = 0; j < P.NZ; j++) for (let i = 0; i < P.NX; i++) { const ch = P.at(i, j); let f = null; if (ch === '#') f = (P.rf(i, j) || k === 0) ? '#3a2a18' : null; else if (P.ind(i, j)) f = col[ch] || col.F; else if (k === 0) f = ch === 'P' ? '#c9b98e' : ch === 'w' ? '#8fa9b0' : ch === 'g' ? '#bdbb86' : '#c4b184'; else if (ch === 'P' && HL.plan(0).rf(i, j)) f = '#c3b48c'; if (f) { x.fillStyle = f; x.fillRect(i * S, j * S, S, S); } }
    const rs = mulberry(9 + k); for (let i = 0; i < 9000; i++) { x.fillStyle = `rgba(${rs() < 0.5 ? '70,50,20' : '255,250,230'},${rs() * 0.05})`; x.fillRect(rs() * c.width, rs() * c.height, 2 + rs() * 5, 1 + rs() * 2); }
    x.textAlign = 'center'; x.textBaseline = 'middle'; for (const q of P.comps) { if (q.kind !== 'room' || !q.name) continue; const w = (q.R.i1 - q.R.i0 + 1) * S, h = (q.R.j1 - q.R.j0 + 1) * S, cx = (q.R.i0 + q.R.i1 + 1) / 2 * S, cy = (q.R.j0 + q.R.j1 + 1) / 2 * S, nm = q.name.replace(/^THE /, '').replace(/^(FIRST|SECOND)-FLOOR /, ''), words = nm.split(' '); let fs = Math.min(19, Math.max(8, Math.min(w / (nm.length * 0.5), h / 2.4))); x.font = `${fs}px HLA, Georgia, serif`; x.fillStyle = 'rgba(52,32,10,0.9)';
        if (x.measureText(nm).width > w - 4 && words.length > 1) { const m2 = Math.ceil(words.length / 2); x.fillText(words.slice(0, m2).join(' '), cx, cy - fs * 0.55); x.fillText(words.slice(m2).join(' '), cx, cy + fs * 0.55); } else x.fillText(nm, cx, cy); }
    if (k === 0 && HL.DUN) { const h = HL.DUN.hole, ax = (HL.PL.X0 - h[2]) * S, az = (HL.PL.Z0 - h[3]) * S; x.fillStyle = '#fffaf0'; x.fillRect(ax, az, (h[2] - h[0]) * S, (h[3] - h[1]) * S); x.strokeStyle = '#3a2a18'; x.lineWidth = 1; for (let q = 0; q <= 12; q++) { x.beginPath(); x.moveTo(ax + q * S, az); x.lineTo(ax + q * S, az + 3 * S); x.stroke(); } x.font = '10px HLA, Georgia, serif'; x.fillStyle = 'rgba(52,32,10,0.95)'; x.fillText('\u2193 DUNGEONS', ax + 36, az + 27); }
    x.strokeStyle = 'rgba(60,36,14,0.8)'; x.lineWidth = 5; x.strokeRect(6, 6, c.width - 12, c.height - 12); return (M.planUrls[k] = c.toDataURL('image/jpeg', 0.9)); };
  M.css2 = `.hlMap.pl { flex-direction: column; gap: 14px; } .hlMap .sheet2 { position: relative;  aspect-ratio: 276 / 316; width: auto; height: min(82vh, 100vw); background-size: 100% 100%; box-shadow: 0 20px 70px #000, 0 0 0 1px #2a1c0c; border-radius: 3px; overflow: hidden; }
.hlMap .tabs { display: flex; gap: 10px; align-items: center; } .hlMap .tab { font-family: 'HLA', serif; letter-spacing: .26em; font-size: 13px; padding: 7px 14px; color: rgba(233,223,201,.7); border: 1px solid rgba(201,164,92,.35); background: rgba(0,0,0,.35); cursor: pointer; pointer-events: auto; } .hlMap .tab.on { color: #1a1206; background: #e2c07a; border-color: #e2c07a; } .hlMap .tab:hover { border-color: #fff3c4; }
.hlMap .tip2 { font-style: italic; color: #a89a80; font-size: 14px; margin-left: 18px; } .hlMap .sheet2 .me i { left: -7px; top: -10px; border-left-width: 7px; border-right-width: 7px; border-bottom-width: 19px; }`;
  M.openPlan = function (k) { const U = HL.ui, a = PLAYER.a, P0 = HL.plan(0), H1 = HL.PL.H1, fl = (y) => y < HL.Y0 - 3 ? -1 : HL.kAt(y), f = fl(a.y); if (k === undefined) k = f; if (!M.url) { M.bake(); const st = document.createElement('style'); st.textContent = M.css; document.head.appendChild(st); } if (!M._c2) { M._c2 = 1; const st = document.createElement('style'); st.textContent = M.css2; document.head.appendChild(st); }
    MG.state = 'map'; if (document.exitPointerLock) document.exitPointerLock(); const pc = (x, z) => `left:${((HL.PL.X0 - x) / P0.NX * 100).toFixed(2)}%;top:${((HL.PL.Z0 - z) / P0.NZ * 100).toFixed(2)}%`, q = HL.quest.way && !HL.Q.on ? HL.quest.way() : null;
    let h = ''; for (const c of HL.LOOT.chests) if (c.open && HL.inFoot(c.x, c.z, 0) && fl(c.y) === k) h += `<div class="cs" style="${pc(c.x, c.z)}"></div>`; if (q && HL.inFoot(q[0], q[2], 2) && fl(q[1] - 1.5) === k) h += `<div class="qm" style="${pc(q[0], q[2])}"></div>`;
    if (f === k) h += `<div class="me" style="${pc(a.x, a.z)};transform:rotate(${(-CAM.yaw).toFixed(3)}rad)"><i></i></div>`;
    const names = ['GROUND FLOOR', 'FIRST FLOOR', 'SECOND FLOOR', 'THIRD FLOOR', 'FOURTH FLOOR']; names[-1] = 'DUNGEONS'; const S = U.screen(`<div class="hlMap pl"><div class="tabs">${[-1].concat(HL.ALLK).map((i) => `<div class="tab ${i === k ? 'on' : ''}" data-k="${i}">${names[i]}${i === f ? ' ·' : ''}</div>`).join('')}<div class="tab" data-k="g">GROUNDS</div></div><div class="tabs"><span class="tip2"><kbd>0</kbd> dungeons · <kbd>1</kbd>–<kbd>5</kbd> storeys · <kbd>G</kbd> grounds · <kbd>M</kbd> / <kbd>Esc</kbd> close${q && fl(q[1] - 1.5) !== k && HL.inFoot(q[0], q[2], 2) ? ' · your errand is on: ' + names[fl(q[1] - 1.5)].toLowerCase() : ''}</span></div><div class="sheet2" style="background-image:url(${M.planUrl(k)})">${h}</div></div>`);
    const close = () => { U.screen(''); MG.state = 'play'; MG.onKey = null; IN.buf = {}; HL.noPauseT = MG.rt + 0.25; }, go = (v) => { close(); if (v === 'g') open0(); else M.openPlan(+v); };
    S.querySelectorAll('.tab').forEach((e) => e.onclick = () => go(e.dataset.k)); MG.onKey = (c) => { if (c === 'Escape' || c === 'KeyM') close(); else if (c === 'KeyG') go('g'); else { const m = /^Digit([0-5])$/.exec(c); if (m) go(+m[1] - 1); } }; };
  M.open = function () { if (MG.state !== 'play' || !PLAYER.a) return; const a = PLAYER.a; if (HL.inFoot(a.x, a.z, 6) && a.z > -58 && a.y < HL.Y0 + 40 && PLAYER.state !== 'fly' && !HL.Q.on) return M.openPlan(); return open0(); };
})();
