/* ==== p81c_hl_mmap.js ==== */
/* HOGWARTS — the map, drawn as an enchanted chart: walls inked by hand on old parchment, every room lettered in a
   clerk's script, a ribbon for a title, a compass and a creature in the loch; and, as such maps do, it shows the
   footprints of everyone in the castle, walking, with their names beside them. Wheel zooms, drag pans.
   M / Esc folds it; 0–5 turn to a storey; G unfolds the chart of the grounds. */
(function () {
  const M = HL.map, INK = '#3a2412', SCRIPT = "Luminari, 'Apple Chancery', 'Snell Roundhand', 'Lucida Calligraphy', 'Brush Script MT', cursive", HAND = "'Apple Chancery', Luminari, 'Snell Roundhand', 'Lucida Calligraphy', cursive";
  const S = 5, MX = 110, MY = 250, MB = 150; M.sheets = {};
  /* ---------------------------------------------------------------- parchment and ink */
  const paper = (x, W, H, seed) => { const rs = mulberry(seed); let g = x.createRadialGradient(W / 2, H / 2, Math.min(W, H) * 0.18, W / 2, H / 2, Math.hypot(W, H) * 0.6); g.addColorStop(0, '#ecdcb2'); g.addColorStop(0.62, '#dfca96'); g.addColorStop(1, '#b08e54'); x.fillStyle = g; x.fillRect(0, 0, W, H);
    for (let i = 0; i < 90; i++) { const bx = rs() * W, by = rs() * H, r = 50 + rs() * 260, gg = x.createRadialGradient(bx, by, 0, bx, by, r); gg.addColorStop(0, rs() < 0.6 ? 'rgba(126,88,38,0.085)' : 'rgba(255,246,214,0.10)'); gg.addColorStop(1, 'rgba(0,0,0,0)'); x.fillStyle = gg; x.fillRect(bx - r, by - r, 2 * r, 2 * r); }
    for (let i = 0; i < 3400; i++) { x.strokeStyle = `rgba(${rs() < 0.5 ? '92,62,26' : '255,247,222'},${0.03 + rs() * 0.05})`; x.lineWidth = 0.6 + rs(); const fx = rs() * W, fy = rs() * H, a = rs() * TAU, l = 6 + rs() * 30; x.beginPath(); x.moveTo(fx, fy); x.quadraticCurveTo(fx + Math.cos(a) * l * 0.5 + (rs() - 0.5) * 7, fy + Math.sin(a) * l * 0.5 + (rs() - 0.5) * 7, fx + Math.cos(a) * l, fy + Math.sin(a) * l); x.stroke(); }
    for (const fx of [W / 3, 2 * W / 3]) { const gg = x.createLinearGradient(fx - 30, 0, fx + 30, 0); gg.addColorStop(0, 'rgba(80,50,20,0)'); gg.addColorStop(0.47, 'rgba(80,50,20,0.17)'); gg.addColorStop(0.5, 'rgba(255,246,216,0.26)'); gg.addColorStop(0.53, 'rgba(80,50,20,0.13)'); gg.addColorStop(1, 'rgba(80,50,20,0)'); x.fillStyle = gg; x.fillRect(fx - 30, 0, 60, H); }
    { const fy = H / 2, gg = x.createLinearGradient(0, fy - 30, 0, fy + 30); gg.addColorStop(0, 'rgba(80,50,20,0)'); gg.addColorStop(0.47, 'rgba(80,50,20,0.15)'); gg.addColorStop(0.5, 'rgba(255,246,216,0.24)'); gg.addColorStop(0.53, 'rgba(80,50,20,0.12)'); gg.addColorStop(1, 'rgba(80,50,20,0)'); x.fillStyle = gg; x.fillRect(0, fy - 30, W, 60); }
    for (let i = 0; i < 700; i++) { const e = (rs() * 4) | 0, t = rs(), r = 10 + rs() * 46, bx = e < 2 ? t * W : e === 2 ? 0 : W, by = e === 0 ? 0 : e === 1 ? H : t * H, gg = x.createRadialGradient(bx, by, 0, bx, by, r); gg.addColorStop(0, 'rgba(58,32,8,0.36)'); gg.addColorStop(1, 'rgba(58,32,8,0)'); x.fillStyle = gg; x.fillRect(bx - r, by - r, 2 * r, 2 * r); }
    for (let i = 0; i < 3; i++) { const bx = W * (0.15 + rs() * 0.7), by = H * (0.2 + rs() * 0.65), r = 46 + rs() * 40; x.strokeStyle = 'rgba(110,70,28,0.10)'; x.lineWidth = 5 + rs() * 4; x.beginPath(); x.arc(bx, by, r, rs() * TAU, rs() * TAU + 4.6); x.stroke(); } };
  /* a line drawn by hand: bowed a little, gone over twice */
  const hl = (x, ax, ay, bx, by, rs, w, a) => { for (let p = 0; p < 2; p++) { x.beginPath(); x.moveTo(ax + (rs() - 0.5) * 1.6, ay + (rs() - 0.5) * 1.6); x.quadraticCurveTo((ax + bx) / 2 + (rs() - 0.5) * 2.6, (ay + by) / 2 + (rs() - 0.5) * 2.6, bx + (rs() - 0.5) * 1.6, by + (rs() - 0.5) * 1.6); x.lineWidth = w * (0.75 + rs() * 0.5); x.globalAlpha = a * (p ? 0.45 : 0.92); x.stroke(); } x.globalAlpha = 1; };
  const frame = (x, W, H, rs) => { x.strokeStyle = INK; for (const [d, w] of [[34, 5], [46, 1.6], [52, 1]]) { hl(x, d, d, W - d, d, rs, w, 0.85); hl(x, W - d, d, W - d, H - d, rs, w, 0.85); hl(x, W - d, H - d, d, H - d, rs, w, 0.85); hl(x, d, H - d, d, d, rs, w, 0.85); }
    for (const [cx, cy, sx, sy] of [[34, 34, 1, 1], [W - 34, 34, -1, 1], [34, H - 34, 1, -1], [W - 34, H - 34, -1, -1]]) { x.save(); x.translate(cx, cy); x.scale(sx, sy); x.globalAlpha = 0.85; x.lineWidth = 2; x.beginPath(); x.moveTo(18, 70); x.bezierCurveTo(18, 30, 30, 18, 70, 18); x.stroke(); x.beginPath(); x.moveTo(30, 96); x.bezierCurveTo(26, 60, 44, 40, 50, 50); x.bezierCurveTo(56, 60, 40, 64, 40, 54); x.stroke(); x.beginPath(); x.moveTo(96, 30); x.bezierCurveTo(60, 26, 40, 44, 50, 50); x.stroke(); x.fillStyle = INK; x.beginPath(); x.moveTo(18, 6); x.lineTo(26, 18); x.lineTo(18, 30); x.lineTo(10, 18); x.fill(); x.restore(); } x.globalAlpha = 1; };
  /* the title: a ribbon with swallow-tails, the name in a black-letter hand, a line beneath */
  const ribbon = (x, W, y, title, sub, rs) => { x.font = `92px ${SCRIPT}`; const tw = Math.max(520, x.measureText(title).width + 150), x0 = W / 2 - tw / 2, x1 = W / 2 + tw / 2, h = 104;
    x.fillStyle = 'rgba(140,96,40,0.5)'; x.strokeStyle = INK; x.lineWidth = 2.4; for (const sd of [-1, 1]) { const ex = sd < 0 ? x0 : x1; x.beginPath(); x.moveTo(ex + sd * 10, y + 26); x.lineTo(ex + sd * 96, y + 26); x.lineTo(ex + sd * 66, y + 26 + h / 2); x.lineTo(ex + sd * 96, y + 26 + h); x.lineTo(ex + sd * 10, y + 26 + h); x.closePath(); x.fill(); x.stroke(); x.beginPath(); x.moveTo(ex, y + h); x.lineTo(ex + sd * 10, y + 26 + h); x.lineTo(ex + sd * 10, y + 26); x.closePath(); x.fillStyle = 'rgba(70,42,14,0.75)'; x.fill(); x.fillStyle = 'rgba(140,96,40,0.5)'; }
    const g = x.createLinearGradient(0, y, 0, y + h); g.addColorStop(0, '#f2e4bc'); g.addColorStop(0.5, '#e6d29c'); g.addColorStop(1, '#cdb276'); x.fillStyle = g; x.beginPath(); x.moveTo(x0, y); x.quadraticCurveTo(W / 2, y - 16, x1, y); x.lineTo(x1, y + h); x.quadraticCurveTo(W / 2, y + h - 16, x0, y + h); x.closePath(); x.fill(); x.stroke();
    x.lineWidth = 1; x.globalAlpha = 0.6; x.beginPath(); x.moveTo(x0 + 12, y + 10); x.quadraticCurveTo(W / 2, y - 5, x1 - 12, y + 10); x.stroke(); x.beginPath(); x.moveTo(x0 + 12, y + h - 12); x.quadraticCurveTo(W / 2, y + h - 27, x1 - 12, y + h - 12); x.stroke(); x.globalAlpha = 1;
    x.fillStyle = '#2c1a0a'; x.textAlign = 'center'; x.textBaseline = 'middle'; x.font = `92px ${SCRIPT}`; x.fillText(title, W / 2, y + h / 2 - 6); x.font = `italic 36px ${HAND}`; x.fillStyle = INK; x.fillText(sub, W / 2, y + h + 46);
    x.strokeStyle = INK; x.lineWidth = 1.6; for (const sd of [-1, 1]) { const sw = x.measureText(sub).width / 2 + 26; x.beginPath(); x.moveTo(W / 2 + sd * sw, y + h + 48); x.bezierCurveTo(W / 2 + sd * (sw + 60), y + h + 30, W / 2 + sd * (sw + 110), y + h + 66, W / 2 + sd * (sw + 170), y + h + 48); x.stroke(); x.beginPath(); x.arc(W / 2 + sd * (sw + 178), y + h + 48, 4, 0, TAU); x.fill(); } };
  const compass = (x, cx, cy, r, rs) => { x.save(); x.translate(cx, cy); x.strokeStyle = INK; x.fillStyle = INK; x.lineWidth = 1.6; for (const rr of [r, r * 0.86, r * 0.3]) { x.beginPath(); x.arc(0, 0, rr, 0, TAU); x.globalAlpha = 0.8; x.stroke(); } for (let i = 0; i < 32; i++) { const a = i / 32 * TAU; x.beginPath(); x.moveTo(Math.cos(a) * r * 0.86, Math.sin(a) * r * 0.86); x.lineTo(Math.cos(a) * r * (i % 4 ? 0.92 : 1), Math.sin(a) * r * (i % 4 ? 0.92 : 1)); x.stroke(); }
    for (let i = 0; i < 8; i++) { const a = i / 8 * TAU - HALF, L = i % 2 ? r * 0.62 : r * 1.16, wd = i % 2 ? 0.14 : 0.2; x.globalAlpha = 0.9; x.beginPath(); x.moveTo(Math.cos(a) * L, Math.sin(a) * L); x.lineTo(Math.cos(a + wd * 2.2) * r * 0.22, Math.sin(a + wd * 2.2) * r * 0.22); x.lineTo(0, 0); x.closePath(); x.fill(); x.beginPath(); x.moveTo(Math.cos(a) * L, Math.sin(a) * L); x.lineTo(Math.cos(a - wd * 2.2) * r * 0.22, Math.sin(a - wd * 2.2) * r * 0.22); x.lineTo(0, 0); x.closePath(); x.globalAlpha = 0.85; x.stroke(); }
    x.globalAlpha = 1; x.font = `${r * 0.5}px ${SCRIPT}`; x.textAlign = 'center'; x.textBaseline = 'middle'; x.fillText('N', 0, -r * 1.42); x.font = `${r * 0.3}px ${SCRIPT}`; x.fillText('S', 0, r * 1.36); x.fillText('E', r * 1.36, 0); x.fillText('W', -r * 1.36, 0); x.restore(); };
  /* the creature of the loch: a few inked coils and a tentacle or two */
  const squid = (x, cx, cy, s, rs) => { x.save(); x.translate(cx, cy); x.scale(s, s); x.strokeStyle = 'rgba(40,52,60,0.7)'; x.lineWidth = 2.2; x.lineCap = 'round'; for (let i = 0; i < 5; i++) { const a = -2.4 + i * 0.5, L = 46 + (i % 2) * 20; x.beginPath(); x.moveTo(0, 0); x.bezierCurveTo(Math.cos(a) * L * 0.4, Math.sin(a) * L * 0.4 - 14, Math.cos(a) * L * 0.8 + 12, Math.sin(a) * L * 0.8, Math.cos(a) * L, Math.sin(a) * L - 10 + (i % 2) * 20); x.stroke(); for (let q = 2; q < 6; q++) { x.beginPath(); x.arc(Math.cos(a) * L * q / 6, Math.sin(a) * L * q / 6 - 6, 1.6, 0, TAU); x.stroke(); } }
    x.fillStyle = 'rgba(40,52,60,0.32)'; x.beginPath(); x.ellipse(6, 16, 24, 15, 0.3, 0, TAU); x.fill(); x.stroke(); x.beginPath(); x.arc(-2, 12, 3, 0, TAU); x.fillStyle = 'rgba(240,230,200,0.9)'; x.fill(); x.stroke(); for (let i = 0; i < 3; i++) { x.beginPath(); x.arc(0, 26, 40 + i * 16, 0.4, 2.2); x.globalAlpha = 0.35 - i * 0.08; x.stroke(); } x.restore(); x.globalAlpha = 1; };
  const tc = (t) => t.toLowerCase().replace(/(^|[\s\-])([a-z\u00e0-\u00ff])/g, (m, a, b) => a + b.toUpperCase()).replace(/\b(Of|The|And|Against)\b/g, (m) => m.toLowerCase()).replace(/^([a-z])/, (m) => m.toUpperCase()).replace(/\u2019S\b/g, '\u2019s');
  const label = (x, text, cx, cy, wpx, hpx, o) => { o = o || {}; const words = text.split(' '), fam = o.fam || HAND; let best = null; for (let nl = 1; nl <= Math.min(3, words.length); nl++) { const per = Math.ceil(words.length / nl), lines = []; for (let q = 0; q < words.length; q += per) lines.push(words.slice(q, q + per).join(' ')); const ml = Math.max(...lines.map((l) => l.length)), fs = Math.min(wpx / (ml * 0.5), hpx / (lines.length * 1.18)); if (!best || fs > best.fs) best = { fs, lines }; }
    const fs = clamp(best.fs, o.min || 15, o.max || 46); x.save(); x.translate(cx, cy); x.rotate(o.rot || 0); x.font = `${o.it ? 'italic ' : ''}${fs}px ${fam}`; x.textAlign = 'center'; x.textBaseline = 'middle'; x.lineJoin = 'round'; best.lines.forEach((l, n) => { const yy = (n - (best.lines.length - 1) / 2) * fs * 1.12; x.strokeStyle = 'rgba(236,220,178,0.82)'; x.lineWidth = fs * 0.26; x.strokeText(l, 0, yy); x.fillStyle = o.col || '#2c1a0a'; x.fillText(l, 0, yy); }); x.restore(); };
  /* ---------------------------------------------------------------- the castle, storey by storey */
  M.castleSheet = function (k) { if (M.sheets[k]) return M.sheets[k]; const P = HL.plan(Math.max(0, k)), P0 = HL.plan(0), NX = P.NX, NZ = P.NZ, W = NX * S + MX * 2, H = NZ * S + MY + MB, c = document.createElement('canvas'); c.width = W; c.height = H; const x = c.getContext('2d'), rs = mulberry(77 + k * 13), px = (i) => MX + i * S, py = (j) => MY + j * S;
    paper(x, W, H, 5 + k);
    // washes, painted small and let to bleed
    { const w = document.createElement('canvas'); w.width = NX; w.height = NZ; const q = w.getContext('2d'), im = q.createImageData(NX, NZ), put = (s, r, g, b, a) => { im.data[s] = r; im.data[s + 1] = g; im.data[s + 2] = b; im.data[s + 3] = a; };
      for (let j = 0; j < NZ; j++) for (let i = 0; i < NX; i++) { const s = (j * NX + i) * 4, c0 = P0.at(i, j); if (c0 === 'w') { put(s, 92, 130, 142, 150); continue; } if (k < 0) { if (P0.rf(i, j)) put(s, 120, 90, 50, 26); else if (c0 === 'g') put(s, 118, 128, 64, 30); continue; }
        const ch = P.at(i, j); if (P.ind(i, j)) { if (ch === 'c' || ch === 'e') put(s, 206, 160, 84, 74); else put(s, 255, 250, 232, 96); } else if (k === 0) { if (c0 === 'P') put(s, 150, 138, 116, 56); else if (c0 === 'g') put(s, 118, 128, 64, 40); } else if (P0.rf(i, j)) put(s, 120, 90, 50, P.rf(i, j) ? 46 : 22); else if (c0 === 'g') put(s, 118, 128, 64, 18); }
      q.putImageData(im, 0, 0); x.imageSmoothingEnabled = true; x.drawImage(w, MX, MY, NX * S, NZ * S); }
    // the loch and the land: little waves, tufts, a tree here and there
    x.strokeStyle = 'rgba(44,70,84,0.42)'; x.lineWidth = 1.3; for (let j = 1; j < NZ; j += 3) for (let i = (j % 6 ? 1 : 3); i < NX; i += 5) { if (P0.at(i, j) !== 'w' || rs() < 0.45) continue; const ax = px(i) + rs() * 8, ay = py(j) + rs() * 8; x.beginPath(); x.moveTo(ax, ay); x.quadraticCurveTo(ax + 4, ay - 4, ax + 8, ay); x.quadraticCurveTo(ax + 12, ay + 4, ax + 16, ay); x.stroke(); }
    if (k <= 0) { x.strokeStyle = 'rgba(70,84,30,0.4)'; x.lineWidth = 1.1; for (let j = 2; j < NZ; j += 4) for (let i = 2; i < NX; i += 4) { if (P0.at(i, j) !== 'g' || P0.rf(i, j) || rs() < 0.62) continue; const ax = px(i) + rs() * 14, ay = py(j) + rs() * 14; if (rs() < 0.14) { x.beginPath(); x.arc(ax, ay - 8, 6 + rs() * 3, 0, TAU); x.moveTo(ax, ay - 2); x.lineTo(ax, ay + 5); x.stroke(); x.fillStyle = 'rgba(70,92,34,0.2)'; x.beginPath(); x.arc(ax, ay - 8, 6, 0, TAU); x.fill(); } else for (const d of [-3, 0, 3]) { x.beginPath(); x.moveTo(ax + d, ay); x.lineTo(ax + d * 1.6, ay - 5 - (d ? 0 : 2)); x.stroke(); } } }
    if (k === 0) { x.fillStyle = 'rgba(70,50,30,0.3)'; for (let j = 0; j < NZ; j += 2) for (let i = (j % 4 ? 0 : 1); i < NX; i += 2) if (P0.at(i, j) === 'P' && !P0.rf(i, j) && rs() < 0.5) x.fillRect(px(i) + rs() * 8, py(j) + rs() * 8, 1.6, 1.6); }
    if (k >= 0) { // the furniture, from the same grid the furnishers use
      const g = HL.occ.grid(k), f = document.createElement('canvas'); f.width = g.W; f.height = g.H; const q = f.getContext('2d'), im = q.createImageData(g.W, g.H); for (let s = 0; s < g.W * g.H; s++) { const v = g.a[s]; if (v === 3 || v === 5 || v === 6) { im.data[s * 4] = 78; im.data[s * 4 + 1] = 48; im.data[s * 4 + 2] = 20; im.data[s * 4 + 3] = v === 6 ? 170 : v === 5 ? 120 : 84; } } q.putImageData(im, 0, 0); x.imageSmoothingEnabled = false; x.drawImage(f, MX, MY, NX * S, NZ * S); x.imageSmoothingEnabled = true; }
    // walls: every run inked as a bar with a hand's unevenness, its edges gone over
    x.fillStyle = INK; x.strokeStyle = INK; const wall = (i0, j0, i1, j1, a) => { const ax = px(i0) + 0.8, ay = py(j0) + 0.8, bx = px(i1 + 1) - 0.8, by = py(j1 + 1) - 0.8, j = () => (rs() - 0.5) * 1.5; x.globalAlpha = a; x.beginPath(); x.moveTo(ax + j(), ay + j()); x.lineTo(bx + j(), ay + j()); x.lineTo(bx + j(), by + j()); x.lineTo(ax + j(), by + j()); x.closePath(); x.fill(); x.globalAlpha = 1; if (bx - ax > by - ay) { hl(x, ax, ay, bx, ay, rs, 1, a * 0.7); hl(x, ax, by, bx, by, rs, 1, a * 0.7); } else { hl(x, ax, ay, ax, by, rs, 1, a * 0.7); hl(x, bx, ay, bx, by, rs, 1, a * 0.7); } };
    if (k < 0) { HL.greedy(P0, (i, j) => P0.isW(i, j) && P0.rf(i, j) ? 'w' : null, (i0, j0, i1, j1) => wall(i0, j0, i1, j1, 0.16)); const D = HL.DUN, yd = 0;
      for (const r of D.rooms) { const ax = px(HL.PL.X0 - r.x1), ay = py(HL.PL.Z0 - r.z1), w = (r.x1 - r.x0) * S, h = (r.z1 - r.z0) * S; x.fillStyle = /PASSAGE|UNDERCROFT/.test(r.name) ? 'rgba(214,170,90,0.42)' : 'rgba(255,250,232,0.6)'; x.fillRect(ax, ay, w, h); x.strokeStyle = INK; for (const [a2, b2, c2, d2] of [[ax - 2, ay - 2, ax + w + 2, ay - 2], [ax + w + 2, ay - 2, ax + w + 2, ay + h + 2], [ax + w + 2, ay + h + 2, ax - 2, ay + h + 2], [ax - 2, ay + h + 2, ax - 2, ay - 2]]) hl(x, a2, b2, c2, d2, rs, 4.2, 0.9); }
      for (const r of D.rooms) label(x, tc(r.name.replace(/^THE /, '')), px(HL.PL.X0 - (r.x0 + r.x1) / 2), py(HL.PL.Z0 - (r.z0 + r.z1) / 2), Math.max(60, (r.x1 - r.x0) * S * (r.z1 - r.z0 > (r.x1 - r.x0) * 2 ? 2.2 : 1) - 8), Math.max(40, (r.z1 - r.z0) * S - 8), { min: 13, max: 30, rot: r.z1 - r.z0 > (r.x1 - r.x0) * 2 ? -HALF : 0 }); }
    else { HL.greedy(P, (i, j) => P.isW(i, j) && (k === 0 || P.rf(i, j)) ? 'w' : null, (i0, j0, i1, j1) => wall(i0, j0, i1, j1, 0.94));
      if (k > 0) HL.greedy(P0, (i, j) => P0.isW(i, j) && P0.rf(i, j) && !P.rf(i, j) ? 'w' : null, (i0, j0, i1, j1) => wall(i0, j0, i1, j1, 0.14));
      // doors: a leaf and the sweep of it
      x.strokeStyle = INK; x.lineWidth = 1.1; for (const d of P.doors) { if (!d.inn || (d.ext && k > 0)) continue; const w = (d.dir === 1 ? d.i1 - d.i0 : d.j1 - d.j0) * S; x.globalAlpha = 0.6; x.beginPath(); if (d.dir === 1) { const ax = px(d.i0), ay = py(d.j0) + (d.j1 - d.j0) * S / 2, sg = (d.i0 + d.j0) % 2 ? 1 : -1; x.moveTo(ax, ay); x.lineTo(ax, ay + sg * w * 0.9); x.arc(ax, ay, w * 0.9, sg > 0 ? HALF : -HALF, 0, sg > 0); } else { const ax = px(d.i0) + (d.i1 - d.i0) * S / 2, ay = py(d.j0), sg = (d.i0 + d.j0) % 2 ? 1 : -1; x.moveTo(ax, ay); x.lineTo(ax + sg * w * 0.9, ay); x.arc(ax, ay, w * 0.9, sg > 0 ? 0 : PI, HALF, sg < 0); } x.stroke(); } x.globalAlpha = 1;
      // the stair wells: a ring and its treads
      for (const nm in HL.WELLN) { const c0 = P0.comps.find((q) => q.name === nm); if (!c0 || !c0.tallH || c0.tallH < k * HL.PL.H1 + 1) continue; const rw = HL.WELLN[nm], ax = px(c0.R.i0 + rw), ay = py(c0.R.j0 + rw), bx = px(c0.R.i1 + 1 - rw), by = py(c0.R.j1 + 1 - rw); x.strokeStyle = INK; hl(x, ax, ay, bx, ay, rs, 1.4, 0.8); hl(x, bx, ay, bx, by, rs, 1.4, 0.8); hl(x, bx, by, ax, by, rs, 1.4, 0.8); hl(x, ax, by, ax, ay, rs, 1.4, 0.8); x.lineWidth = 1; x.globalAlpha = 0.55; for (let t = ax + 6; t < bx - 14; t += 5) { x.beginPath(); x.moveTo(t, ay + 2); x.lineTo(t, ay + 13); x.stroke(); } for (let t = ay + 16; t < by - 4; t += 5) { x.beginPath(); x.moveTo(ax + 2, t); x.lineTo(ax + 13, t); x.stroke(); } x.globalAlpha = 1; }
      if (k === 0 && HL.DUN) HL.DUN.holes.forEach((h, n) => { const ax = px(HL.PL.X0 - h[2]), ay = py(HL.PL.Z0 - h[3]), w = (h[2] - h[0]) * S, hh = (h[3] - h[1]) * S, lx2 = w >= hh; x.fillStyle = 'rgba(60,36,16,0.3)'; x.fillRect(ax, ay, w, hh); x.strokeStyle = INK; x.lineWidth = 1; for (let t = 0; t <= (lx2 ? w : hh); t += 5) { x.beginPath(); if (lx2) { x.moveTo(ax + t, ay); x.lineTo(ax + t, ay + hh); } else { x.moveTo(ax, ay + t); x.lineTo(ax + w, ay + t); } x.stroke(); } label(x, n ? 'down to Slytherin' : 'down to the dungeons', lx2 ? ax + w / 2 : ax + w + 44, lx2 ? ay + hh + 13 : ay + hh / 2 + 18, 160, 22, { min: 15, max: 17, it: 1 }); });
      // names: rooms in a clerk's hand; courts and bridges in italics
      for (const q of P.comps) { if (q.kind !== 'room' || !q.name || q.type === 'closet') continue; const w = (q.R.i1 - q.R.i0 + 1) * S, h = (q.R.j1 - q.R.j0 + 1) * S; if (w < 34 || h < 28) continue; const nm = q.name.replace(/^THE /, '').replace(/^(FIRST|SECOND|THIRD|FOURTH)-FLOOR /, ''), tall = h > w * 1.9 && w < 90; label(x, tc(nm), px((q.R.i0 + q.R.i1 + 1) / 2), py((q.R.j0 + q.R.j1 + 1) / 2), (tall ? h : w) - 14, (tall ? w : h) - 10, { rot: tall ? -HALF : (rs() - 0.5) * 0.05, min: 14, max: 44 }); }
      if (k === 0) for (const o of HL.OUTDOOR || []) { const w = (o.x1 - o.x0) * S, h = (o.z1 - o.z0) * S, cx2 = px(HL.PL.X0 - (o.x0 + o.x1) / 2), cy2 = py(HL.PL.Z0 - (o.z0 + o.z1) / 2), nm = o.name.replace(/^THE /, ''); label(x, tc(nm), cx2, cy2 - (o.kind === 'court' ? h * 0.3 : 0), Math.max(w, h) - 16, o.kind === 'bridge' ? 26 : Math.min(w, h) * 0.5, { it: 1, col: '#4a3418', min: 14, max: o.kind === 'court' ? 30 : 20, rot: h > w * 1.6 ? -HALF : 0 }); } }
    // the chart's furniture: frame, title, compass, the creature, a motto
    frame(x, W, H, rs); ribbon(x, W, 62, 'Hogwarts', k < 0 ? 'the Dungeons: kitchens, cellars & two common rooms' : ['the Ground Floor: its halls, courts & classrooms', 'the First Floor', 'the Second Floor', 'the Third Floor', 'the Fourth Floor, & the tower rooms'][k], rs);
    compass(x, MX + 92, H - MB - 150, 54, rs); squid(x, px(92), py(228), 1.7, rs); squid(x, px(196), py(40), 1.2, rs);
    x.fillStyle = INK; x.textAlign = 'center'; x.font = `italic 30px ${HAND}`; x.globalAlpha = 0.85; x.fillText('Draco dormiens nunquam titillandus', W / 2, H - 84); x.font = `22px ${HAND}`; x.fillText('~ a true & faithful chart of the castle, drawn for the use of its students ~', W / 2, H - 116); x.globalAlpha = 1;
    return (M.sheets[k] = { url: c.toDataURL('image/jpeg', 0.88), W, H, pc: (wx, wz) => [(MX + (HL.PL.X0 - wx) * S) / W * 100, (MY + (HL.PL.Z0 - wz) * S) / H * 100], inSheet: (wx, wz) => HL.inFoot(wx, wz, 30) }); };
  /* ---------------------------------------------------------------- the grounds: the world seen from above, taken down as an illustrated chart */
  M.groundSheet = function () { if (M.sheets.g) return M.sheets.g; const N = M.N, r = R.renderer, rt = new THREE.WebGLRenderTarget(N, N, { depthBuffer: true }), cam = new THREE.OrthographicCamera(-M.W / 2, M.W / 2, M.W / 2, -M.W / 2, 1, 2400);
    cam.position.set(M.cx, 1200, M.cz); cam.up.set(0, 0, 1); cam.lookAt(M.cx, 0, M.cz); cam.updateMatrixWorld(true);
    const fd = R.scene.fog ? R.scene.fog.density : 0, hi = R.hemi.intensity, vis = []; if (R.scene.fog) R.scene.fog.density = 0; R.hemi.intensity = HL.LOOK.hemiI * Math.PI * 1.3; for (const a of [PLAYER.a].concat(HL.npcs)) if (a && a.root.visible) { a.root.visible = false; vis.push(a); }
    const prev = r.getRenderTarget(); r.setRenderTarget(rt); r.clear(true, true, true); r.render(R.scene, cam); const pxl = new Uint8Array(N * N * 4); r.readRenderTargetPixels(rt, 0, 0, N, N, pxl); r.setRenderTarget(prev); rt.dispose(); if (R.scene.fog) R.scene.fog.density = fd; R.hemi.intensity = hi; for (const a of vis) a.root.visible = true;
    const SC = 1.5, PAD = 120, TOP = 250, W = N * SC + PAD * 2, H = N * SC + TOP + 150, c = document.createElement('canvas'); c.width = W; c.height = H; const x = c.getContext('2d'), rs = mulberry(41); paper(x, W, H, 23);
    // classify what was seen: water, wood, open ground; paint it as washes
    const cls = new Uint8Array(N * N), lum = new Float32Array(N * N), w = document.createElement('canvas'); w.width = w.height = N; const q = w.getContext('2d'), im = q.createImageData(N, N);
    for (let j = 0; j < N; j++) for (let i = 0; i < N; i++) { const s = ((N - 1 - j) * N + i) * 4, t = j * N + i, R0 = Math.pow(Math.min(1, pxl[s] / 255 * 1.5), 1 / 2.2), G0 = Math.pow(Math.min(1, pxl[s + 1] / 255 * 1.5), 1 / 2.2), B0 = Math.pow(Math.min(1, pxl[s + 2] / 255 * 1.5), 1 / 2.2), l = R0 * 0.3 + G0 * 0.6 + B0 * 0.1; lum[t] = l;
      const water = B0 > G0 * 1.02 && B0 > R0 * 1.15 && l < 0.5, wood = !water && G0 > R0 * 1.12 && G0 > B0 * 1.2 && l < 0.4, path = !water && l > 0.62 && Math.abs(R0 - G0) < 0.08; cls[t] = water ? 1 : wood ? 2 : path ? 3 : 0; const o = t * 4;
      if (water) { im.data[o] = 96; im.data[o + 1] = 134; im.data[o + 2] = 146; im.data[o + 3] = 170; } else if (wood) { im.data[o] = 70; im.data[o + 1] = 88; im.data[o + 2] = 36; im.data[o + 3] = 120; } else if (path) { im.data[o] = 250; im.data[o + 1] = 240; im.data[o + 2] = 210; im.data[o + 3] = 110; } else { const d = clamp((0.5 - l) * 2, -0.5, 1); im.data[o] = d > 0 ? 96 : 255; im.data[o + 1] = d > 0 ? 80 : 248; im.data[o + 2] = d > 0 ? 40 : 220; im.data[o + 3] = Math.abs(d) * 110; } }
    q.putImageData(im, 0, 0); x.imageSmoothingEnabled = true; x.drawImage(w, PAD, TOP, N * SC, N * SC);
    const gx = (i) => PAD + i * SC, gy = (j) => TOP + j * SC, at = (i, j) => cls[clamp(j | 0, 0, N - 1) * N + clamp(i | 0, 0, N - 1)], wpx = (wx, wz) => { const u = M.uv(wx, wz); return [PAD + u[0] * N * SC, TOP + u[1] * N * SC]; };
    // waves on the water, firs in the forest, hills where the land climbs
    x.strokeStyle = 'rgba(44,70,84,0.45)'; x.lineWidth = 1.3; for (let j = 6; j < N; j += 11) for (let i = (j % 22 ? 4 : 10); i < N; i += 16) { if (at(i, j) !== 1 || at(i + 6, j) !== 1 || rs() < 0.3) continue; const ax = gx(i) + rs() * 8, ay = gy(j) + rs() * 6; x.beginPath(); x.moveTo(ax, ay); x.quadraticCurveTo(ax + 5, ay - 5, ax + 10, ay); x.quadraticCurveTo(ax + 15, ay + 5, ax + 20, ay); x.stroke(); }
    x.lineWidth = 1.2; for (let j = 5; j < N; j += 9) for (let i = (j % 18 ? 3 : 8); i < N; i += 10) { if (at(i, j) !== 2 || rs() < 0.2) continue; const ax = gx(i) + (rs() - 0.5) * 8, ay = gy(j) + (rs() - 0.5) * 6, s2 = 0.8 + rs() * 0.6; x.fillStyle = 'rgba(52,70,28,0.5)'; x.strokeStyle = 'rgba(34,44,16,0.75)'; x.beginPath(); x.moveTo(ax, ay - 13 * s2); x.lineTo(ax + 6 * s2, ay); x.lineTo(ax + 2 * s2, ay); x.lineTo(ax + 7 * s2, ay + 7 * s2); x.lineTo(ax - 7 * s2, ay + 7 * s2); x.lineTo(ax - 2 * s2, ay); x.lineTo(ax - 6 * s2, ay); x.closePath(); x.fill(); x.stroke(); x.beginPath(); x.moveTo(ax, ay + 7 * s2); x.lineTo(ax, ay + 11 * s2); x.stroke(); }
    { const hs = []; let hmin = 1e9, hmax = -1e9; const GN = 56; for (let b = 0; b < GN; b++) for (let a = 0; a < GN; a++) { const wx = M.cx + M.W / 2 - (a + 0.5) / GN * M.W, wz = M.cz + M.W / 2 - (b + 0.5) / GN * M.W, h = HL.h(wx, wz); hs.push(h); hmin = Math.min(hmin, h); hmax = Math.max(hmax, h); } const srt = hs.slice().sort((p1, p2) => p1 - p2), thr = Math.max(HL.Y0 + 40, srt[(srt.length * 0.84) | 0]);
      x.strokeStyle = 'rgba(58,36,18,0.7)'; x.lineWidth = 1.5; for (let b = 0; b < GN; b++) for (let a = (b % 2); a < GN; a += 2) { const h = hs[b * GN + a]; if (h < thr || rs() < 0.25) continue; const i = (a + 0.5) / GN * N, j = (b + 0.5) / GN * N; if (at(i, j) === 1) continue; const ax = gx(i) + (rs() - 0.5) * 12, ay = gy(j) + (rs() - 0.5) * 8, s2 = clamp(0.8 + (h - thr) / 70, 0.8, 1.7) * 17; x.fillStyle = 'rgba(232,216,172,0.85)'; x.beginPath(); x.moveTo(ax - s2, ay + s2 * 0.5); x.lineTo(ax - s2 * 0.2, ay - s2 * 0.7); x.lineTo(ax + s2 * 0.15, ay - s2 * 0.3); x.lineTo(ax + s2 * 0.45, ay - s2 * 0.55); x.lineTo(ax + s2, ay + s2 * 0.5); x.closePath(); x.fill(); x.stroke(); x.globalAlpha = 0.5; for (let t = 0; t < 4; t++) { x.beginPath(); x.moveTo(ax - s2 * 0.2 + t * 2, ay - s2 * 0.6 + t * 3); x.lineTo(ax - s2 * 0.5 + t * 3, ay + s2 * 0.4); x.stroke(); } x.globalAlpha = 1; } }
    // the castle, from its own plan; the pitch, the village, the hut, as little drawings
    { const P0 = HL.plan(0), o = wpx(HL.PL.X0, HL.PL.Z0), k2 = N * SC / M.W; x.fillStyle = 'rgba(236,220,178,0.9)'; for (let j = 0; j < P0.NZ; j++) for (let i = 0; i < P0.NX; i++) if (P0.rf(i, j) || P0.at(i, j) === 'P') x.fillRect(o[0] + i * k2, o[1] + j * k2, k2 + 0.6, k2 + 0.6); x.fillStyle = INK; for (let j = 0; j < P0.NZ; j++) for (let i = 0; i < P0.NX; i++) if (P0.isW(i, j)) x.fillRect(o[0] + i * k2, o[1] + j * k2, k2 + 0.3, k2 + 0.3); }
    const house = (wx, wz, s2) => { const p = wpx(wx, wz); x.fillStyle = 'rgba(236,220,178,0.95)'; x.strokeStyle = INK; x.lineWidth = 1.4; x.beginPath(); x.rect(p[0] - 6 * s2, p[1] - 4 * s2, 12 * s2, 9 * s2); x.fill(); x.stroke(); x.fillStyle = 'rgba(120,70,40,0.75)'; x.beginPath(); x.moveTo(p[0] - 8 * s2, p[1] - 4 * s2); x.lineTo(p[0], p[1] - 12 * s2); x.lineTo(p[0] + 8 * s2, p[1] - 4 * s2); x.closePath(); x.fill(); x.stroke(); };
    if (HL.VIL) for (let q2 = 0; q2 < 11; q2++) house(HL.VIL.x - 52 + q2 * 10.5, HL.VIL.z + (q2 % 2 ? 8 : -8) + (q2 % 3) * 3, 0.9 + (q2 % 3) * 0.15); if (HL.HUT) house(HL.HUT.x, HL.HUT.z, 1.1); if (HL.BOAT) house(HL.BOAT[0], HL.BOAT[1], 1.0);
    if (HL.PITCH) { const p = wpx(HL.PITCH.x, HL.PITCH.z), k2 = N * SC / M.W; x.strokeStyle = INK; x.lineWidth = 2; x.fillStyle = 'rgba(96,120,50,0.35)'; x.beginPath(); x.ellipse(p[0], p[1], 38 * k2, 82 * k2, 0, 0, TAU); x.fill(); x.stroke(); for (const sd of [-1, 1]) for (const dx of [-9, 0, 9]) { x.beginPath(); x.moveTo(p[0] + dx * k2, p[1] + sd * 66 * k2); x.lineTo(p[0] + dx * k2, p[1] + sd * 66 * k2 - 12); x.stroke(); x.beginPath(); x.arc(p[0] + dx * k2, p[1] + sd * 66 * k2 - 16, 4, 0, TAU); x.stroke(); } }
    if (HL.OWLERY) { const p = wpx(HL.OWLERY[0], HL.OWLERY[2]); x.fillStyle = 'rgba(236,220,178,0.95)'; x.strokeStyle = INK; x.lineWidth = 1.4; x.beginPath(); x.rect(p[0] - 5, p[1] - 14, 10, 20); x.fill(); x.stroke(); x.beginPath(); x.moveTo(p[0] - 7, p[1] - 14); x.lineTo(p[0], p[1] - 26); x.lineTo(p[0] + 7, p[1] - 14); x.closePath(); x.fillStyle = 'rgba(70,80,100,0.7)'; x.fill(); x.stroke(); }
    squid(x, wpx(300, -260)[0], wpx(300, -260)[1], 2.2, rs);
    for (const p of M.PLACES()) { const o = wpx(p[1], p[2]); label(x, p[0], o[0], o[1] + (p[3] ? 0 : 6), p[3] ? 560 : 300, p[3] ? 64 : 34, { fam: p[3] ? SCRIPT : HAND, min: p[3] ? 40 : 24, max: p[3] ? 58 : 30, it: !p[3] }); }
    frame(x, W, H, rs); ribbon(x, W, 62, 'Hogwarts', 'the castle, its grounds, the loch & the village of Hogsmeade', rs); compass(x, W - PAD - 120, H - 150 - 140, 60, rs);
    x.fillStyle = INK; x.textAlign = 'center'; x.font = `italic 30px ${HAND}`; x.globalAlpha = 0.85; x.fillText('Draco dormiens nunquam titillandus', W / 2, H - 84); x.globalAlpha = 1;
    return (M.sheets.g = { url: c.toDataURL('image/jpeg', 0.88), W, H, pc: (wx, wz) => { const u = M.uv(wx, wz); return [(PAD + u[0] * N * SC) / W * 100, (TOP + u[1] * N * SC) / H * 100]; } }); };
  /* ---------------------------------------------------------------- the open map */
  M.css3 = `.hlMap.mm { background: radial-gradient(ellipse at 50% 40%, rgba(40,26,10,0.9), rgba(4,3,6,0.96)); gap: 0; overflow: hidden; perspective: 1600px; }
.hlMap.mm .view { position: relative; height: 94vh; aspect-ratio: var(--ar); max-width: 76vw; overflow: hidden; border-radius: 4px; box-shadow: 0 30px 90px #000, 0 0 0 1px #1c1206, 0 0 60px rgba(255,200,120,0.08); cursor: grab; animation: hlUnfold 0.55s cubic-bezier(.2,.8,.2,1) both; transform-origin: 50% 0%; }
.hlMap.mm .view.drag { cursor: grabbing; } .hlMap.mm .sheet3 { position: absolute; inset: 0; background-size: 100% 100%; transform-origin: 0 0; will-change: transform; }
@keyframes hlUnfold { from { transform: rotateX(-78deg) scale(0.86); opacity: 0; filter: brightness(0.4); } to { transform: none; opacity: 1; filter: none; } }
.hlMap.mm .fp { position: absolute; width: 0; height: 0; pointer-events: none; } .hlMap.mm .fp b { position: absolute; width: var(--fs, 5px); height: calc(var(--fs, 5px) * 2.1); background: var(--fc, #3a2412); border-radius: 50% 50% 46% 46% / 62% 62% 38% 38%; opacity: 0.9; } .hlMap.mm .fp b::after { content: ''; position: absolute; left: 12%; right: 12%; bottom: -34%; height: 30%; background: inherit; border-radius: 40%; }
.hlMap.mm .fp b:nth-child(1) { left: calc(var(--fs, 5px) * -1.25); top: calc(var(--fs, 5px) * -1.6); animation: hlStep 1.1s steps(1) infinite; } .hlMap.mm .fp b:nth-child(2) { left: calc(var(--fs, 5px) * 0.25); top: calc(var(--fs, 5px) * -0.2); animation: hlStep 1.1s steps(1) infinite 0.55s; }
@keyframes hlStep { 0% { opacity: 0.95; } 50% { opacity: 0.28; } 100% { opacity: 0.95; } }
.hlMap.mm .nm { position: absolute; transform: translate(-50%, 0); white-space: nowrap; font: italic 13px ${HAND}; color: #2c1a0a; padding: 0 7px 1px; border: 1px solid rgba(58,36,18,0.75); border-radius: 2px 9px 2px 9px; background: rgba(240,226,188,0.88); pointer-events: none; }
.hlMap.mm .sheet3.far .nm:not(.you) { display: none; } .hlMap.mm .sheet3.far .fp:not(.me) { --fs: 3.2px; }
.hlMap.mm .me { --fs: 8px; --fc: #8a1810; z-index: 5; } .hlMap.mm .me i { display: none; } .hlMap.mm .nm.you { font-size: 16px; color: #7a120c; border-color: #7a120c; z-index: 5; }
.hlMap.mm .qm { z-index: 4; width: calc(20px * var(--inv, 1)); height: calc(20px * var(--inv, 1)); margin: calc(-10px * var(--inv, 1)); border: 2px solid #7a4c00; background: radial-gradient(#fff6b0, #f0b020); box-shadow: 0 0 14px #ffd040, 0 0 30px rgba(255,200,60,0.6); }
.hlMap.mm .fl { width: calc(18px * var(--inv, 1)); height: calc(24px * var(--inv, 1)); margin: calc(-16px * var(--inv, 1)) calc(-9px * var(--inv, 1)); border: 0; border-radius: 50% 50% 46% 46% / 66% 66% 34% 34%; background: radial-gradient(ellipse at 50% 72%, #f4ffe0 0%, #7df08a 34%, #17964a 68%, rgba(10,80,40,0) 72%); box-shadow: 0 0 12px #3cff86; animation: hlFlick 0.7s ease-in-out infinite alternate; z-index: 3; } @keyframes hlFlick { from { transform: scale(1, 1) rotate(-3deg); } to { transform: scale(0.9, 1.14) rotate(3deg); } } .hlMap.mm .fl:hover { filter: brightness(1.4); }
.hlMap.mm .cs { width: calc(12px * var(--inv, 1)); height: calc(9px * var(--inv, 1)); margin: calc(-5px * var(--inv, 1)) calc(-6px * var(--inv, 1)); background: #7a4a16; border: 1px solid #2c1a0a; border-radius: 3px 3px 1px 1px; box-shadow: inset 0 3px 0 #b88a3a; } .hlMap.mm .pg { width: 9px; height: 11px; margin: -6px -5px; background: #f4ecd0; border: 1px solid #3a2412; transform: rotate(-12deg); opacity: 1; }
.hlMap.mm .tabs3 { display: flex; flex-direction: column; gap: 9px; margin-right: 22px; align-self: center; } .hlMap.mm .tab3 { font: 19px ${HAND}; color: #2c1a0a; padding: 7px 26px 7px 16px; background: linear-gradient(90deg, #cdb276, #e6d29c); clip-path: polygon(0 0, 100% 0, calc(100% - 14px) 50%, 100% 100%, 0 100%); cursor: pointer; pointer-events: auto; opacity: 0.62; transition: transform .15s, opacity .15s; text-align: left; min-width: 150px; } .hlMap.mm .tab3:hover { opacity: 0.95; transform: translateX(5px); } .hlMap.mm .tab3.on { opacity: 1; transform: translateX(12px); background: linear-gradient(90deg, #e2c07a, #f6e6b4); box-shadow: 0 0 18px rgba(255,210,120,0.4); } .hlMap.mm .tab3 small { font: italic 13px ${HAND}; opacity: 0.7; margin-left: 8px; }
.hlMap.mm .card { width: 270px; margin-left: 26px; align-self: center; padding: 22px 22px 18px; color: #2c1a0a; background: linear-gradient(160deg, #ecdcb2, #d2b97e); box-shadow: 0 16px 50px #000, inset 0 0 40px rgba(120,80,30,0.35); border-radius: 3px; font: 17px/1.35 ${HAND}; transform: rotate(1.2deg); } .hlMap.mm .card h3 { font: 34px ${SCRIPT}; margin: 0 0 4px; color: #2c1a0a; letter-spacing: 0; } .hlMap.mm .card b { display: block; font: italic 14px ${HAND}; letter-spacing: 0.04em; color: #6a4418; margin-top: 12px; border-bottom: 1px solid rgba(58,36,18,0.35); } .hlMap.mm .card p { margin: 4px 0 0; font-size: 16px; } .hlMap.mm .card .lg { font-size: 15px; margin: 5px 0; display: flex; align-items: center; gap: 10px; } .hlMap.mm .card .lg span { position: relative; width: 24px; height: 22px; display: inline-block; } .hlMap.mm .card .lg span > * { position: absolute !important; left: 12px !important; top: 12px !important; animation: none !important; } .hlMap.mm .card kbd { background: rgba(58,36,18,0.14); border: 1px solid rgba(58,36,18,0.5); color: #2c1a0a; }`;
  const kOfY = (y) => y < HL.Y0 - 3 ? -1 : HL.kAt(y);
  M.show = function (mode) { const U = HL.ui, a = PLAYER.a; if (!M._c3) { M._c3 = 1; for (const cs of [M.css, M.css3]) { const st = document.createElement('style'); st.textContent = cs; document.head.appendChild(st); } }
    const inC = HL.inFoot(a.x, a.z, 6) && a.z > -62 && a.y < HL.Y0 + 40, f = kOfY(a.y); if (mode === undefined) mode = inC && PLAYER.state !== 'fly' && !HL.Q.on ? f : 'g';
    const sh = mode === 'g' ? M.groundSheet() : M.castleSheet(mode), isG = mode === 'g', q = HL.quest.way && !HL.Q.on ? HL.quest.way() : null, Qc = HL.quest.cur(), onK = (y) => isG || kOfY(y) === mode, inS = (x, z) => isG ? !HL.inFoot(x, z, 0) || true : HL.inFoot(x, z, 12), pos = (x, z) => { const p = sh.pc(x, z); return `left:${p[0].toFixed(2)}%;top:${p[1].toFixed(2)}%`; };
    MG.state = 'map'; if (document.exitPointerLock) document.exitPointerLock();
    let h = ''; for (const c of HL.LOOT.chests) if (c.open && onK(c.y) && (isG || HL.inFoot(c.x, c.z, 0))) h += `<div class="cs" style="${pos(c.x, c.z)}"></div>`; for (const s of HL.SECRETS) if (s.got && onK(s.p.y - 1.5) && (isG || HL.inFoot(s.p.x, s.p.z, 0))) h += `<div class="pg" style="${pos(s.p.x, s.p.z)}"></div>`;
    HL.FLOO.forEach((fl, i) => { const inF = HL.inFoot(fl.p[0], fl.p[2], 0) && fl.p[1] < HL.Y0 + 40; if (isG ? !inF : inF && kOfY(fl.p[1]) === mode) h += `<div class="fl" data-f="${i}" title="${fl.name}" style="${pos(fl.p[0], fl.p[2])}"></div>`; });
    if (q && (isG || (HL.inFoot(q[0], q[2], 2) && kOfY(q[1] - 1.5) === mode))) h += `<div class="qm" style="${pos(q[0], q[2])}"></div>`;
    const names = { '-1': ['The Dungeons', '0'], 0: ['The Ground Floor', '1'], 1: ['The First Floor', '2'], 2: ['The Second Floor', '3'], 3: ['The Third Floor', '4'], 4: ['The Fourth Floor', '5'], g: ['The Grounds', 'G'] }, order = [4, 3, 2, 1, 0, -1, 'g'];
    const qk = q && HL.inFoot(q[0], q[2], 2) ? kOfY(q[1] - 1.5) : 'g';
    const S3 = U.screen(`<div class="hlMap mm"><div class="tabs3">${order.map((o) => `<div class="tab3 ${String(o) === String(mode) ? 'on' : ''}" data-k="${o}">${names[o][0]}<small>${[TOUCH.on ? '' : names[o][1], inC && o === f ? 'you' : '', String(o) === String(qk) ? 'errand' : ''].filter(Boolean).join(' · ')}</small></div>`).join('')}</div>
      <div class="view" style="--ar:${(sh.W / sh.H).toFixed(4)}"><div class="sheet3" style="background-image:url(${sh.url})">${h}<div class="lay"></div></div></div>
      <div class="card"><h3>${names[mode][0]}</h3><b>your errand</b><p>${Qc.t.charAt(0) + Qc.t.slice(1).toLowerCase()}: ${Qc.n}</p><b>found</b><p>Field Guide pages ${HL.SECRETS.filter((s) => s.got).length} of ${HL.SECRETS.length}<br>Chests opened ${HL.LOOT.chests.filter((c) => c.open).length} of ${HL.LOOT.chests.length}</p>
      <b>the signs</b><div class="lg"><span><div class="fp me"><b></b><b></b></div></span>you</div><div class="lg"><span><div class="fp"><b></b><b></b></div></span>others, by their footprints</div><div class="lg"><span><div class="qm"></div></span>your errand</div><div class="lg"><span><div class="fl"></div></span>a Floo flame: click to travel</div><div class="lg"><span><div class="cs"></div></span>a chest you have opened</div>
      <b>the map</b><p style="font-size:15px">${TOUCH.on ? 'pinch to look closer, drag to move · tap a storey · ✕ folds it away' : 'wheel to look closer, drag to move · <kbd>0</kbd>–<kbd>5</kbd> storeys · <kbd>G</kbd> the grounds · <kbd>M</kbd> or <kbd>Esc</kbd> to fold it away'}</p></div></div>`);
    const view = S3.querySelector('.view'), sheet = S3.querySelector('.sheet3'), lay = S3.querySelector('.lay'); let sc = 1, tx = 0, ty = 0, drag = null, timer = 0;
    const apply = () => { const vw = view.clientWidth, vh = view.clientHeight; tx = clamp(tx, vw - vw * sc, 0); ty = clamp(ty, vh - vh * sc, 0); sheet.style.transform = `translate(${tx.toFixed(1)}px,${ty.toFixed(1)}px) scale(${sc.toFixed(3)})`; sheet.style.setProperty('--inv', (1 / sc).toFixed(3)); sheet.classList.toggle('far', sc < 1.3); };
    const zoomAt = (mx, my, k2) => { const s1 = clamp(sc * k2, 1, 5); tx = mx - (mx - tx) * s1 / sc; ty = my - (my - ty) * s1 / sc; sc = s1; apply(); };
    view.addEventListener('wheel', (e) => { e.preventDefault(); const r = view.getBoundingClientRect(); zoomAt(e.clientX - r.left, e.clientY - r.top, e.deltaY < 0 ? 1.18 : 1 / 1.18); }, { passive: false });
    view.addEventListener('mousedown', (e) => { if (e.target.classList.contains('fl')) return; drag = [e.clientX - tx, e.clientY - ty]; view.classList.add('drag'); }); const mv = (e) => { if (drag) { tx = e.clientX - drag[0]; ty = e.clientY - drag[1]; apply(); } }, up = () => { drag = null; view.classList.remove('drag'); }; window.addEventListener('mousemove', mv); window.addEventListener('mouseup', up); view.addEventListener('dblclick', () => { sc = 1; tx = ty = 0; apply(); });
    // open looking at where you stand
    { const showMe = isG || (inC && f === mode); if (showMe && !isG) { const p = sh.pc(a.x, a.z), vw = view.clientWidth || 600, vh = view.clientHeight || 700; sc = 1.7; tx = vw / 2 - p[0] / 100 * vw * sc; ty = vh / 2 - p[1] / 100 * vh * sc; } apply(); }
    // the footprints: you, and everyone else who is on this sheet
    const prevP = new Map(), steps = () => { let o = ''; const me = isG || (inC && f === mode); if (me) { const p = sh.pc(a.x, a.z); o += `<div class="fp me" style="left:${p[0].toFixed(2)}%;top:${p[1].toFixed(2)}%;transform:rotate(${(-CAM.yaw + PI).toFixed(2)}rad) scale(var(--inv,1))"><b></b><b></b></div><div class="nm you" style="left:${p[0].toFixed(2)}%;top:calc(${p[1].toFixed(2)}% + 12px);transform:translate(-50%,0) scale(var(--inv,1));transform-origin:50% 0">You</div>`; }
      let n = 0; for (const b of HL.npcs) { if (n > 110) break; const inF = HL.inFoot(b.x, b.z, 2); if (isG ? inF : !(inF && kOfY(b.y) === mode)) continue; const p = sh.pc(b.x, b.z), pr = prevP.get(b), yaw = pr && Math.hypot(b.x - pr[0], b.z - pr[1]) > 0.05 ? Math.atan2(b.x - pr[0], b.z - pr[1]) : b.yaw; prevP.set(b, [b.x, b.z]); n++;
        o += `<div class="fp" style="left:${p[0].toFixed(2)}%;top:${p[1].toFixed(2)}%;transform:rotate(${(-yaw + PI).toFixed(2)}rad) scale(var(--inv,1));${b.sitY !== undefined && !(HL.ghosts || []).some((g) => g.a === b) ? 'opacity:.55' : ''}"><b></b><b></b></div>`; if (b.label) o += `<div class="nm" style="left:${p[0].toFixed(2)}%;top:calc(${p[1].toFixed(2)}% + 9px);transform:translate(-50%,0) scale(var(--inv,1));transform-origin:50% 0">${b.label}</div>`; }
      lay.innerHTML = o; }; steps(); timer = setInterval(steps, 400);
    const close = () => { clearInterval(timer); window.removeEventListener('mousemove', mv); window.removeEventListener('mouseup', up); U.screen(''); MG.state = 'play'; MG.onKey = null; IN.buf = {}; HL.noPauseT = MG.rt + 0.25; }, go = (v) => { close(); M.show(v === 'g' ? 'g' : +v); };
    S3.querySelectorAll('.tab3').forEach((e) => e.onclick = () => go(e.dataset.k));
    S3.querySelectorAll('.fl[data-f]').forEach((e) => e.onclick = () => { if (HL.Q.on || PLAYER.state === 'fly') { HL.ui.toast('', 'Land first — Floo powder needs your feet on the ground.'); return; } const fl = HL.FLOO[+e.dataset.f]; U.fade(1); close(); setTimeout(() => { const p = PLAYER.a; p.x = fl.p[0]; p.y = fl.p[1] + 0.1; p.z = fl.p[2]; p.vx = p.vy = p.vz = 0; p.yaw = fl.p[3]; CAM.yaw = fl.p[3]; CAM.snap = true; if (p.inst.cloth && p.inst.cloth.reset) p.inst.cloth.reset(); U.fade(0); U.spellName(fl.name); }, 500); });
    MG.onKey = (c) => { if (c === 'Escape' || c === 'KeyM') close(); else if (c === 'KeyG') go('g'); else { const m = /^Digit([0-5])$/.exec(c); if (m) go(+m[1] - 1); } }; };
  M.open = function () { if (MG.state !== 'play' || !PLAYER.a) return; M.show(); }; M.openPlan = function (k) { M.show(k); };
})();
