/* ==== p85_tests.js ==== */
/* TESTS — ?test: boot through the Sorting, real DOM input, survival at spawn and beside the poachers, every spell,
   Protego, a duel to the end, the broom (flight, collision, landing), the interiors, a Quidditch match with a goal
   and the Snitch, a Field Guide page. */
const TEST = { results: [], n: 0, pass: 0 };
TEST.ok = function (name, cond, info) { TEST.n++; if (cond) TEST.pass++; const s = (cond ? 'PASS ' : 'FAIL ') + name + (info !== undefined ? '  ' + info : ''); TEST.results.push(s); console.log(s); document.title = `${TEST.pass}/${TEST.n} · HOGWARTS tests`; };
TEST.steps = function (n, dt) { for (let i = 0; i < n; i++) MG.tick(dt || 1 / 60); };
TEST.wait = async function (fn, max) { for (let i = 0; i < (max || 600) && !fn(); i++) await new Promise((r) => setTimeout(r, 25)); return fn(); };
TEST.place = function (x, y, z, yaw) { IN.buf = {}; IN.keys = {}; const P = PLAYER.a; if (HL.fly.on) HL.fly.dismount(true); PLAYER.state = 'move'; P.stop(0.01); P.x = x; P.y = y; P.z = z; P.vx = P.vy = P.vz = 0; P.yaw = yaw || 0; CAM.yaw = yaw || 0; CAM.pitch = -0.05; CAM.snap = true; TEST.steps(20); };
TEST.key = (c, d) => IN.fireKey(c, d); TEST.tap = (c) => { IN.fireKey(c, true); TEST.steps(2); IN.fireKey(c, false); };
TEST.run = async function () {
  try {
    await TEST.wait(() => MG.state === 'title', 400); TEST.ok('boots to the title', MG.state === 'title' && !MG.errors.length, MG.errors[0]);
    HL.ui.sorting(); TEST.ok('the Sorting opens', MG.state === 'house' && document.querySelectorAll('.hlH').length === 4);
    HL.begin('ravenclaw', true); await TEST.wait(() => MG.state === 'play', 400); MG.manual = true;
    const P = () => PLAYER.a, Y = HL.Y0;
    TEST.ok('sorted and spawned on the viaduct', MG.state === 'play' && HL.house === 'ravenclaw' && Math.abs(P().y - Y) < 0.6 && P().grounded, 'y=' + P().y.toFixed(2));
    TEST.steps(1800); TEST.ok('thirty idle seconds at the spawn: alive, unhurt', P().alive && P().hp >= P().hpMax);
    { const z0 = P().z; TEST.key('KeyW', true); TEST.steps(120); TEST.key('KeyW', false); TEST.ok('W walks (real key events)', P().z - z0 > 5, (P().z - z0).toFixed(1) + ' m'); }
    { const z0 = P().z; TEST.key('KeyW', true); TEST.key('ShiftLeft', true); TEST.steps(120); TEST.key('KeyW', false); TEST.key('ShiftLeft', false); TEST.ok('Shift sprints', P().z - z0 > 11, (P().z - z0).toFixed(1) + ' m'); }
    { TEST.steps(20); TEST.key('ShiftLeft', true); TEST.steps(4); TEST.key('ShiftLeft', false); TEST.steps(6); TEST.ok('a tap of Shift rolls', PLAYER.state === 'dodge' || P().act === 'dodge', PLAYER.state); TEST.steps(60); }
    { TEST.tap('Space'); TEST.steps(10); TEST.ok('Space jumps', !P().grounded || P().y > Y + 0.2); TEST.steps(80); }
    // ---- wand work at the dummies
    const D = HL.dummies[1]; TEST.place(D.x - 6.5, Y + 0.06, D.z, HALF); const aimAt = (t) => { const a = P(); CAM.yaw = Math.atan2(t.x - a.x, t.z - a.z); CAM.pitch = -0.02; };
    { aimAt(D); TEST.steps(10); const h0 = D.hits; IN.fireMouse(0, true); IN.fireMouse(0, false); TEST.steps(60); TEST.ok('LMB casts and strikes the dummy', D.hits > h0, 'hits ' + (D.hits - h0)); }
    { let ok = 0; const bad = []; for (let i = 0; i < 8; i++) { TEST.steps(60); TEST.place(D.x - 6.5, Y + 0.06, D.z, HALF); aimAt(D); TEST.steps(8); for (let q = 0; q < 3; q++) { const c = R.camera.position; CAM.yaw = Math.atan2(D.x - c.x, D.z - c.z); TEST.steps(4); } const h0 = D.hits; TEST.tap('Digit' + (i + 1)); TEST.steps(100); if (D.hits > h0 && HL.P.cd[HL.BAR[i]] > 0) ok++; else bad.push(HL.BAR[i] + (D.hits > h0 ? ':cd' : ':miss') + '@' + P().x.toFixed(1) + ',' + P().z.toFixed(1) + ' d' + D.x.toFixed(1)); } TEST.ok('all eight spells cast, land and go on cooldown', ok === 8, ok + '/8 ' + bad.join(' ')); }
    { MG.god = false; const a = P(); a.hp = a.hpMax; TEST.key('KeyQ', true); TEST.steps(30); const src = { x: a.x + 6, y: a.y, z: a.z, team: 'foe', alive: true, chest: (o) => (o || new THREE.Vector3()).set(a.x + 6, a.y + 1.2, a.z) };
      HL.shoot(src, V3(a.x + 6, a.y + 1.2, a.z), V3(-1, 0, 0), 'foe', { target: a }); TEST.steps(40); TEST.key('KeyQ', false); TEST.ok('Protego stops a curse', a.hp >= a.hpMax, 'hp ' + a.hp); TEST.steps(20);
      HL.shoot(src, V3(a.x + 6, a.y + 1.2, a.z), V3(-1, 0, 0), 'foe', { target: a }); TEST.steps(40); TEST.ok('an unshielded curse hurts', a.hp < a.hpMax, 'hp ' + a.hp.toFixed(0)); }
    // ---- the poachers' camp: stand still 20 s (you must live), then win the duel
    { const cp = HL.CAMP, gy = HL.gy(cp.x - 12, cp.z); TEST.place(cp.x - 12, gy + 0.1, cp.z, HALF); P().hp = P().hpMax; TEST.steps(1200); TEST.ok('twenty seconds motionless beside four poachers: still alive', P().alive && Math.hypot(P().x - cp.x, P().z - cp.z) < 40 && HL.foes.some((f) => f.ai === 'fight'), 'hp ' + P().hp.toFixed(0) + ' foes ' + HL.foes.length + ' ' + HL.foes.slice(0, 4).map((f) => f.ai + ':' + f.dist(P()).toFixed(0)).join(' '));
      const foes = HL.foes.filter((f) => f.alive && Math.hypot(f.home[0] - cp.x, f.home[1] - cp.z) < 12); MG.god = true; let n = 0;
      for (let k = 0; k < 9000 && foes.some((f) => f.alive); k++) { const t = foes.filter((f) => f.alive).sort((p, q) => p.dist(P()) - q.dist(P()))[0]; aimAt(t); CAM.pitch = Math.atan2(t.y + 1.2 - P().y - 1.5, Math.max(1, t.dist(P()))); if (k % 16 === 0) { IN.fireMouse(0, true); IN.fireMouse(0, false); } if (k % 90 === 0) TEST.tap('Digit' + (1 + (n++ % 8))); MG.tick(1 / 60); }
      TEST.ok('the camp is cleared with spells', foes.every((f) => !f.alive), foes.filter((f) => f.alive).length + ' left ' + foes.map((f) => f.ai + ':' + f.hp.toFixed(0) + ':' + f.dist(P()).toFixed(0) + ':' + (f.hidden ? 'H' : '') + (f.ward || '')).join(' ') + ' st=' + PLAYER.state + ' act=' + P().act + ' tgt=' + (HL.P.target && HL.P.target.label) + ' p=' + [P().x, P().y, P().z].map((v) => v.toFixed(0))); MG.god = false; }
    // ---- the broom
    { TEST.place(0, Y + 0.06, -150, 0); TEST.tap('KeyB'); TEST.steps(20); TEST.ok('B mounts the broom', PLAYER.state === 'fly'); const z0 = P().z; CAM.pitch = 0.3; TEST.key('KeyW', true); TEST.steps(180); TEST.ok('W flies forward and climbs', P().z - z0 > 25 && P().y > Y + 6 && HL.fly.speed > 15, `dz ${(P().z - z0).toFixed(0)} y ${P().y.toFixed(0)} v ${HL.fly.speed.toFixed(0)}`);
      { const r0 = R.camera.matrixWorld.elements[1]; CAM.yaw -= 1.2; TEST.steps(12); TEST.ok('a right turn banks the camera right (right side dips)', R.camera.matrixWorld.elements[1] < r0 - 0.01, R.camera.matrixWorld.elements[1].toFixed(3)); }
      P().y = Y + 200; TEST.key('ShiftLeft', true); TEST.steps(120); TEST.ok('Shift boosts', HL.fly.speed > 32, HL.fly.speed.toFixed(0)); TEST.key('ShiftLeft', false);
      // into the Great Hall's wall: the castle is solid
      const a = P(); a.x = (HL.GHR.x0 + HL.GHR.x1) / 2 + 4; a.y = Y + 9; a.z = HL.GHR.z0 - 26; CAM.yaw = 0; CAM.pitch = 0; HL.fly.R.yaw = 0; HL.fly.speed = 30; HL.fly.vel.set(0, 0, 30); TEST.steps(120); TEST.ok('the broom cannot pass through a wall', a.z < HL.GHR.z0 + 0.5, 'z ' + a.z.toFixed(1));
      TEST.key('KeyW', false); a.x = -2; a.z = -32; a.y = Y + 3; HL.fly.vel.set(0, 0, 0); HL.fly.speed = 0; TEST.key('KeyC', true); TEST.steps(120); TEST.key('KeyC', false); TEST.steps(40); TEST.ok('sinking onto the quad dismounts', PLAYER.state !== 'fly' && Math.abs(a.y - Y) < 0.6, PLAYER.state + ' y ' + a.y.toFixed(2)); }
    // ---- indoors
    { const G = HL.GHR, E = HL.EHR, gx = (G.x0 + G.x1) / 2, gz = (G.z0 + G.z1) / 2, Z = HL.zoneAt(gx, Y + 1, gz), g = PHY.ground(gx + 2, gz, 0.2, Y + 1, Y - 2); TEST.ok('the Great Hall has a floor and a name', Z && /GREAT HALL/.test(Z.name) && Math.abs(g - Y) < 0.1, Z && Z.name); { const yd = Y - HL.DUN.d, gm = PHY.ground(-88, 84.5, 0.2, Y + 1, Y - 9), gb = PHY.ground(-90, 88.5, 0.2, yd + 2, Y - 12), gk = PHY.ground(-79.5, 27.4, 0.2, yd + 2, Y - 12), Zk = HL.zoneAt(-79.5, yd + 1, 30), Zs = HL.zoneAt(HL.DUN.sly.cx, yd + 1, HL.DUN.sly.cz), gs2 = PHY.ground(-6.5, 107.5, 0.2, Y + 1, Y - 9), gs3 = PHY.ground(HL.DUN.sly.cx - 2.6, HL.DUN.sly.cz - 5.5, 0.2, yd + 2, Y - 12); TEST.ok('stairs go down to the dungeons: from the Reception Hall to the kitchens and Hufflepuff, from the Slytherin entrance to its common room under the lake', Math.abs(gm - (Y - 3.5)) < 0.6 && Math.abs(gb - yd) < 0.1 && Math.abs(gk - yd) < 0.1 && Zk && /KITCHENS/.test(Zk.name) && Zs && /SLYTHERIN/.test(Zs.name) && HL.DUN.rooms.length === 8 && Math.abs(gs2 - (Y - 3.5)) < 0.7 && Math.abs(gs3 - yd) < 0.1, 'stair ' + (gm - Y).toFixed(1) + ' floor ' + (gb - Y).toFixed(1) + ' ' + (Zk && Zk.name)); }
      const PL = HL.plan(0), rooms = PL.comps.filter((c) => c.kind === 'room').length, names = PL.comps.filter((c) => c.name).map((c) => c.name).join('|'); { const want = ['THE GREAT HALL', 'THE ENTRANCE HALL', 'THE RECEPTION HALL', 'THE GRAND STAIRCASE', 'THE LIBRARY', 'THE CENTRAL HALL', 'THE CLOCK TOWER', 'THE SOUTH HALL', 'THE POTIONS CLASSROOM', 'THE TRANSFIGURATION CLASSROOM', 'THE CHARMS CLASSROOM', 'DEFENCE AGAINST THE DARK ARTS', 'THE ASTRONOMY TOWER', 'THE GRYFFINDOR TOWER', 'THE RAVENCLAW TOWER', 'THE FACULTY TOWER', 'THE LONG GALLERY', 'THE DIVINATION CLASSROOM', 'THE ARITHMANCY CLASSROOM', 'THE VIADUCT ENTRANCE'], miss = want.filter((n) => !PL.comps.some((c) => c.name === n));
        TEST.ok('the castle is raised from the Hogwarts Legacy map: rooms, doorways, the named places', rooms >= 28 && PL.doors.length >= 60 && PL.NX === 276 && !miss.length && HL.GREEN.length === 3 && HL.GREEN[0].xc < HL.LIBRARY[0], rooms + ' rooms, ' + PL.doors.length + ' doorways' + (miss.length ? ' missing ' + miss.join(', ') : '')); }
      { const C = HL.CLOCK, g = PHY.ground(-0.5, -6, 0.3, Y + 4, Y - 1), ax = Math.abs(C.xc - (-0.5)); let clear = true; for (let z = -44; z <= C.z1 + 3; z += 0.5) { if (z > -24.5 && z < -12.5) continue; /* the fountain in the middle of the court: you walk round it */ const gg = PHY.ground(-0.5, z, 0.3, Y + 4.4, Y + 0.45); if (gg !== null) clear = false; } for (let z = -24; z <= -13; z += 0.5) if (PHY.ground(-6.5, z, 0.3, Y + 4.4, Y + 0.45) !== null) clear = false;
        TEST.ok('the bridge leads straight to the Clock Tower\u2019s great doors: a clear walk from the court through the tower into the South Wing', ax < 1.2 && clear && C.z0 > -2 && C.z0 < 8, 'tower axis off the bridge by ' + ax.toFixed(1) + ' m, clear ' + clear); }
      { const P0 = HL.plan(0), NX = P0.NX, NZ = P0.NZ, C = P0.comps.find((c) => c.name === 'THE CLOCK TOWER'), Gh = P0.comps.find((c) => c.name === 'THE GREAT HALL'), D = new Int32Array(NX * NZ).fill(-1), s0 = ((C.R.j0 + C.R.j1) >> 1) * NX + ((C.R.i0 + C.R.i1) >> 1), qu = [s0]; D[s0] = 0; let far = -1;
        for (let h = 0; h < qu.length; h++) { const s = qu[h], i = s % NX, j = (s / NX) | 0; if (P0.comp[s] === Gh.id) { far = D[s]; break; } for (const [di, dj] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) { const ni = i + di, nj = j + dj, t = nj * NX + ni; if (ni < 0 || nj < 0 || ni >= NX || nj >= NZ || D[t] >= 0 || P0.isW(ni, nj) || !P0.ind(ni, nj)) continue; D[t] = D[s] + 1; qu.push(t); } }
        TEST.ok('indoors all the way from the Clock Tower doors to the Great Hall: South Wing, Long Gallery, Reception Hall', far > 0 && far < 190, far + ' m on foot, under a roof'); }
      { const st = HL.auditStray(), G2 = HL.GHR, v = new THREE.Vector3(); TEST.ok('nothing built for the inside of the castle hangs outside it (no roof timbers in the sky, no sun patches over the courts)', st.bad.length === 0 && st.n > 100000, st.n + ' points checked' + (st.bad.length ? ': ' + st.bad.slice(0, 4).join('; ') : '')); }
      { const P0 = HL.plan(0), sh = P0.comps.find((c) => c.name === 'THE SOUTH HALL'), ct = P0.comps.find((c) => c.name === 'THE CLOCK TOWER'), beds = []; for (const k of HL.ALLK) for (const c of HL.plan(k).comps) if (c.type === 'hospital' || c.type === 'dorm') beds.push(k + ':' + c.name); const lowBeds = beds.filter((b) => b[0] === '0' || b[0] === '1');
        TEST.ok('the way in makes sense: Clock Tower, then a great South Hall (no ward, no dormitory on the ground or first floor), the Hospital Wing upstairs', !!sh && sh.type === 'lobby' && sh.tallH > 12 && !lowBeds.length && beds.some((b) => /HOSPITAL WING/.test(b)), 'South Hall ' + (sh && sh.tallH) + ' m high; beds only at ' + beds.join(', ')); }
      { const legs = [['from the Clock Tower doors to the Great Hall', 0, [-0.5, 6], [HL.GHR.x0 + 16.5, HL.GHR.z0 + 30]], ['from the Great Hall to the Library', 0, [HL.GHR.x0 + 16.5, HL.GHR.z1 - 6], [HL.LIBRARY[0], HL.LIBRARY[2]]], ['out by the great doors: from the Entrance Hall to the Viaduct Courtyard fountain', 0, [-79.5, 112], [-79.5, 147]], ['over the suspension bridge: from the South Wing passage to the Defence classroom', 0, [29, 70], [56, 86]], ['from the Grand Staircase to the Gryffindor common room (fourth floor)', 4, null, /GRYFFINDOR COMMON/], ['from the Grand Staircase to the Headmaster\u2019s Office (fourth floor)', 4, null, /HEADMASTER/], ['from the Grand Staircase to the Hospital Wing (second floor)', 2, null, /HOSPITAL WING/], ['from the Central Hall stair to the Library Reading Room (second floor)', 2, 'ch', /READING ROOM/]];
        for (const [nm, k, from, to] of legs) { const Pk = HL.plan(k), P0 = HL.plan(0), wc = P0.comps.find((c) => c.name === (from === 'ch' ? 'THE CENTRAL HALL' : 'THE GRAND STAIRCASE')), s2 = Array.isArray(from) ? from : [P0.X(wc.R.i0) - 1.5, P0.Z((wc.R.j0 + wc.R.j1 + 1) / 2)], rc = Array.isArray(to) ? null : Pk.comps.find((c) => c.name && to.test(c.name)), e2 = rc ? [Pk.X((rc.R.i0 + rc.R.i1 + 1) / 2), Pk.Z((rc.R.j0 + rc.R.j1 + 1) / 2)] : to, path = HL.occ.path(k, s2[0], s2[1], e2[0], e2[1]);
          let r = null; if (path) { TEST.place(s2[0], Pk.y + 0.06, s2[1], 0); r = HL.botWalk(path, { max: 600 }); } TEST.ok('the bot walks (pathfinding, W held) ' + nm, !!path && r.ok, path ? (r.ok ? Math.round(path.length * 1.5) + ' m in ' + r.steps + ' steps' : 'stuck at ' + r.x + ',' + r.z) : 'no way through on the grid'); } }
      { let clash = 0; const Hs = HL._hangs; for (let a2 = 0; a2 < Hs.length; a2++) for (let b2 = a2 + 1; b2 < Hs.length; b2++) { const p = Hs[a2], q = Hs[b2]; if (Math.abs(p.nx - q.nx) > 0.05 || Math.abs(p.nz - q.nz) > 0.05 || Math.abs(p.d - q.d) > 0.5) continue; if (Math.abs(p.u - q.u) < (p.w + q.w) / 2 && p.y0 < q.y1 && p.y1 > q.y0) clash++; }
        TEST.ok('every painting hangs on solid wall: none across a window, a doorway or a corner, none over another', clash === 0 && HL.HANGSTAT.ok > 300, HL.HANGSTAT.ok + ' paintings hung; ' + HL.HANGSTAT.wall + ' refused for want of wall, ' + HL.HANGSTAT.clash + ' for want of room'); }
      { const Lf = HL.LIFE || {}; let moved = 0; const w0 = (HL.walkers || []).map((w) => [w.a.x, w.a.z]); TEST.steps(240); (HL.walkers || []).forEach((w, i) => { if (Math.hypot(w.a.x - w0[i][0], w.a.z - w0[i][1]) > 0.5) moved++; });
        { const nan = HL.npcs.filter((q) => !(q.x === q.x && q.z === q.z && q.y === q.y)).length; TEST.ok('nobody is nowhere: every person in the castle has a real position', nan === 0, HL.npcs.length + ' people, ' + nan + ' without a position'); }
        { const a0 = PLAYER.a, w = (HL.walkers || []).find((q) => q.la.hall && q.la.k === 0); let said = ''; if (w) { TEST.place(w.a.x - Math.sin(w.a.yaw) * 3, HL.Y0 + 0.06, w.a.z - Math.cos(w.a.yaw) * 3, w.a.yaw); for (let q = 0; q < 420 && !(HL.SAY.el.style.opacity === '1' && HL.SAY.el.textContent); q++) { CAM.yaw = Math.atan2(w.a.x - a0.x, w.a.z - a0.z); TEST.steps(1); } said = HL.SAY.el.textContent; } TEST.ok('people speak as you pass: a line appears over someone near you', !!said && !/undefined/.test(said) && said.length > 12, said.slice(0, 70)); }
        TEST.ok('the castle is lived in: people walking its halls and passages, a professor before every class, groups at talk', Lf.walkers >= 70 && moved >= 40 && Lf.profs >= 12 && Lf.groups >= 20, Lf.walkers + ' walkers (' + moved + ' on the move in four seconds), ' + Lf.profs + ' professors, ' + Lf.groups + ' at talk, ' + HL.npcs.length + ' people in all'); }
      { const a = HL.auditDoors(); let over = 0; for (const k of HL.ALLK) { const g = HL.occ.grid(k); for (let s = 0; s < g.a.length; s++) if (g.a[s] === 2) { /* doorway zones stay doorway zones: nothing was ever marked over them */ } } TEST.ok('no furniture stands in a doorway or on another piece: every doorway of every storey is clear on the threshold and two paces either side', a.bad.length === 0 && HL.FURN.n > 600, a.doors + ' doorways clear, ' + HL.FURN.n + ' pieces placed, ' + HL.FURN.skip + ' refused for want of room'); }
      const ex = (E.x0 + E.x1) / 2; TEST.place(ex, Y + 0.06, E.z1 + 9, PI); TEST.key('KeyW', true); TEST.steps(300); TEST.key('KeyW', false); TEST.ok('the great doors stand open (walked from the Viaduct Courtyard into the Entrance Hall)', P().z < E.z1 - 2, 'z ' + P().z.toFixed(1));
      TEST.place(ex, Y + 0.06, E.z0 + 6, PI); TEST.key('KeyW', true); TEST.steps(420); TEST.key('KeyW', false); const Z2 = HL.zoneAt(P().x, P().y + 1, P().z); TEST.ok('walked from the Entrance Hall through the Reception Hall into the Great Hall', Z2 && /GREAT HALL/.test(Z2.name), 'z ' + P().z.toFixed(1) + ' ' + (Z2 && Z2.name));
      /* walking, not placing: W held, the camera turned toward each waypoint in turn, exactly as a player goes — a test that set the player down on each flight once passed while nobody could climb past the first half-flight */
      const walkTo = (x, z, max) => { MG.noRender = true; TEST.key('KeyW', true); let ok = false, lx = 1e9, lz = 1e9, still = 0; for (let st = 0; st < (max || 1500); st += 3) { const a = P(), yaw = Math.atan2(x - a.x, z - a.z); CAM.yaw = yaw; a.yaw = yaw; TEST.steps(3); if (Math.hypot(a.x - x, a.z - z) < 0.75) { ok = true; break; } if (Math.hypot(a.x - lx, a.z - lz) < 0.004) { if (++still > 40) break; } else still = 0; lx = a.x; lz = a.z; } TEST.key('KeyW', false); TEST.steps(4); MG.noRender = false; return ok; };
      for (const nm of ['THE GRAND STAIRCASE', 'THE CENTRAL HALL']) { const P0 = HL.plan(0), c = P0.comps.find((q) => q.name === nm), rw = HL.WELLN[nm], x0 = P0.X(c.R.i1 + 1), x1 = P0.X(c.R.i0), z0 = P0.Z(c.R.j1 + 1), z1 = P0.Z(c.R.j0), xa = x0 + rw, xb = x1 - rw, za = z0 + rw, zb = z1 - rw, xc = (x0 + x1) / 2, zc = (z0 + z1) / 2, nS = Math.round(c.tallH / HL.PL.H1);
        for (const [dn, sx, sz, pre] of [['west', x1 - 1.4, zc, [[xc, zc], [xa - 1.4, zc]]], ['east', x0 + 1.4, zc, []]]) { TEST.place(sx, Y + 0.06, sz, 0); TEST.steps(10); let at = '', ok = true; const way = pre.map((q) => [q[0], q[1], 'the foot of the stair']).concat([[xa - 1.4, zb - 1.3, 'the foot of the stair']]); for (let q = 0; q < nS - 1; q++) way.push([xb - 1.3, zb - 1.3, 'half-landing ' + (q + 1)], [xb - 1.3, za - 1.4, 'floor ' + (q + 1)], [xa - 1.4, za - 1.4, 'floor ' + (q + 1)], [xa - 1.4, zb - 1.3, 'floor ' + (q + 1)]);
          for (const [wx, wz, lab] of way) if (!walkTo(wx, wz)) { ok = false; at = lab; break; }
          TEST.ok(nm.toLowerCase() + ': walked (no placing) from the ' + dn + ' door up every flight to the top gallery', ok && P().y > Y + (nS - 1) * HL.PL.H1 - 0.3, ok ? 'y +' + (P().y - Y).toFixed(1) + ' of ' + ((nS - 1) * HL.PL.H1).toFixed(1) : 'stuck on the way to ' + at + ' at y +' + (P().y - Y).toFixed(1)); } }
      for (const [nm, sx, sz, bx, bz] of [['the dungeon stair in the Reception Hall', -80.5, 84.5, -96, 84.5], ['the Slytherin stair', -6.5, 115.4, -6.5, 99.8]]) { TEST.place(sx, Y + 0.06, sz, 0); TEST.steps(10); const dn = walkTo(bx, bz), yb = P().y - Y, up = dn && walkTo(sx, sz); TEST.ok(nm + ': walked down and back up', dn && up && yb < -6.5 && Math.abs(P().y - Y) < 0.3, 'down to ' + yb.toFixed(1) + (up ? ', up to ' + (P().y - Y).toFixed(1) : ', stuck coming up')); }
      { /* every doorway of every storey, walked through with the W key from three paces one side to three paces the other */ let nD = 0; const stuck = []; for (const k of HL.ALLK) { const Pk = HL.plan(k); for (const d of Pk.doors) { if (!d.inn || (d.ext && k > 0)) continue; const cx = (Pk.X(d.i0) + Pk.X(d.i1)) / 2, cz = (Pk.Z(d.j0) + Pk.Z(d.j1)) / 2, t = d.dir === 1 ? d.j1 - d.j0 : d.i1 - d.i0, a2 = d.dir === 1 ? [cx, cz - t / 2 - 2.6] : [cx - t / 2 - 2.6, cz], b2 = d.dir === 1 ? [cx, cz + t / 2 + 2.6] : [cx + t / 2 + 2.6, cz], okc = (p) => { const i = Math.floor(HL.PL.X0 - p[0]), j = Math.floor(HL.PL.Z0 - p[1]); return !Pk.isW(i, j) && (Pk.ind(i, j) || k === 0) && HL.occ.at(k, p[0], p[1]) !== 6; }; if (!okc(a2) || !okc(b2)) continue; nD++;
            TEST.place(a2[0], Pk.y + 0.06, a2[1], 0); if (!walkTo(b2[0], b2[1], 330)) stuck.push('k' + k + ' ' + cx.toFixed(0) + ',' + cz.toFixed(0)); } }
        TEST.ok('every doorway of every storey can be walked through (W held, no placing)', stuck.length === 0 && nD > 180, nD + ' doorways walked' + (stuck.length ? '; blocked: ' + stuck.slice(0, 8).join(' | ') : '')); }
      TEST.ok('five storeys stand on the Hogwarts Legacy plan', HL.ALLK.length === 5 && HL.plan(4).comps.filter((c) => c.kind === 'room').length >= 5 && !!HL.plan(4).comps.find((c) => /GRYFFINDOR COMMON/.test(c.name || '')), HL.ALLK.map((k) => HL.plan(k).comps.filter((c) => c.kind === 'room').length).join('/'));
      { let deep = 0; for (let x = -110; x < 150; x += 6) for (let z = -50; z < 250; z += 6) if (HL.gorge(x, z) > 6) deep = Math.max(deep, Y - HL.h(x, z)); TEST.ok('the water of the map is a gorge cut into the crag', deep > 25, 'depth ' + deep.toFixed(0)); } }
    // ---- gear, potions, chests, the map
    { const Lt = HL.LOOT, n0 = Lt.bag.length; Lt.give(Lt.make({ slot: 'wand', r: 2, il: 8 }), true); Lt.give(Lt.unique('elder'), true); TEST.ok('loot goes to the pack', Lt.bag.length === n0 + 2, Lt.bag.length);
      const p0 = HL.G.power; Lt.equip(Lt.bag.length - 1); TEST.ok('wearing the Deathstick raises spell power', HL.G.power > p0 + 0.3 && Lt.eq.wand.uq === 'elder', HL.G.power.toFixed(2));
      TEST.tap('KeyI'); TEST.steps(3); TEST.ok('I opens the inventory', MG.state === 'inv' && !!document.querySelector('.hlInv')); MG.onKey('Escape'); TEST.steps(20); TEST.ok('Esc closes it without pausing', MG.state === 'play', MG.state);
      TEST.tap('KeyM'); TEST.steps(3); TEST.ok('M opens the map', MG.state === 'map' && !!document.querySelector('.hlMap .me')); TEST.ok('the map is an inked chart with footprints: a parchment sheet, your prints, others\u2019 prints with names, storeys to turn to', !!document.querySelector('.hlMap.mm .sheet3') && document.querySelectorAll('.hlMap.mm .fp').length > 3 && document.querySelectorAll('.hlMap.mm .tab3').length === 7, document.querySelectorAll('.hlMap.mm .fp').length + ' sets of footprints'); MG.onKey('KeyM'); TEST.steps(20);
      P().hp = 20; Lt.pots.wiggen = 1; TEST.tap('KeyG'); TEST.steps(3); TEST.ok('G drinks a Wiggenweld', P().hp > 60 && Lt.pots.wiggen === 0, P().hp.toFixed(0));
      const c = Lt.chests.find((q) => q.id === 'quad'); TEST.place(c.x + 1.2, c.y + 0.06, c.z, 0); const g0 = Lt.gold; TEST.tap('KeyE'); TEST.steps(6); const K = Lt.lk; TEST.ok('a chest shows its charmed lock in the world, over the chest, with the game still running: a sequence of spell keys', MG.state === 'play' && !!K && K.seq.length >= 4 && !!document.querySelector('#hlLockW .rn.cur') && !document.querySelector('.hlLock'), MG.state); if (K) { MG.onKey('Digit' + (K.seq[0] + 1)); TEST.ok('…a rune cast lights, and a thread links it to the next', K.pos === 1 && !!document.querySelector('#hlLockW .rn.ok') && !!document.querySelector('#hlLockW .ln.ok') && !!document.querySelector('#hlLockW .rn.cur'), 'pos ' + K.pos); } if (K) { K.press((K.seq[1] + 1) % 8); TEST.ok('a wrong spell resets the sequence', K.pos === 0 && !c.open && !document.querySelector('#hlLockW .ln.ok')); for (const k of K.seq) MG.onKey('Digit' + (k + 1)); K.end(true); } TEST.steps(120); TEST.ok('the right combination opens it and its loot is gathered by walking over it', c.open && (Lt.gold > g0 || Lt.bag.length > n0 + 1), 'gold ' + Lt.gold); }
    { TEST.steps(30); TEST.tap('Escape'); TEST.steps(5); const p1 = MG.state; IN.fireKey('Escape', true); if (MG.onKey) MG.onKey('Escape'); TEST.steps(2); IN.fireKey('Escape', false); TEST.steps(30); TEST.ok('Esc pauses, and Esc again resumes — it is not read a second time as a new pause', p1 === 'pause' && MG.state === 'play', p1 + ' then ' + MG.state); if (MG.state !== 'play' && MG.onKey) { MG.onKey('Enter'); TEST.steps(30); } }
    { const G2 = HL.GHR; TEST.place((G2.x0 + G2.x1) / 2, HL.Y0 + 0.06, G2.z0 + 20, 0); TEST.steps(40); let candles = null, memos = 0, sky = HL.CEILING; R.scene.traverse((o) => { if (o.isInstancedMesh && o.count >= 500 && o.userData.tag === 'in0' && o.material && o.material.customProgramCacheKey && o.material.customProgramCacheKey() === 'hlcandle') candles = o; if (o.isInstancedMesh && /^in\d$/.test(o.userData.tag || '') && o.frustumCulled === false && o.visible && o.count <= 26 && o.count > 3) memos++; });
      TEST.ok('standing in the Great Hall you see its hundreds of floating candles and the bewitched ceiling (neither is culled away), and paper memos are on the wing in the castle', !!candles && candles.visible && !!sky && sky.visible && memos >= 1, (candles ? candles.count + ' candles ' + (candles.visible ? 'drawn' : 'HIDDEN') : 'no candles') + ', ceiling ' + (sky && sky.visible ? 'drawn' : 'HIDDEN') + ', ' + memos + ' flights of memos'); }
    // ---- the Astronomy Tower is climbed on foot: from the classroom door at its foot, up every flight, out of the door at the top onto the deck
    { const S = HL.TSQ, a = P(), P3 = HL.plan(3), D = HL.DECK; let ok = !!S, at = '', hi = 0; if (S) { HL.save.deck = 0; TEST.place(86, P3.y + 0.06, 80, PI); TEST.steps(20); const p0 = HL.occ.path(3, a.x, a.z, S.foot[0], S.foot[1] + 0.2), w0 = p0 ? HL.botWalk(p0, { max: 500 }) : { ok: false, x: 'no path', z: '' }; if (!w0.ok) { ok = false; at = 'the foot: ' + w0.x + ',' + w0.z; }
        for (let i = 0; ok && i < S.way.length; i += 8) { const w = HL.botWalk(S.way.slice(i, i + 8).map((q) => [q[0], q[1]]), { max: 600 }); hi = a.y - HL.Y0; if (!w.ok) { ok = false; at = w.x + ',' + w.z + ' at ' + hi.toFixed(1) + ' m'; } } TEST.steps(60); }
      const onDeck = ok && Math.hypot(a.x - D[0], a.z - D[2]) > D[3] && Math.abs(a.y - D[1]) < 0.6;
      TEST.ok('the Astronomy Tower can be climbed: W held from the classroom at its foot up thirty-two flights and out onto the observation deck (and that is noticed)', ok && onDeck && HL.save.deck === 1 && a.alive, ok ? 'on the deck at ' + (a.y - HL.Y0).toFixed(1) + ' m' : 'stuck at ' + at); }
    // ---- the evening out of doors: leaves falling, rooks over the bridge, the squid in the loch, the Express at its platform, capes in house colours
    { TEST.place(0, HL.Y0 + 0.06, -120, 0); TEST.steps(60); const lv = HL.LEAVES, rk = HL.ROOKS, sq = HL.SQUID, st = HL.STN, cape = PLAYER.a.inst.cloth && PLAYER.a.inst.cloth.panels.find((q) => q.pd.bone === 2), cm = cape && cape.mesh.material;
      TEST.ok('out of doors toward evening: leaves are falling and rooks are flying over the bridge, the giant squid is in the loch beside it, the Hogwarts Express stands at Hogsmeade Station, and your cape carries your house\'s shield', !!lv && lv.visible && !!rk && rk.visible && rk.count >= 20 && !!sq && HL.lake(sq.x, sq.z) > 0.9 && !!st && !!st.plat && !!st.door && !!cm && !!cm.map && HL.SUN.y < 0.5, (lv && lv.visible ? 'leaves' : 'NO leaves') + ', ' + (rk ? rk.count + ' rooks' : 'no rooks') + ', squid ' + !!sq + ', station ' + !!(st && st.plat) + ', cape map ' + !!(cm && cm.map)); TEST.place(0, HL.Y0 + 0.06, 9, 0); TEST.steps(80); TEST.ok('…and none of that comes indoors: no leaves fall in the Clock Tower hall', !HL.LEAVES.visible, 'leaves ' + (HL.LEAVES.visible ? 'STILL FALLING' : 'gone')); }
    // ---- the lands: the Quidditch stands are full, Hogsmeade's pub can be walked into and a Butterbeer ordered at its bar
    { const C = HL.PITCH; TEST.place(C.x, HL.Q.Y0 + 0.3, C.z - 40, 0); TEST.steps(40); const cr = HL.Q.crowd; TEST.ok('at the Quidditch pitch the stands are full: the crowd is drawn (low ground is not mistaken for the dungeons)', !!cr && cr.visible && cr.count > 1200 && HL.CULL.deep === false, cr ? cr.count + ' spectators, ' + (cr.visible ? 'drawn' : 'HIDDEN') : 'no crowd');
      const T = HL.TB, V = HL.VIL, a = P(); TEST.place(V.x - 6, HL.gy(V.x - 6, V.z - 9) + 0.2, V.z - 9, 0); TEST.steps(20); a.hp = 30; HL.quest.flags.beer = 0; let ok = true, at = '';
      for (const p of [[T.door[0], T.z0 - 3], [T.door[0], T.z0 + 2.2], [T.x0 + 5.0, T.z0 + 5.2], [T.x0 + 6.2, T.z0 + 6.7]]) { const seg = [], L2 = Math.hypot(p[0] - a.x, p[1] - a.z), N2 = Math.max(1, Math.ceil(L2 / 2)); for (let q = 1; q <= N2; q++) seg.push([a.x + (p[0] - a.x) * q / N2, a.z + (p[1] - a.z) * q / N2]); const w = HL.botWalk(seg, { max: 400 }); if (!w.ok) { ok = false; at = w.x + ',' + w.z; break; } }
      const zn = (HL.zoneAt(a.x, a.y + 1, a.z) || {}).name; CAM.yaw = 0; TEST.steps(10); TEST.tap('KeyE'); TEST.steps(20);
      { TEST.place(2.5, HL.Y0 + 0.06, -180, PI); TEST.steps(20); let okR = true, atR = ''; for (const p of [[2.5, -250], [1, -292], [-6, -312], [-30, -335], [-90, -380], [-190, -428], [-262, -450], [-320, -450], [T.door[0] + 2, T.z0 - 3.4]]) { const seg = [], L2 = Math.hypot(p[0] - a.x, p[1] - a.z), N2 = Math.max(1, Math.ceil(L2 / 3)); for (let q = 1; q <= N2; q++) seg.push([a.x + (p[0] - a.x) * q / N2, a.z + (p[1] - a.z) * q / N2]); const w = HL.botWalk(seg, { max: 500 }); if (!w.ok) { okR = false; atR = w.x + ',' + w.z; break; } }
        TEST.ok('the road to Hogsmeade can be walked: from the long bridge, off its far end onto the bank (it used to stop over a drop), along the road and up the high street to the pub door', okR && Math.hypot(a.x - (T.door[0] + 2), a.z - (T.z0 - 3.4)) < 3 && a.alive, okR ? 'arrived' : 'stopped at ' + atR); }
      { const S = HL.STN, Pl = S.plat; TEST.place(V.x + 5.5, HL.gy(V.x + 5.5, V.z - 4) + 0.2, V.z - 4, PI); TEST.steps(20); let okS = true, atS = ''; for (const p of [[V.x + 5.5, V.z - 26.5], [V.x + 7.6, V.z - 28.5], [V.x + 7.8, V.z - 41], [V.x + 13.5, V.z - 45.5], [S.steps[0], S.steps[1] + 0.5], [S.steps[0], Pl.z1 - 1.2], [S.door[0] + 2.5, Pl.z0 + 2.2], [S.door[0], S.door[2] + 0.6]]) { const seg = [], L2 = Math.hypot(p[0] - a.x, p[1] - a.z), N2 = Math.max(1, Math.ceil(L2 / 2)); for (let q = 1; q <= N2; q++) seg.push([a.x + (p[0] - a.x) * q / N2, a.z + (p[1] - a.z) * q / N2]); const w = HL.botWalk(seg, { max: 500 }); if (!w.ok) { okS = false; atS = w.x + ',' + w.z; break; } }
        TEST.ok('Hogsmeade Station: from the square you can walk round Honeydukes, up the steps onto the platform and along it to the door of the Hogwarts Express', okS && Math.abs(a.y - Pl.y) < 0.25 && Math.hypot(a.x - S.door[0], a.z - S.door[2]) < 2.2, okS ? 'on the platform by the carriage door' : 'stopped at ' + atS); }
      { const D = HL.HD, c = HL.VILDOORS['HONEYDUKES']; TEST.place(V.x - 1, HL.gy(V.x - 1, V.z - 20) + 0.2, V.z - 20, PI); TEST.steps(20); let ok2 = true, at2 = ''; for (const p of [[D.door[0], D.z1 + 2.2], [D.door[0], D.z1 - 2.0], [c[0], c[2] + 0.3]]) { const seg = [], L2 = Math.hypot(p[0] - a.x, p[1] - a.z), N2 = Math.max(1, Math.ceil(L2 / 2)); for (let q = 1; q <= N2; q++) seg.push([a.x + (p[0] - a.x) * q / N2, a.z + (p[1] - a.z) * q / N2]); const w = HL.botWalk(seg, { max: 400 }); if (!w.ok) { ok2 = false; at2 = w.x + ',' + w.z; break; } } const z2 = (HL.zoneAt(a.x, a.y + 1, a.z) || {}).name; CAM.yaw = PI; TEST.steps(10); TEST.tap('KeyE'); TEST.steps(10); const shop = MG.state; if (MG.onKey) MG.onKey('Escape'); TEST.steps(30);
        TEST.ok('Hogsmeade: Honeydukes at the back of the square is a shop you walk into, and E at its counter opens the shop', ok2 && z2 === 'HONEYDUKES' && shop === 'inv' && MG.state === 'play', ok2 ? 'in ' + z2 + ', E gave state ' + shop : 'stuck at ' + at2); }
      TEST.ok('Hogsmeade: you can walk from the square through the door of the Three Broomsticks to the bar, and E orders a Butterbeer there', ok && zn === 'THE THREE BROOMSTICKS' && HL.quest.flags.beer === 1 && a.hp === a.hpMax && HL.inLot(V.x, V.z, 0) && HL.inLot(T.x0 + 5, T.z0 + 5, 0), ok ? 'in ' + zn + ', beer ' + HL.quest.flags.beer : 'stuck at ' + at); }
    // ---- the quest journal, the duelling club, and people in their seats
    { TEST.tap('KeyJ'); TEST.steps(3); const its = document.querySelectorAll('.hlJ .it').length; TEST.ok('J opens the quest journal: an open book, the story down one page and the side quests under it, the chosen quest written out on the other', MG.state === 'journal' && its >= 9 && !!document.querySelector('.hlJ .pg.r h2') && !!document.querySelector('.hlJ .ob'), its + ' entries');
      const sd = [...document.querySelectorAll('.hlJ .it')].find((e) => /^s:/.test(e.dataset.id)); if (sd) sd.click(); TEST.ok('a side quest not yet taken up is a rumour of where to look', /rumour/i.test((document.querySelector('.hlJ .pg.r .ch') || {}).textContent || ''), (document.querySelector('.hlJ .pg.r .ch') || {}).textContent); MG.onKey('Escape'); TEST.steps(20); TEST.ok('Esc shuts the journal and play goes on', MG.state === 'play', MG.state);
      const D = HL.duel, a = P(), d0 = HL.save.duel || 0; HL.save.duel = 0; TEST.place(D.lucan.x + 1.5, HL.Y0 + 0.06, D.lucan.z - 1.5, 0); TEST.steps(10); D.ask(); D.ask(); TEST.steps(90);
      TEST.ok('Crossed Wands: asking Lucan twice puts you in the ring with an opponent, wands up, the ladder on the HUD', D.on && D.foes.length === 1 && D.foes[0].alive && D.el.style.display === 'block' && Math.abs(a.x - D.arena.cx) < 1.5, D.on + ' ' + D.foes.length);
      TEST.steps(260); TEST.ok('the opponent fights: after the bow it comes at you', D.phase === 'fight' && D.foes[0].ai === 'fight', D.phase + ' ' + (D.foes[0] && D.foes[0].ai));
      a.x = D.arena.x1 + 9; TEST.steps(3); TEST.ok('the ring keeps the fight in it', a.x <= D.arena.x1 + 0.01, a.x.toFixed(1));
      for (const f of D.foes.slice()) COMBAT.damage(f, 999, { src: a, kind: 'spell', dir: new THREE.Vector3(0, 0, 1), p: f.chest(new THREE.Vector3()) }); TEST.steps(200); TEST.ok('Stupefying the opponent wins the round: it is chalked up, the story and the side quest move on', !D.on && HL.save.duel === 1 && HL.J.st(HL.SIDE[0]).i >= 0, 'won ' + HL.save.duel);
      D.ask(); D.ask(); TEST.steps(120); const two = D.foes.length; PLAYER.die(); TEST.steps(120); TEST.ok('the second round is two at once, and losing a bout does not kill you: you come round by Lucan with the ring cleared', two === 2 && !D.on && a.alive && a.hp === a.hpMax && PLAYER.state === 'move' && HL.foes.filter((f) => f.duel && f.alive).length === 0, two + ' opponents, state ' + PLAYER.state); HL.save.duel = Math.max(d0, 1);
      let off = 0, n = 0, air = 0; for (const r of HL.SEATREC.filter((q, i) => i % 9 === 0)) { const b = HL.seatWake(r); n++; if (Math.hypot(b.x - r.x, b.z - r.z) > 0.03 || Math.abs(b.y - r.y) > 0.05) off++; const k = HL.kAt(r.y + 0.5); if (HL.occ.at(k, r.sx, r.sz) !== 3 && HL.occ.at(k, r.sx, r.sz) !== 5 && r.top - HL.plan(k).y < 1.3 && HL.inFoot(r.sx, r.sz, 0)) air++; }
      TEST.ok('people sit ON their seats: nobody is shoved off their chair when they appear, and under every sitter there is a piece of furniture', off === 0 && air <= Math.ceil(n * 0.3), n + ' sitters woken, ' + off + ' moved off their place, ' + air + ' with nothing marked under them'); }
    // ---- the lesson quests: each has things in the world to walk up to and use, and the story moves on when they are done
    { const qi = HL.quest.i, fl = HL.quest.flags, sq = HL.save.quest, res = []; for (const id of ['restricted', 'potions', 'herbs']) { HL.quest.i = HL.QUESTS.findIndex((q) => q.id === id); HL.quest.flags = {}; HL.quest._o = null; TEST.steps(30); const S = HL.TASKS[id] || [], on = S.filter((q) => !q.u.off).length, early = S.filter((q) => q.last && !q.u.off).length; for (const q of S.filter((q) => !q.last)) q.u.fn(); TEST.steps(30); const lastOn = S.filter((q) => q.last).every((q) => !q.u.off); for (const q of S.filter((q) => q.last)) q.u.fn(); TEST.steps(40);
        res.push(id + ' ' + S.length + ' things, ' + on + ' live at the start, then ' + HL.quest.cur().id); if (!(S.length >= 1 && on >= 1 && early === 0 && lastOn && S.every((q) => q.got) && HL.quest.cur().id !== id)) res.push('BAD ' + id); for (const q of S) { q.got = false; q.g.visible = true; } }
      HL.quest.i = qi; HL.quest.flags = fl; HL.save.quest = sq; HL.quest._o = null; TEST.steps(5);
      TEST.ok('the lessons can be done: the chained book read, three jars and then (only then) the cauldron, a Mandrake repotted in each greenhouse — and each hands on to the next', !res.some((r) => /^BAD/.test(r)), res.join(' · '));
      { const fl = HL.occ.flood(0, -0.5, 6); let n = 0, far = []; for (const id of ['restricted', 'potions']) for (const q of HL.TASKS[id] || []) { if (HL.kAt(q.p[1] + 0.5) !== 0) continue; n++; if (!fl.near(q.p[0], q.p[2], 1.9)) far.push(id + '@' + q.p[0].toFixed(0) + ',' + q.p[2].toFixed(0)); } const P0 = HL.plan(0), pc = P0.comps.find((q) => q.name === 'THE POTIONS CLASSROOM'), mid = pc ? fl.near(P0.X((pc.R.i0 + pc.R.i1 + 1) / 2), P0.Z((pc.R.j0 + pc.R.j1 + 1) / 2), 2.5) : true;
        TEST.ok('every lesson thing indoors can be walked up to from the castle doors (a body\u2019s width of clear floor all the way), and the Potions room is still open through its middle', n >= 5 && far.length === 0 && mid, n + ' things, out of reach: ' + (far.join(' ') || 'none') + ', middle ' + mid); } }
    // ---- a Field Guide page
    { const s = HL.SECRETS.find((q) => q.id === 'fountain'); TEST.place(s.p.x, s.p.y - 1.2, s.p.z + 0.3, 0); TEST.steps(10); TEST.ok('a Field Guide page is collected', s.got); }
    // ---- Quidditch
    { MG.manual = false; HL.Q.start(); await TEST.wait(() => HL.Q.on && HL.Q.phase !== 'off', 600); MG.manual = true; const Q = HL.Q; TEST.ok('the match starts: ten flyers, you mounted', Q.on && Q.flyers.length === 10 && PLAYER.state === 'fly', Q.flyers.length + ' ' + PLAYER.state);
      TEST.steps(700); TEST.ok('play begins after the intro and the count', Q.phase === 'play', Q.phase); TEST.steps(900); TEST.ok('fifteen seconds of play without an error', !MG.errors.length && Q.ball, MG.errors[0]);
      /* ---- the arcade layer (p77c): the stadium holds you, the HUD is up, F faces the play, the broom finds the ball's height, a lunge steals, a roll dodges, a Roaring Shot counts double; the match has its own pause menu */
      { const A = Q.arena, B0 = Q.ball, me = Q.me, a = P(), C0 = Q.C, park = (on) => { for (const b of Q.bl) { b.park = on; if (!on) b.m.visible = true; } }, clear = () => { if (B0.holder) Q.drop(B0.holder); B0.holder = null; B0.shot = null; B0.passTo = null; Q.rsT = 0; me.stunT = 0; me.noCatch = 0; HL.fly.spinT = 0; HL.fly.spinCd = 0; }, edge = () => Math.hypot((a.x - C0.x) / A.BX, (a.z - C0.z) / A.BZ); park(true); TEST.steps(2);
        a.x = C0.x - 20; a.z = C0.z; a.y = Q.Y0 + 10; CAM.yaw = -HALF; CAM.pitch = 0; HL.fly.R.yaw = -HALF; IN.fireKey('KeyW', true); IN.fireKey('ShiftLeft', true); TEST.steps(200); const e1 = edge(); CAM.pitch = 0.8; TEST.steps(240); const top = a.y - Q.Y0; IN.fireKey('ShiftLeft', false); IN.fireKey('KeyW', false);
        TEST.ok('Quidditch: you cannot fly out of the stadium (the side rail and the ceiling hold at full boost)', e1 <= 1.001 && edge() <= 1.001 && top <= A.TOP + 0.01, 'edge ' + e1.toFixed(3) + ' / ' + edge().toFixed(3) + ', height ' + top.toFixed(1) + ' m');
        TEST.ok('Quidditch: the match HUD is drawn (markers on the play, the radar)', Q.hud.vis && Q.hud.n > 0 && Q.hud.cv.width > 100 && !MG.errors.length, 'markers ' + Q.hud.n + (MG.errors[0] ? ' ' + MG.errors[0] : ''));
        { clear(); a.x = C0.x; a.z = C0.z - 30; a.y = Q.Y0 + 10; CAM.yaw = 0; CAM.pitch = -0.08; HL.fly.vel.set(0, 0, 0); HL.fly.speed = 0; const pin = () => { B0.holder = null; B0.p.set(C0.x + 10, Q.Y0 + 10, C0.z - 60); B0.v.set(0, 0, 0); for (const f of Q.flyers) f.noCatch = 1; }; pin(); TEST.tap('KeyF'); for (let q = 0; q < 30; q++) { pin(); TEST.steps(1); } const want = Math.atan2(B0.p.x - a.x, B0.p.z - a.z), off = Math.abs(wrapA(CAM.yaw - want)); TEST.ok('Quidditch: F turns you to face the Quaffle', off < 0.2, 'off by ' + off.toFixed(2) + ' rad'); }
        { clear(); a.x = C0.x; a.z = C0.z - 25; a.y = Q.Y0 + 7; HL.fly.vel.set(0, 0, 0); const bx = C0.x + 6, by = Q.Y0 + 16, bz = C0.z + 10; CAM.yaw = Math.atan2(bx - a.x, bz - a.z); CAM.pitch = -0.08; HL.fly.R.yaw = CAM.yaw; IN.fireKey('KeyW', true); let got = -1; for (let q = 0; q < 360 && got < 0; q++) { if (!B0.holder) { B0.p.set(bx, by, bz); B0.v.set(0, 0, 0); } for (const f of Q.flyers) if (!f.isPlayer) f.noCatch = 1; me.stunT = 0; TEST.steps(1); if (B0.holder === me) got = q; } IN.fireKey('KeyW', false);
          TEST.ok('Quidditch: W at the Quaffle with the view level gets it, nine metres above you (the broom finds the height, the last yards are flown for you)', got >= 0, got >= 0 ? 'in hand after ' + (got / 60).toFixed(1) + ' s' : 'missed: ' + Math.hypot(a.x - bx, a.y + 0.9 - by, a.z - bz).toFixed(1) + ' m off, height ' + (a.y - Q.Y0).toFixed(1)); }
        { clear(); const rv = Q.flyers.find((f) => f.team === 1 && f.role === 'chaser'), st0 = Q.D.st; Q.D.st = 1; a.x = C0.x; a.z = C0.z; a.y = Q.Y0 + 9; CAM.yaw = 0; CAM.pitch = -0.08; HL.fly.R.yaw = 0; HL.fly.vel.set(0, 0, 0); rv.a.x = C0.x; rv.a.y = Q.Y0 + 9; rv.a.z = C0.z + 9; rv.stunT = 0; rv.holdT = 0; rv.vel.set(0, 0, 0); B0.holder = rv; B0.lastTeam = 1; Q.lgCd = 0; TEST.steps(1); IN.fireMouse(0, true); IN.fireMouse(0, false); let got = -1; for (let q = 0; q < 70 && got < 0; q++) { TEST.steps(1); if (B0.holder === me) got = q; } Q.D.st = st0;
          TEST.ok('Quidditch: LMB near the rival with the Quaffle is a lunge that comes away with the ball', got >= 0 && Q.stats.steals > 0, got >= 0 ? 'stolen after ' + (got / 60).toFixed(2) + ' s' : 'holder ' + (B0.holder ? B0.holder.name : 'nobody') + ', gap ' + Math.hypot(rv.a.x - a.x, rv.a.z - a.z).toFixed(1)); }
        { clear(); park(false); const b = Q.bl[0], d0 = Q.stats.dodges; Q.bl[1].park = true; b.p.set(a.x, a.y + 1, a.z + 11); b.v.set(0, 0, -6); b.tgt = me; b.tT = 30; b.hitT = 0; TEST.steps(2); TEST.tap('KeyR'); TEST.steps(4); TEST.ok('Quidditch: a roll (R) with a Bludger bearing down on you is a dodge', Q.stats.dodges === d0 + 1 && me.stunT <= 0, 'dodges ' + d0 + ' → ' + Q.stats.dodges); park(true); }
        { clear(); B0.holder = me; B0.lastTeam = 0; Q.power = true; Q.mom = 1; const h = Q.hoops[1][0], s0 = Q.score[0]; a.x = h.x; a.y = h.y - 0.9; a.z = h.z - 14; CAM.yaw = 0; CAM.pitch = 0; HL.fly.R.yaw = 0; HL.fly.vel.set(0, 0, 0); HL.fly.speed = 0; TEST.steps(3); IN.fireMouse(0, true); IN.fireMouse(0, false); TEST.steps(40); TEST.ok('Quidditch: with House Spirit full the shot is a Roaring Shot — past the Keeper, worth twenty', Q.score[0] === s0 + 20 && !Q.power, 'score ' + s0 + ' → ' + Q.score[0]); }
        { HL.ui.pause(); const h3 = document.querySelector('#hlScreen h3'), ok1 = MG.state === 'pause' && h3 && /QUIDDITCH/.test(h3.textContent), rb = document.querySelector('#hlScreen [data-a="r"]'); if (rb) rb.click(); TEST.ok('Quidditch: Esc opens the match’s own menu (controls, restart, quit) and RESUME returns to play', ok1 && MG.state === 'play', (h3 ? h3.textContent : 'no menu') + ' → ' + MG.state); HL.noPauseT = 0; }
        clear(); park(false); }
      /* a Quaffle dropped on the grass must not end the game: left there with nobody holding it, a Chaser has it again within ten seconds (it used to lie under everybody's reach for the rest of the match) */
      { const B0 = Q.ball; if (B0.holder) Q.drop(B0.holder); B0.holder = null; B0.shot = null; B0.p.set(Q.C.x + 6, Q.Y0 + 0.25, Q.C.z + 20); B0.v.set(0, 0, 0); for (const f of Q.flyers) f.noCatch = 0; P().x = Q.C.x - 25; P().z = Q.C.z - 70; P().y = Q.Y0 + 30; let got = -1; for (let q = 0; q < 600 && got < 0; q++) { TEST.steps(1); if (B0.holder && !B0.holder.isPlayer) got = q; } TEST.ok('Quidditch plays itself on: a Quaffle dropped on the grass hangs a broom\'s height up and a computer Chaser picks it up', got >= 0, got >= 0 ? 'picked up after ' + (got / 60).toFixed(1) + ' s by team ' + B0.holder.team : 'still loose after 10 s at height ' + (B0.p.y - Q.Y0).toFixed(1)); }
      // take the Quaffle to the hoops and shoot
      const B = Q.ball, me = Q.me, h = Q.hoops[1][1]; let scored = false; for (let tries = 0; tries < 12 && !scored; tries++) { const s0 = Q.score[0]; if (B.holder && B.holder !== me) Q.drop(B.holder); me.stunT = 0; for (const b of Q.bl) { b.p.set(0, 300, 0); b.v.set(0, 0, 0); b.tgt = Q.flyers[5]; b.tT = 9; } B.holder = me; B.lastTeam = 0; const a = P(); a.x = h.x + (tries % 3 - 1) * 2; a.y = h.y - 0.9; a.z = h.z - 13; HL.fly.vel.set(0, 0, 0); HL.fly.speed = 0; CAM.yaw = 0; CAM.pitch = 0.0; HL.fly.R.yaw = 0; TEST.steps(3); IN.fireMouse(0, true); IN.fireMouse(0, false); TEST.steps(50); scored = Q.score[0] > s0; }
      TEST.ok('a shot through the hoop scores ten', scored, Q.score.join('-'));
      Q.snT = 0; TEST.steps(30); TEST.ok('the Snitch is released', !!Q.snitch); /* flying Chaser, the Snitch is a race between the two Seekers that you can see (the bars) and tip: a goal spurs your side's, a lunge knocks theirs off it; flying through the Snitch yourself does nothing */
      { const a = P(), s0 = Q.score[0]; a.x = Q.snitch.p.x; a.y = Q.snitch.p.y - 0.9; a.z = Q.snitch.p.z; TEST.steps(3); const still = Q.phase === 'play' && Q.score[0] === s0; const r0 = Q.race[0]; Q.goal(0, Q.hoops[1][1]); const spur = Q.race[0] > r0 + 0.04; const s1 = Q.score[0]; Q.race[1] = Math.min(Q.race[1], 0.3); Q.race[0] = 0.999; TEST.steps(30);
        TEST.ok('the Snitch is the Seekers’ race: a Chaser flying through it changes nothing, a goal spurs your Seeker, and when yours gets there the match ends (+' + Q.SNP + ')', still && spur && Q.phase === 'over' && Q.score[0] === s1 + Q.SNP, (still ? '' : 'a Chaser caught it; ') + (spur ? '' : 'no spur; ') + Q.phase + ' ' + Q.score.join('-')); }
      MG.manual = false; await TEST.wait(() => !Q.on, 800); MG.manual = true; TEST.steps(30); TEST.ok('back on foot by the pitch afterwards', !Q.on && PLAYER.state !== 'fly' && P().alive, PLAYER.state); }
    /* ---- the flying lesson: it starts with its own small cast, a ring flown through counts, and it ends on its results card with the match tidied away */
    { const Q = HL.Q; MG.manual = false; Q.lesson(true); await TEST.wait(() => Q.on && Q.tut && Q.tut.i === 0, 600); MG.manual = true; const T = Q.tut, panel = document.getElementById('hlQtut');
      TEST.ok('the flying lesson starts: you, a team-mate, a rival and their Keeper; step one on screen', !!T && Q.flyers.length === 4 && T.rings.length === 3 && panel && panel.style.display !== 'none' && /TAKE OFF/.test(panel.textContent), T ? Q.flyers.length + ' flyers, ' + T.rings.length + ' rings' : 'no lesson');
      if (T) { const a = P(), r = T.rings[0].p; a.x = r.x; a.y = r.y - 0.9; a.z = r.z - 1; TEST.steps(3); TEST.ok('…a ring flown through counts', T.rings.length === 2, T.rings.length + ' rings left');
        let steps = 0; for (let i = 1; i < Q.TUT.length; i++) { Q.tutGo(i); TEST.steps(20); steps++; } TEST.ok('…every step of the lesson can be entered without an error', steps === Q.TUT.length - 1 && !MG.errors.length, MG.errors[0] || steps + ' steps');
        Q.tutGo(Q.TUT.length); MG.manual = false; await TEST.wait(() => !Q.on && MG.state === 'house', 600); const h3 = document.querySelector('#hlScreen h3'); TEST.ok('…and it ends on its results card, the match tidied away', !Q.on && !Q.tut && h3 && /LESSON COMPLETE/.test(h3.textContent), (h3 ? h3.textContent : 'no card') + ', on ' + Q.on);
        const bb = document.querySelector('#hlScreen [data-a="b"]'); if (bb) bb.click(); MG.manual = true; TEST.steps(20); TEST.ok('…back to the castle on foot afterwards', MG.state === 'play' && PLAYER.state !== 'fly', MG.state + ' ' + PLAYER.state); } }
    /* an open door leaf stops the trailing camera: stand 0.8 m off its face with your back to it, and the eye does not end up behind the oak (the leaves had no collider at all and the eye sat inside them). Leaves at least 1.4 m wide, so the over-the-shoulder ray cannot pass beside one. And the leaf still does not stop a walker. */
    { const D = (HL.DLEAF || []).filter((d) => d[4] >= 1.4); let n = 0, bad = 0, note = '', walked = 0, tried = 0; const stp = Math.max(1, Math.floor(D.length / 12));
      for (let q = 0; q < D.length && n < 8; q += stp) for (const sd of [1, -1]) { const d = D[q], nx = Math.sin(d[3]) * sd, nz = Math.cos(d[3]) * sd, px = d[0] + nx * 0.8, pz = d[2] + nz * 0.8; TEST.place(px, d[1] + 0.06, pz, Math.atan2(nx, nz)); const a = PLAYER.a; if (Math.hypot(a.x - px, a.z - pz) > 0.25 || Math.abs(a.y - d[1]) > 0.5) continue; n++;
        const c = R.camera.position, side = (c.x - d[0]) * nx + (c.z - d[2]) * nz, along = Math.abs((c.x - d[0]) * nz - (c.z - d[2]) * nx); if (side < 0.1 && along < d[4] / 2 + 0.05) { bad++; note = note || ('leaf at ' + d[0].toFixed(1) + ',' + d[2].toFixed(1) + ': eye ' + side.toFixed(2) + ' m'); }
        if (tried < 4 && !PHY.solidAt(d[0] - nx * 0.9, d[1] + 1, d[2] - nz * 0.9)) { tried++; TEST.place(px, d[1] + 0.06, pz, Math.atan2(-nx, -nz)); IN.fireKey('KeyW', true); TEST.steps(60); IN.fireKey('KeyW', false); if ((a.x - d[0]) * nx + (a.z - d[2]) * nz < -0.2) walked++; } }
      TEST.ok('an open door leaf stops the trailing camera (the eye used to sit inside the oak)', n >= 3 && !bad, n + ' leaf sides tried of ' + D.length + ' wide leaves' + (bad ? ', ' + bad + ' failed — ' + note : ''));
      TEST.ok('…and a walker still passes a door leaf (it is no wall)', walked >= 1, walked + ' of ' + tried + ' walked through'); }
    /* ---- sound (p83): the takes are embedded and every one of them decodes; the things that happened in this run were heard (a bolt, its strike, the whistle, a goal and the cheer, a catch); the passer-by's line was spoken; the mixer threw nothing */
    { const AU = HL.AU, names = AU.names(), fx = names.filter((n) => !/^mus_/.test(n)), mus = names.filter((n) => /^mus_/.test(n)); AU.init();
      TEST.ok('sound: music, effects and voices are in the file', mus.length >= 5 && fx.filter((n) => !/^say_/.test(n)).length >= 38 && fx.filter((n) => /^say_/.test(n)).length >= 40 && !!AU.ctx, mus.length + ' themes, ' + fx.filter((n) => !/^say_/.test(n)).length + ' effects, ' + fx.filter((n) => /^say_/.test(n)).length + ' spoken lines' + (AU.ctx ? '' : ', no audio context'));
      if (AU.ctx) { MG.manual = false; const got = await Promise.all(fx.map((n) => AU.load(n).then((b) => [n, b]))); MG.manual = true; const bad = got.filter(([n, b]) => !b || !(b.duration > 0.2) || !(b._norm > 0)).map(([n]) => n), late = got.filter(([n, b]) => b && b._off > 0.6).map(([n]) => n);
        TEST.ok('sound: every effect and every spoken line decodes, is not silent, and starts promptly', !bad.length && !late.length, bad.length ? 'bad: ' + bad.slice(0, 6).join(', ') : late.length ? 'slow to start: ' + late.slice(0, 6).join(', ') : got.length + ' takes');
        const P0 = AU.played, heard = ['cast_basic', 'hit_basic', 'whistle', 'goal', 'cheer', 'catch', 'throw', 'broom_mount', 'ui_open'].filter((n) => !(P0[n] > 0));
        TEST.ok('sound: what happened in this run was heard (a bolt and its strike, the whistle, a goal and the cheer, a catch, a throw, the broom, a menu)', !heard.length, heard.length ? 'never played: ' + heard.join(', ') : Object.keys(P0).length + ' different sounds asked for');
        { const sl = ['stone', 'grass', 'gravel', 'wood'].map((k) => (AU.buf['steps_' + k] && AU.buf['steps_' + k]._sl ? AU.buf['steps_' + k]._sl.length : 0)), want = ['ring', 'ring_done', 'inc_f_incendio', 'inc_m_expelliarmus', 'com_' + AU.hash('Saved by the Keeper!'), 'com_' + AU.hash('And they’re off!'), 'les_0', 'les_4b', 'les_done', 'hat_ravenclaw', 'letter_hufflepuff', 'mus_dark', 'mus_feast', 'mus_castle2', 'amb_fire', 'amb_station'].filter((n) => !AU.has(n)), dl = HL.npcs.filter((q) => q.talkL), dmiss = dl.reduce((c, q) => c + q.talkL.slice(1).filter((l) => !AU.has('dlg_' + AU.hash(String(l).replace(/<[^>]+>/g, '').trim()))).length, 0);
          TEST.ok('sound, second helping: each recorded walk is cut into at least four footfalls; the ring chime, incantations, commentator, coach, Hat, letter, new themes and beds are in; every line a character can say has a voice; the music sits at the quieter level', Math.min.apply(null, sl) >= 4 && !want.length && dmiss === 0 && dl.length > 20 && AU.vol.music <= 0.21, 'footfalls ' + sl.join('/') + (want.length ? ', missing ' + want.join(', ') : '') + ', ' + dmiss + ' unvoiced lines of ' + dl.length + ' speakers, music ' + AU.vol.music); }
        TEST.ok('sound: a passer-by’s line was spoken as it showed, and the mixer threw nothing', (HL.SAY.n === 0 || /^say_(p?)[fm]\d\d$/.test(AU.spoke || '')) && !AU.err, 'lines shown ' + HL.SAY.n + ', last spoken ' + (AU.spoke || '—') + (AU.err ? ' · ' + AU.err.slice(0, 160) : '')); } }
    TEST.ok('no errors in the whole run', !MG.errors.length, MG.errors.slice(0, 2).join(' | '));
  } catch (e) { TEST.ok('test run threw', false, String(e.stack || e).slice(0, 400)); }
  MG.testResult = TEST.pass + '/' + TEST.n; document.title = MG.testResult + ' · HOGWARTS tests'; console.log('TEST RESULT ' + MG.testResult); MG.manual = false;
};
